### ISSUE TITLE
<id> directories in "Nintendo 3DS"?

### ISSUE THREAD

**Issue by MZ-4** [Plailect/Guide#10]
I think there are 2 additional <id> directories built in "Nintendo 3DS" on the way to emuNAND_formatted.
Are they obsolete and may be deleted in the final cleanup or do they have some function?
I want my SD to be as clean as possible. :-)

**Comment by Plailect** [comment]
Once you are completely done, there may be multiple folders in the
"Nintendo 3DS" folder. The largest one will be your SysNAND folder, and the
other ones can be deleted as they are leftover from EmuNAND.
