### ISSUE TITLE
Able to play online after using CFW? 

### ISSUE THREAD

**Issue by TheAzure289** [Plailect/Guide#100]
This is my final question and last time (hopefully that I'll create an issue topic here. Don't want to screw up anything.

**Comment by deadair3210** [comment]
AFAIK playing online is fine as long as you are on the latest firmware, whether its cfw or not. The server only cares if you have the latest cver and nver and the latest game version

**Comment by dbw-holic** [comment]
Some information adding to @deadair3210 's comment; Playing cia games would be fine, if you are loading .3ds format games from flashcart (gateway) your NNID could be banned.

**Comment by dbw-holic** [comment]
I am pretty sure if you do some research on Google, you will get answer much sooner and more thoroughly.
