### ISSUE TITLE
SafeCTRTransfer / GodMode 9 / missing *.sha

### ISSUE THREAD

**Issue by SlydWeis** [Plailect/Guide#1003]
Thanks for the guide and for everyone involved in these projects.
I have completed numerous 3DS softmods and hardmods.
The guide now uses SafeCTRTransfer. This was new to me.

I noticed when following guide I received a black screen after restoring <serialnumber>_nand.bin.
https://3ds.guide/installing-arm9loaderhax
Section IV - Restoring the System
"If you get a black screen, follow 9.2.0 CTRTransfer"
9.2.0 CTRTransfer guide fails when using any method. It fails to find SecureInfo_A

I realized that when using SafeCTRTransfer that a .sha file is not generated.
I generated one for the <serialnumber>_nand.bin using GodMode9.
I followed the steps again under "Section IV - Restoring the System"
The 3DS was able to boot. (Galaxy Model)
Thanks everyone.

**Comment by Plailect** [comment]
.sha is not used in GodMode9/SafeCTRTransfer right now.
