### ISSUE TITLE
Kor ctrtransfer for region change?

### ISSUE THREAD

**Issue by Real96** [Plailect/Guide#1008]
Can you add this ctrtransfer files only for the region change section?

**Comment by jkcgs** [comment]
Check #547 
Also the guide says "if your device is not from one of these regions, just pick one".

**Comment by 3096** [comment]
@jkcgs I think he is trying to region change to KOR...

**Comment by jkcgs** [comment]
@3096 Oh, you're right, my bad. But what could be the reason to do that?

**Comment by Real96** [comment]
Many reason, for example Pokémon events

**Comment by 3096** [comment]
I suppose you can find someone who has a KOR system with A9LH and ask them to dump a ctr transfer image?
If only we have a way to change country code anyway we want... [TuxSH says it's not possible](https://github.com/AuroraWright/Luma3DS/issues/298) when someone asked about it at Luma's repo. I am not sure either if it is possible, but I made [a thread](http://gbatemp.net/threads/request-an-ntr-plugin-or-homebrew-to-change-systems-country-code.467897/) on gbatemp requesting such thing.

**Comment by Real96** [comment]
In the end i created 2 ctrtransfer (Old ans New 3DS) myself. I region changed to Kor using the old method

**Comment by LordZane** [comment]
@Real96, if you have pokemon, could you test to see if creating a fresh save has the correct country/subcountry? Just make a new save, export it with jksv, and then view it with pkhex

**Comment by Real96** [comment]
Yes they have

**Comment by LordZane** [comment]
Thanks alot, this gives me a way to rng legitimate japanese events

**Comment by 3096** [comment]
@LordZane you don't actually need a fresh save. Use your current game on a different region the game automatically loads the current region info, and the Pokemon you obtain will have the current region data.
