### ISSUE TITLE
Part 5 (arm9loaderhax & Luma3DS)

### ISSUE THREAD

**Issue by for2ch** [Plailect/Guide#101]
Small typo in Section I - Preparatory work; line 15

> In the /luma/payloads folder, rename arm9loaderhax.bin to x_Uncart.bin

**Comment by Plailect** [comment]
What typo are you talking about...?

**Comment by for2ch** [comment]
Shouldn't `Uncart.bin` be renamed to `x_Uncart.bin` and `arm9loaderhax.bin` be placed as is to the root of the SD card?

**Comment by d0k3** [comment]
Seeing it, too, now... Should arm9loaderhax.bin be renamed to x_Uncart.bin? If this is correct, I missed something.

**Comment by Plailect** [comment]
It's fine as-is. The arm9loaderhax.bin file from the Uncart zip should be renamed and placed in the payloads folder.
