### ISSUE TITLE
Issue with Section V - Injecting FBI

### ISSUE THREAD

**Issue by kazuts** [Plailect/Guide#1010]
My 3DS is OLD XL EUR
My system was 4.5.0

I'm trying to inject the FBI to H&S on sysnand and I'm getting inject failed

**Comment by quantumcat1** [comment]
Update to 11.3 first like the guide tells you to.

**Comment by kazuts** [comment]
I did it
that's why I written WAS

**Comment by quantumcat1** [comment]
In that case the information you have provided is insufficient to be able to tell you what you did wrong.

**Comment by Plailect** [comment]
Upload a picture of the exact error message.

**Comment by kagamutora** [comment]
![20170412_231851](https://cloud.githubusercontent.com/assets/27398297/24990112/0c9cafd6-1fd7-11e7-854d-6300c5f1c6ff.jpg)
I am also having the same issue. I did update to 11.4 and still nothing. I even tried to follow the steps regarding downgraded gateway device but there were not two sets of uppercase and lowercase files just lowercase

**Comment by kagamutora** [comment]
Sorry my system was 11.1 before I started

**Comment by kazuts** [comment]
![dsc_0119 1](https://cloud.githubusercontent.com/assets/26900354/25001139/adc364ca-204c-11e7-8a17-3a0ff5d84378.JPG)
That's the thing there's no error just inject failed as shown in the picture

**Comment by kazuts** [comment]
The guide is easy to follow and I did every step and yet I have no idea what's the problem
And I know that everything works because I can enter Luma3DS config and Godhand
I tried doing the soundhax way by installing the fbi from homebrew but I also have a different issue there as well:
Searcing for target
Homebrew Launcher ropbin is ready
And then it just sends me back to the main menu of the 3ds

**Comment by kagamutora** [comment]
I fixed my issue by moving the aeskeydb.bin from the folder it was in to the root of the card and now it works

**Comment by kazuts** [comment]
I tried it and it didn't work for me

**Comment by kagamutora** [comment]
No idea I later found out my real issue was I named the files9 folder file9 and that caused the problem, I went back and changed the name correctly then I was able to inject no issues

**Comment by kazuts** [comment]
![image](https://cloud.githubusercontent.com/assets/26900354/25063065/8602ac7e-21e2-11e7-8966-0c84fc3ae69c.png)
Maybe the problem is one of the files/folders?
This is my 3ds SD card now

**Comment by Plailect** [comment]
Not sure, but it's limited to pretty much just you so it must be user error.

**Comment by kazuts** [comment]
Well I was able to fix my problem
I just started following the 11.3 guide of soundhax and toggle the last option about patching arm9/svc access to be able to launch fbi and install the other CIA's
