### ISSUE TITLE
Delay but no delay

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#1015]
https://3ds.guide/safectrtransfer-%28homebrew-launcher%29

" It is not on a timer or anything like that."

"you should continue without delay to avoid any possibility of this happening!"

If it isn't on a timer, saying that you should continue without delay is confusing (it confused a user on reddit, which is why I am submitting this).

**Comment by quantumcat1** [comment]
It's referring to the fact that the console will not go to sleep of its own volition - it won't go to sleep after say five minutes of inactivity like a laptop or phone. But you should finish the section quickly to minimise the risk that you accidentally shut the lid. For example, don't get part way through, then go to work leaving your console on your bed. It might fall shut or someone might shut it.

**Comment by Plailect** [comment]
This is correct.
