### ISSUE TITLE
Issue with SafeCTRTransfer (MSET) Section II step 5

### ISSUE THREAD

**Issue by castorio** [Plailect/Guide#1017]
After doing all the previous steps carefully and coming to step 4, the system freezes at step 5 when you entered the Nintendo DS profile. Complete freeze, you have to restart by holding the power button.

Version 6.2.0-0E.
Used flashcard: r4i SDHC Dual Core 2017 version.

I tried formatting the SD card, new SD card, bigger SD card (16GB), renaming and replacing different files.
Formatted with SDFormatter tool.
Flashcard seems to work perfectly, the step with .nds file seemed to work perfectly, console says it was successful.

**Comment by Plailect** [comment]
This will be fixed soon by an update to [mid-kid/CakeHax](https://github.com/mid-kid/CakeHax), which has a problem with SafeCTRTransfer.

**Comment by castorio** [comment]
It's now saying:
"An error has occurred, forcing the software to close. The system will now restart. (Unsaved data may be lost.)"
After changing some

**Comment by castorio** [comment]
Won't an older version work?

**Comment by Nelis77** [comment]
Same problem here, with Version 4.1.0-0E 
Same flashcard.
Same issue. Grey screen after entering nintendo ds profile.
Where to find the update? New SafeCTRTransfer version?
Thanks

**Comment by castorio** [comment]
Fixed with latest realease of SafeCTRTransfer, v0.0.5
