### ISSUE TITLE
Broken 3DS (Power on Issues)

### ISSUE THREAD

**Issue by TrevTV** [Plailect/Guide#1018]
I don't know if this is the place to talk about this, but I did everything right on the guide after I was done I used MicroSD Transfer and after it shutdown my 3ds without warning! If I press the power button it turns on for about 1.5 seconds and then shuts off. Can you help me?

**Comment by sora10pls** [comment]
`arm9loaderhax.bin` is missing/corrupt on SD root. Replace it with the one from Luma3DS' `.zip` package.

**Comment by TrevTV** [comment]
Thank you so much!!!!!
