### ISSUE TITLE
11.3 CTRNAND FIRM issue

### ISSUE THREAD

**Issue by TrevTV** [Plailect/Guide#1019]
Yep, third issue. Well I did right but when I tried to restore it says it worked then I press A then it says "Failed to get the CTRNAND FIRM." I don't know what happened. Please Help!

**Comment by TrevTV** [comment]
Also, I repaired the SD drive with windows and it dropped the size by a lot! 1.25 GB to 265 MB

**Comment by TrevTV** [comment]
I tried doing the 9.2.0 CTRTransfer but SafeCTRTransfer didn't allow me to do it

**Comment by Plailect** [comment]
9.2.0 CTRTransfer doesn't use SafeCTRTransfer....

Try reading the instructions?
