### ISSUE TITLE
Cannot boot RedNand

### ISSUE THREAD

**Issue by meseli2** [Plailect/Guide#102]
Hi,
I've followed this guide completely since part I. While doing PART 4 - Getting the OTP, I am having an issue at the moment.
* I was doing Section I of Part 4- Step 33 for the second time, which means I had TinyFormatted my RedNand twice. So after booting again into the RedNand to do the initial setup, I was trying to put a new hour and day.
When I clicked Ok an error black screen was shown ("Hit power-off button to turn off... bla bla"). Anyone had this issue before ? Now I am not able to boot into RedNand using LUMA3ds, it just shows a black screen.
Should I restore the RedNand Backup previously created?

Thank you,
Marcos

**Comment by Plailect** [comment]
Check your Luma settings (hold select on boot)

**Comment by meseli2** [comment]
@Plailect I just restored the RedNand Backup as this was not working. Everything is fine. Closing.
