### ISSUE TITLE
[11.3] Browser Freezing when installing Arm9LoaderHax

### ISSUE THREAD

**Issue by RarePika** [Plailect/Guide#1020]
I am trying to install CFW on my old 3ds when I run into this issue. I followed every step and I'm at the part of the guide where we go to http://2xrsa.3ds.guide in our internet browser. The problem here is that whenever I go to that website, the whole system freezes and I can't do anything. It doesn't seem to be loading arm9loaderhax at all. It's stuck on the checkerboard loading screen on the browser. Please help! What do I do to get it working?

Thanks
- RarePika

**Comment by TrevTV** [comment]
Are you sure you have all the files (arm9.bin, arm11.bin, and arm9loaderhax.bin) from the SafeA9LHInstaller.zip?

**Comment by RarePika** [comment]
Yes. I got all 3 of those.

**Comment by TrevTV** [comment]
Then I don't know what would be going on. Sorry

**Comment by RarePika** [comment]
Thanks anyways 😃 ! Anyone else? Please?

**Comment by RarePika** [comment]
I can even send a zip of my current 3ds sd card if anyone wants it.

**Comment by Plailect** [comment]
https://3ds.guide/troubleshooting#ts_browser

**Comment by RarePika** [comment]
Thanks. I looked at it earlier, but I must have missed the part about browser issues. Thanks! 😃
