### ISSUE TITLE
Discrepancy between "Updating A9LH" and "Installing A9LH"

### ISSUE THREAD

**Issue by beanjo55** [Plailect/Guide#1021]
Not sure if this is intended, a typo, or something overlooked, but Installing A9LH states to use data_input_V3, but Updating A9LH states to use data_input_V4. The two files do contain different files. Is there a reason to use V3 over V4, or is V4 only for updating and not for install purposes?

**Comment by Plailect** [comment]
They're different because updating a9lh has you use the latest SafeA9LHInstaller while installing it has you use an old version (required for compatibility with 2xrsa).
