### ISSUE TITLE
Updating the guide (I didn't know where/how to write this)

### ISSUE THREAD

**Issue by Volcah** [Plailect/Guide#1022]
Being that Luma has been updated for 11.4, may you please update your guide suggesting to download the latest nightly (which fixes DS and GBA launch) please?

**Comment by beanjo55** [comment]
I'm assuming that it says to use stable for well, stability. No point in telling people to use risky code if they don't have to. The guide also says thy you don't have to update to .4, but can rather go back to the version you started the guide with.

**Comment by AndreaSnep** [comment]
[It seems like we're going to get a new release build tomorrow](https://gbatemp.net/threads/luma3ds-noob-proof-3ds-custom-firmware.411110/page-921#post-7241933), so this issue should resolve itself.

**Comment by jkcgs** [comment]
I think this issue can be closed now
