### ISSUE TITLE
Unnecessary Extra Text

### ISSUE THREAD

**Issue by CorrosiveCat** [Plailect/Guide#1026]
In multiple steps of the guide currently, it says to rename GodMode9.bin to, well, GodMode9.bin which is a bit redundant and a little confusing. Thanks

**Comment by CorrosiveCat** [comment]
I now see that @jkcgs already addressed this in a pull request so I will now be closing this. Thanks

**Comment by jkcgs** [comment]
Thanks to you! 😄
