### ISSUE TITLE
Idk who to ask 

### ISSUE THREAD

**Issue by jmx077** [Plailect/Guide#1031]
Hello I don't who to ask and I was hoping you may know how but I got a new sd card as my old one  filled up and I'm having trouble Transferring I have (CFW 11.30 all ready) but when I put it in to my 3ds just a few games show up and also I am no longer on CFW I'm confused by this

**Comment by jmx077** [comment]
I have lost everything now nothing is showing I messed up on my sd card I deleted the wrong one now when I try to put my backup in non of my things are showing up I dont know what I am doing now HELP

**Comment by Plailect** [comment]
This is not a support forum.
