### ISSUE TITLE
God Mode doesn't start

### ISSUE THREAD

**Issue by Bix97** [Plailect/Guide#1033]
Hi, after section 3, i boot my 3ds pressing start button but i have a black screen and nothing happen.
If i boot pressing select the Luma3DS configuration menu  works. Without any pressing i have a black screen with/without the sd card.

**Comment by sora10pls** [comment]
Make sure the GodMode9 payload is on your SD Card.

**Comment by Bix97** [comment]
I have resolved by downloading godmode9 v 1.0.6 instead the v 1.0.7
