### ISSUE TITLE
Stuck at 2xrsa! Website freezes

### ISSUE THREAD

**Issue by jo4jam** [Plailect/Guide#1037]
I have all the files in the right places, i'm on 2.10, so what else do I need? I've even tried troubleshooting!

**Comment by camatthew88** [comment]
you probably forgot to move all the files make sure you move all the files. i forgot to and it didnt work either, but one i moved all the files it worked

**Comment by camatthew88** [comment]
double check

**Comment by CorrosiveCat** [comment]
Is it actually frozen or is the bottom screen just glitched? If it looks glitched, try the [troubleshooting](https://3ds.guide/troubleshooting#ts_safe_a9lh_screen) for that section

**Comment by jo4jam** [comment]
The whole thing is frozen. Nothing moves. I'll double check the file placement.

**Comment by jo4jam** [comment]
Still nothing.

**Comment by CorrosiveCat** [comment]
After it freezes, try waiting a few seconds, pressing (Select), wait a few more seconds, and then trying pressing any button (like (A)) to turn off the device and see if A9LH is installed.

**Comment by jo4jam** [comment]
Would it be installed on the home screen?

**Comment by CorrosiveCat** [comment]
No, it would of been known if it was installed if you can continue with the guide. Also, try posting your issue to [/r/3dshacks](www.reddit.com/r/3dshacks) for you will probably get more help in the Q&A thread.

**Comment by toomanylegos** [comment]
Same thing happens to me! Although when I load the webpage it displays on the top screen: load arm11.bin . Also I am using a 2ds.

**Comment by toomanylegos** [comment]
Also you link gives a 404 error

**Comment by CorrosiveCat** [comment]
Yeah just search 3dshacks on reddit and ask in the latest Q&A thread

**Comment by jo4jam** [comment]
That's what i did.
