### ISSUE TITLE
Health&Care application

### ISSUE THREAD

**Issue by RenzoHelpmeplease** [Plailect/Guide#1038]
Okay so I tried to inject FBI into Health and Care but nothing happened so then the guide told me to erase two uppercase files or something but I only had 3 lowercase files so I erases two of them then tried injecting again but now it seems like I erased health and care app from my ads I only have the button on me home screen of it please help me I've been spending 20 hours installing everything and I have almost had a problem with every step it's so frustrating please I'm just doing this for one game to play (fire emblem shadows of valencia) I already have the .CIA from the ROM game but it seems like I have to get acces to FBI but I can't do that when it's not injected into health and care which I deleted... Please answer and help me sorry i'm just lost

**Comment by Plailect** [comment]
You seem to have mistakenly interpreted the troubleshooting instructions which didn't even apply to you. Run a system update and it will automatically replace the needed Health and Safety application, then carefully reread the section on FBI injection.
