### ISSUE TITLE
Region Chang

### ISSUE THREAD

**Issue by david-zzj** [Plailect/Guide#1047]
an old3ds(TWN) done A9 already, and i try to Region Chang to JPN. all goes well.
but when i access the eshop many time, it failed, error code : 007-2001.
what can i do now?

**Comment by sora10pls** [comment]
Reading is hard

![img_8353](https://cloud.githubusercontent.com/assets/17801814/25434391/2424c318-2a5a-11e7-934e-723d8728a47a.PNG)

**Comment by david-zzj** [comment]
4.4T --》2.1U（get otp，A9）--》9.2J--》11.4J
is it the reason why i can't access the eshop？

**Comment by Plailect** [comment]
Unfortunately region changing does not allow eShop access on some consoles. This is because of some problem with the NNID and Nintendo's Servers. It is not known how to fix it at this time.

**Comment by helmergoza** [comment]
i have the same problem with 50 3ds japan to USA, did you get any solution to go to eshop after the change.??

**Comment by david-zzj** [comment]
I found some consoles can access, and some can't. Maybe as Plailect said, because of some problem with the NNID and Nintendo's Servers.
