### ISSUE TITLE
CIA Installation Problems

### ISSUE THREAD

**Issue by Sorrento6** [Plailect/Guide#105]
I went through all of the steps on the guide and everything went smoothly on my Old 3DS XL. Even though my FBI installed the HBL CIA file with no problems, It doesn't give me the option to install the CIA game files. When I select one of my game CIA files it only gives me the option to either Delete, Copy or Paste. Any tips or suggestions? current firmware is Sys 10.7.0.32U and I went the Luma3DS route.

**Comment by Plailect** [comment]
Use the SD menu to install off the SD, guide has been updated.

**Comment by Sorrento6** [comment]
SD menu from the FBI installer?

**Comment by Plailect** [comment]
Yes.

**Comment by Sorrento6** [comment]
Hmm. I'm not seeing any options on the FBI installer. Still giving me the delete, copy or paste and not the install option. I put the CIA files in a folder that I created named CIA. I select sd from the FBI menu and pick a file but it only gives me those options.

**Comment by Plailect** [comment]
Open FBI, press SD, then press A on the CIA you want to install.

**Comment by Sorrento6** [comment]
That's what I've been doing but not getting the Install option. Only Delete, Copy or Paste.

**Comment by Plailect** [comment]
The CIA may be corrupted, download again.

**Comment by Sorrento6** [comment]
I have about twenty of them, all producing the same results. I'll try to get another one though. Could there be an issue with anything from the modification? Does it seem correct If my Settings show SYS 10.7.0-32U?

**Comment by Plailect** [comment]
Yes that's fine. Perhaps ask @steveice10 since he wrote the thing.

**Comment by Sorrento6** [comment]
OK. Thanks, Plailect!
