### ISSUE TITLE
updating to 11.4.0

### ISSUE THREAD

**Issue by toomanylegos** [Plailect/Guide#1051]
I recently followed 3ds.guide to jailbreak my 2ds and I am wondering if I can update to 11.4.0. I know it states it is ok to do so in the guide but my friend who also jailbroke his 3ds updated and he said that the homebrew launcher was broken after updating. also if it matters my friend was updating from 11.3.0 and I am on 11.2.0. could you please help me? is there a certain way I should install the update?

**Comment by jaxrogers2** [comment]
Once A9LH is installed (if you can open ARM9 payloads or the Luma config menu on boot using specific buttons, you have A9LH), you can update normally through system settings. The thing about Homebrew Launcher being broken on 11.4 on old3DSes: it's not broken on Custom Firmware (which is what A9LH runs on every boot). All you have to do is use the 11.2 Homebrew Launcher payload and it will work fine. Instructions on getting this payload is in the last section of the Guide.
