### ISSUE TITLE
9.2.0 CTRTransfer needs a warning message

### ISSUE THREAD

**Issue by MelonGx** [Plailect/Guide#1061]
9.2.0 CTRTransfer makes every console use Same-Region 9.2.0 CTRNAND image share some system files, including per-console WLAN information.
This makes Same-Region-9.2.0-CTRTransferred consoles cannot local play each other.
For those people who want to use 9.2.0 CTRTransfer instead of restoring original NAND, I think we need a warning message to mention this to those guys.

**Comment by Plailect** [comment]
I've never seen anything about this being an issue, and to my knowledge anything that would affect local play isn't overwritten by the transfer (CTCERT, localfriendcodeseed, etc).

Have any examples?

**Comment by james-d-elliott** [comment]
Related: https://www.3dbrew.org/wiki/NWM_Services#Local-WLAN

**Comment by MelonGx** [comment]
OK, the unable-to-local-play-with-same-image-CTRTransferred-consoles case is caused by a non-Guide(tm) provided CTRTransfer-NAND & D9WIP steps.
Guide(tm) 9.2.0 CTRTransfer-NAND & GM9 steps makes their local play properly.
Closing this issue this side.
