### ISSUE TITLE
Black Screen after doing CTRTransfer

### ISSUE THREAD

**Issue by TheCoolCat1995** [Plailect/Guide#1064]
I did 2 versions of CTRTransfer (9.2.0, 11.3.0) and when they finished I rebooted and got a black screen nothing happened. If someone could help that would be great. Thanks

**Comment by CorrosiveCat** [comment]
Boot without the SD card, and then insert the card on the home screen

**Comment by TheCoolCat1995** [comment]
didn't work

**Comment by MelonGx** [comment]
Delete Nintendo 3DS folder before boot.

**Comment by Plailect** [comment]
Not a support forum
