### ISSUE TITLE
The incompatibility between Guide(TM) and O3DS 初階版 (Beginner Edition) selling in Taiwan/HK

### ISSUE THREAD

**Issue by MelonGx** [Plailect/Guide#1067]
The Beginner Edition:
![000001_1478448561](https://cloud.githubusercontent.com/assets/7697767/25770188/55d602b4-3261-11e7-9609-e91358f0dd2a.jpg)

This kind of O3DS has a Nintendo-modified 9.7.0-25J, which blocks e-shop, Friend Code, Internet Browser.
In order to "unlock" e-shop, Friend Code, Internet Browser on this kind of O3DS, we have to install O3DS JPN System CIA to OVERWRITE them.

Since:
- SysDowngrader / SysUpdater CIAs NEVER work on A9LH + Luma (maybe cobernik can make them work?) so we can't install System CIA with them
- FBI / BigBlueMenu will skip some System CIA installations which make the "unlock" incomplete

Only 9.2.0 Downgrade can both "unlock" Internet contents & not losing local play.

9.2.0 CTRTransfer can "unlock" Internet contents but it makes the console losing local play (because it makes thousands of 3DSes which performed same-region 9.2.0 CTRTransfer sharing same system files about local play).

**Comment by GarnetSunset** [comment]
My question is, what have you attempted so far? 

You have BBM and FBI installed? 

I'd love to look into this

**Comment by Plailect** [comment]
Any reason you can't just CTRTransfer to a standard J image? Do any entrypoints work? (SoundHax?)

**Comment by Still34** [comment]
This shouldn't even be an issue. Simply CTRTransfer to 9.2.0 and then upgrade back up to 12.4.0. I have repaired and modded this console before. Works flawlessly.

**Comment by MelonGx** [comment]
OK, the unable-to-local-play-with-same-image-CTRTransferred-consoles case is caused by a non-Guide(tm) provided CTRTransfer-NAND & D9WIP steps.
Guide(tm) 9.2.0 CTRTransfer-NAND & GM9 steps makes their local play properly.
So it will not make the beginner edition losing any function.
