### ISSUE TITLE
Broken Link to torrents

### ISSUE THREAD

**Issue by Cottoneyes** [Plailect/Guide#1071]
On the homepage the section that says 'This guide needs your help to seed these torrents!' has a broken link and goes to https://3ds.guide/rss.xml which doesn't display properly.

**Comment by Plailect** [comment]
This page works fine for me. Try another browser?

**Comment by Cottoneyes** [comment]
Broken across Chrome, Firefox and Edge for me. Just get 'This XML file does not appear to have any style information associated with it. The document tree is shown below.'.

**Comment by Committee** [comment]
Same here.

**Comment by Plailect** [comment]
That's not broken, it's a torrent RSS feed. You'll need a torrent client with RSS support such as Deluge.

**Comment by Cottoneyes** [comment]
I do, but I assume that's a problem on my side. Is it possible to make that clearer?

**Comment by Jan200101** [comment]
You need to start the Torrent link IN Deluge

**Comment by james-d-elliott** [comment]
I've not used Deluge but here is a guide I found in about a minute. https://www.rapidseedbox.com/kb/use-rss-deluge-using-yarss2-plugin
