### ISSUE TITLE
Hebrew RTL button issues

### ISSUE THREAD

**Issue by PhoenixBound** [Plailect/Guide#1078]
In the navigation bar for Hebrew, the icons (to choose a different language or see the rest of the menu bar) are created in their normal positions. Clicking on them makes the selector for them show up in the intended position, on the left, though:

![image](https://cloud.githubusercontent.com/assets/13182187/26028690/5d5b9ad2-37eb-11e7-9508-83c62b6c9fee.png)

Reproduced on Firefox 53.0.2. Doesn't seem to happen in Chrome 58 (64-bit). The buttons are centered on Edge 40/EdgeHTML 15.

**Comment by Plailect** [comment]
This seems to be an issue in Firefox with [this](https://github.com/Plailect/Guide/blob/master/assets/js/_main.js#L103-L104), though that same bit works in Chrome. I'll try to see if I can figure it out later.

**Comment by Plailect** [comment]
Fixed by https://github.com/Plailect/Guide/commit/8e3142ba93569d4ea5e5387214c4e8b94fb97799
