### ISSUE TITLE
Quick Guide Correction

### ISSUE THREAD

**Issue by Aevroze** [Plailect/Guide#1082]
https://3ds.guide/updating-to-boot9strap

Section III, Step 1: 
In the Luma3DS configuration menu, use the (A) button and the D-Pad to turn on the following:
“Autoboot **SysNAND**”
“Use **SysNAND** FIRM if booting with R”
“Show NAND or user string in System Settings”

The Luma3DS v7.1 configuration menu says EmuNAND instead of SysNAND in all the above instances.

**Comment by Plailect** [comment]
Fixed
