### ISSUE TITLE
Integrate DsWifiPWN/DS wifi hax/etc (potential free CFW for 11.4 with a homebrew entrypoint)

### ISSUE THREAD

**Issue by Margen67** [Plailect/Guide#1084]
https://gbatemp.net/threads/tutorial-dswifipwn.463547/

This might have been patched but if it still works with the latest stock firmware (11.4 as of writing) maybe it could be integrated into the guide?

**Comment by Plailect** [comment]
This is just a safety measure for having the ability to restore a NAND backup if your CFW (a9lh/b9s/etc) is somehow overwritten. This is very unlikely to happen and is mostly unnecessary. It is definitely not an entrypoint.
