### ISSUE TITLE
DSiWare list is missing

### ISSUE THREAD

**Issue by keyserbrian1** [Plailect/Guide#1085]
The list of compatible DSiWare for the DSiWare overwrite method is currently missing. Could you please put it back?

**Comment by Committee** [comment]
You mean the ones listed here?

https://3ds.guide/installing-boot9strap-(dsiware-save-injection)

**Comment by keyserbrian1** [comment]
No, I mean the ones on the other method (DSiWare **game** injection).

Specifically, they should be at the URL https://3ds.guide/dsiware-list.
