### ISSUE TITLE
Updated version of LumaUpdater

### ISSUE THREAD

**Issue by KunoichiZ** [Plailect/Guide#1086]
Hello Plailect,

I've updated Luma3DS Updater (originally by Hamcha) to download the latest version of Luma3DS, with sighax and boot.firm support. The code and download can be found [here](https://github.com/KunoichiZ/lumaupdate). I don't know if you'll want to use it in your guide or not, so I thought I would mention it to you. 

Also, I would like to mention that there is nothing in the latest Luma3DS nightly .zip (commit #55b2db4a from Luma3DS's repo) from astronautlevel2's nightly site, so if you try to download the nightly, it will fail.

Thank you for your time!

**Comment by Plailect** [comment]
Sure :)
