### ISSUE TITLE
done CTRTransfer to 2.1.0, but can not install arm9loaderhax

### ISSUE THREAD

**Issue by easy4880** [Plailect/Guide#1087]
Hello Plailect,

I have one issue about New3DS, hope you could help. Thanks in advance.

I was just following the old guide, and I had already downgraded to 2.1.0, then I just follow the last page https://3ds.guide/installing-arm9loaderhax
to prepare the files used to install arm9loaderhax.

But, when I use the browser to try to open the URL http://2xrsa.3ds.guide, I found this URL is no longer available, and I found the webpages are updated. So I am stuck here, and don't know what should I do next.

Should I continue follow the old guide? or should I switch to some step of the new guide? and also it seems the old guide is not accessible any more.

Please help me. Thank you very much.

**Comment by Plailect** [comment]
You can find the old version of that page [here](https://github.com/Plailect/Guide/blob/a46352fc570872f7c8c19878e8ebb04da270dcb7/_pages/en_US/Installing-arm9loaderhax.txt).

The URL http://2xrsa.3ds.guide/ still works.

**Comment by easy4880** [comment]
Hi, thanks for providing that page.
But, why when I try to open the URL, the 3DS freezes there? any suggestions? Thanks.
