### ISSUE TITLE
Homebrew entrypoints for downgrading

### ISSUE THREAD

**Issue by deadair3210** [Plailect/Guide#109]
supermysterychunkhax is listed as a entrypoint for homebrew, but downgrading does not work with it. possibly add a disclaimer stating such

**Comment by Plailect** [comment]
Do you have a source for this?

**Comment by deadair3210** [comment]
If you remember, a few days ago, I was talking on irc about how i could not get your downgrader to progress past HAX INIT.

**Comment by Plailect** [comment]
I have added a notice for this, although I cannot fix it as this [appears to be an issue with svchax](http://gbatemp.net/threads/423926/page-9#post-6303617).
