### ISSUE TITLE
b9s, file9 folder and NAND backups

### ISSUE THREAD

**Issue by natinusala** [Plailect/Guide#1091]
At the end of the A9LH to B9S guide, you say that it's safe to delete `arm9loaderhax.bin` and the `files9` folder. 

Shouldn't you add a warning there, because the `files9` folder might contains NAND backups made via GodMode9 or similar softwares ? It may be a good idea to say to backup any NAND_xxxxx.bin file before deleting the folder, if it has not been done already.

**Comment by Jan200101** [comment]
The backup was suggested in the original soft moddig guide.
If the user hasn't made a backup it's mostly their fault

**Comment by natinusala** [comment]
That's true but as the guide aims to be noob proof, it doesn't cost much to put it and could save some 3ds
