### ISSUE TITLE
Is it safe to delete the /boot9strap/ folder?

### ISSUE THREAD

**Issue by Rick74crx** [Plailect/Guide#1093]
The guide isn't perfectly clear on this point in the `Updating to boot9strap` section: it's said in here that the `firm0firm1.bak` and `sector0x96.bak` can be deleted, but the folder still contains `boot9strap.firm`, `boot9strap.firm.sha` and `secret_sector.bin`. Looking at the "regular" procedure from scratch though, the entire folder is deleted at the end.
So, could you please make clearer if the entire folder with those three files can be deleted or not, upgrading from a9lh to sighax?

**Comment by Plailect** [comment]
yep, will fix
