### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by thatjohnkid** [Plailect/Guide#11]
I am having issues updating my EmuNAND. I've been using my OOT as an entry point, but everytime I try to update it to the latest version, from 9.2, it fails, saying it needs to restart. However, as far as I can tell, I think my emuNAND and sysNAND are unlinked. Any ideas?

**Comment by Plailect** [comment]
Servers were in maintenance yesterday and others reported a similar problem, it should be fixed now.

**Comment by thatjohnkid** [comment]
Alright, so I think I bricked. I followed the guide through Step four. I did all of the steps restoring to the SYSnand from the EMUnand backup. However, whenever I boot all I get is a power light but both screens are black. This happens with and without the SD card. I can only turn it off by holding down the power button. :/ Is there anything at all that can be done or is it just a brick?

**Comment by Plailect** [comment]
You will need a hardmod.
