### ISSUE TITLE
Guide unnecessarily requires removing the SD

### ISSUE THREAD

**Issue by yuriks** [Plailect/Guide#1107]
As is, if you follow the guide to the letter, upon reaching the end of [Installing boot9strap](https://3ds.guide/installing-boot9strap-(homebrew-launcher)) you now have an unusable device. If you have no way of taking out the SD card or of using it on a computer you're toast.

But this can be very easily avoided by just pulling the copying of the firm payload [from the next step](https://3ds.guide/finalizing-setup) forward. At that point you can boot the device, and then copy the rest of the files through SD management or your previous homebrew entrypoint.

I know it's recommended to have a way to write to your SD in case something goes wrong and you need to recover, but this arrangement of steps seems to just leave people stuck for no reason. Had a friend ranting about that before. If you instead don't follow the guide and install most files to the SD in advance you get a much smoother experience.

**Comment by Plailect** [comment]
This is easier yes, but it *vastly* complicates the guide (I'd have to repeat steps in 6 different locations!)
