### ISSUE TITLE
Error? with updating to boot9strap

### ISSUE THREAD

**Issue by insanedude63** [Plailect/Guide#1111]
I am currently unable to update to boot9strap. Even though I follow the guide listed at [you website](https://3ds.guide/updating-to-boot9strap) I am either greeted with a black screen or a crash report when following the Section II step 2 (Running SafeB9SInstaller).
The black screen is weird because something does flash on the screen for maybe 1/4 of a second before going entirely black. Because I do not have super-human reflexes, I cannot read it.
The crash is within luma somehow as I get a crash report loaded into my SD card under the /luma/dump folder.

This could be localised to my specific 3ds for countless reasons but I will be as specific as I can with the details. It is a Japanese New 3ds LL running the latest system firmware (11.4.0-37J) with luma3ds (arm9loaderhax) version 7.0.5-ec6e9f73

Any help with this issue would be appreciated.

**Comment by Plailect** [comment]
Try formatting your SD or using a new SD
