### ISSUE TITLE
Instructions to upgrade from a9lh to b9s copy /luma/titles/... to CTRNAND

### ISSUE THREAD

**Issue by Kingwad** [Plailect/Guide#1117]
The instructions read:

Press (Y) on the luma folder to copy it
Press (B) to return to the main menu
Navigate to [1:] SYSNAND CTRNAND -> rw
Press (X) on the existing luma folder to delete it

    If you do not have this folder, just proceed with the instructions

Press (A) to confirm
Press (Y) to paste a copy of the luma folder from your SD card

This will copy all files in /luma/titles, including all patches for all patched games. It will also copy all payloads in /luma/payloads as well. This could potentially be much more data than possible, and certainly more than is needed.

**Comment by sora10pls** [comment]
Yeah I think these steps should ONLY apply to those who are going from stock to boot9strap. Existing users, like myself, had a lot of game patches there thanks to Luma LayeredFS when moving to B9S so I ended up moving only several certain things (payloads, config.bin, customversion_sys.txt) to CTRNAND.

**Comment by deadair3210** [comment]
Agreed, considering LayeredFS support has been established, people might end up copying much more data than required
