### ISSUE TITLE
Most apps do not boot in Homebrew

### ISSUE THREAD

**Issue by skylinekiller** [Plailect/Guide#112]
I successfully completed the hack.  I tested it and everything worked.   Somewhere along the line trying to install Rxtools,  I screwed something up...Now , nothing in Homebrew launcher will laucnh.  When launching Decrypt9WIP it trys to load and returns to HBL, Same thing with EmuNAND9, Lumnas 3D "make sure your launcher is located at /Limina3DS.DAT, FBI doesn't load from HBL, but FBI does launch from Health screen.  OTP Helper doesn't launch either

I have my sysNAND-A9LHAX.bin, how do I restore it back to this bin?

**Comment by skylinekiller** [comment]
And btw, I did change out a memory card and formatted it to 32mb sections as the guides say

**Comment by skylinekiller** [comment]
so I jsut checked my other new 3DS, I hacked both of them the same time.. THey both were successfull, but I think changing my memory card out messed something up..  I can still play .cia mario games and go to FBI on the health, but can't go into any of the HomebrewLauncher stuff

**Comment by skylinekiller** [comment]
Some more troubleshooting.  I used Lumupadater, it said not configuration fount...Then it successfully installed.   I open up HBL, and try to boot Luma, but it just goes to red screen then back to HBL main menu..

**Comment by Plailect** [comment]
You don't launch 9.2 required homebrew from the homebrew launcher, you boot it by holding the key combo at boot. You don't launch luma from homebrew, you launch it automatically on boot.
