### ISSUE TITLE
Dupe system titles

### ISSUE THREAD

**Issue by nickthegamer5** [Plailect/Guide#113]
After finishing install a9lh I someone got 2 of all system titles. One works the other just crashes and forces you to reatart your 3DS. I was wondering if there is a fix for this as it is anoing me very much, also I love your tutorial plan on donating some bit coin ^-^

**Comment by nickthegamer5** [comment]
Also I have been wanting to learn how to make home brews and if you know a good tutorial or if your working on one can you tell me :3

**Comment by Plailect** [comment]
Uninstall them with FBI, they'll have the wrong region in the product code.
