### ISSUE TITLE
Add a warning about the recent 3ds Ban-wave 

### ISSUE THREAD

**Issue by Valeri0p** [Plailect/Guide#1131]
[Source](https://gbatemp.net/threads/regarding-the-recent-3ds-banwave.471781/)

Also, seems that the ban chance is related to the ["send information about the console to Nintendo"](https://gbatemp.net/threads/poll-bans-and-send-information-about-the-console-to-nintendo.471814/) setting.

Sorry for my English.

**Comment by Valeri0p** [comment]
@plailect please, if Nintendo can really detect if you have cfw or not, cfw titles or legit ones, add a warning for newcomers to stay offline for the next weeks can save a lot of user's consoles!

**Comment by Plailect** [comment]
^Wrong button!

I'll add something about this when I'm home later today.

**Comment by Valeri0p** [comment]
Thank you 😃
