### ISSUE TITLE
Change Region to USA FIX O3DS only

### ISSUE THREAD

**Issue by zfirered** [Plailect/Guide#114]
add this to your guide

after downgrade to change region Firmware
open FBI and install FBI.cia ( do not use FBI from hs app )
open FBI.cia and press R,R,L
jump to the bottom by pressing right button until you find CTR-N-XXXX
delete everything the rear there is a letter J
example CTR-N-HA3J
and then Update to the latest version using system setting
the last thing
Legit system format (from system setting) i mean FORMAT it

this will fix notification BUG and SSB,mh series problem...

thansk to jasonal21 for tell me about formatting system

**Comment by nickthegamer5** [comment]
You should message him about this or make a fork, change it, then merge it(or how ever you edit wikis) please don't put it in the issues as it is for issues only.

**Comment by Plailect** [comment]
Opening an issue for this is fine, GitHub doesn't allow pull requests to wikis.

Why is this o3DS only?

**Comment by zfirered** [comment]
because SSB and MH series need to reboot after u launch the game.. CMIIW

if we dont do this ( FORMAT SYSTEM ) it will stuck.. like notification bug... as well

**Comment by zfirered** [comment]
oh yeah.. N3DS need to delete that file too.. CTR JAP system... if not.. 
it will more worst than O3DS..

**Comment by Plailect** [comment]
"press R,R,L" <- I'm not running an old FBI version, exactly what does this do?

**Comment by ihaveamac** [comment]
assuming looking at the default state, "R,R" changes it to delete title (install CIA -> delete CIA -> delete title), "L" changes it to NAND.

**Comment by Plailect** [comment]
This has been incorporated into the guide.
