### ISSUE TITLE
Fix some screen caps of folder structures

### ISSUE THREAD

**Issue by CorrosiveCat** [Plailect/Guide#1154]
1. On `Installing boot9strap (Homebrew Launcher)`, the screen cap is missing the `luma` folder (from my recent pull request #1153)

2. On `Finalizing Setup`, the first screen cap has the wrong file name for Luma Updater

**Comment by Plailect** [comment]
1. There is 0 need to create that folder there, and it only complicates things.
1. This will be updated when I have time

**Comment by William-Imm** [comment]
To add to this, the DCIM folder is missing from the `Finalizing Setup` screen cap. In the most recent a9lh version of the guide, there were warnings against deleting that folder if pictures were already taken on the device.

**Comment by CorrosiveCat** [comment]
Adding to what @William-Imm said, we should add the DCIM folder to the final folder screen cap, but we should also let people know that the DCIM folder is only created when pictures are taken and they should not worry if they do not have that DCIM folder.

**Comment by CorrosiveCat** [comment]
Now, @Plailect, you also need to fix the screen caps for the hombrew launcher soundhax method as well as anything else using the starter kit since the kit is now using the new homebrew menu.
