### ISSUE TITLE
Issue on 10.5

### ISSUE THREAD

**Issue by ZizouZ** [Plailect/Guide#116]
I'm following the guide from part 1 and every time i scan the qr code the screen changes color and an error occurs. Any tips?

**Comment by nickthegamer5** [comment]
QR code? Are you booting into hb launcher with menuhax?

**Comment by ZizouZ** [comment]
I'm trying to boot into HBL with browserhax using the QR cod URL.

**Comment by nickthegamer5** [comment]
Ok, this is normal don't worry. BrowserHax is not the best method of booting into homebrew, when this happens just repeat steps 6-8 until it boots. It might take a bit because like i said it's not the best method, just keep trying until it boots and once it does boot you should install menuhax for a quicker(and no so repetitive method). But if you get a yellow screen when using any method to boot into homebrew just hold power till it shuts off(May take a bit longer than normal) and just do it aging. I hope this help :3

**Comment by nickthegamer5** [comment]
If you need to know how to install menu hax go [here](https://www.youtube.com/watch?v=AANCmoCtbMc)

**Comment by ZizouZ** [comment]
Thx :D ive done it around 50 times now no luck so it'll eventually work?  I've booted it once and tried to instal menuhax but i didn't set a trigger for it and turned it off and now i can't get back. so now im trying to do 6-8 to set a trigger and i keep getting the error.

**Comment by nickthegamer5** [comment]
As it boots hold down L then tell me if it boots in

**Comment by nickthegamer5** [comment]
Also are you using O3DS or N3DS?

**Comment by nickthegamer5** [comment]
Also you don't need to change the Configure/check haxx trigger if you want to you can but if you like to hold down L don't change it :100:

**Comment by ZizouZ** [comment]
if i deleted the theme file in the 3ds i can still run it? im using O3DS.

**Comment by ZizouZ** [comment]
and no i cant run it by pressing L

**Comment by nickthegamer5** [comment]
No it uses the theme file > Make sure to at least set a theme once then turn off the theme > Boot in though browser hax > Install it but don't change anything else

**Comment by nickthegamer5** [comment]
If your still having trouble booting into homebrew go [here](https://www.youtube.com/watch?v=i2lEtnNaPVU)

**Comment by ZizouZ** [comment]
ive looked at these videos before and keep getting error/update nag. then i reset the time again and keep getting the error

**Comment by ZizouZ** [comment]
holy moly finally booted. i had to delete the temp webkit and reboot and try again.

**Comment by nickthegamer5** [comment]
Ok now install menuhax

**Comment by nickthegamer5** [comment]
DO NOT change any of the keys yet!
Just tell me if it says succes

**Comment by ZizouZ** [comment]
https://www.twiddla.com/nsq3vs

**Comment by nickthegamer5** [comment]
fixed #116
