### ISSUE TITLE
Warn Plebs not to use ReiNand when downgrading

### ISSUE THREAD

**Issue by izzy420** [Plailect/Guide#117]
because it blocks Nfirm

**Comment by nickthegamer5** [comment]
You never use ReiNand you only use LumaCFW and RedNand

**Comment by nickthegamer5** [comment]
Please respond where he uses ReiNand or tell me if it was a mistake

**Comment by Plailect** [comment]
Not only does this not matter because it only blocks firm partition writes and not the installation of the NATIVE_FIRM CIA file (am installation CIA then writes to the partitions), but Luma3DS *also* blocks firm partition writes.

**Comment by Plailect** [comment]
I will reopen this issue because I have received more than one report, although the reason this happens is unknown because Luma and ReiNand both block firm updates.

Have you contacted @Reisyukak yet?

**Comment by Plailect** [comment]
The cause for this issue is an outdated version of ReiNand; you must be using a version after commit [110668e](https://github.com/Reisyukaku/ReiNand/commit/110668eb75d9db3f2d750cf2caf75ac73958a564) which fixed this.
