### ISSUE TITLE
Issue with dsiwarehax

### ISSUE THREAD

**Issue by Milanpsmp** [Plailect/Guide#1173]
Tried to install dsiwarehax using Sleep Clock, Sudoku injected fine, however I cannot inject the savedata.bin. The public.sav is 64kb like it should be, but when I mount it, it shrinks to 60kb, therefore I cannot inject the save. Maybe the game is not compatible?

**Comment by Plailect** [comment]
This seems like a GodMode9 issue to me.     
https://github.com/d0k3/GodMode9/issues/new
