### ISSUE TITLE
Minor error in "Updating B9S"

### ISSUE THREAD

**Issue by slaugaus** [Plailect/Guide#1181]
In the prep work section, it says to "Copy `SafeB9SInstaller.bin` from the SafeB9SInstaller `.zip` to the `/luma/payloads/` folder on your SD card." Obviously, it should be the `.firm` and not the `.bin`.

**Comment by james-d-elliott** [comment]
https://github.com/Plailect/Guide/commit/5fbdf162ec4764dcc046ea3ba46fd9df708cb7f9

**Comment by slaugaus** [comment]
Oh.
