### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by Selver-gba** [Plailect/Guide#119]
https://github.com/Plailect/Guide/wiki/Part-4-(Getting-the-OTP) has the following listed for step #29 of (sub)section I:

> Reinsert your SD card into your 3DS, press Start and ***right*** at the same time to reboot, then boot your 3DS into RedNAND using any CFW (if you followed Part 3 of this guide, you can do this by launching Luma3DS from the HomeBrew Launcher)

However, if following this guide, I think the required button sequence is to hold ***down***.

**Comment by Plailect** [comment]
No...

Read the key combo for rebooting in OTPHelper. It requires 2 button presses since you could brick yourself by rebooting accidentally if you're in the middle of a troubleshooting step or something.

**Comment by Selver-gba** [comment]
Mea culpa!  You are correct again.

As always, Plailect, you remain not only calm but also polite when responding to those who are obviously and 100% wrong (as I was here).  :)  Thank you for the civility, and excuse me while I blush...
