### ISSUE TITLE
updated a9lh to boot9strap now have 2 luma updaters. Pls help!

### ISSUE THREAD

**Issue by merkin97** [Plailect/Guide#1191]
Sorry for the noob ? but I just updated to boot9strap from a9lh. Now I have luma updater 1.4.2 amd 2.1.2 on home screen. Tried to uninstall 1.4.2 thru FBI to no avail. Any help resolving would be greatly appreciated!

**Comment by KunoichiZ** [comment]
Uninstall 1.4.2 from system settings.

**Comment by merkin97** [comment]
I'm an idiot. thank you so much

**Comment by james-d-elliott** [comment]
Feel free to close this. @merkin97 @Plailect
