### ISSUE TITLE
I have a problem when try to boot my new 3ds xl after updating Luma3ds

### ISSUE THREAD

**Issue by Rafinho92** [Plailect/Guide#1204]
First sorry for my english.

I have a error message ''An exception occurred''

Processor:      ARM11 (core 1)
Exception type: prefetch abort (svcBreak)
Current process: pm(00000000000000000000000000)

numbers and letters

You can find a dump in the folloring file.....

Help me please, i dont know what to do.

**Comment by Plailect** [comment]
What is your system version?

**Comment by Rafinho92** [comment]
11.4.0-37U, This happens when tried tu boot my 3ds, this happens after updating luma7.1 to luma8.0

**Comment by Rafinho92** [comment]
No, i have the program luma updater, first updates to luma8, then when i try to enter to safeb9sintaller and press de buttons sequenze the error ''An exception occurred''....

**Comment by Rafinho92** [comment]
https://drive.google.com/open?id=0BxeEzeoPtajPbkxVSUFTWEY0N3M here is my dump file

**Comment by Rafinho92** [comment]
My error was update luma first and then try to a9lh to b9s :(

**Comment by Plailect** [comment]
Revert to luma 7.1, then follow that page's instructions
