### ISSUE TITLE
Is it safe for Arm9loaderhax Users to update?

### ISSUE THREAD

**Issue by SuryaKmuar** [Plailect/Guide#121]
Current 3ds version sys 10.7
Latest release 11.0.0, So is it safe to update ?
I made backups of everything possible.

**Comment by SuryaKmuar** [comment]
Any Arm9loaderhax users here who updated their 3ds to latest version? Are you facing any kind of problem or is it still working fine?

**Comment by KonsoleHL** [comment]
I updated 3 hours ago.  

Everything's working fine 😉👍

**Comment by Plailect** [comment]
Read the home page, right at the top.

**Comment by mjdiaz54** [comment]
Try opening homebrew. If it didnt work, rename payload to the version you
have.
