### ISSUE TITLE
DspDump not compatible with last HomebrewLauncher/Luma3DS FW

### ISSUE THREAD

**Issue by phtom** [Plailect/Guide#1213]
Hi,
I am trying to use DspDump but when launched i said it needed HAX 2.0, then on the second try to launch the program it gave me a crash error.
I am on lastest Luma FW and lastest B9S and 2DS FW 11.4.37E, what can i do to get the dump?

**Comment by iuzwpr2p39rh7w** [comment]
As described in the [last step of this guide](https://3ds.guide/finalizing-setup):
Download [DSP1.cia](https://github.com/zoogie/DSP1/releases/latest), install it with FBI, launch it and press (B) once it has completed.

**Comment by phtom** [comment]
Worked!! Great! Thanks!
https://github.com/zoogie/DSP1/releases
