### ISSUE TITLE
(Suggestion) Add the Pillows2 Homebrew Starter Pack to the Guide

### ISSUE THREAD

**Issue by MatthewchuK** [Plailect/Guide#1228]
the old Starter Pack has unneeded stuff, such as CHMM2. Pillows2 has a lot more stuff that people will like. Here is the download link: https://github.com/pillows2/3dsplaykit/releases/download/v1.0.1/playkit.zip
What you do for the CFW community is really great, and is really appreciated. <3

**Comment by Plailect** [comment]
I know nothing about this person and can't really recommend people to download stuff I know nothing about
