### ISSUE TITLE
(Question) Blank version ranges on Old 3DS Get Started table

### ISSUE THREAD

**Issue by lordscales91** [Plailect/Guide#1229]
I have noticed that there are some blanks here https://3ds.guide/get-started-(old-3ds)

What is the meaning of those blanks? They are not directly hackable, so the only option is to hardmod (or wait for ntrboothax) or it means something else? Anyway, for completeness you should specify it there.

**Comment by Plailect** [comment]
They have no install path other than ntrboothax/hardmod.
