### ISSUE TITLE
Homebrew Launcher doesn't download the payload

### ISSUE THREAD

**Issue by voldart** [Plailect/Guide#123]
Hi, this is a wonderful guide and thank you for that.

My problem migth be caused from the new system firmware 11.0.0-33. I reported this already to yellow8's github page. But I'm posting it here also to notify you and ask if there is a solution.

I think my problem is caused by the new 11.0.0-33 firmware. I just installed am9loaderhax yesterday and when I launch the HBL I encounter with this error :

hblauncher_loader v1.1 by yellows8.
Getting system-version/system-info etc...
Detected system-version: New3ds 11.0.0-33 USA
Since the X button isn't pressed, this will now check for the otherapp payload on SD, with the following filepath: sdmc :
/hblauncherloader_otherapp_payload_NEW-1
1-0-0-33-USA.bin
Requesting the actual payload URL with HTTP...
Downloading the actual payload with HTTP...
Error: server returned HTTP statuscode 404.
Failed to download the actual payload with HTTP: 0xfffffffe.
If the server isn't down, and the HTTP request was actually done, this may mean your system-version or region isn't supported by the hblauncher-payload currently.
An error occured, please report this to here if it persists (or comment on already existing issue if needed), with an image of your 3DS system: https://github.com/yellows8/hblauncher_loader/issues/
Press the START button to exit.

**Comment by nickthegamer5** [comment]
If you did it before the 11.0.0 update just rename the payload file to show the current version you are running ( so 1-13-0 --> 11-0-0) and it should work. If you did it after the update I sadly can't help you and you will just need to wait until they release a proper 11.0.0 payload

**Comment by Plailect** [comment]
Seriously?

>**19) Copy the 11.0.0 Homebrew Launcher Payload to the root of your SD card**

from [here](https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax))
