### ISSUE TITLE
(Suggestion) Improved DSIWare method

### ISSUE THREAD

**Issue by Aluminite** [Plailect/Guide#1230]
I've figured out how someone could do dsiware method without losing data: make 2 emunands on cfwed system, transfer stock system to emunand 1, get the dsiware on emunand 2, do the stuff to it, emunand 2 to stock system, install b9s, emunand 1 to stock (now b9s) system.
There are a few problems though:
1. N3DS can't transfer to O3DS, but that doesn't matter if the target system is old and the CFW one is new because they could just do a ctrtransfer to o3ds firmware.
2. If the CFW system is old and the stock one is new, then this won't work at all.
edit: nobody seems to understand this. **Normally the target system loses all data when doing a system transfer. But this can avoid that. It (sort of) makes a copy of the target system's data, installs b9s on it, then restores that data.**

**Comment by pbanj** [comment]
are you saying to install b9s to the emunand? thats not how it works
