### ISSUE TITLE
FBI via Rosalina HBL crashes and throws an arm11 exception

### ISSUE THREAD

**Issue by GriffinG1** [Plailect/Guide#1231]
Multiple people have had this happen. Please see @chenzw95 for all crash dump information. Suggested reversion to H&S injection method, as this has solved the problem 100% of the time.

**Comment by chenzw95** [comment]
[crashdumps.zip](https://github.com/Plailect/Guide/files/1099431/crashdumps.zip)

This has been collected by other volunteers on the Nintendo Homebrew discord server, but I will also be keeping an eye out in the assistance channels for more of these cases.

**Comment by Ryuzaki-MrL** [comment]
You need the [new hbl](https://github.com/fincs/new-hbmenu/releases) which afaik isn't stated in the guide.
@Plailect could you add a link to the new hbl on the "Finalizing Setup" page?

**Comment by chenzw95** [comment]
The homebrew starter kit has already been updated to include the v2.0 `boot.3dsx`, though. Depending on their upgrade/installation path, users are prompted to (re-)copy the contents of the starter kit.

Attempting to launch HBL without `boot.3dsx` present results in a svcBreak in loader.

**Comment by GriffinG1** [comment]
As a note, I tested with 1.1.1 hbmenu, and while FBI does crash, there's still no reason anyone installing from stock (who are the majority of the people getting this issue) would have 1.1.1's boot.3dsx instead of 2.0.0's

**Comment by Plailect** [comment]
This is because of user error (attempting to use 1.1.1 or not having a `boot.3dsx` at all)

**Comment by gpgrocker** [comment]
I'd buy this, except they would have to compile 1.1.1 themselves as the github no longer has it as a release, and as I said before this is a majority of stock installs, the majority of those being on the first console. Missing boot.3dsx throws a different error, and they wouldn't be able to get fbi failing to launch without it

**Comment by gpgrocker** [comment]
(Oops I signed into the old account, oh well)

**Comment by Plailect** [comment]
You're saying this error happens to people who have never used the hbl before and therefore cannot have 1.1.1?

**Comment by Ryuzaki-MrL** [comment]
Oh, so it was that then. A friend of mine had this issue and said his HBL was 1.1.1. He must have been using HBL for quite some time now and forgot to replace it with the new one from the starter pack.
