### ISSUE TITLE
PSA: Installing cias with fbi injected as h&s has a problem

### ISSUE THREAD

**Issue by Seba201x** [Plailect/Guide#1232]
The problem is the 3ds won't turn off normally, you have to force the shut down pressing power button

**Comment by Plailect** [comment]
Need more details...

**Comment by Seba201x** [comment]
Try installing a cia using injected fbi on h&s, after that press the shutdown button and select "power off", the 3ds get stuck with the led on.

**Comment by Plailect** [comment]
This is not something the guide ever tells you to do....
