### ISSUE TITLE
Uninstall B9S?

### ISSUE THREAD

**Issue by lunalik** [Plailect/Guide#1240]
I'm looking to sell my O3DS to a used game store, and upgrade to a N2DS, but my O3DS has boot9strap installed, and I don't know how to remove it.

**Comment by ZenIsBestWolf** [comment]
My recommendation, sell it on Craigslist. Hacked 3ds systems go for more.

But here's how to do it anyways.

download the .firm from the hardmod page, rename to firm0.bin, use godmode9 to write it to sysnand virtual (ignore the warning about it being 900kbish despite the entire firm partition being 4mb), reboot, then perform a system update
 + don't do this if you have region swapped, and test the firm that you downloaded by chainloading into it with luma first.

**Comment by lunalik** [comment]
Thx

**Comment by ZenIsBestWolf** [comment]
Credit ih8ih8sn0w#5727 on discord.

**Comment by lunalik** [comment]
Sure. Btw, the used game store didn't accept modified units, and it was a very good upgade deal (get $125 towards N2DS/N3DS), but thanks for the suggestion anyways.

**Comment by ZenIsBestWolf** [comment]
Go for Craigslist then. Assuming you have an o3DS, you could sell it for a decent 150-170 USD.
