### ISSUE TITLE
[Request] Update GodMode9 Usage Page

### ISSUE THREAD

**Issue by sora10pls** [Plailect/Guide#1242]
As per the latest release, NAND backups are now done via scripts.
(Home) -> More... -> Scripts... -> SysNAND Backup
The SysNAND Backup script is included in the latest release (`sdmc:/gm9/scripts/Backup SysNAND.gm9`).

Also, all files are now outputted to `sdmc:/gm9/out/`

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/bd8c0e7f0b1075d2a42c888adf47517fe0080c8f
