### ISSUE TITLE
On b9s 1.0 no SYSNAND TWLN folder on gm9

### ISSUE THREAD

**Issue by rashevskyv** [Plailect/Guide#1245]
Need to mention it on the guide

**Comment by Plailect** [comment]
What?

**Comment by rashevskyv** [comment]
Sometimes on b9s 1.0 SYSNAND TWLN on gm9 is dissapeard. Upgrade to b9s 1.2 fix this issue

**Comment by Plailect** [comment]
They shouldn't be using 1.0 anyway
