### ISSUE TITLE
Please add Tubehax disabling/Auto DNS Enabling in the downgrading section!

### ISSUE THREAD

**Issue by CrispyYoshi** [Plailect/Guide#125]
Someone has hard bricked because the guide didn't mention anything about setting DNS back to auto in part 2!

(Do you think you can also add that it's safe to update through System Settings at the very end of the guide?)

**Comment by Plailect** [comment]
*Shit.*

This has been added.

**Comment by Plailect** [comment]
Apparently you can edit the settings from recovery if it can't connect to the internet.

![huh](https://imgur.com/DSTKCTH)

**Comment by CrispyYoshi** [comment]
Oh that's great news! I'll try to let them know as soon as I can!
