### ISSUE TITLE
11.4 CFW line

### ISSUE THREAD

**Issue by Sichisky** [Plailect/Guide#1260]
why is dsiware are not in 11.4 CFW line?
I mean..
![_2017_07_23_19_54_58_931](https://user-images.githubusercontent.com/28685734/28703920-0d4a991a-73a2-11e7-91fa-f58a755a0253.png)
There is DSIWARE in 11.5, and not int 11.4

**Comment by Sichisky** [comment]
I think you can make mistake but..
like 1.1.0, people can think there is no CFW way in 11.4.

**Comment by james-d-elliott** [comment]
Currently there is no documented method on 11.4 other than via 11.5. The previous method was DSiWare which no longer works (latest version required).

**Comment by brettface** [comment]
Maybe instead of a blank cell you can fill it with "Upgrade 11.5, then proceed."

**Comment by Sichisky** [comment]
oh, I see. thx!
