### ISSUE TITLE
Chainloader not working on Luma3DS v7.1

### ISSUE THREAD

**Issue by KunoichiZ** [Plailect/Guide#1262]
I haven't had this issue but I've seen people have issues trying to boot into the chainloader on Luma3DS v7.1. On the steps where it says to boot into the chainloader (on the "Updating b9s" page or anywhere else it mentions opening the chainloader),, if the chainloader doesn't want to work for whatever reason, could you maybe add a note to move a fresh v7.1 boot.firm (or respective boot.firm if on a different page) to the person's SD card root, overriding the existing file? This has fixed the issue and it could help prevent future frustration. 

An example of this actually working can be found [here](https://gbatemp.net/threads/cant-boot-into-chainloader.479107/). I believe that there were a few other threads similar to this as well.

**Comment by Plailect** [comment]
This is definitely user error on their part as copying the exact same file on top of itself would not affect this whatsoever...
