### ISSUE TITLE
DSiWare game inject, Prior CFW on target system

### ISSUE THREAD

**Issue by jonissemand** [Plailect/Guide#1264]
Issue that happened after B9s game injection system transfer.
The target system had CFW installed in the past, but was uninstalled at some point.
Broken DS / DSiWare functionality after completing transfer on target console. (Section V, Step 7)
Does not load DS games, or the Suduko DsiWare game for completing the guide.
Console is now bricked from DS games, please add a warning to prior CFW users wanting to reinstall CFW using DSiWare Inject.

**Comment by Plailect** [comment]
You most likely failed to follow the instructions on previous versions detailing how to fix DS / DSi games. These steps to fix it cannot be done without access to CFW, so you're SOL.
