### ISSUE TITLE
Accidently Updated

### ISSUE THREAD

**Issue by biscoitinhocomleite** [Plailect/Guide#127]
After doing this steps:

Go to "NAND Backup & Restore" -> "Clone RedNAND to SysNAND" then use "NAND Validation Options" -> "Validate SysNAND Downgrade" and confirm your SysNAND only has the same error as EmuNAND. If you get a NEW error after cloning RedNAND to SysNAND, restore SysNAND from SysNAND_original.bin, restore RedNAND from emuNAND_formatted.bin 

My system update from 9.2 to 11, there is something that i can do to solve this?

**Comment by Plailect** [comment]
Congrats, that means you restored *SysNAND* from `emuNAND_formatted.bin` by mistake; you will need to restore your SysNAND from `sysNAND_original.bin` with a hardmod.
