### ISSUE TITLE
Website buttons look messed up

### ISSUE THREAD

**Issue by gnmmarechal** [Plailect/Guide#1271]
![image](https://user-images.githubusercontent.com/11259227/29046141-1290724a-7bbe-11e7-8389-0612a35be7b1.png)
This on Windows 10 Home (amd64), Microsoft Edge.

**Comment by Committee** [comment]
Possible browser issue, try a different one.

**Comment by gnmmarechal** [comment]
Could be an issue with the website itself not liking Edge for some reason, though.

**Comment by Plailect** [comment]
Closing as not reproducible.
