### ISSUE TITLE
NTRBoot (Installling Boot9Strap) Section 2 Step 4 Phrasing Issue

### ISSUE THREAD

**Issue by Saphiresurf** [Plailect/Guide#1276]
![image](https://user-images.githubusercontent.com/272940/29244336-aa439630-7f6a-11e7-8d3c-072dc53c5790.png)

Step 4 in Section 2 has a bit of an issue with the phrasing that was tripping me up quite a bit. Here it says `Power on your device, with the magnet in the sleep triggering position (or toggling the sleep switch on non-folding style devices), while holding (Start) + (Select) + (X)`. This seems to infer that you can just press the power button like you normally do, but it ends up you do actually have to hold the power button with the ST + SEL + X for a few seconds in order for it to boot properly. Otherwise the console will not boot into B9SInstaller (although "New" devices may, see below, but this is a definite issue for old devices). 

Something curious is when you only press the power button, not hold, some interesting and differing behavior happens between the old and new devices. This part has nothing to do with the issue, just an interesting bit. The Old devices won't show any LED's on at all/won't boot up while the "New" devices (from what I've tested with already B9S'd devices at least) will turn the LED's on, but won't boot until you let go of ST + SEL + X (which is pretty interesting behavior, I do wonder why the difference), but will boot into CTR nonetheless. Either way though it won't boot into the flashcart unless you're holding the power button with it.

**Comment by Plailect** [comment]
>but won't boot until you let go of ST + SEL + X (which is pretty interesting behavior, I do wonder why the difference)

This was introduced with B9S 1.2 to prevent conflict with the Luma3DS chainloader
