### ISSUE TITLE
Wiki part 4, section I, point 11. Is it emuNAND or SYSnand option?

### ISSUE THREAD

**Issue by royr719** [Plailect/Guide#128]
You said:
'Open Decrypt9 (This can sometimes take a few tries), then go to "EmuNAND Options", then select the "Health & Safety Dump" option to dump Health & Safety to hs.app'.
But dumping the Health & Safety app from emuNAND will generate a _hs_emu.app_ file, instead of a _hs.app_.
Hs.app is generated if the Health & Safety app is dumped from sysNAND, not emuNAND.
Anyway, we can rename hs_emu.app to hs.app, but this does even matter or should we dump the app from sysNAND instead?
Even if not, this should be clarified at point 11.

**Comment by Plailect** [comment]
>Open Decrypt9 (This can sometimes take a few tries), then go to "EmuNAND Options", then select the "Health & Safety Dump" option to dump Health & Safety to **hs.app (you can use Up and Down / Left and Right to change the name)**

**Comment by royr719** [comment]
Right, I didn't notice you could use Up / Down to change name. My bad, thanks.
