### ISSUE TITLE
Hacking options for stock FW 11.4.0 are gone

### ISSUE THREAD

**Issue by lordscales91** [Plailect/Guide#1280]
I've noticed that there aren't any hacking options on the https://3ds.guide/get-started-(old-3ds) page for firmware 11.4 

Does it means that it's not possible to hack these systems (except by using the the new NTRBoot), not even updating? DSiWare Game injection doesn't work on this version?

**Comment by Committee** [comment]
No it means that 11.4 and 11.5 are similar hence what works in 11.5 should work in 11.4, and vice-versa.

Feel free to correct me though, as that is how I understand it.

**Comment by Milanpsmp** [comment]
In order to system transfer both 3dses need to have the latest system version available, thus dsiwarehax cannot be completed on 11.4

**Comment by lordscales91** [comment]
> In order to system transfer both 3dses need to have the latest system version available, thus dsiwarehax cannot be completed on 11.4

If that's the case, then I think there should be a clarifying note there, something like "Update to 11.5 and follow DSiWare guide"

**Comment by Plailect** [comment]
The guide says you can update to latest to follow its versions steps. Reading the page will reveal all the information the user needs.
