### ISSUE TITLE
Ntrboot can now be installed to an Ak2i using a dsphat/dslite 

### ISSUE THREAD

**Issue by nl255** [Plailect/Guide#1283]
I just saw that someone [released a ntrboot flasher for the Ak2i that runs in ntr mode here](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/releases).  Unfortunately it requires an original ds or ds lite to use (a dsi or 3ds won't work).

**Comment by safan41** [comment]
Why is this an issue?

**Comment by nl255** [comment]
It is an issue because that method is not covered in the guide yet.
