### ISSUE TITLE
Minor typo in this most helpful guide

### ISSUE THREAD

**Issue by peter1357908** [Plailect/Guide#129]
Thanks for the AWEEESOME guide! Here is a little bit towards perfection:
In part 5,

> Once arm9loaderhax is installed and Luma3DS setup with the correct options, we then backup our SD card and format it using EmuNAND9 to remove the now **_obolete_** RedNAND and reclaim the SD card space it previously used.

I believe that should be "obsolete," should it? Again, thanks for your grand contribution to the 3dshacks society!

**Comment by Plailect** [comment]
Fixed
