### ISSUE TITLE
Clarification that B9STool is "boot.nds" and OLD/NEW FIRM clarification too

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#1291]
Hello again! There has been quite a number of people getting confused one where "boot.nds" comes from in the DSiWare guides. Can you mention to "copy boot.nds" from the B9STool .zip?

I also wanted to mention, on those pages, that the OLD/NEW FIRM doesn't specifically say to download it for O3DS/N3DS, but only "for the target console": Can you also make this more clear to avoid any potential confusion?

Thanks!

**Comment by Plailect** [comment]
B9STool doesn't *have* a `.zip` files in the releases.
