### ISSUE TITLE
Add DSi to the ntrboot (3DS Single System) page

### ISSUE THREAD

**Issue by jerbear64** [Plailect/Guide#1298]
I have just confirmed that the DSi version of ntrcardhax_flasher works on my DSi (not that it wouldn't, but since it was only tested on a 3DS and I have backups of my AK2i I figured I'd test it). 
Because of this, I think the DSi should be added to the 3DS Single System installation page, so it accommodates both systems, becoming 3DS Single System/DSi.

**Comment by safan41** [comment]
Actually it should be added to the (nds) method. It should just say that it works for the dsi.

**Comment by jerbear64** [comment]
The process for the DSi is the same as the process for the 3DS, which is why it would be under that section.

The DS and DS Lite method won't work on a DSi.

**Comment by Plailect** [comment]
A separate page would be best since the 3DS version would then be irrelevant

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/529bd70e0ad4a0ac3d896d8f801fa012b1b3bb3b
