### ISSUE TITLE
(Enhancement) Add mention of 10.7.0-32 software update

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#13]
Since there are many brand new 3DS hacking noobs out there that are using this guide or are going to in the future, mentioning that the 10.7 update exists and still supports the 10.6 entry points (ninjhax and OoT3Dhax with or without Powersaves) along with the 10.4+ sysupdater application might be helpful for those users.

**Comment by Plailect** [comment]
Added
