### ISSUE TITLE
Git Tags

### ISSUE THREAD

**Issue by jamesyc** [Plailect/Guide#1306]
For historical reasons, viewing this guide at older states is a pain in the ass right now. 

There should be commits that are tagged, such as "Last version before B9H", "Last version with RedNAND", etc etc. 

It's actually fairly difficult now to do research. Quick, name the hax that 10.x systems used to downgrade to 9.2.0 before Soundhax came out... This takes a lot of time to discover without knowing which commit to look at.

**Comment by Plailect** [comment]
This would be a bunch of work that almost nobody would care about.
