### ISSUE TITLE
Multi system flash page says either arm9loaderhax or boot9strap, but only b9s works

### ISSUE THREAD

**Issue by ZetaDesigns** [Plailect/Guide#1307]
The Multisystem Flash method of ntrboot states the following:

`
This method requires temporary access to a second 3DS family device that is already running some kind of custom firmware (such as boot9strap or arm9loaderhax). `

However, since ntrboot_flasher only exists in .firm form, arm9loaderhax will not work. This should either not state arm9loaderhax, or link to the a9lh to b9s updating page.

**Comment by deadair3210** [comment]
I'm not sure, but you should be able to load ntrboot_flasher firm with OldLoader
