### ISSUE TITLE
About Soundhax

### ISSUE THREAD

**Issue by Sichisky** [Plailect/Guide#1308]
My 3DS is in 9.0.0-16 K, and I tried Soundhax, and I failed in download otherapp "File not found"
So I ask him I can't download, and he said
![_2017_08_21_09_19_26_443](https://user-images.githubusercontent.com/31066511/29499670-dc4126aa-8651-11e7-9d95-50b84333635c.jpg)
..What should I do?

**Comment by pokecraft98** [comment]
You need to ask for help on Nintendo Honebrew: https://discord.gg/C29hYvh

**Comment by Sichisky** [comment]
Thanks!
