### ISSUE TITLE
Devmode

### ISSUE THREAD

**Issue by biscoitinhocomleite** [Plailect/Guide#132]
I'm trying to update to 9.2, but when i select "DevMode" on RxTools menu i just get a black screen.

**Comment by dbw-holic** [comment]
Did you copy and paste the rxtools.bin only or the entire RXTools folder?

**Comment by biscoitinhocomleite** [comment]
Copied only the rxtools.dat and what was said in the tutorial.

**Comment by Plailect** [comment]
What is your system version?

**Comment by biscoitinhocomleite** [comment]
5.1.0-4U

**Comment by MelonGx** [comment]
Retried several times but same result?
If no, then retry it several more times.
If yes, then it's an incompatible issue of launching 2.5.2 Devmode on higher main version -4 frankenfirmwares, which gives you 2 choices only to solve this problem:
- Cartridge upgrade to 6.0.0-4U - 6.3.0-4U, then use MSET to boot rxTools Devmode
- Cartridge upgrade to 9.9, enter HBL, use SaveSysupdater to DG to 9.2

**Comment by biscoitinhocomleite** [comment]
Actually i just used Pokemon X to update to 6.0 and it worked. It seems that the rxTools devmode for 5.0 isn't working properly
