### ISSUE TITLE
The HW_A5 and the HW_A7 torrents are swapped

### ISSUE THREAD

**Issue by scala619** [Plailect/Guide#1320]
In https://3ds.guide/installing-boot9strap-(ntrboot) of Section V (iii)

![](https://cdn.discordapp.com/attachments/196635695958196224/351993916268085249/unknown.png)

**Comment by ShadixAced** [comment]
Nope, it is not. R4i Gold are indeed shown as A7 and Infinity R4i's are shown as A5.

**Comment by ShadixAced** [comment]
This is about the HW id's. R4i Gold are shown as A7A7A7A7 and Infinity as A5A5A5A5

You may see Kitling's flashcart_core git if you need to see.

**Comment by scala619** [comment]
Sorry, should've added more detail, when you click to download the torrent, clicking the HW_A7 torrent gives you the HW_A5 link instead and vice versa.

**Comment by Plailect** [comment]
It's been fixed
