### ISSUE TITLE
Suggestion: use nds mode ntrboot_flasher version with flashrom backup/restore to SD

### ISSUE THREAD

**Issue by Valeri0p** [Plailect/Guide#1323]
Since using ak2i_ntrcardhax_flasher is the easiest way to install ntrboot for many people, [some](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/issues) of them are complaining that you can't save your flashrom backup on the flashcard SD card, when using it on Dsi/3ds.
I know that there is a flashrom backups archive, but it will be impossible to cover them all when more cards will be added, and more clones will be supported.
But this is not an unsolvable problem; knowing that with dldi you can interface with most flashcards SD card, you can save here your flashrom dump for further restoring. And someone have already implemented that:

https://github.com/saibotu/nds_ntrboot_flasher

This fork does exactly that, alongside with rewritten graphics, more user friendly. The only thing is that it uses an older flashcard_core commit, but it shouldn't be hard to [fix that](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/commit/6bac9984c5dc2445a075eeb252d356bf968f8ca5) (also knowing that @Plailect has rewritten fwtool for dsiwarehax). Maybe it needs some testing, but it will be a very good improvement to the actual method of installing ntrboot with only one device.

Sorry if this issue is seen as a duplicate, but I really hope to see this method improved.

PS: I won't be able to reply tomorrow, since I'm travelling.

**Comment by Plailect** [comment]
@saibotu should pull request his changes to the main repo if he feels they are ready for widespread use.

**Comment by Valeri0p** [comment]
I've seen the update... Well, good luck finding the 50+ flashrom dumps for the ones that will flash a dstt from an NDS.
