### ISSUE TITLE
Enhancement: Add folder path for renaming sysNAND.bin

### ISSUE THREAD

**Issue by Sunii** [Plailect/Guide#133]
Confused me for a second when i didnt see this file in the root of the SD Card, could the subfolder path be added to this step to help others avoid confusion?

https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax)#section-vi---finalising-setup

Step 4 

Rename sysNAND.bin to sysNAND-A9LHAX.bin

**Comment by Ginkyway** [comment]
sysNAND.bin should definitely end up in the root of the SD card, not in any subfolders. The guide is 100% accurate on that step.

**Comment by Sunii** [comment]
I just finished using the guide on a 2ds with the newest versions of all software required and mine was definitely NOT in the root of the SD, it was in a subfolder. Perhaps a change in a new version of one of the apps? I have no explanation for this myself.

**Comment by dbw-holic** [comment]
Sunii is correct, EMUNAND9 places the created sysNAND.bin in the subfolder "EMUNAND9" under root directory in this step.

**Comment by peter1357908** [comment]
Had exactly the same experience. Emunand9 did place created back-ups in the subfolder EMUNAND9 and it made me panic when I couldn't find it in the first place...

**Comment by Plailect** [comment]
If the folder EmuNAND9 already exists then the backup will be placed there. Instructions to remove the folder have been added.
