### ISSUE TITLE
Finalizing Setup

### ISSUE THREAD

**Issue by wildfirebill** [Plailect/Guide#1336]
Edit needed for

Section V - CTRNAND Luma3DS

 **_1    Remove sd card and cut and paste GodMode9.firm into luma/payloads folder_**

    Launch GodMode9 by holding (Start) during boot
    If you are prompted to create an essential files backup, press (A) to do so, then press (A) to continue once it has completed
    Press (Home) to bring up the action menu
    Select “More…”
    Select “Scripts…”
    Select “setup_ctrnand_luma3ds”
    When prompted, press (A) to proceed
    Press (A) to unlock SysNAND (lvl1) writing, then input the key combo given
    Press (A) to continue
    Press (A) to relock write permissions

**Comment by Plailect** [comment]
https://github.com/Pirater12/ocs/releases/tag/v1.2.5
