### ISSUE TITLE
Noobs think that soundhax works after installing & configuring luma

### ISSUE THREAD

**Issue by jason0597** [Plailect/Guide#1348]
I've seen this a lot in the discord channel, people come in and say "how do i access homebrew"  just after they finished installing & configuring luma, they completely ignore the "Continue to finalizing setup" button, for whatever reason. 

I am not sure of the reason for why this happens, but I think it's either because of:

1)the button is not big enough
2)finalizing-setup seems optional while in 99% of the cases it is mandatory and if not, it's highly recommended (installing anemone/fbi/dsp/luma updater isn't considered bloatware and people who do consider it know that not installing it doesn't damage their 3DS)
3)Whatever this person meant: https://prntscr.com/gnjjsb

My suggestion would be to make the installing-b9s page say in big letters that "You cannot access the homebrew launcher until you follow finalizing-setup" (technically this is a lie since you can inject hbl with rosalina, but people only learn about this in the next page, so you have to lie to them for a split moment to get them to click on finalizing-setup)

**Comment by Plailect** [comment]
If they can't read that there is another page, then they cannot be surprised that things don't work. It's fine as is IMO.
