### ISSUE TITLE
Tell users to grab arm9.bin instead of SafeB9SInstaller.bin from SafeB9SInstaller.zip during boot9strap installation so that they don't have to rename it

### ISSUE THREAD

**Issue by jason0597** [Plailect/Guide#1349]
since safehax loads in this order (priority high to low):

safehaxpayload.bin
arm9.bin
arm9loaderhax.bin

**Comment by Plailect** [comment]
The current way keeps it more clear as to what is actually happening (for those who know what they're doing). Renaming a file is fine IMO.
