### ISSUE TITLE
Wiped SysNAND POST-HACK

### ISSUE THREAD

**Issue by jimbo4273** [Plailect/Guide#135]
I hacked a friend's O3DS and he accidentally wiped SysNAND through TinyFormat. What do I need to do to fix it?

**Comment by dbw-holic** [comment]
If you have modded your friend's console following Pailect's guide, you should have an updated sysNAND + Luma3DS. You can safely wipe using Tinyformate, what's the problem?

**Comment by jimbo4273** [comment]
What exactly happened? And is there a way to undo it?

**Comment by Plailect** [comment]
Restore a backup, or you're SOL.

**Comment by jimbo4273** [comment]
Is it good if I restore from the emuNAND_original.bin?

**Comment by Kikoshi** [comment]
If you do, do so with (with A9LH) option.. i think that should work c. c

**Comment by jimbo4273** [comment]
Figured that. Thanks!
