### ISSUE TITLE
Add DSTT Flashrom Backup

### ISSUE THREAD

**Issue by Milanpsmp** [Plailect/Guide#1352]
There are currently no DSTT flashrom backups avaible on the site.
This is from a MATRONIX MX29LV400B chip, don't know if it's compatible with other chips

[backup.zip](https://github.com/Plailect/Guide/files/1324323/backup.zip)

**Comment by Plailect** [comment]
There are quite a few so this is currently infeasible. I'm looking into alternative options.

**Comment by Plailect** [comment]
This will be addressed whenever ntrboot_flasher is updated to support DS/DSi launching (and can backup flashroms before flashing).
