### ISSUE TITLE
After Downgrading

### ISSUE THREAD

**Issue by biscoitinhocomleite** [Plailect/Guide#136]
Hi, after i did the part 4, section II, step 10, my 3ds keeps in a black screen if my SD is inside it. Moreover, in my system setting, when i iniciate without sd, it says that i'm alredy in 2.1 what should i do?

**Comment by dbw-holic** [comment]
You should provide as much information as possible so we can help.
How far have you gone through Section II? Have you done step 10 yet? Are you having a new 3DS or old? Read guide carefully, getting a black screen when SD is inserted in some certain steps is normal.

**Comment by biscoitinhocomleite** [comment]
Sorry, i just had to delete te exdata form the nintendo 3ds folds and it worked. Actually, i just finished the tutorial, thanks :)

**Comment by jaxrogers2** [comment]
Yeah, 2.1 is pretty non functional. When I downgraded to it, it wouldn't boot with the SD card in, and if I went to system settings and exited (triggered an MCU) I would just get a black hang. So yeah, this 2.1 weirdness is considered stangely normal.
