### ISSUE TITLE
NTRBOOT: People copy files to the wrong SD cards

### ISSUE THREAD

**Issue by jason0597** [Plailect/Guide#1361]
(Primarily single system ntrboot) 
A lot of people copy over the files to their R4i's SD card instead to the 3DS' SD card. They get this mixed up quite frequently. Can it be made more clear which files go to which SD card?

**Comment by Plailect** [comment]
There is only one file. The exact instruction is `Insert your flashcart's SD card into your computer`, followed by `Copy `ak2i_ntrcardhax_flasher_dsi.nds` to your flashcart's SD card`...

**Comment by quantumcat1** [comment]
Any changes made are not good enough, people still have issues with this even now.
