### ISSUE TITLE
Menu links reversed

### ISSUE THREAD

**Issue by Onoitsu2** [Plailect/Guide#1367]
The Site Navigation and Uninstall CFW links are reversed.

Site Navigation points to https://3ds.guide/uninstall-cfw
and
Uninstall CFW points to https://3ds.guide/site-navigation

An easy fix but could be annoying for other languages potentially if it is more than just English pages.

**Comment by Mike15678** [comment]
Plailect already fixed this. The latest commit has been built already and you should be able to see it.
I can verify that this issue was fixed.
