### ISSUE TITLE
What if a old3ds already on sys.ver 2.1.0?

### ISSUE THREAD

**Issue by liangziqi124** [Plailect/Guide#138]
Note that we generally need to downgrade the rednand to 2.1.0, copy downgraded rednand to sysnand, extract OTP on sysnand via browser, do a9lh, and finally restore system.

But for an old3ds already on system version 2.1.0, since it has no HBL setup nor rednand, several steps should be modified if we start directly from extracting the OTP.

Assume that we have extracted the OTP now. Since we don't have a 9.2 "original" system backup, there's no way to restore but update the system to 9.2. After upgrading to 9.2 with a proper method, the steps following should be installing HBL, creating a rednand, and restoring the rednand to sysnand with a9lh. Then the rest would be similar to the original steps.

Are there any problems on above? Or it's totally inaccessible so we still need to upgrade the system 2.1.0 to 9.2.0 then follow the origin steps?

Thank you.

**Comment by Plailect** [comment]
You'd need to cart update to 9.2, or cart update to 4.x and do the 9.2 update instructions.

**Comment by liangziqi124** [comment]
But where is the problem if we directly extract the OTP?
Or the "One click setup" must be performed in order to extract it?

**Comment by maorninja** [comment]
No. First, get the OTP. Then, get a gamecart of 4.x (Luigi mansion), follow the 9.2 update, follow Part 1 and follow Part 5. Doing Parts 2,3 and 4 are getting 9.2, rednand, and 2.1 which you wouldn't need. The only part of part 5 you skip is formatting SD card and restoring your emunand backup
