### ISSUE TITLE
Some suggestions for part 3

### ISSUE THREAD

**Issue by chinhodado** [Plailect/Guide#139]
On step 10 ("Ignore the starter.bin prompt and press A to continue"), I think it's just not A, but you also have to press U/D/L/R (there's a percent indicator on the lower right screen)

On step 13 ("Put your SD card in your computer, then copy all your files back into it"), you should mention to overwrite the `boot.3dsx` file, since after creating RedNAND EmuNAND9 created a `boot.3dsx` file and an `EmuNAND9` folder on the SD card for the homebrew starter pack, which if you don't overwrite, upon boot it will extract a dozen files/folders for homebrew stuffs, which we do not need.

On step 16 ("Open Luma3DS"), it should be mentioned that you can get a black screen, and you should try to reboot.

On step 22 ("Press Y to format your SysNAND"), it's probably worth mentioning that this will unlink sysnand and rednand.

**Comment by Plailect** [comment]
Steps 10 and 13, you weren't supposed to copy the starter.bin which extracted stuff to your SD card.

Step 16, I'll mention this.

Step 22, this is explained at the top of the page...
