### ISSUE TITLE
Working Flashcard Disclaimer

### ISSUE THREAD

**Issue by Majickhat55** [Plailect/Guide#1390]
"Ensure your flashcart is able to launch correctly before starting. Be sure to have any required kernel or firmware files copied to your flashcart’s SD card. Consult your specific flashcart’s instructions for more information"

Is only present on the NTRBooT (3DS Single System) page. Could you please add this to all other pages requiring NTRBoot to be flashed? It only leads to confusion when people using other methods (multiple system, DSi, NDS) don't realize their card is go to go OOB.

**Comment by figgyc** [comment]
would it be a better idea to move this to the general ntrboot page, or all speific methods?

**Comment by figgyc** [comment]
would it be a better idea to move this to the general ntrboot page, or all speific methods?

**Comment by Majickhat55** [comment]
In my personal opinion it would be better suited on all pages. The majority of the people using the guide almost never read things they should.

**Comment by Plailect** [comment]
There's no need to put it on every page.
