### ISSUE TITLE
Can't uninstall boot9strap

### ISSUE THREAD

**Issue by Seba201x** [Plailect/Guide#1397]
When i use the script it shows this 
![img-20171019-wa0010](https://user-images.githubusercontent.com/25125986/31754704-d683d2fc-b46f-11e7-851a-dad87c846672.jpg)
I want to uninstall because luma can't let me open any app because it shows this 
![img-20171019-wa0002](https://user-images.githubusercontent.com/25125986/31754710-f12d26ee-b46f-11e7-90a1-563a3ea944c5.jpg)
I have a new 3ds xl

**Comment by Plailect** [comment]
This means you have a modified secret sector installed to NAND. This really shouldn't occur under normal circumstances, but to repair it you can get a copy of a valid `secret_sector.bin` from https://3ds.guide/a9lh-to-b9s and rename it to `sector0x96.bin`, then copy it to the [S:] drive in GodMode9 (overwriting the existing one).
