### ISSUE TITLE
Can I add Uncart

### ISSUE THREAD

**Issue by Delphi79** [Plailect/Guide#14]
I completed the guide days ago before you added the uncart to the guide. Is there a way for me to add that in? If so at what point in the guide do I need to start from to add it to my current setup or do I need to start from part 1 and redo the entire process?

**Comment by Plailect** [comment]
Copy `Uncart.bin` to `/a9lh/` and copy the current `boot_config.ini` file to the root of your SD card.

**Comment by Delphi79** [comment]
Great thanks so much!
