### ISSUE TITLE
Potential issue downgrading rednand to 2.1.0?

### ISSUE THREAD

**Issue by Dimensional** [Plailect/Guide#140]
Hello. I'm not sure if this has been answered in a different context, but I'm trying to change my system from using GW to A9HL. I used the SafeSysUpdater to downgrade my o3DS a few months back from 10.6U to 9.2U, and then installed the GW emuNand. This system doesn't have any NNID links, so I erased it and followed the steps to install RedNand and Luma. But now downgrading it to 2.1.0U gives the error message, but it doesn't show any NFIRM installation. In fact it doesn't while scanning the files in preparation for downgrading.

Obviously, I can't test to see if it works, due to 2.1.0 not being loadable on RedNand, but I don't want to run the risk of bricking my 3DS if the downgrade actually failed. I've attempted this a number of times, and I'm just unsure if this is known and just needs patience, or if I need to do something else. Looking the log over, it managed to install 70 files, and the 71st isn't finishing. I'm uncertain as to what else needs to be done, but any help would be appreciated. I can provide a copy of the log if requested. Thank you.

Edit: I saved multiple copies of the logs, and it keeps failing on 004003000008f02.

**Comment by solress** [comment]
Are you sure you have updated redNAND? Since if it's 9.2 or lower, you can't downgrade as it will fail.

**Comment by Dimensional** [comment]
Probably. I've been looking around some more, and others had the same problem, claiming they had to update rednand to 11 before downgrading. Which is weird because I didn't need to do that on my n3DS XL.

**Comment by solress** [comment]
anything above 9.2 should work. 9.2 or lower is guaranteed to fail.

**Comment by Dimensional** [comment]
Like I said, my n3DS XL didn't need rednand upgraded to 11. It was on 9.2 and it all worked. But regardless, I'm attempting to do it with rednand on 11.0
