### ISSUE TITLE
Add a section for GM9 usage to generate new friend code

### ISSUE THREAD

**Issue by KumaKuma** [Plailect/Guide#1401]
Deleting ctrnand/data/***/sysdata/00010032 will generate a new friend code and help users avoid formatting their device. 

This issue comes up when users are installing b9s with Dsiware injection System transfer. The guide does not warn about having the same friend code if you restore the nand backup.

**Comment by Plailect** [comment]
Changing the friend code is not the only network thing that formatting does. It communicates with nintendo's servers, so this is not really an adequate workaround to the formatting requirement.
