### ISSUE TITLE
Button get started

### ISSUE THREAD

**Issue by thomleg50** [Plailect/Guide#1406]
![3ds guide 05-19-17](https://user-images.githubusercontent.com/26003687/32063298-1a834106-ba77-11e7-8386-214834bd35ed.png)

This button are missing 
can you return

**Comment by Mike15678** [comment]
The "button" is now on the bottom of the 'Get Started' page, starting with this commit:  [https://github.com/Plailect/Guide/commit/0b17a365dc9e965f3a7653f66e69bd0d4b07d743](https://github.com/Plailect/Guide/commit/0b17a365dc9e965f3a7653f66e69bd0d4b07d743). Please make sure that you have read the whole entire page before making an issue.
