### ISSUE TITLE
Use luma to install boot9strap with ntrboot instead of only safeb9sinstaller

### ISSUE THREAD

**Issue by Seba201x** [Plailect/Guide#1410]
If you put luma as boot.firm and safeb9sinstaller in Luma/Payloads is more fast to install, you trigger ntrboothax and complete luma config and press start immediately and safeb9s starts!

**Comment by Plailect** [comment]
This would introduce the danger of people thinking they've done everything (without reading properly) and updating their systems

**Comment by Seba201x** [comment]
Oh i didnt thinked that, you're right
