### ISSUE TITLE
Part 4 suggestions

### ISSUE THREAD

**Issue by chinhodado** [Plailect/Guide#142]
Step 16 ("Press down once to select FBI_inject_with_banner.app, then press A to inject"): you actually need to press all U/D/L/R/A. Screenshot:
![image](https://cloud.githubusercontent.com/assets/1388219/15417469/37d38202-1e24-11e6-9d9b-01eb141e4a63.png)

Step 19 ("Open OTPHelper"): should mention that it may black screen and take a few tries

**Comment by Plailect** [comment]
Done.
