### ISSUE TITLE
A9LH to B9S upgrade steps will not work for ancient A9LH users

### ISSUE THREAD

**Issue by chenzw95** [Plailect/Guide#1420]
Per discussion on #meta in Nintendo Homebrew at 14:45 UTC, 1 November, the following commits cause issues for ancient A9LH users due to lack of screeninit functionality:

- b06a8a0
- 186590a
- 4469478

Issue #1411 is related to this, which itself was closed by #1415.

**Comment by jason0597** [comment]
You're late
https://github.com/Plailect/Guide/pull/1421

**Comment by jason0597** [comment]
https://github.com/Plailect/Guide/pull/1421
