### ISSUE TITLE
Part 5 Suggestion

### ISSUE THREAD

**Issue by ZeroGravity83** [Plailect/Guide#143]
On Section VI of Part 5, "Launch Luma3DS Updater and install the latest hourly build" should be added, or "The latest release of Luma3DS(as of now v5.4)" under "What you need" section should be changed to "The latest hourly build of Luma3DS"
These days, many people on gbatemp are reporting issues due to the updated friends module on 11.0, which can be simply fixed by installing the latest hourly build of Luma3DS with the updated friends module patch. Luma3DS v5.4 doesn't have this patch.

https://gbatemp.net/threads/friend-list.427051/
https://gbatemp.net/threads/i-have-a9lh-updated-to-11-00-and-pokebank-says-i-need-to-update-my-system-to-use-it.427309/
https://gbatemp.net/threads/a9lh-luma-friend-list-online-gaming-doesnt-work.427103/
https://gbatemp.net/threads/unable-to-play-super-smash-bros-online-with-11-0-0-arm9-with-1-1-5-update.427234/
https://gbatemp.net/threads/help-error-code-on-friend-list.427227/
https://gbatemp.net/threads/saying-there-is-a-new-system-update.427162/

**Comment by dbw-holic** [comment]
But is hourly build stable?

**Comment by ZeroGravity83** [comment]
Maybe it's not very stable so I get your point, but I think it should at least be mentioned in the guide/FAQ that you can fix the issue by using the latest hourly build of Luma3DS, until Aurora finally releases an official update with the patch.

**Comment by Plailect** [comment]
Done.
