### ISSUE TITLE
r4i Gold 3DS RTS rev6-8 are currently incompatible with ntrboot

### ISSUE THREAD

**Issue by twocows** [Plailect/Guide#1435]
The r4i Gold 3DS RTS flashcarts currently on the market are hardware revisions 6-8 (the latest versions). These revisions are currently incompatible with ntrboot, but there is no mention of this on the flashcart compatibility page at https://3ds.guide/ntrboot

See also:
https://github.com/ntrteam/flashcart_core/issues/9
https://github.com/ntrteam/flashcart_core/issues/75

It sounds like they may be supported in the next few weeks, but currently they're not. This information should be added under the "notes" column for the relevant row.

**Comment by Plailect** [comment]
Those issues are both with non-RTS carts, which i do not list as supported.

**Comment by twocows** [comment]
The cart I'm using is revision 7 and is labeled RTS on the sticker and doesn't appear to work with ntrboot. I don't believe r4ids has offered non-RTS flashcarts for several years (my previous now-dead card was also an r4i Gold and was ordered in 2013 and was labeled RTS). I suspect the issues on the page are just mislabeled and are referring to the later line RTS carts, especially since revisions 5 and earlier work just fine.
![img_20171111_195237626_burst003](https://user-images.githubusercontent.com/6536741/32694912-f4d37b46-c71a-11e7-9a75-1921afb644a0.jpg)

**Comment by Plailect** [comment]
That's an "R4i Gold 3DS RTS Plus", which I do not believe is compatible

**Comment by twocows** [comment]
That's my bad, I didn't even realize they were distinct. It does restore to a functional state from the A7 firmware backup on the guide, though.

**Comment by twocows** [comment]
It looks like this cart's kind of strange. It seems to have two boot modes, I'm guessing the flashcart mode runs off the old A7 firmware and the ntrboot mode uses something custom. There's a switch on the PCB to switch between the two modes. I'll have to tool around with it a bit.

**Comment by twocows** [comment]
Got it all working, though I had to restore the flash cart firmware from an actual backup instead of the A7 one in the guide. So you can add the r4i Gold RTS Plus to the working list, but you might want to add to the notes that it requires you to flip a switch on the PCB, which itself requires opening the flash cart's case (not too hard to do, but might throw some people).

**Comment by jason0597** [comment]
The carts with a switch on them are a special case. If you do have one, then you will just jump ahead to the installing-boot9strap-(ntrboot) page, [As the guide mentions.](https://image.prntscr.com/image/_HUDiupTSaiEXnBlGBjrFw.png)
