### ISSUE TITLE
Specify that the region changing guide (https://3ds.guide/region-changing) can be used for EmuNAND, and in what places you have to change in order to do it for EmuNAND.

### ISSUE THREAD

**Issue by FrootyRamn** [Plailect/Guide#1441]
Thanks! Might also want to specify that the title backup script probably won't work for EmuNAND (haven't tested it tho)

**Comment by jason0597** [comment]
The ctr_transfer_ticketcopy.gm9 script would need modifying as it is hardcoded for sysNAND right now. Or perhaps provide an emuNAND one (however this won't account for multi-emuNAND setups)

**Comment by Plailect** [comment]
The guide does not support the creation or use of EmuNANDs beyond moving them to SysNAND.
