### ISSUE TITLE
Dangling reference to DS version

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#1444]
The ntrboot guide has a paragraph:

> Flashing ntrboot (NDS)
> 
> This method requires temporary access to a Nintendo DS or Nintendo DS Lite that is compatible with your flashcart. This method uses the flashcart to run the ntrboot flasher .nds file on your NDS. This means that your flashcart must support launching .nds files on your NDS’s version. See the flashcart table above for more information.

No such information is in the flashcart table above (and all flashcarts support launching .nds files on your NDS).

**Comment by arromdee** [comment]
This is still a problem.  The above change fixes ir in https://3ds.guide/flashing-ntrboot-(nds) but it's still a problem in https://3ds.guide/ntrboot

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/4940c712e819bb835a16717ba55f0f58d8eeb03c
