### ISSUE TITLE
The picture in installing-boot9strap-(ntrboot) has a 3ds folder when it shouldn't have one

### ISSUE THREAD

**Issue by jason0597** [Plailect/Guide#1450]
![img](https://image.prntscr.com/image/jQESrl5XSvazOmt8vSzDkQ.png)

This is a leftover from when starter.zip was removed from the guide

**Comment by jason0597** [comment]
Here's a modified image

![img](https://i.imgur.com/sV5pG73.png)

**Comment by Plailect** [comment]
This is more complicated as several images have this problem.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/5e49b41031c1397e13f9f2649d482679ff72edf3
