### ISSUE TITLE
Some wrong information about ntrboot cards

### ISSUE THREAD

**Issue by Einhuman197** [Plailect/Guide#1452]
Just reposting for a friend, he doesn't have github. 

![img_20171122_200456-1](https://user-images.githubusercontent.com/33909943/33145537-093d6dc2-cfc1-11e7-8f63-c46c61f21655.jpg)

**Comment by Plailect** [comment]
Is the R4i B9S timebomb date known?

**Comment by Plailect** [comment]
Counterfeit R4iSDHC carts are not supported. I can't reasonably be expected to list every single site that sells them. The line "only original listed flashcarts are supported" should be enough to cover that.

**Comment by Einhuman197** [comment]
-the timebomb has the same date as r4isdhc.com
-2013 cards have a different hardware and a different Kernel (wood): https://web.archive.org/web/20130709182707/http://www.r4isdhc.com:80/r4-product the sticker says "new" but the download page says "2013": https://web.archive.org/web/20131022235620/http://www.r4isdhc.com:80/download_white_new2013/
-Whatever "counterfeit" means these days. It would be helpful to say "only r4isdhc.com is supported" or something. Are you sure that r4isdhc.com is "original" and not another site?

**Comment by kitling** [comment]
1. The timebomb existing sounds about right, it's somewhere in 2019, right?
2. The 2013 cart... I remember someone saying something of the sort. Apologies for failing to convey that information, @Plailect. Off the top of my head it's the same as the r4isdhc.hk and r4igold.cc carts, but I haven't checked today to make sure.

**Comment by Einhuman197** [comment]
@kitling In the off topic 3ds hacking discord channel, there are two independent proofs that the card has a time bomb. Between 6 and 6:15 pm UTC+1

**Comment by Plailect** [comment]
@Einhuman197 huh? Timebombs are when the cart stops working after a specific *date*, not a time of day.

**Comment by kitling** [comment]
@Plailect he's probably referring to the time it was posted in the discord.

Looking around, are you referring to the timebomb in 2020 mentioned in #off-topic? @Einhuman197

**Comment by Einhuman197** [comment]
@Plailect nah, I mean you can find the proofs there :D. I think the timebomb is Q3 or Q4 2019

**Comment by Plailect** [comment]
If it matches the others, it'll be September 3, 2019

**Comment by Einhuman197** [comment]
Yep, then it's Sep 3.
