### ISSUE TITLE
Add a warning to Uninstall CFW guide that it isn't the solution to issues

### ISSUE THREAD

**Issue by KumaKuma** [Plailect/Guide#1466]
There have been users in the Nintendo Homebrew discord thinking uninstalling CFW is a solution to issues which is almost never the case. This can result in undesirable consequences like not being able to reinstall CFW thus locked out of actually fixing the issue.

It would be nice if there is a large red disclaimer that says something in the line of uninstalling CFW is almost never the solution to any issues, and to visit the troubleshooting page or the discord server before they do anything unnecessary.

**Comment by jason0597** [comment]
this happens in gbatemp as well
