### ISSUE TITLE
How many tries does it take to downgrade from 10.7 to 9.2 just wondering BECAUSE I'VE TRIED IT OVER 80 FUCKING TIMES!

### ISSUE THREAD

**Issue by NetWorths** [Plailect/Guide#147]

**Comment by ihaveamac** [comment]
what entry point are you using?

**Comment by NetWorths** [comment]
Ninjhax.

**Comment by ihaveamac** [comment]
what's the specific error you're trying to get, "HAX INIT" with PlaiSysUpdater?

**Comment by NetWorths** [comment]
No, it's just erroring to tell me to turn off my system is it bricked or something?

**Comment by ihaveamac** [comment]
you get something like "An error has occurred. Hold the POWER button..."? when does it happen?

**Comment by NetWorths** [comment]
Hold on.

**Comment by NetWorths** [comment]
Yes, after the 4 lines of texts of you press y.

**Comment by ihaveamac** [comment]
are you sure you have an updates folder at the root with the correct CIAs for your region?

**Comment by NetWorths** [comment]
Yes, except it's in the 3ds folder.

**Comment by ihaveamac** [comment]
it goes at the root of the SD card

**Comment by NetWorths** [comment]
Thanks.

**Comment by NetWorths** [comment]
Still not working.

**Comment by ihaveamac** [comment]
"Still not working." please explain?

**Comment by NetWorths** [comment]
Still not working after the same texts.

**Comment by ihaveamac** [comment]
so you still get "An error has occurred....." even with the updates folder at the root, that match your region/model and have all the CIAs in it?

**Comment by NetWorths** [comment]
Yes

**Comment by NetWorths** [comment]
It's erroring after it said 'Check update integrity' and the folder is in the root and I think it has all the cia files but I'm not sure.

**Comment by ihaveamac** [comment]
try extracting it again, to make sure that all of the CIA files are in it

**Comment by NetWorths** [comment]
Ok.

**Comment by NetWorths** [comment]
What am I supposed to delete the non-extracted folder.

**Comment by dbw-holic** [comment]
To my eye, it appears to be quite clear that if you get error message after 'Check update integrity', which pretty much indicates CIAs are mismatched.

**Comment by ihaveamac** [comment]
I think it'd show "An error has occurred....." would show if a file was missing and it tried to check it. if a file existed but was corrupted, it would show a specific error for that file.

**Comment by NetWorths** [comment]
So what do I do?

**Comment by NetWorths** [comment]
How do I check if the CIA files are incorrect?

**Comment by maorninja** [comment]
SafeSysUpdater could check it for you. But do us all a favor and only use it to check the update files. There are many bricks reported when downgrading to 9.2 with safesysupdater.
