### ISSUE TITLE
No directions on where to put a script

### ISSUE THREAD

**Issue by Armastan** [Plailect/Guide#1475]
Here:
https://3ds.guide/troubleshooting.html

On the "Removing an NNID without formatting your device" section, it's asked to download a GodMode9 script but never told where to place it.

**Comment by Vikijaka** [comment]
root\gm9\scripts\*.gm9

**Comment by Armastan** [comment]
I know where to place the script, the fact is that it's not specified on the guide and some people might get lost. :P
