### ISSUE TITLE
Clarification for emuNAND transfer 

### ISSUE THREAD

**Issue by kidManuel** [Plailect/Guide#1479]
I would like to propose a clarification for the guide.
I had a sd with an old emuNAND build and savegames I intended to transfer. The guide assumes you either keep everything from the emuNAND on the SD card, or you make a nand.bin backup with decrypt9/godmode9. My idea of a backup was just copying every file from the SD card to my PC, leading me to lose my savefiles. 
So my suggestion would be to add a "You need a nand.bin file before starting if you wanna transfer you emuNand" in the "Getting Started" chapter, or in the "Move Emunand" section.

**Comment by Plailect** [comment]
It does not require a `nand.bin` file. It uses GodMode9's virtual file interface to read from the EmuNAND directly (which is named `nand.bin` in the menu, but is not really a file on the SD card). If the instructions are followed exactly as indicated, no data will be lost.
