### ISSUE TITLE
Can I just skip steps 18 & 19?

### ISSUE THREAD

**Issue by NetWorths** [Plailect/Guide#148]

**Comment by ihaveamac** [comment]
steps 18 and 19 of what part?

**Comment by NetWorths** [comment]
Part 2.

**Comment by ihaveamac** [comment]
>When you have booted, change your theme to anything else, then change it back to remove the old menuhax version
Reinstall menuhax using browserhax and the HomeBrew Launcher (you do not need to reconfigure, just press install in menuhax_manager)

you can probably skip menuhax install, if it's already working for you on 9.2 now.

**Comment by NetWorths** [comment]
I've never had menuhax still can skip?

**Comment by ihaveamac** [comment]
you probably shouldn't skip these (or any) steps.

**Comment by NetWorths** [comment]
Ok but why won't browserhax work for me on firmware 9.2?

**Comment by ihaveamac** [comment]
if the issue is it keeps crashing,

try picking your version at http://smealum.github.io/3ds/#otherapp and download ropbin. place it at the root of the SD and rename it to `browserhax_hblauncher_ropbin_payload.bin`.

**Comment by NetWorths** [comment]
It doesn't crash it won't do nothing when I go to the link also I got nothing of browserhax on my sd card.

**Comment by NetWorths** [comment]
What do I do I need browerhax to complete Part 2.

**Comment by ihaveamac** [comment]
Old3DS? there's a slider you probably need to tap...

**Comment by NetWorths** [comment]
What slider? What do you mean?

**Comment by ihaveamac** [comment]
if you're using Old3DS there is a slider on the page you need to tap. zoom in, and tap the very right edge of it.

**Comment by NetWorths** [comment]
It won't let me install menuhax

**Comment by ihaveamac** [comment]
.......and what kind of error do you get?

**Comment by NetWorths** [comment]
It says to verify multiple things.

**Comment by NetWorths** [comment]
It failed to get the body size of the body-filepath

**Comment by NetWorths** [comment]
The error code is 0x00000002

**Comment by ihaveamac** [comment]
try getting a new menuhax_manager, since it can't seem to find the right file...

https://github.com/yellows8/3ds_homemenuhax/releases

**Comment by NetWorths** [comment]
Do I put it in the root or the 3ds folder?

**Comment by ihaveamac** [comment]
place menuhax_manager in "3ds", replacing the older one.

**Comment by NetWorths** [comment]
ok

**Comment by NetWorths** [comment]
Done and thanks
