### ISSUE TITLE
Update Sysupdater version for 10.4+

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#15]
Flagrama releases weekly builds of the 10.4+ version of Sysupdater at http://larbob.com/build/sysupdater/ every Wednesday. Today, he released a new version that adds better compatibility for 10.7 downgrading (direct download can be found at http://larbob.com/build/sysupdater/working/sysupdater-10-7-3152016442.zip. This version should probably be in the guide for downgrading, perhaps alongside the older March 8 build you already have included, for the sake of 10.7 users.

**Comment by Plailect** [comment]
Done
