### ISSUE TITLE
Issue with luma3ds and a9lh region free

### ISSUE THREAD

**Issue by jem4687** [Plailect/Guide#150]
I recently installed a9lh and luma3ds following your guide and have had issues with installing things using shameless and FBI, I am able to install things that have the ALL region but anything else fails. I have set luma3ds to emulate region also. Not sure if this is a valid issue for you but thought I would try and ask seeing as you have also contributed to FBI.

**Comment by Plailect** [comment]
Not sure, talk to steveice10 or open an FBI issue.
