### ISSUE TITLE
Isn't it already updated to 11.0

### ISSUE THREAD

**Issue by maorninja** [Plailect/Guide#152]
I have been noticing that you say the following:

"If your RedNAND / EmuNAND has been updated to version 11.0.0 or higher, you must either put the NTR firmware.bin from Part 3 into the /luma/ folder or restore your EmuNAND from a backup of an older version to be able to downgrade. This is because 11.0.0's FIRM broke downgrading."

But all 3DS have been updated to 11.0. On part 3 you said:

"28. Update your RedNAND to the latest version using system settings"

And on Part 4:

"6. Update your RedNAND to the latest version using system settings if it is not already."

**Comment by Plailect** [comment]
Yeah, that info was redundant. It's been removed.
