### ISSUE TITLE
Problem on Part 3 Step 27.

### ISSUE THREAD

**Issue by NetWorths** [Plailect/Guide#153]
I don't know what's wrong.

**Comment by khang06** [comment]
Please give a screenshot or at least something.

**Comment by NetWorths** [comment]
It won't show Emu in the System Setting.

**Comment by astronautlevel2** [comment]
This isn't a support forum.

**Comment by Plailect** [comment]
Stop opening issues for pointless or trivial questions and wasting my time.

Seriously, what the fuck?
