### ISSUE TITLE
Luma3DS isn't working

### ISSUE THREAD

**Issue by NinjaOreoStar** [Plailect/Guide#157]
There is no Luma3DS.dat, 3ds folder, or the /luma/ folder in the Luma3DS-5.4.zip file. The only files in the .zip are folders and other files:
CakeBrah
CakeHax
Injector
Loader
Patches
Pathchanger
screeninit
source
Makefile
linker.ld
README.md
LICENSE.txt
icon.png

**Comment by astronautlevel2** [comment]
Download the release rather than a zip of the source.

**Comment by NinjaOreoStar** [comment]
@astronautlevel2 how

**Comment by nickthegamer5** [comment]
Download this https://github.com/AuroraWright/Luma3DS/releases/download/v5.4/Luma3DSv5.4.7z

**Comment by nickthegamer5** [comment]
Fixed #157

**Comment by nickthegamer5** [comment]
Close #157

**Comment by nickthegamer5** [comment]
fixed #157

**Comment by nickthegamer5** [comment]
That's should work
