### ISSUE TITLE
Question about part 3-4 + 1, Contradicting/confusing statements between them.

### ISSUE THREAD

**Issue by the100guy** [Plailect/Guide#158]
At the end of part 3, it says to update RedNAND to current version. As of writing this, that is version 11, and a line in part 1 says that a hardmod is required to downgrade this version. Part 4 requires me to downgrade the updated RedNAND to 2.1.0 in order to get the otp. If version 11 is non-downgradable, Then how the heck do I do this without a hardmod? Part 4 never mentions needing one for this particular circumstance.

**Comment by ihaveamac** [comment]
11.0 "stock" is what needs a hardmod to downgrade. if you use the firmware.bin then you can downgrade 11.0 RedNAND.

**Comment by the100guy** [comment]
Cool, thanks a lot.
