### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by the100guy** [Plailect/Guide#159]
Just completed the guide, and noticed that the health and safety, which is now FBI, still has its old health and safety icon. I noticed that in part 4 where I formatted to unlink the NANDs, health and safety had the FBI icon instead of the warning symbol it has by default. If I format using tinyformat, will it reset it back to the FBI icon? And also will tinyformat remove A9LH?

**Comment by jaxrogers2** [comment]
If you want your Health and Safety Icon to be restored to its former generic yellow warning sign glory after injecting FBI into it, you can use this guide: https://gbatemp.net/threads/tutorial-clear-3ds-icon-cache-useful-for-universal-inject-generator-users.427993/ NOTE: This requires FBI 2.0 or higher and requires Godmode9 loaded through the A9LH payload (.3dsx version will NOT work for this) if you get a "file in use" error in FBI. 

If you want the FBI logo back, I guess you might be able to take the corresponding extdata folder with the icon working and copy it over to the one without the icon. This might only work with a sysNAND and an emuNAND on the same firmware version, I haven't ever tested this so don't do it. I don't want to be responsible for a brick. I'm just throwing an idea out there that might work but probably doesn't.

**Comment by dbw-holic** [comment]
I don't really know why would people ever want to do that, the hs.app itself has been useless anyway, and having it replaced with powerful tool such as FBI would definitely be the way to go.

**Comment by the100guy** [comment]
I'm saying that I wanted the FBI logo back, rather than having the yellow warning sign (which is rather ugly in comparison) . I still want to keep FBI injected into the app. I was just wondering if formatting again so that the cfw reads from the other emuNAND folder (this was the formatted redNANDs folder) would cause arm9loaderhax to get all messed up. Or if I just restored the already formatted backup, would it still mess up a9lh

**Comment by Ginkyway** [comment]
What I think many people are doing is simply hiding the FBI-injected Health & Safety app away (maybe with the other system apps that you'll never use) and installing and using the CIA version of FBI instead, essentially having two FBI apps on their system.

You get to have a FBI with a proper icon, it makes it much more straightforward to update it than having to re-inject into hs.app and you have a second "backup" FBI just in case anything happens to the CIA one.

That would probably be the simplest and easier to maintain way to achieve the effect you desire.

**Comment by the100guy** [comment]
True, I totally forgot about the fact that there's a CIA of it (despite the fact that that's what I injected into h&s in the first place, lol). And I have another question but I'm thinking I'll just make a new "issue" for it just to keep things simple and not to confuse anything.
