### ISSUE TITLE
Part 2 specifically refers to system version "U"

### ISSUE THREAD

**Issue by Cu3PO42** [Plailect/Guide#16]
Hi there,

on [this wiki page](https://github.com/Plailect/Guide/wiki/Part-2-(Downgrading)) you have "**If you are already on 9.2.0-20U, skip to step 18.**". I would like to suggest you change this so that it is agnostic of the region of a system.

Best regards,  
Cu3PO42

**Comment by Plailect** [comment]
Fixed
