### ISSUE TITLE
On 9.9.0-26u, upgrade to 10.2.0 via sysupdater before downgrade?

### ISSUE THREAD

**Issue by gajewsk2** [Plailect/Guide#160]
According to the guide, I ought to be able to throw oot3dhax on, and be fine downgrading from 9.9.0 to 9.2.0, but I've seen a couple claims that it is safer to use upgrade to 10.2.0 via sysupdater before downgrading. Is this truly safer and worth doing? Would I use just plain sysupdater for this or PlaiSysUpdater?

**Comment by frikisama** [comment]
I was on 9.6 and did the downgrade directly. No problem whatsoever. You should be able to follow the guide as-is, and you don't even need oot3dhax since browserhax should work fine on 9.9.

**Comment by MelonGx** [comment]
Personally I strongly recommend this.
From my discovery & gathered informations, Factory SysNANDs (which are not upgraded by CIA or official Internet upgrade, no matter what version they are) have a nearly 100% "An error occured..." Blackscreen rate on NATIVE_FIRM step of first downgrading.
But Internet upgraded SysNANDs have 0%.

**Comment by frikisama** [comment]
Could this "An error occured.." message be caused by not formatting? This is something the guide mentions. In my case, I formatted just before downgrading, and as stated above had not trouble. Still, YMMV, and by upgrading time is the only thing you loose, so if you have it, go ahead.

**Comment by gajewsk2** [comment]
Been searching aroind but can't find a guide on how to update to a specific version these days. 3DNUS doesnt seem to have any guides.

**Comment by nickthegamer5** [comment]
I downgraded to 9.2 on 10.6 so you should be fine when downgrading.

**Comment by Plailect** [comment]
>According to the guide, I ought to be able to throw oot3dhax on, and be fine downgrading from 9.9.0 to 9.2.0, but I've seen a couple claims that it is safer to use upgrade to 10.2.0 via sysupdater before downgrading. Is this truly safer and worth doing? Would I use just plain sysupdater for this or PlaiSysUpdater?

It doesn't matter, just downgrade directly.

**Comment by gajewsk2** [comment]
Downgraded Directly, got a partial dg. Used oot3dhax to load hb, redowngraded, and all was fine. Thanks.
