### ISSUE TITLE
Japanese eShop error

### ISSUE THREAD

**Issue by HoobertDoobert** [Plailect/Guide#162]
I recently performed the region change on my 3DSXL to Japan. I followed all the steps. I deleted my eShop account before downgrading and I formatted then updated. Now when I go to the eShop I get the error code 005-5602. I do have a NAND back up. Should I restore the NAND and try again or is
there a fix for it?

**Comment by dbw-holic** [comment]
New 3DSXL?

**Comment by HoobertDoobert** [comment]
Nope I have a O3DSXL

**Comment by Plailect** [comment]
What console is it, and does it have any titles installed from the wrong region?

**Comment by HoobertDoobert** [comment]
It's the NES edition 3DSXL. It didn't have anything on it. I restored a NAND backup from a9lh and now I'm back at step one so I'm going to try again and post results later.

**Comment by HoobertDoobert** [comment]
I tried again and I still got the same error code.

**Comment by HoobertDoobert** [comment]
Also I noticed some titles ended with "A"
Should those he deleted as well? I left those out just to be safe.

**Comment by HoobertDoobert** [comment]
Just to add on to this: There were some product codes that ended in "A"
For example
CTR-N-XXXA
I'm not sure whether or not those titles should be deleted as well with the titles from my previous region.

**Comment by Plailect** [comment]
"A" corresponds to region free titles and shouldn't affect anything to my knowledge, but you could try removing them.

**Comment by HoobertDoobert** [comment]
Alright so deleting those CTR-N-___A titles causes it to freeze at the system update part. So that doesn't work either.

**Comment by BOBdotEXE** [comment]
Quick question (Sorry to interrupt)
 
I saw the update to the guide mentions deleting eshop account *Before* formatting.
 
If i'm already region changed, and in the latest update (still without eShop access)
 
Am I too late to get eshop access?

**Comment by HoobertDoobert** [comment]
You can restore a NAND backup from your previous region and try again. I honestly don't know why my 3DS is refusing to go into the eShop even when I followed all the steps.

**Comment by HoobertDoobert** [comment]
I have another question. I'm still stuck on region swap (no working eShop) but I've been thinking. Would renaming the SecureInfo_C to SecureInfo_B affect anything?

**Comment by Plailect** [comment]
It shouldn't. I am unsure as to what could be causing this issue for you, and I am also unsure as to why nobody else seems to be reporting it.

**Comment by zfirered** [comment]
i tought eshop will not working after change region

**Comment by zfirered** [comment]
u can access eshop if the Device it self NEVER access it to eshop before.. 
i did it on N3DS from Japan to USA and its working...

**Comment by zfirered** [comment]
![13275328_1322933301053660_484933602_o](https://cloud.githubusercontent.com/assets/17750324/15803041/7d1d6d96-2af4-11e6-8a68-7d3ec858ae25.jpg)
The White one is Changed Region to USA
The Black one is JAPAN region
these device never access eshop before

**Comment by HoobertDoobert** [comment]
Well that wouldn't make any sense because you need to get into the eShop at one point to delete the eShop account. It's listed on the first paragraph. You delete the eShop account before starting then you format and update when you're finished.

**Comment by Plailect** [comment]
Lacking any other reports or new information, I'm just going to have to chalk this up to a weird server related quirk for you and close the issue. Not much we can do without access to the servers or more info about how this stuff works.

**Comment by aeglon** [comment]
OP did you manage to get this to work? I'm having the same issue on my j2ds. I forgot to delete eshop account beforehand. I restored a9lh backup and started over, making sure to delete eshop account first. Still no access. I get a different error though, 007-2001.

**Comment by HoobertDoobert** [comment]
Never got it to work sadly

**Comment by IcySon55** [comment]
I just performed a region-change on my original O3DS and I too am receiving the 007-2001 error. But I followed the guide and it didn't say anything about deleting the account first...

**Comment by helmergoza** [comment]
estimated friend

i have the same problem with 50 3ds japan to usa, did you get some solution to go to eshop after the change.?
