### ISSUE TITLE
9.2.0 Update Step 33 lacks description of Two-Folder inside Nintendo 3DS

### ISSUE THREAD

**Issue by MelonGx** [Plailect/Guide#163]
In SD://Nintendo 3DS/ folder, there are 2 folders when Unlinked emuNAND exists.
In this case, the guide should teach noobs how to not to create import.db & title.db into emuNAND's folder.

BTW, the guide also needs to teach noobs how to reveal known files' extension in Windows/Mac/Linux.
Because there were some noobs who always created **title.db.txt** like files, then failed fixing database error, then claimed.

**Comment by Plailect** [comment]
This actually isn't needed anymore since FBI now creates the databases automatically. These instructions will be remove.
