### ISSUE TITLE
Can't downgrade 9.2 2DS with 11.0 emu

### ISSUE THREAD

**Issue by Amadren** [Plailect/Guide#164]
Using sysUpdater: 004001000022000.cia install failed with exception "0xD8E08027"

Using PlaiSysUpdater: downgrade failed for nfirm ("An error occured, press button power...." message)

Already tried 12 times to restore emunand and retry

**Comment by willkof2** [comment]
In the luma folder put the firmware.bin correspondent to your console

**Comment by Amadren** [comment]
Really reammy weird.

I already had firmware.bin. I formated everything and tried again from scratch, unlinked nands and downgraded, the same "an error occured...". Rebooted to OTPHelper, used the one click setup, didn't worked, reinjected FIRM0 and FIRM1, retried, it worked.

And... AND.... Bricked. I'll install a hardmod next weekend

**Comment by Plailect** [comment]
You used One Click Setup, everything verified properly, and you can't boot without the SD card in?

**Comment by Amadren** [comment]
Exactly

**Comment by Plailect** [comment]
You are bricked and will need a hardmod, but you should contact @d0k3 about this odd issue.

**Comment by Amadren** [comment]
And what about the failed downgrade for nfirm? Should I make an issue in PlaiSysUpdater repo?

**Comment by d0k3** [comment]
I have an assumption that the system settings (that's the app that did not install properly at first) still did not install correctly. Possible reasons? Some earlier modifications maybe? 

Anyways @Amadren, get back to me once you have that hardmod. Best to join us on freenode #Cakey then.

**Comment by Amadren** [comment]
@dok3, Nope no previous modifications and I don't think of any possible reason, it was my little brother's (4yo) 2DS, I even used a whole new SD Card. And ok, I'll join you on #Cakey when i'll have my hardmod. I'll install it sometimes during next week.
