### ISSUE TITLE
Need to add 1.0 1.1 2.0 2.2 direct OTP guide

### ISSUE THREAD

**Issue by MelonGx** [Plailect/Guide#168]
This wiki only introduces how to dump OTP from 2.1.0-4.
However, OTP can not only be dumped by 2.1 but also be dumped by 1.0 1.1 2.0 2.2.
For 1.0 and 1.1, they don't have valid browser, so we should use other OTP dumper.
For 2.0.0-2, its browser is different from 2.1.0-4, (Edit) Plailect said it had incompatibility so we should use other OTP dumper.
For 2.2.0-4, it should be the same method as current one.

**Comment by MelonGx** [comment]
We can also perform a 9.X upgrade then DG to 2.1 for the final resolution, but this idea sucks.

**Comment by dbw-holic** [comment]
My understanding is that, this guide, has been very helpful and easy-to-use for most of the people, who are interested in getting the console successfully modded. To make sure its usability for the majority, the guide should be kept as simple is it can. If we add all the possibilities as well as feasible solutions to this guide, it will not make any easier for noobs but complicate the guide itself as many people will likely to get lost in front of multiple choices. We already had many issues raised here that were meant to be asked on the IRC channel.

**Comment by dbw-holic** [comment]
I agree that there are people starting with those specific firmware versions, but seriously,  it would be very rare and only very few people encounter this.
I think the current solution (cartridge upgrade) would be the easiest way to keep it running on the track.

**Comment by MelonGx** [comment]
@dbw-holic
No. Noobs can always have a specific console. Writing an additional page to them will not conflict the main guide, but help them with a better route.
If one person have a 2.1.0-4 or 2.2.0-4, there are two routes:

Route One 
- Get OTP directly with OTPhelper
- Use 9.2.0 upgrade guide to upgrade to 9.2.0
- Continue Part 5

Route Two
- Upgrade to 9.2.0
- Follow the full guide which wastes you 80% of steps and several hours

Is route two stupid?

**Comment by MelonGx** [comment]
I can also say it's unfriendly to specific noobs who have specific firmware.
Well, if you guys have problem or rejection on it, I can establish one myself.

**Comment by Plailect** [comment]
Added with #336722c
