### ISSUE TITLE
Removing emuNAND after arm9loaderhax CTRNAND injection (arm9loaderhax & AuReiNAND)

### ISSUE THREAD

**Issue by holddasoysauce** [Plailect/Guide#17]
Upon reaching this step my system has the arm9loaderhax and no longer booting to sysNAND, but the new CFW sysNAND. The next step mentions removing emuNAND but entry is from sysNAND to HBL to emuNAND9. Does it matter that I'm not on sysNAND? I followed the previous revision on another N3dsxl yesterday successfully. I tried on another N3dsReg(AC happy home edition) and noticed step 5 has gone through some revision. The removing emuNAND step is almost unchanged but with the introduction of safea9lhinstaller step sysNAND has become CFWsysNAND. Should I treat the sysNAND part of removing emuNAND and the new CFW sysNAND and boot emuNAND9 through coldboot (L+R+Y) to delete emuNAND off SD?

**Comment by Plailect** [comment]
Fixed in the instructions
