### ISSUE TITLE
Need page for going from Gateway to CFW

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#172]
Issues that would be covered:
-- Cart encryption methods that cause problems if they started on Gateway on 4.x, remind the user to back up cart saves when necessary
-- A link to the document describing how to convert saves from Gateway format, for SaveDataFiler and JKSM
-- [Problems with Luma if the system has had a Gateway downgrade](https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-get-a-black-screen-on-boot-with-an-old-3ds-which-has-been-downgraded-from-the-gateway-menu-in-the-past)
-- Don't run Sysupdater from Gateway (at least not pre-4.0b Gateway)
-- How to go from Gateway a9lh to normal (and possibly a warning to avoid Gateway a9lh to begin with)

Using Gateway and CFW at the same time:
-- Reminder not to update A9LH SysNAND from Gateway
-- How to get an a9lh v2 install that works with Gateway arm9loaderhax.bin (apparently it can be done if you install the correct way)

**Comment by Plailect** [comment]
Honestly, I just don't want to deal with gateway in any way, shape, or form.

I have decided that I will not be making this page, although info on their save encryption stuff has been linked to from the FAQ for a while.
