### ISSUE TITLE
Decrypt9.dat named differently

### ISSUE THREAD

**Issue by ihaveamac** [Plailect/Guide#173]
a few of the 9.2.0-20 update guides use a file called `Decrypt9.dat`, however in the given download for Decrypt9, it is actually named `Decrypt9WIP.dat`.

* https://github.com/Plailect/Guide/wiki/9.2.0-Update-(rxTools-2.5.2) steps 3 and 8
* https://github.com/Plailect/Guide/wiki/9.2.0-Update-(rxTools-3.0) steps 8 and 9

**Comment by Plailect** [comment]
Fixed
