### ISSUE TITLE
homebrew launcher 

### ISSUE THREAD

**Issue by maroko51** [Plailect/Guide#177]
hello, done everything as shown, great tutorial, thanks but there is one thing, i wanted to install some nice themes via CHMM2 but everytime i launch homebrew launcher from my home menu my 3ds freezes. Is there another way to access CHMM2? Thank you.

**Comment by nickthegamer5** [comment]
Download the CCHM2 CIA and install it then boot it.

**Comment by maroko51** [comment]
thank you, i really aprreciate it
