### ISSUE TITLE
chainloading GodMode or EmuNand/Hourglass9 hang with v2 safea9hinstaller

### ISSUE THREAD

**Issue by xuefer** [Plailect/Guide#180]
luma3ds updated to current dev latest (5.5-22dc187)
device: new 3ds LL
a9lh used to work
Hourglass9-20160606-212826.zip
GodMode9-20160502-103931.zip

I've just "re"install a9lh using updated v2 version of files:
with old files removed. then extract data_input_v2.zippayload_input_v2.zip /a9lh/, place my otp.bin
copied arm9.bin arm11.bin from SafeA9LHInstallerv2.0.zip to sdcard root folder
copied arm9loaderhax.bin from SafeA9LHInstallerv2.0.zip to /luma/left_a9lhinstaller.bin
hold LEFT, press START. got into new a9lh installer, press SELECT so it got updated
results are: it boots luma3ds fine into 3ds menu. able to show luma3ds config menu by holding SELECT when when booting on
but if i hold RIGHT to boot GodMode, Y for EmuNand, the screen goes black. or START for Hourglass9 it hang after "checking arm9loaderhax ... success"
X for uncart and LEFT for A9LH installer works

maybe those chained payload that hang need a new release?

**Comment by Plailect** [comment]
https://www.reddit.com/r/3dshacks/comments/4n695x/_/d415mta

Guide has been reverted to v1 until this is resolved.
