### ISSUE TITLE
Comments on 9.2 update (II)

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#181]
(Also posted in the Reddit thread)

Changing section 5 to directly install a9lh on 2.1 prevents the instructions from working for people starting on 1.x and 2.x. If they try to follow it, they will get the OTP, then skip to step 5, install a9lh on 1.x or 2.x, and then not have anything to copy to SysNAND. (I believe that Luma now allows recovery mode without breaking a9lh so they could update to 11.0 using recovery mode. Would that work, if they are on 1.x/2.x?)

Cart update should tell the user not to be connected to the Internet while doing the cart update.

The 9.2.0 update section ignores the possibility of the user being on 2.2, which [does seem to exist.](https://www.3dbrew.org/wiki/2.2.0-X).

Also, has it been confirmed that 9.0-9.2 with low browser has a problem with Ninjhax?

**Comment by Plailect** [comment]
>Changing section 5 to directly install a9lh on 2.1 prevents the instructions from working for people starting on 1.x and 2.x. If they try to follow it, they will get the OTP, then skip to step 5, install a9lh on 1.x or 2.x, and then not have anything to copy to SysNAND. (I believe that Luma now allows recovery mode without breaking a9lh so they could update to 11.0 using recovery mode. Would that work, if they are on 1.x/2.x?)

The steps don't have them install a9lh on 2.X at all if they're already there, if you read the chart.

"for 2.1.0 get your OTP **do the following** then skip to Part 5 - arm9loaderhax (ignore Sections IV and V)"

>Cart update should tell the user not to be connected to the Internet while doing the cart update.

Yellows8 told me this doesn't matter.

>The 9.2.0 update section ignores the possibility of the user being on 2.2, which does seem to exist..

Their only option is Cubic Ninja, 2xrsa doesn't work on 2.2

>Also, has it been confirmed that 9.0-9.2 with low browser has a problem with Ninjhax?

I have gotten no reports of this.

**Comment by arromdee** [comment]
My criticism was wrong, but even following the proper steps won't work.

For 1.x-2.x they will
-- get OTP
-- cart update (leaves them on 4.x/6.x)
-- rxtools (leaves them on 9.2)
-- skip to part 5

But here the difference between the old and new versions of the guide matter.  The old version of the guide has part 5 assume they were on 9.2.  The new version of the guide has part 5 assume they are on 2.1.  Because they upgraded from 1.x-2.x, but then skipped part 4 which downgrades, they are not on 2.1, they are on 9.2.  For instance they cannot follow the part 5 step "Reinsert your SD card into your 2.1.0 3DS".  Also, they cannot perform the step "Copy emuNAND_original.bin and emuNAND_original.sha ..." from part 5 section I.

It might be even easier if they are on exactly 2.1.0-4.  They should be able to get the OTP, avoid cart update/rxtools, and install a9lh on 2.1.  However, I don't know if that works, because Luma can't run 2.1, so they may not have a way to get out of 2.1.  Is Luma capable of running recovery mode on 2.1?

**Comment by Plailect** [comment]
Luma cannot boot *anything* on 2.1.0, and neither can any CFW. As for part 5 and cubic ninja, I have updated the chart.

**Comment by MelonGx** [comment]
Need to separate 4.0.0 out of 4.X.X because it's unable to be directly booted.

**Comment by arromdee** [comment]
The 4.0 section has 6.0 cart update + 6.0 mset, or 4.0 mset.

Is there *ever* a situation where 6.0 cart update+6.0 mset has any benefits over just using 4.0 mset?

**Comment by Plailect** [comment]
Nope, but it's still technically a valid option
