### ISSUE TITLE
Missing Health and Safety Question

### ISSUE THREAD

**Issue by m0nm0npalam0n** [Plailect/Guide#182]
i have already done this before on my n3DS and it works very well. Thanks for this. i am planning to do this on a 2nd hand o3DS (E) that i just recently bought i just noticed that it was missing the Health and Safety App. Just wanted ask if this will still work? Thanks.

**Comment by Plailect** [comment]
Part 3 has you update RedNAND, which will install the H&S app if it doesn't exist.

**Comment by m0nm0npalam0n** [comment]
Thanks.
