### ISSUE TITLE
[Enhancement] Add how to update your a9lh

### ISSUE THREAD

**Issue by nickthegamer5** [Plailect/Guide#186]
(I don't know how to add labels :P)After the new a9lhsafeinstaller brick thing being fixed and a new a9lh payload(I don't exactly know what to call it) made, I was wondering how do I update it? I already got luma3ds a9lh so it can't be that hard. Also I haven't found a tutorial on how to do it yet

**Comment by Plailect** [comment]
Added :D

**Comment by nickthegamer5** [comment]
@Plailect Add this to the update guide. https://github.com/OperationNT414C/CtrBootManager/releases/tag/V7 <--- that version of ctrbm works with payload 2.1.
