### ISSUE TITLE
Dumping Emergency files when installed A9LH using old version of the guide

### ISSUE THREAD

**Issue by TheNain38** [Plailect/Guide#187]
You could add a section for 3DS which already have A9LH installed but using an old version of your guide, to dump the emergency files, you just need to boot the OTPHelper.bin payload, and go to: "NAND Backup & Restore" and here, choose: "Dump Emergency Files".

**Comment by Plailect** [comment]
This really isn't needed once a9lhax is already installed and they have functional backups.
