### ISSUE TITLE
If on 9.2.0 already, the guide should say skip up to step 21

### ISSUE THREAD

**Issue by wrsg** [Plailect/Guide#189]
https://github.com/Plailect/Guide/wiki/Part-2-(9.2.0-Downgrade)

It seems like the correct step to continue from if the fw is already 9.2.0 would be 21, not 18

**Comment by wrsg** [comment]
or step 22 maybe, since we're already on 9.2.0 anyway

**Comment by Plailect** [comment]
Fixed
