### ISSUE TITLE
Guide issue

### ISSUE THREAD

**Issue by Guardian9978** [Plailect/Guide#190]
I'm modding a New Nintendo 3DS and have followed all the steps up to "Part 5 (arm9loaderhax)" "Section II - Installing arm9loaderhax" and have ran into a issue with the third step "Select Full Install" which OTPHelper does not have. Isn't there a full section about dumping the otp.bin file missing?
Since the next step is to copy the otp.bin from the a9lh to the root of the sdcard.

**Comment by garbage911** [comment]
It's part 4 that is missing information.  Basically, the guide ends at downgrading the EMUNAND to 2.1.0.  Previously, the guide in part 4 continued to show you how to clone EMUNAND to sysnand and extract the OTP.

I presume it might be revised soon.  However, it shouldn't be a problem as EMUNAND should be safe.  Just do not clone it to sysnand for now.  => basically stay on part 4 of the guide and wait for it to be updated.

Your sysnand should be on 9.2; you emunand will be on 2.1  if all goes well.

**Comment by nickthegamer5** [comment]
You should already be on 2.1 and OTPhelper should not of opened, SafeA9LHInstaller should of opened instead so you copied the wrong folder. You should be carful for what you do, people have bricked  when keeping n3ds in sleep mode for awhile.

**Comment by Plailect** [comment]
You don't need to dump the otp in part 4 as part 5's installer dumps it automatically.

**Comment by garbage911** [comment]
thank you for the clarification
