### ISSUE TITLE
9.2.0 update guides should not include New3DS packs

### ISSUE THREAD

**Issue by ihaveamac** [Plailect/Guide#192]
no New3DS system (besides JPN, but that's a special case) would come below 9.0.0-20, so having packs for it to update to 9.2 is confusing.

[I've already seen at least one person brick because they mistakenly used the wrong one](https://gbatemp.net/threads/using-rxtools-but-cant-upgrade-it-to-the-latest-due-to-how-low-my-firmware-is.430763/page-2#post-6445467), so they should be removed.

**Comment by Plailect** [comment]
Updated
