### ISSUE TITLE
Formatting after having followed the guide

### ISSUE THREAD

**Issue by bel3atar** [Plailect/Guide#194]
What should I do after I have formatted the console?

**Comment by nickthegamer5** [comment]
What are you trying to do? You finished the guide but you formatted? Formatted what the sysnand or the sd card. Please try to be more clear.

**Comment by bel3atar** [comment]
@nickthegamer5 formatted the console through system settings

**Comment by nickthegamer5** [comment]
Where you on luma 5.5 when you formatted?

**Comment by bel3atar** [comment]
@nickthegamer5 yeah, I just finished the whole guide today

**Comment by nickthegamer5** [comment]
I don't get what your trying to do, you said you System formatted, but what are you trying to do?

**Comment by bel3atar** [comment]
@nickthegamer5 I am trying to restore all the homebrew functionality (FBI, HBL... etc)

**Comment by FenrirWolf** [comment]
I don't believe that injected FBI would have been killed by the format. Even if it were, all you would need to do is boot Decrypt9 and re-do the injection process. From there you can proceed to reinstall other CIAs.

**Comment by bel3atar** [comment]
Cool thanks.
Closed?

**Comment by bel3atar** [comment]
One more thing: what if a new system version from Nintendo is out, would it be safe to upgrade?

**Comment by FenrirWolf** [comment]
Updating has generally proven safe, though not always without complications such as when firmware 11.0 killed svcbackdoor. That was worked around later on, though it was a source of inconvenience for a bit.

Either way, you can always make a NAND backup prior to updating and thereby have the option of rolling back.
