### ISSUE TITLE
nfirm fail after during downgrade to 2.1

### ISSUE THREAD

**Issue by ryan842** [Plailect/Guide#195]
HAve an issue when im downgrading to 2.1.
Have a 2ds console and the downgrade always stops at the nfirm.
Have followed the guides exactly, not sure how to proceed. Any help will be much appreciated.
cheers

**Comment by ryan842** [comment]
issue has been solved.

you need to place
Luma3DS NTR firmware bin from part 5 in the luma folder.

**Comment by Plailect** [comment]
Use the latest Luma version.
