### ISSUE TITLE
Guide on Updating from AuReinand version to Luma3DS

### ISSUE THREAD

**Issue by m0nm0npalam0n** [Plailect/Guide#197]
I have used the previous version of this guide that uses AuReinand and i wanted to change to Luma3DS. Please add instructions on how can it be done. Thanks.

**Comment by nickthegamer5** [comment]
Where you running AuReunand as emunand?

**Comment by m0nm0npalam0n** [comment]
No. It was already my Sysnand.

**Comment by nickthegamer5** [comment]
So you already got A9LH, hmm. I think you can just download the luma3DS drag over the luma folder, put the NTR firm file into the luma folder and replace the a9lh launcher file. It should work fine because Luma is just a fork of it.

**Comment by nickthegamer5** [comment]
You should also add the payloads and back a backup of your sysnand just in case :3

**Comment by m0nm0npalam0n** [comment]
Yes i already go A9LH. okay. Maybe I'll try it. i want a clean setup tho :3 Thanks

**Comment by Plailect** [comment]
@nickthegamer5, thanks for the help with the support questions :D

**Comment by m0nm0npalam0n** [comment]
@nickthegamer5 @Plailect I am unable to backup cause the shortcuts/homebrews are not working. do i need to update something?

**Comment by nickthegamer5** [comment]
The payloads are not loading odd, you may have of spelled them wrong they should be like y_uncard start_Hg9 if they are sorta like they you forgot to rename them. If that does not work the payloads should be in luma/payloads(also make sure you got a firmware.bin in the luma folder). Beside that I can't think of anything else beside you using the wrong payload from the rar or it got corrupt.

**Comment by nickthegamer5** [comment]
I found out what your issue is just give me a few hours because it's 12 pm where I live :P

**Comment by m0nm0npalam0n** [comment]
I was already able to access Luma3ds menu, hourglass, uncart and emunand9.. thanks.. but just wondering why the homebrews like Decrypt9WIP wont load.. i've already downloaded the current version and updated the files on the 3ds folder

**Comment by m0nm0npalam0n** [comment]
sorry to bother you @nickthegamer5 .. i really appreciate your help.. thank you very much

**Comment by nickthegamer5** [comment]
That's your problem right there :P when you download decrypt9WIP there will be a .bin .nds .dat and a 3ds. Now the .bin files for for a9lh payloads so you just copy it and past it into the luma/payloads, then rename it to up_decrypt9.bin

There is no need to boot trough home brew channel with a9lh(sorta):p

**Comment by m0nm0npalam0n** [comment]
Oh i see.. thank you very much @nickthegamer5
