### ISSUE TITLE
Step 4 point 35

### ISSUE THREAD

**Issue by wrsg** [Plailect/Guide#198]
Sorry but I thought it might be better to be clear i.e. we reboot back to RedNAND at this point, right?

**Comment by nickthegamer5** [comment]
Not needed but @Plailect can add it if he wants to.

**Comment by wrsg** [comment]
There were a couple of other points where the next step wasn't clear, should I mention them all here? Or separately? I think it makes sense just to list them here or probably just send a PR...

**Comment by Plailect** [comment]
Considering 32 says specifically to "Reboot back into RedNAND", yes
