### ISSUE TITLE
[Enhancement] Add page for switching CFW

### ISSUE THREAD

**Issue by nickthegamer5** [Plailect/Guide#199]
After the last problem I solved where he wondered how he could change is current CFW to luma 3DS I was thinking for a long time and after quite a bit of typing I made a semi compleat page for it which you can download [here](https://mega.nz/#!61xTnRLR!mQjTAEtLK0pslyv__stKsJ0mCIvRWBBmfgx3NDp_fsQ)(Its a .md file). I would have done a Fork then Pull but when I tried to fork it, it didn't copy the wiki :/. I wanted to know if it was good and if it is I'll fix it up and work on it some more. Just wanted to make sure before I finish it :3

Also, the reason I put [Enhancement] in the title is because I don't know how to add tags :p

**Comment by Plailect** [comment]
I really like the idea, but I really don't want to do it the right way and account for all possible CFW configs people are switching from (just see the 9.2.0 Update page for how accounting for all possibilities is complicated), and I don't want to do it if it's not done right.

I have nothing against the idea, but honestly it's just not worth it when [Luma's wiki](https://github.com/AuroraWright/Luma3DS/wiki) covers pretty much everything anyways.
