### ISSUE TITLE
A warning to potential users of this guide

### ISSUE THREAD

**Issue by historikal** [Plailect/Guide#2]
Be wary of using this guide. During part 3 of the guide, there is a section where you're first installing ReiNand. According to the guide, only way to check to see if ReiNand is installed correctly is if you boot up to the home screen when launching ReiNand from Homebrewlauncher. The guide does not provide any other way to see if you're on your EmuNAND or your SysNAND. Then the guide tells you to update your system, which can basically result in your 3DS being updated to the latest firmware so that you can no longer install any homebrew on it. I would suggest using one of the guides on gbatemp or finding another more, clearly written guide,

**Comment by Plailect** [comment]
This will only happen if you leave system settings (which you are not instructed to do), which would reboot you back into SysNAND.  If you follow all instructions (the "on EmuNAND" is even bolded), you will be fine.

Just in case following instructions is not enough, I have added steps to use a different theme on each to tell them apart.
