### ISSUE TITLE
Arm9loaderhaxInstaller Problem

### ISSUE THREAD

**Issue by Pokemaster623** [Plailect/Guide#20]
When I used the installer my sysnand didn't look different (I didn't know if it was supposed to) and decrypt9 didn't work.

**Comment by Plailect** [comment]
It doesn't look different until you move the CTRNAND partition. You need to boot Decrypt9 with arm9loaderhax.

**Comment by Pokemaster623** [comment]
Decrypt9 isn't opening I just gives me a black screen while holding L+R and booting.

**Comment by Plailect** [comment]
Copy the file again
