### ISSUE TITLE
TWL modifications

### ISSUE THREAD

**Issue by Azebu** [Plailect/Guide#200]
The TWL modifications are mentioned in one place, and there is really barely any information on them. After a bit of googling and asking around I managed to learn they're related to DS mode. 
While the guide mentions you have very small chance of having such modifications, there could be an instance where you installed something years ago and forgot, or bought used console. 
There isn't words of encouragement that if you do have TWL mods and proceed, nothing bad will happen, either.

I suggest elaborating on that a bit, mentioning common TWL mods, and clearing up on what DSmode stuff is popular but isn't TWL mod, and if you do happen to have one, how to get rid of them.

Personally, I've installed flashcarttimewarp.cia before, and maybe bluecardfix.cia too, I can't remember. And I've had quite a pickle as there is barely anything that I could find via googling, nobody talking about similar concerns or problems, and nobody from eager to help people really knew if this can mess things up.

**Comment by nickthegamer5** [comment]
It would be nice to link to a guide that removes the TWL modifications

**Comment by nickthegamer5** [comment]
I found this https://gbatemp.net/threads/arm9lh-preperations-remove-any-twl-modifications.417998/ not realy a guide but if you go down abit it shows you how to remove them

**Comment by Plailect** [comment]
Added :D
