### ISSUE TITLE
OTPHelper 0.90 Questions

### ISSUE THREAD

**Issue by ThunderRemix** [Plailect/Guide#202]
I know I already did the guide, but https://github.com/Plailect/Guide/wiki/Part-4-(2.1.0-Downgrade) says to use the latest version of OTPHelper. The current latest version (0.90) says that it "Removed SysNAND partition dumping / injecting" yet the guide says to dump Sysnand. I ended up using 0.89 instead because someone said 0.9 didn't work for them, so I don't know if 0.9 would have worked or not. Just want to let you know.

**Comment by Plailect** [comment]
Partition dumping and injecting, not the entire nand.
