### ISSUE TITLE
uncart is compatible with a9lh,now

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#203]
https://github.com/citra-emu/uncart/commit/1577f365f66ffe0f6835539839d1053655a2b6dd
No official release,so I don't know if it can be added...

**Comment by nickthegamer5** [comment]
Uncard has always been compatible with a9lh. I think your looking at the wrong uncart.

**Comment by Plailect** [comment]
@nickthegamer5 we've been using a fork based on unreleased patches, which have finally been merged upstream

I've opened https://github.com/citra-emu/uncart/issues/23

**Comment by nickthegamer5** [comment]
That explains it :P
Also thanks for the heads up so now I can compile the new one for my 3ds.

**Comment by Plailect** [comment]
Added https://github.com/AileSc/uncart/releases, which is current with upstream
