### ISSUE TITLE
Part 3, step 26

### ISSUE THREAD

**Issue by ApolloFortyNine** [Plailect/Guide#205]
https://github.com/Plailect/Guide/wiki/Part-3-(RedNAND)

**Update your RedNAND to the latest version using system settings (Once you exit System Settings / SD Card Management you will be returned to SysNAND, make sure to enter back into RedNAND before updating!)**

If you follow the steps up to this point, you will be in system settings, and therefore be returned to SysNAND. I wasn't paying enough attention here and didn't fully read the whole step before updating.

I think it would make more sense to have the warning before the step, perhaps as it's own step, so as to avoid this happening to any other poor soul.

**Comment by nickthegamer5** [comment]
He already did give a warning, when you leave you will be back in sysnand return to RedNand before updating

**Comment by ApolloFortyNine** [comment]
Well from what I can tell the warning is after the text telling you to update. It'd be clearer and harder to screw up if it was before telling you to update.

Unless I just missed a previous warning, the warning comes after.

**Comment by nickthegamer5** [comment]
He did put a warning to make sure it says Emu in front of your version number, and a warning that you can brick but besides that I don't see one

**Comment by ApolloFortyNine** [comment]
I know, the step before puts you in the settings, the next step tells you to update, and the text after that says you're actually supposed to reboot after the settings screen.

I'm not bricked, just update to 11. It's my fault, I just think it could be clearer than it is.

**Comment by Plailect** [comment]
Not changing this, users should read entire steps before doing them.

**Comment by ApolloFortyNine** [comment]
In my opinion this is simply being stubborn, it wouldn't take more than a minute to modify the steps. I know it's majority user error to make this mistake, but I don't think anything that's impossible to recover from should be written in reverse order. (Step 1. Turn the key. However, make sure to also have your foot on the brake or your car will explode.)

It's your guide though, thanks for taking the time to write it.
