### ISSUE TITLE
Stuck on step 3

### ISSUE THREAD

**Issue by tony3260** [Plailect/Guide#206]
I got to step 3 but stuck on part 18 reboot into sysnand.
I dont no where that is.
I got a new 3ds on 9.0.0-20E defaut so I skipped step 2.

**Comment by nickthegamer5** [comment]
Sysnand is what is on the  3ds chip it self RedNand is your sdcard. So by rebooting your 3ds you will be in Sysnand where as RedNand you need to open the homebrew lancher to get to it.
Other words just turn off your 3ds, turn it back on and you will be in sysnand wich from there you boot into the homebrew channel

**Comment by tony3260** [comment]
So when I turn on 3ds and see all my apps that's sysnand?.
And holding down on dpad in boot to homebrew is rednand?.

**Comment by nickthegamer5** [comment]
Holding down on boot brings you to the homebrew lancher which from there you boot RedNand with luma3ds. Also all of your apps/games should be on RedNand, only system apps should be on sysnand

**Comment by tony3260** [comment]
Also how do i boot unofficial .cia such as pokemon neo y using only
homebrew i can boot official .cia like nomal pokemon y just not unofficial
ones i get signature or hash check fail message.

**Comment by Plailect** [comment]
You can stop the piracy discussions right here.
