### ISSUE TITLE
Part 5 - Section IV - Item 8 - Incorrect nand!

### ISSUE THREAD

**Issue by heymufti** [Plailect/Guide#207]
The correct nand to restore is emuNAND_formatted.bin!  This is the nand that includes FBI as referenced in later steps.

**Comment by Plailect** [comment]
Er, no.

FBI is injected into `emuNAND_original.bin` before the backup is made, and will be there after it is restored.

**Comment by heymufti** [comment]
No it is not...

From you instructions, emuNAND_original.bin is created before the injection of FBI into H&S.  It's incorrect, and you're an idiot.

**Comment by heymufti** [comment]
Not to mention there's a bug with the injector that forces you to use a prior version to finish teh injection correctly.  But what do I know.  I only followed your instructions.
