### ISSUE TITLE
Question about Part 5 Section I step 12

### ISSUE THREAD

**Issue by onmyouji** [Plailect/Guide#208]
**12. Copy and merge the 3DS folder from the EmuNAND9 zip to the root of your SD card**

Since we already run EmuNAND9.bin as a Luma payload, do we still need to copy and merge the 3DS folder from the EmuNAND9 zip? Is that step actually still needed?

Because when I tried to run that EmuNAND9 (the one on the 3DS folder) via Homebrew Launcher, it doesn't work.

**Comment by nickthegamer5** [comment]
It's not needed any longer do if you want you can delete it, besides that @Plailect can remove it if he wants to.

**Comment by Plailect** [comment]
Fixed
