### ISSUE TITLE
Decrypt9 Not Starting

### ISSUE THREAD

**Issue by Pokemaster623** [Plailect/Guide#21]
Now when I hold L+R on boot to start Decrypt9 it doesn't do anything and starts normally

**Comment by marilleo** [comment]
Make sure that:

1) Decrypt9 is renamed to default.bin
2) You're using the latest version that's compatible with AuReiNAND

**Comment by Plailect** [comment]
Boot with the SD out to confirm arm9loaderhax is installed. If it boots properly without an SD card, you messed up somewhere.

**Comment by Pokemaster623** [comment]
It seem to work now I guess I didn't press the buttons correctly earlier
