### ISSUE TITLE
Part 4, Step 27 Trouble

### ISSUE THREAD

**Issue by 43eloki** [Plailect/Guide#210]
I'm in the process of downgrading my RedNAND and after updating updating it in the system settings and making backups of both the Sys and Red NANDs in OTPhelper. I'm stuck on Step 27 where I have to boot into Luma to then launch FBI from the Health & Safety app but booting into Luma consistently gives me a black screen and I've rebooted numerous times with no success.

I've reset the config for Luma and injected my EmuNAND backup and still have black screen when trying to boot Luma.

**Comment by nickthegamer5** [comment]
If you have downgraded already its because luma can't open any version =>5.0(correct me if I'm wrong) besides that your sysnand may of updated it self.

**Comment by 43eloki** [comment]
I have not downgraded yet and thankfully my SysNAND is still at 9.0.0 (how I got it when I bought this console a year ago). I'm still working on setting up RedNAND and formatting it a 1st and then 2nd time to disconnect it from sysnand. 

Currently formatting the sd card and just trying to restart the rednand creation process and see if something goes for the better

**Comment by nickthegamer5** [comment]
If you formate the sd card(not in emunand9) you will need to redo the RedNand part from the start.

**Comment by 43eloki** [comment]
I've retraced my steps back to Part 3~4, and have setup RedNAND again and updated it to 11.0 and initialized the home menu before doing the Health & Safety injection to see if the difference in order will let me get into Luma after I do the injection + backup Sys and Red NANDs.

**Comment by nickthegamer5** [comment]
Any progress?

**Comment by 43eloki** [comment]
Score! Managed to get into Luma this time on the first try after doing the respective sys and emu nand backups. I guess the problem was there was a hiccup in trying to initialize the home menu in RedNAND after doing the H&S injection. 

H&S shows the FBI icon and I'm now picking up from where I left off in the downgrade process. Thanks

**Comment by 43eloki** [comment]
Another update, seemed to have installed al9h successfully and payloaders/homebrew launcher works from the cfw-based sysnand. Thanks, closing.
