### ISSUE TITLE
Accumulated list of improvements to the guide

### ISSUE THREAD

**Issue by neobrain** [Plailect/Guide#211]
* https://github.com/Plailect/Guide/wiki/Get-Started and https://github.com/Plailect/Guide/wiki/Part-1-(Homebrew) both contain a list of things to do separated by firmware. It's cognitively hard to find the appropriate section for a particular firmware though, so it should be grouped as a table, or at least as a proper list (via *). E.g.
    * 9.0 - 9.8: blabla
    * 9.9 - 10.5: blabla
    * ....
* Booting my EmuNAND took *really* long to get any (useful) visual feedback. It would be good to note somewhere that it may take up to two minutes, especially when the emunand has been formatted from the system settings (or via TinyFormat).
* 23:41 < neobrain> Plailect: the D9WIP version linked at https://github.com/Plailect/Guide/wiki/9.2.0-Update-(rxTools-2.5.2) doesn't work for me, https://github.com/d0k3/Decrypt9WIP/releases/tag/20160607 does
* Part 4 could really benefit from grouping steps 17 to 25 into "Backup your NANDs" (such grouping should take place more oftenly anyway, but it's really annoying in that part)
* 01:27 < neobrain> Plailect: https://github.com/Plailect/Guide/wiki/NAND-Size should use MiB instead of MB, since apparently you are measing in units of 1024
* part 4/step 35 lacks a note that the user needs to boot back into rednand (since tinyformat will have rebooted to sysnand after step 33 AFAICT) (note that this was incorrectly reported as part3/step 35 on IRC)
* https://github.com/AuroraWright/arm9loaderhax/releases has two kinds of releases (noscreeninit vs screeninit), and it's not clear from the guide (part 5) which one to use. If it's explained at the top of the page, some sort of reference needs to be given from within the bullet list.
* Part 5/Section 1/Step 14 talks about "the Uncart zip", but the link provided for uncart (https://github.com/AileSc/uncart/releases) at the top of the page does not provide any zip (anymore?), but just plain binaries
* The end of Part 5/Section 1 is just annoying to read. Please merge those separate "Copy *.bin to ..." and "rename X to Y" bullet points into one point (because they constitute a single logical step). If people fail to do this properly, it will not cause any harm down the line and it's trivial to troubleshoot ("nothing happens when I press Y on boot" => fix your filenames)
* In Part 5 / Section 5 / Step 8, no message relating to "starter.bin" was printed for me
* Part 5 / section6 needs a note as to which program should be used and how to start it (EmuNAND9, holding Y on boot). Also, I think this is the first time in the guide that EmuNAND9 is used for NAND dumping (OTHelper was used before), so a little more handholding might be a good idea. A possibly better alternative might be to even replace prior use of OTHelper for NAND dumping with EmuNAND9 for consistency.

**Comment by nickthegamer5** [comment]
Oh wow nice work, the starter.bin thing is normal and the slow emunand booting is propbly because your sd card's speed is low. Besides that @Plailect can add it if he wants.

**Comment by maorninja** [comment]
https://github.com/maorninja/Guide/wiki for (1st bullet point)
It does mention it (7th bullet point)
8. Its fine.
10. What?

**Comment by nickthegamer5** [comment]
I don't get what your trying to do? Also that's not even Plailects guide it's a fork of it and may be out of date.

**Comment by maorninja** [comment]
What I'm trying to is answer his questions. Also, I updated it so it's more then Plailect's guide.

**Comment by neobrain** [comment]
@maorninja These aren't questions.

**Comment by maorninja** [comment]
@neobrain sorry. I mean't your list.

**Comment by Plailect** [comment]
These have all been implemented.
