### ISSUE TITLE
N3DS-JAP downgrade question

### ISSUE THREAD

**Issue by mockatoy** [Plailect/Guide#212]
Hello Plailect thanks for the guide and for always keeping it updated.  I just got a N3DS-J and I haven't done one yet do you still have to delete  000400102002CA00.cia from the downgrade to 9.2? I ask since its not mentioned in the guide.

Thanks

**Comment by Plailect** [comment]
It has been removed for you.

**Comment by mockatoy** [comment]
Cool thanks Plailect Have a good one!
