### ISSUE TITLE
Part 5 step 14

### ISSUE THREAD

**Issue by ferruiz97** [Plailect/Guide#213]
What can i do if i accidentaly deleted the backup file mentioned in that step? To which nand does it refer to? Is it the same as as the rednand backup?

**Comment by ferruiz97** [comment]
I mean can I use emunand_formated instead of emunand_original, or what should I do If I accidentally deleted that file ( sorry I just had a ton of backups and it got me confused )

**Comment by maorninja** [comment]
It's the NAND backup with all your games. If you lost it, you need to restore from sysnand_original.bin

**Comment by ferruiz97** [comment]
That means I can't use the rednand backup that I created in part 4 section iv, step 3 ? if not  forgive my ignorance but how do I restore it from sysnand_original.bin? 
Here is a list of the backups I have, as It seems I deleted the folder that contained sysnand_original.bin and emunand_original.bin.
I have an original 4.5 backup 
Another original 9.2 backup 
A rednand backup 
And lastly when doing the one click setup with the OTPhelper I did backup the nand there when it asked me to. Can I use this one ?

**Comment by maorninja** [comment]
You do have emunand_original.bin. And that's the file in part 5, step 14

**Comment by ferruiz97** [comment]
That's the problem I don't have the backups of part 4 
Section 2 the only ones I have are:
I original 4.5 backup 
 original 9.2 backup 
A rednand backup
And the part 4 section iv backup when prompted by the top installer ( which the guide says is not necessary, but I did anyway)
Is the backup in part 4 section iv the same as the one I'm supposed to have of part 4 section iv? If yes can I just rename it to emunand_original.bin? Or what I'm I supposed to do?

**Comment by ferruiz97** [comment]
ohh and by the way, the rednand backup i have is the one we made in part 4,section iv,step 3.
Can i use this to restore or what is the difference between this one and the one created at part 4 section 2, and what is the difference between those two and the one otphelper prompts you to make at part 4,section 4 ,step 15.
The ultimate issue is in a few words i dont know if any of those backups will function (i dont know if i have a functional backup) to restore the nand,and use luma, since it doesnt boot in 2.1

**Comment by Plailect** [comment]
Use your original 4.5 backup instead.

**Comment by ferruiz97** [comment]
And re-do the whole process?

**Comment by Plailect** [comment]
In place of the one it tells you to use.
