### ISSUE TITLE
Crash when launching Rednand after updating it

### ISSUE THREAD

**Issue by benayed** [Plailect/Guide#214]
Hello,
I followed all the steps until part 4 where I am stuck. It is said to update RedNand in the system parameters what I have done but everytime I launch RedNand with Luma3ds, I have a message saying to wait until menu arrive and then it crashes.
Can you help me?
Thanks in advance.

**Comment by Plailect** [comment]
Redo Part 3, something has gone wrong somewhere...

**Comment by benayed** [comment]
I actually had no problem to lauch RedNand before updating it. I was on EMU 9.2. Is there perhaps a problem with Luma3ds ?

**Comment by Plailect** [comment]
Ask @AuroraWright
