### ISSUE TITLE
black screen after copying rednand data to sysnand 

### ISSUE THREAD

**Issue by Feilaikie** [Plailect/Guide#215]
I'm having problems restring the emunand on my new3ds doesn't seem to boot after i did that does it have to do with my emunand?

**Comment by Plailect** [comment]
Check your luma settings

**Comment by Feilaikie** [comment]
I even check on Autoboot SysNAND"
"SysNAND is updated"
"Force A9LH detection"
"Show current NAND in System Settings"
"Show GBA boot screen in patched AGB_FIRM" is my new3ds bricked? well I manage to load emunand and others

**Comment by Plailect** [comment]
Restore it again.

**Comment by Feilaikie** [comment]
I try to restore it. my nand said it was corrupt how do i make my own emunand if I can't make the one in the armloadhaxx

**Comment by Plailect** [comment]
Restore the sysNAND.bin from Part 2 instead.

**Comment by Feilaikie** [comment]
I  just try to restore the sysNAND.bin to it successfully did it but it didn't fix the black screen problem should i make the sysNAND.bin or I can't since I got the black screen problem

**Comment by phdcoder** [comment]
I have the same problem. Until part 5 section iii, i got everything smooth !! But on section IV,  after the SysNand restore from emunand_original , i got a black screen. Tried to restore Sysnand_original (twice)  got black screen too.  I can boot on LUMA3DS ( just checked all the options)  and of course on Hourglass9.    What should i do ?
