### ISSUE TITLE
Part 1 (Homebrew): Relocate browser version warning

### ISSUE THREAD

**Issue by RollingStar** [Plailect/Guide#216]
>9.0.0 - 9.8.0: Follow this guide, but skip changing the date and time and initializing savedata in the beginning.

>9.9.0 - 10.5.0: Follow this guide as written.

>10.6.0 - 11.0.0, **or have a browser version (the last number in the version, such as 11.0.0-33) of less than -20:**

(Emphasis added). This pertains to *all* firmwares, because Browserhax won't work on firmwares less than -20.

I had an o3DS on firmware 8.x and then followed the guide to use a cart update to get to version 9.8.0U. Because the first sentence of this post indicated 9.8.0 users would be fine, I neglected the warning in the third line of this post.

As such, I think the warning should be relocated.

**Comment by Plailect** [comment]
Huh? Those are both qualifiers for the section below it containing all alternate entrypoints...

I'm not going to copy and paste that entire section, and users should read everything before proceeding to do any instructions.

**Comment by RollingStar** [comment]
Could you please just bold "or"?

>10.6.0 - 11.0.0, **or** have a browser version (the last number in the version, such as 11.0.0-**33**) of less than -**20**:
