### ISSUE TITLE
I mange to restore my sysnand.bin now what should I do to make another emunand

### ISSUE THREAD

**Issue by Feilaikie** [Plailect/Guide#218]
my sys nand is 9.0.0-20E

**Comment by nickthegamer5** [comment]
Follow from part 3 of the guide

**Comment by Feilaikie** [comment]
okay because I had problem trying to restore my emunand because my emunand is corrupt can I still do that? I have the arm9loaderhaxx install already.

**Comment by nickthegamer5** [comment]
Restore your emunand from a backup using emunand9.

Also this is off topic from this please post it on GBATemp or Reddit.
