### ISSUE TITLE
Not an issue, but it might help

### ISSUE THREAD

**Issue by akirayuki** [Plailect/Guide#219]
I think it's worth mentioning that you could still install a9lh and get the otp even though it appears to be stuck on the glitched screen. It happened to me twice, Safea9lhinstaller didn't boot properly. I only had a glitched screen on the bottom, but when I press select then press a button, the console shutdown and voila, otp is in the a9lh folder and a9lh is properly installed.

**Comment by nickthegamer5** [comment]
I don't think I have ever seen thing happen before but he will probly add it to trouble  shooting

**Comment by Plailect** [comment]
https://github.com/AuroraWright/SafeA9LHInstaller/issues/16

I've added troubleshooting instructions.
