### ISSUE TITLE
Help with part 4

### ISSUE THREAD

**Issue by psychomati** [Plailect/Guide#220]
So, I was following every step perfectly fine, until I reached the sysnand and emunand backups. I was using a 2 gb sd card and it ran out of space (The emunand takes 943 mb approximately and the maximum space available was 930 mb), so i couldn't make the backups. I got a new 16 gb sd card and tried to follow [this tutorial](https://gbatemp.net/threads/how-to-transfer-emunand-to-another-sd-card-working-on-new3ds.383684/) but I get an error when I try to expand the partition. I also tried using emunand tool but it doesn't detect the emunand sd. I don't know what to do, I think the only option is inject my original nand backup to the 3ds and create an emunand from it (I can't create a new emunand since I did a system format in a previous step). Any ideas? Thank you and sorry for my english.

**Comment by maorninja** [comment]
Its outdated. Use this guide: 

1. Make an emunand backup on 2 GB
2. Make an emunand on 16 GB
3. Copy emunand.bin to 16 GB
4. Restore emunand from emunand.bin 16 gb

If you can understand what I just wrote, do it. Also, I'm learning English (I'm french). Sorry.

~Maorninja3222

**Comment by psychomati** [comment]
I understood, thanks. However, the problem is that my 2 GB SD doesn't have enough space for the backup, since its real storage space is 1.83 GB and the emunand uses a partition of 943 mb, which leaves me with 932 mb of remaining space (The numbers don't add up but that's what my pc says). Therefore, I'm 11 mb short at best. Any other ideas/options?

Thanks again.

**Comment by nickthegamer5** [comment]
Backup games and DELEAT them off your emunand

**Comment by psychomati** [comment]
I don't have anything installed on the emunand, it only has the default apps. I tried to find something to erase but there isn't a thing.

Is it safe to restore the sysnand backup that I made on step 2 to create a new emunand and start all over?

**Comment by nickthegamer5** [comment]
Just redo the RedNand part of the guide then
