### ISSUE TITLE
sysNAND.bin.sha?

### ISSUE THREAD

**Issue by PrometheusG** [Plailect/Guide#222]
Hi!
my system was 2DS 7.2.0.-12E and with your guide[from your guide 9.2.0 Update (rxTools 3.0) ] it's now 9.2.0-20E , thank you!I can inject QR codes now in pokemon :-)

So,I made the backup of my sysNAND.bin, renamed it to sysNAND-old.bin and deleted it from my SD card and followed all your steps.
The thing is that I have a sysNAND.bin.sha left in my sd card which I didn't rename and din't delete it from the system.
what should I do with that?

Part 1 and the 9.2.0 Update where successful and I hope to continue so that I can go to eshop and friends list without updating from the CFW I am now(9.2.0-20E)

Thank you very much

**Comment by Ev1lbl0w** [comment]
Tha is just a checksum for the program to ensure your SysNAND backup is not corrupted. Rename it to sysNAND-old.bin.sha, and place in the same folder of the backup. When you restore the backup, place the 2 files in the SD card.

It's just another safety check. You don't need the .sha file to restore a backup.

**Comment by PrometheusG** [comment]
Ok saved it in my backup folder with the other sysNAND-old.bin file on my PC!thank you for your fast response,this my first attemp so I am pretty nervous and I am sorry If my questions sound silly.
thank again for helping me!
I will now "safely" and without anxiety move to part 3

**Comment by PrometheusG** [comment]
I am sorry to bother you again, but after completing part 3,when I boot my 2DS, by default it will run the sysNAND (9.2.0-20E this won't change after part 3 If I don't accidentally update it confusing it with RedNAND),when I press the down button it will enter HBL, and RedNAND,which is the only I can update to latest FW to get eshop,friends list etc, will launch by going to the homebrew launcher and the Luma 3DS?

At part 18 when I reboot, I get to sysNAND by default and then I press down to boot to HBL
At part 20 when I format the sysNAND from the system settings I don't have to eject the sd card before formating.
So,no update on sysNAND to keep it 9.2.0-20E and just updating RedNAND in the system settings(emu) which I activate by going to Luma3DS from HBL
Did I understood it correctly?
