### ISSUE TITLE
I think there are some steps missing from the 9.2.0-Update-(rxTools-MSET) page

### ISSUE THREAD

**Issue by champgm** [Plailect/Guide#223]
https://github.com/Plailect/Guide/wiki/9.2.0-Update-(rxTools-MSET)

I have a 4.5.0-0U O3DS and I was following the guide down through step 9. At this point, the instructions stop making sense. It skips all steps to actually get into Decrypt9 and assumes you are already there. When I load up my DS flashcart, I get the normal menu where you would select an nds file and instead of anything named Decrypt9, I see "Cakes ROP Installer". In that program, there are several choices about what to write/install. None of them seem to end in Decrypt9 launching though... Not sure what to do from here.

**Comment by Plailect** [comment]
You should put the decrypt9 nds file on your flashcart and launch it...

It skips exactly how because all flashcarts are different
