### ISSUE TITLE
Part 2: Use consistent naming for safe mode / recovery mode

### ISSUE THREAD

**Issue by RollingStar** [Plailect/Guide#224]
https://github.com/Plailect/Guide/wiki/Part-2-(9.2.0-Downgrade)

>Once this error happens, it can only be fixed by using safe mode (A + R + L + Up on the D-Pad) to update to the latest system version.

and

>If you encounter this error and cannot use recovery mode, you can edit the connection settings as long as the 3DS completely fails to connect to any access point (such as if the point being out of range).

It would be less confusing if one name was used both times, or a slash was used in both cases to indicate that they mean the same thing.

**Comment by Plailect** [comment]
edited
