### ISSUE TITLE
Part 2: Change "READ THIS" to something like "CLICK THIS" or "READ & CLICK THIS"

### ISSUE THREAD

**Issue by RollingStar** [Plailect/Guide#225]
https://github.com/Plailect/Guide/wiki/Part-2-(9.2.0-Downgrade)

https://github.com/Plailect/PlaiSysUpdater/issues/8#issuecomment-220489061

>Mine soft-bricked too. Saw the "read this" as a title, didn't know I needed to click it so I did not format.
Any info I can give to help narrow it down?

I didn't have as dire of a consequence, because I eventually figured I should click that link. However, Markdown has some obscure commands for headers. I would not have been surprised if "READ THIS" was really just an in-page nav anchor, like they have on Wikipedia.

It would be less confusing and more novice-proof if the link was made more explicit that it is meant to be *clicked on*, not just an intro for the rest of the current page.

**Comment by Plailect** [comment]
Seriously? Do people actually not know how links work and what they look like?

Also, the section right below it is exactly copy and pasted from that link, so it doesn't matter if they click it or not.
