### ISSUE TITLE
Part 3 Luma3ds

### ISSUE THREAD

**Issue by klizzi** [Plailect/Guide#226]
im on Part 3 github guide now. When i do 16 (Press Start to boot RedNAND) there's just some colors on screen, and after this console restart and open Homebrew Launcher, not the default console menu.
tried to rerun plaisysupdater and deleting config file of luma3ds, doesnt helped.
what i should do?

**Comment by nickthegamer5** [comment]
Make sure your on sysnand 9.0-9.2 you may have updated your sysnand instead of your RedNand

**Comment by klizzi** [comment]
9.2 sysnand right now, checked it.

**Comment by Plailect** [comment]
This is something to do with luma, not my instructions. Make sure you have done everything right then ask @AuroraWright
