### ISSUE TITLE
Troubleshooting suggestions

### ISSUE THREAD

**Issue by timbiotic** [Plailect/Guide#230]
After a successful implementation, during the process I ran into a couple of issues that might help others.

1. The downgrade process from 11+ to 2.1 wouldn't work until I switched to cake and it worked immediately.

2.  Luma 5.5 didn't work on my O3DS, only 5.2 or 5.3 did.  Later based on their FAQ I found out that 3DS that had been downgraded with gateway had messed with sysnan. Followed their FAQ and it was fixed.  I believe this is also why I couldn't downgrade in Luma.

These two things had me hung up for a long time and are easy fixes. I got black screen when booting with luma 5.5 until I ran the cia  fixes using Luma 5.2 or cake.

**Comment by Plailect** [comment]
1. You should be using the latest luma version or it won't work.

2. I'm not including this, but yes the information is available in Luma's wiki.

**Comment by timbiotic** [comment]
I found many others having same issues.  It might help to add to troubleshooting for black screens in luma. Also for the downgrade cake was immediate after 6 tries in luma.  I'm thinking it's all related.  Even if it's a note for O3DS users with gateway to run those CIA files if stuck. Your guide is the bomb though!
