### ISSUE TITLE
No space in my 4GB sd card

### ISSUE THREAD

**Issue by PrometheusG** [Plailect/Guide#231]
Hi,
So I was pretty happy that it worked till part 3 and  want to complete the last steps.
But I run out of space ( downloaded games) and now I ordered a new micro sd card 32GB.
Can someone tell me what are the steps to safely transfer everything from my old sd card( until part 3) to the new one to continue the process?(+the hidden partition which I don't know how to move it)
Thank you!
(Plailect, thank you for everything again)

**Comment by nickthegamer5** [comment]
This will take some time to do if you want to keep your games save data.
1. Download and install [JKSV](https://gbatemp.net/threads/release-jks-savemanager-homebrew-cia-save-manager.413143/)
2. Backup games save data by selecting SD/CIA, then the game you want to backup, then export save data(and ext data if you want to) 
3. Delete the games as you back them up to free space.
4. Make a RedNand backup on 4 GB
5. Make a RedNand on 32 GB
6. Copy emunand.bin to 32 GB
7. Restore RedNand from emunand.bin on the 32 gb

Steps 4-7 where a modification from @maorninja so thanks him :3
If you don't understand by `Make a RedNand on 32 GB` or `Restore RedNand from emunand.bin on the 32 gb` tell me and ill tell you how.

**Comment by PrometheusG** [comment]
thank you!My games are new so I don't care If I lose my saves I can restart them again :-)
So I backup rednand with decrypt9,make a new one as done in part 3,I copy the backup of rednand I made(emunand.bin) and I restore it to my new sd card?
what about sysNAND?I simply drag and drop everything to the new sd card?

**Comment by nickthegamer5** [comment]
Yes first drag and drop everything to the other sd then restore the RedNand from the back up. I hope this helped! Also you will need to reinstall menuhax

**Comment by PrometheusG** [comment]
thanks!I am just backing up redNAND and then sysNAND(just to have an extra sysNAND backup) as the guide 9.2.0 update says from steps 18-25.
I don't understand  the step 5 you write above though,Can't I just simply restore from emuNAND.bin?

**Comment by nickthegamer5** [comment]
Ok this is how you make a RedNAND on the new sd card and restore from it
1. Keep the 4gb sd card in the 3ds
2. Boot EmuNAND9 in the HomeBrew channel
3. Click Complete RedNAND Setup **ALL DATA WILL BE ERASED FROM THE NEW SD CARD!**
4. Take out your 4gb sd card and put in your 32gb one
5. Confirm you want to RedNAND format it.
6. Wait for it to finish
7. Go back to the main menu of EmuNAND9 and shut down your 3ds(Do not reboot!)
8. Copy all of the folders from the 4gb sd card to the 32gb sd card **Including the emunand.bin**
9. Boot your 3ds with the new 32gb sd card in the 3ds
10. Open the HomeBrew channel
11. Boot decrypt9
12. EmuNAND Options > EmuNAND Backup/Restore > Emunand Restore > restore from emunand.bin
13. Wait for it to finish
14. Reboot and get back to the Home Brew Channel
15. Boot luma
16. Cross fingers
If it boots into the home menu it worked! If it didn't tell me what happened when you tried to boot luma/what you got confused on.
Hoped this helped!

**Comment by nickthegamer5** [comment]
Also, if you got the new EmuNAND9/Decrypt9 you will need emunand.bin.sha

**Comment by PrometheusG** [comment]
Thank you very much for you time!
I think I understand now how to do it,yes I have the new Decrypt9(started the whole process 2 days ago) thanks for telling me to have the bin.sha too  :-)
My sd card will be here tomorrow so I can't wait to try it.
One last question:sysNAND will be in version 9.2.0-20E as it was?I am not restoring any sysNAND.bin backup,I just drag and drop all the files to the new sd card
Again thank you

**Comment by nickthegamer5** [comment]
Your SysNAND is not on your sd card look at this amazing diagram not made by me(I would link to whoever made it but I don't know who)
![untg8i0](https://cloud.githubusercontent.com/assets/13785390/16423970/2dd0bc30-3d2c-11e6-8d65-c234f499742c.jpg)
So yes your SysNAND will say in 9.2 as long as you don't update.
Also, if you got any more questions just ask I'm here almost all day long :ghost:

**Comment by Plailect** [comment]
@nickthegamer5: You've been doing an absolutely stellar job replying to questions like this, thank you very much :D

**Comment by nickthegamer5** [comment]
No problem I got nothing to do all day so I enjoy doing this :3

**Comment by PrometheusG** [comment]
I am so noob, thank you for all!I will re-read the whole guide again and maybe search all the "new words" I am seeing here.
THank again!

**Comment by nickthegamer5** [comment]
If you don't care about your games/saves that are on you 3ds(Not the card ones, once you finish the guide you can dump the cards and install along with transfer the save data(Wich means no more lugging around 10 game cards)) you can redo the whole guide with the new sd but just skip the downgrading part.

**Comment by PrometheusG** [comment]
So since I am already on sysNAND 9.2.0-20E ,(upgraded from 7.2.0-12E with plailect's guide-9.2.0 update) you say that I can just remove the old sd card, since I don't care about the installed games,make it like it never happened and do all the steps again from the start with new 32gb sd card?

Nice,thank you again!

**Comment by nickthegamer5** [comment]
Yes once your done the guide.

**Comment by PrometheusG** [comment]
what do you mean?I am ok if i just do this?

**Comment by nickthegamer5** [comment]
It's ok as long as it's related with the guide(like this issue) but once you follow the instruction I posted and finish the guide you can just use the 4gb card anywhere else.

**Comment by PrometheusG** [comment]
you mean the plailect's guide?So I first follow your instructions to move to the new 32gb sd card and then finish part 4 and 5 from plailect's guide to get arm9loaderhoax?

**Comment by nickthegamer5** [comment]
Yes also make sure to update the emunand NOT SYSNAND and then just finish the guide

**Comment by PrometheusG** [comment]
My RedNAND is now on emu 11.0.0-33E, I am happy I didn't screw this up :-P
I can't thank you enough for your help.I hope one day I will help others too :-)
This is my last post
Thank you again and have a good night!
(and thanks again Plailect for your guide)

**Comment by PrometheusG** [comment]
I just got my new sd card,followed your instructions step-by-step but there is one "problem".
Decrypt9 is not in my homebrew and maybe I have to access it via my browser on sysNAND.what shall I do?

**Comment by nickthegamer5** [comment]
Download the .3dsx version of decrypt9

**Comment by PrometheusG** [comment]
So I Delete the Decrypt9WIP.dat+Launcher.dat+Decrypt9.log from my sd card and put the .3dsx from the Decrypt9 folder of the zip file, into the root of my sd card?
I was using the old Decrypt9WIP 20160607-215224.zip .Is there a problem if I just drag and drop the new .3dsx version from the new zip file?(20160626-231556)

**Comment by nickthegamer5** [comment]
Ok download a new decrypt9, there should a a 3ds folder in there open it, now with your sd card in the PC open the 3ds folder on the sd card and drag in the .3dsx and .shmd(something like that can't remember rn) in to the 3ds folder. From there boot the HB channel and open Decrypt9

**Comment by PrometheusG** [comment]
It worked!Thank you so much for helping me!
I will go finish the rest of Plailect's Guide but I wouldn't be able to move to the next part (4) if you were not here to help me!
Thank you again!
(sorry Plailect for continuing the topic you closed but I didn't want to open a new "issue")

**Comment by nickthegamer5** [comment]
People usually continue posting there issues even after its closed so don't worry :3

**Comment by nickthegamer5** [comment]
If it works please tell me so if another person asks I can show them this.

**Comment by PrometheusG** [comment]
yes, your instructions worked for me!
I have put also the.3dsx and .smdh files from the new Decrypt9WIP.zip to my 3ds folder and left Decrypt9WIP.dat+Launcher.dat+Decrypt9.log that I used for Plailect's Guide untouched.I succesfully installed a new sd card thanks to you without even losing my game saves or bricking RedNAND.(or even sysNAND) :-)
I am going to make another backup of my entire new SD Card + sysNAND + RedNAND just in case :-)
Again, thank you

**Comment by nickthegamer5** [comment]
Thanks for telling me that it works :3

**Comment by Beeskey** [comment]
So glad I found this page, I'm having the same issue as PrometheusG. I'm stuck at the CTRTransfer page of Pailect's guide, unable to create a sysNAND backup due to lack of space on my SD. I'm trying to RedNAND my new SD card, but EmuNAND9 isn't working. When I try to start it up, the bottom screen on my 2DS flashes red twice and then returns me to the Homebrew Launcher.

I found somewhere that you couldn't run EmuNAND9 from within CFW, and that if you boot it outside CFW it should work. Others confirmed this, but I have no idea how to boot outside the CFW unless I totally undo my work thus far....

Sorry I'm such a noob with this. Could anyone help me with getting started?

**Comment by PrometheusG** [comment]
In what part of the guide are you? My issue was that I didn't know how to move RedNAND,which I had already created, to a new SD card to continue with the old guide, an "issue" that was solved with the help of nickthegamer5.What is your problem exactly? You don't need RedNAND with the new guide,you can start with copying your files to a new sd card to finish the ctrtransfer backup and then install Luma+arm9loaderhax . You can later boot emunand as a payload if you want RedNAND

**Comment by Beeskey** [comment]
Thanks for responding! Your response makes me think perhaps there's an easier way...

Essentially, I got to this part of Plailect's guide (in Dekrypt9):
1. Go to “SysNAND Options”, then “CTRNAND Transfer”, then “Auto CTRNAND Transfer”
2. Input the key combo given, then select the 2.1.0 ctrtransfer image when prompted by pressing (A)
3. If you do not already have a NAND backup, backup SysNAND to NANDmin.bin when prompted by pressing (A)

When I pressed "A," it showed up that I didn't have enough space on my SD card to create my NAND backup. I just assumed I'd have to do some sort of special formatting or something to swap out SD cards, so I went searching and found this thread. I downloaded EmuNAND9 and tried to go from there with creating a RedNAND on a new card but EmuNAND9 won't open. 

Is there an easier way? Could you expand upon the last couple sentences from your response above?

Thanks!

**Comment by Beeskey** [comment]
Actually...I may not need to, I think I found a way. I'll post if I run into another issue related to this, but I think I worked it out. Thank you for your response, though!

**Comment by PrometheusG** [comment]
RedNAND takes space from your SD card because it is installed in a hidden partition and won't help you with your problem.the easiest way is to copy and paste all your files from your sd card to a bigger one and continue with the guide without creating a RedNAND.follow the guide from where you left off and you won't have any problems.don't forget to post if you have any other issues or if something you tried worked :-)
