### ISSUE TITLE
Error while downgrading to 2.1.0

### ISSUE THREAD

**Issue by plep** [Plailect/Guide#234]
I'm on my 6th 3DS I've followed this guide for, although this is the first time I've gotten this issue.  As to be expected, I follow the guide word for word, and even used the Guide Enhancement to check off my progress.  On my attempt to downgrade to 2.1.0 I get "An error has occured. Hold down the POWER Button to turn off the power, then turn it on and try again." I've tried it five times without luck.  I looked carefully at the unit as it was downgrading, and the last step it appeared at before an error was related to NFIRM.  The PlaiSys.log confirms this.  What do I do to fix this? I've read the guide but I can't imagine I skipped over a step?

The troubleshooter told me to make a gist file with my PlaiSys.log in it.  Hopefully this is what you meant https://gist.github.com/plep/5b5b2e7d8c7d7e6f58e332fb4278dd1a

**Comment by plep** [comment]
It seems using the latest Luma was the fix.  Why is this the reason? I've been using Luma 5.2 for a few of the 3DS I've set up without issue, and then updated later once the guide was complete

In any case, the problem is solved

**Comment by nickthegamer5** [comment]
Did you have the firmware.bin in the luma folder, that could be it if you didn't have it. Also if it's fixed could you please close this. And 5.2 is no longer used in the guide so I'm abit confused on why you didn't try luma 5.5 in the first place, anyway thanks for reporting this.

**Comment by Plailect** [comment]
Older Luma versions do not patch 11.0 to be able to downgrade and need either a firmware.bin or the latest Luma version.
