### ISSUE TITLE
Help! Part 5 - Section 2

### ISSUE THREAD

**Issue by KratZ88** [Plailect/Guide#235]
Hi Plailect,

I couldn't access this link:  http://dukesrg.github.io/2xrsa.html?arm11.bin
the browser will just freeze half way, is there any work around,  so that I don't need to visit this link?

Thanks

**Comment by nickthegamer5** [comment]
Did you copy arm11.bin to your sd card?

**Comment by nickthegamer5** [comment]
It's in the safea9lh file

**Comment by KratZ88** [comment]
yes yes, I did all the steps written on the guide

**Comment by KratZ88** [comment]
anyway, I have a cubic ninja copy, if this helps to do other work around...

**Comment by nickthegamer5** [comment]
try it a few more times it can take a bit.
You could also reset the browsers data ever time you try it to increase the chances.

**Comment by KratZ88** [comment]
somehow got it work, copy and replacing the same file and I got the glitched screen, pressed select to install and everything works like a charm =)

Thanks @nickthegamer5
