### ISSUE TITLE
Part 5 -  Section 5 - Item 5 

### ISSUE THREAD

**Issue by phdcoder** [Plailect/Guide#236]
It would be nice to add a subitem. 
  If you get  a black screen , and used gateway do downgrade to 4.5 in the past, [defrag your CTRNAND](https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-get-a-black-screen-on-boot-with-an-old-3ds-which-has-been-downgraded-from-the-gateway-menu-in-the-past) . 

It happened to me !!

**Comment by Plailect** [comment]
added

**Comment by phdcoder** [comment]
@Plailect  I made a mistake , is on Part 5 , section 4,  item 5.

**Comment by Plailect** [comment]
fixed
