### ISSUE TITLE
Please add that menuhax is patched on 10.6+

### ISSUE THREAD

**Issue by Erulak** [Plailect/Guide#237]
Hello, it is not mentionned that menuhax is patched for 10.+6 version, and it is required for this guide, so please can you write it in case of people don't lose their time ?
Thanks and sorry for my bad english.
Ps : Is there an alternative to menuhax to follow the guide ?

**Comment by Plailect** [comment]
Try reading?

>10.6.0 - 11.0.0, or have a browser version (the last number in the version, such as 11.0.0-33) of less than -20:
Use the following instructions for various alternate entrypoints in place of Part 1 (as Browserhax and menuhax were patched with 10.6.0 and will no longer work and versions less than -20 cannot be used with Browserhax.)
