### ISSUE TITLE
Add a new build of AuroraWright's A9LH fork (since it adds booting without SD)

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#238]
As has been documented in this subreddit post here (https://reddit.com/r/3dshacks/comments/4p3ycq/aurora_wrights_arm9loaderhax_fork_updated_merges/), Aurora's A9LH fork now supports booting without the SD card. The post provided a download link of a compiled build including the new features at (https://mega.nz/#!e49CVSCS!DvjDvq9H0Bd9jKn-aYFcyioPiGDJFyOwhUj_1-1fLJU) but you could also build your own version too from the Github page if you were to use this in the guide. This is essentially a small update to A9LH 2.0, so this could be used in "updating A9LH" and/or Part 5 of the guide. The installation process is pretty much the same, the only difference is that arm9loaderhax.bin needs to be renamed to arm9loaderhax_si.bin if the user is using screen_init. If they are using no screen init A9LH they do not have to rename the file.

**Comment by Plailect** [comment]
I am aware of this build, but I am waiting for a stable release. Aurora has confirmed that reboot patches and other issues exist in the latest commit.
