### ISSUE TITLE
Part 4, Section 1, Step 6 - Be more clear on where to go to update

### ISSUE THREAD

**Issue by TheDgtl** [Plailect/Guide#239]
Currently Part 4, Section 1, Step 6 just says "Update your RedNAND to the latest version using system settings". 
I've had two friends who have ended up going to random places in the Settings menu (Including "SD CARD MANAGEMENT") looking for the place to update, and ended up updating their SysNAND.

I know there's a big warning in that step about SD CARD MANAGEMENT, but it may be a good idea to outline what menus to go into to update the RedNAND to the latest version, as opposed to assuming everyone knows where the update section of Settings is.

**Comment by dark-samus** [comment]
I think you meant step 26? In any case, will add
