### ISSUE TITLE
An error has occurred. Please save your data in any software currently in use, and then restart the system

### ISSUE THREAD

**Issue by renbe2001** [Plailect/Guide#24]
I am getting the message "An error has occurred. Please save your data in any software currently in use, and then restart the system" Everytime I click on the slider bar.  I have cleared the internet stuff a dozen times, clicked multiple spots on the slider bar.. Seems no matter what I do, I always get that error.

I am on 9.2.0-20U

After I click the slider bar the bottom screen goes yellow and then grey.  Then it takes me home and gives me the above error.  Any help would be appreciated.

**Comment by Plailect** [comment]
Sliderhax is unreliable. The issues section is not for troubleshooting steps.

**Comment by renbe2001** [comment]
Then why is that a step in your guide?  Where would I go for troubleshooting then?

**Comment by Plailect** [comment]
It's unreliable, meaning you have to try a ton to use it. Check the footer on every page and the FAQ for support.
