### ISSUE TITLE
Region Changed - Still no eshop :(

### ISSUE THREAD

**Issue by aeglon** [Plailect/Guide#242]
First of all I want to say thanks for the superb guide, got a9lh without any issues

I followed the region change guide on my new j2ds except for deleting the eshop account before starting because I had never opened eshop before or created an NNID, so I assumed I didnt need to.

Following the guide i had successfully changed to eur and formatted, and had no eshop access (error 007-2001)

So after realising I needed to delete the eshop account I recovered my a9lh sysnand and started over, making sure to delete the eshop using the serial on the back of my console this time around, but I still have no eshop access. I have asked for help from reddit, the IRC and gbatemp and haven't received any replies :(

**Comment by willkof2** [comment]
hi! do you manage how to solve this error 007-2001? i'm in the same situation here! thanks!

**Comment by aeglon** [comment]
damn! I did what you said and now I'm getting error 005 5602! I even tried changing region in settings.. So close..
