### ISSUE TITLE
Format my sd card

### ISSUE THREAD

**Issue by kelvin453** [Plailect/Guide#245]
I have done all the guide last 2 days. i am in my 2 week holiday but unfortunaly i format my sd card . I have the back up of all file at home  but i only can get it after 2 weeks. Do any one have back up for that?
I realy need that for my next 2 week holiday. 
Thanks
My console is new 3ds

**Comment by Ev1lbl0w** [comment]
So, you lost your SD card contents, and since you have a backup at home and can't go there now, you're asking for a backup of other guy's SD card?

Just get the homebrew starter kit and copy Luma again to SD card. And if you want your games, you'll have to wait till you get home.

**Comment by kelvin453** [comment]
Ok bro i will try it .is that ok without arm9loaderhax  bin ?

**Comment by Ev1lbl0w** [comment]
No. Your 3DS won't boot without an arm9loaderhax.bin file in the root of your sd card.
