### ISSUE TITLE
Add 11.0 downgrade without a hardmod method

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#246]
Add this: https://gbatemp.net/threads/what-options-do-we-have-on-11-fw-w-o-hardmod.434512/#post-6531644

**Comment by nickthegamer5** [comment]
Oh wow that cool, one thing I don't get is where it says "Dump your nand and then follow the 11.0 FIRM downgrading procedure." I thought you don't need a hardmod?

**Comment by nickthegamer5** [comment]
OHHH I get it, dam I never knew that could work on 11.0 only thing it they may need to fix there TWL(It shows how to do it in the guide somewhere

**Comment by arromdee** [comment]
The 11.0 downgrade without a hardmod method is so awkward that it may be a better idea to say something like "for most practical purposes, you need a hardmod.  If you *really* want to try without a hardmod, go to _____."

**Comment by nickthegamer5** [comment]
Ya it is a bit risky and does require another 3DS that's hacked but I think it's worth it

**Comment by Ev1lbl0w** [comment]
Change your link to this one: https://www.reddit.com/r/3dshacks/wiki/fieldrunners_downgrade

It has detailed instructions.

But I don't think it's good to add it to the guide. According to it, **"This is experimental, and may not work. You may break your system with this"**.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/wiki/DSiWare-Downgrade
