### ISSUE TITLE
7.x.0-4 reported as able to use rxtools

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#249]
https://www.reddit.com/r/3dshacks/comments/4tjsrs/3dshacking_qa_waiting_for_the_freehax_edition/d5i054y is a user who had 7.x with an old -4 browser.

According to the guide, if you have 7.x with an -4 browser, you *have* to cart update and cannot run rxtools on the 7.x.  However, this user was able to run rxtools, via browser.  So the guide should be fixed to add rxtools as an option for 7.x with low browser.  (And to take out the "cart update to 8.x and run rxtools" since this is not necessary.)

(Was it ever confirmed that 7.x would not work?  Or just that 5.x would not work?)

(He was actually running 2.6, not 2.5.2 or 3.0, so research may need to be done to find out whether the guide should recommend 2.5.2 or 3.0.)

**Comment by SirBeethoven** [comment]
Holy cow! That's awesome!!

**Comment by arromdee** [comment]
[Second person able to use rxtools on 7.x](http://gbatemp.net/threads/i-just-found-my-old-3ds-on-7-1-0-12e-what-now.434899/)

**Comment by Plailect** [comment]
Fixed

**Comment by arromdee** [comment]
The person at my second link had 7.x with -12 browser and claimed to have used rxtools 2.5.2.  Is 3.0 necessary for it?

**Comment by Plailect** [comment]
I guess not, but the latest version is probably a better idea if it can be used.
