### ISSUE TITLE
DSiWare Downgrade SD Cards

### ISSUE THREAD

**Issue by DanTheMan827** [Plailect/Guide#250]
It should probably be taken into account that a O3DS to O3DS system transfer has you physically transfer the SD card rather than transferring the data over Wi-Fi

**Comment by Plailect** [comment]
the user should realize this because the process tells them so

**Comment by DanTheMan827** [comment]
I'm aware of that but by switching the SD cards the NAND backups from 3DS #1 will be on the SD in 3DS #2 and the SD card in #2 won't have boot.nds

Maybe I'm just being thorough but it seems like something that may confuse at least some people

Great overall guide though!
