### ISSUE TITLE
Add guide to use emu/redNAND to DSi 11.0 downgrade

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#255]
I have A9LH on my old 3DS but would like to help out somebody with an old3ds on 11.0. I was wondering if I could create a redNAND, format the redNAND using System Format (in settings), set up a new NNID, buy Fieldrunners/Legends of Arcadia and install the hacked save, and then system transfer my redNAND to the other person's 11.0 old3ds instead of doing all of that on my sysNAND. Would this work?

Also, since there is a risk of softbricking after using Plaisysupdater/sysupdater etc. especially on systems with DSiWare installed, it might be a good idea to add a step to system format 3DS #2 at the very end.

**Comment by Plailect** [comment]
Yes you can, but the guide will assume a9lhax.

**Comment by jaxrogers2** [comment]
So I can use emu/redNAND for this (assuming they are unlinked)? Thanks for the reply, that's what I'll use.
