### ISSUE TITLE
smashhax entry causes PlaiSysupdater to Freeze on HAX INIT... screen

### ISSUE THREAD

**Issue by DrWhiteRaven** [Plailect/Guide#256]
At least two others and myself on GBA temp Have this issue, it seems like Smashhax is not compatible with the downgrade methods in this guide (PlaiSysupdater Freezes on HAX INIT... screen). opening and closing apps on homebrew launcher does not fix the issue, L+R+B+down debug does not fix the issue. Formatting Sys memory and changing SDcards also does not fix the issue. 
Several have mentioned using smashhax to get homebrew launcher and use OOThax to continue the downgrade process so that method could be added to the guide if enough people can confirm it works.

**Comment by the4anoni** [comment]
I had this issue on 9.4 browserhax ,but not just with plaisysupdater...

**Comment by Plailect** [comment]
Take it up with @aliaspider, it's "svchax" related
