### ISSUE TITLE
Can I play online with this method?

### ISSUE THREAD

**Issue by ayurai** [Plailect/Guide#258]
?

**Comment by ihaveamac** [comment]
yes you'll be able to play games online

**Comment by nickthegamer5** [comment]
Everything will stay the same except you will be able to install custom CIA,s

On Jul 25, 2016, at 3:51 PM, Ian Burgwin <notifications@github.com<mailto:notifications@github.com>> wrote:


yes you'll be able to play games online

-

**Comment by Plailect** [comment]
# FAQ <- read it
