### ISSUE TITLE
Missing step?

### ISSUE THREAD

**Issue by fjdreyes** [Plailect/Guide#26]
Part 3 (EmuNAND), after step 10:
When [A] is pressed to ignore starter.bin, another prompt appears:
"You may now switch the SD card
The inserted SD card will be formatted
All data on it will be lost!
If you wish to proceed, enter:
[Down], [Up], [Left], [Right], [A]
(B to cancel)"

I just entered the combination, it seems it was the correct choice. Others may be confused on this part because it is telling to switch SD cards and the thought of formatting might be scary...

**Comment by Plailect** [comment]
Fixed
