### ISSUE TITLE
Part 5 - Section II

### ISSUE THREAD

**Issue by 3dsm** [Plailect/Guide#260]
Everything has been a sucess so far, but on the "Installing arm9loaderhax" part, the link in step 2 opens OTPHelper and there's no "Full Install" option like on step 3. I only get "Dump otp.bin (0x100), Dump otp.bin (0x108), validate otp.bin..."

What's wrong? 
Thanks

**Comment by nickthegamer5** [comment]
You put the wrong arm11 and arm9 bin files in look at step six of part 5.
You must drag the arm9.bin and arm11.bin from the a9lhinstaller folder.


On Jul 25, 2016, at 10:03 PM, 3dsm <notifications@github.com<mailto:notifications@github.com>> wrote:


Everything has been a sucess so far, but on the "Installing arm9loaderhax" part, the link in step 2 opens OTPHelper and there's no "Full Install" option like on step 3. I only get "Dump otp.bin (0x100), Dump otp.bin (0x108), validate otp.bin..."

What's wrong?
Thanks

-

**Comment by 3dsm** [comment]
I took the files from the "SAFEA9LHinstaller zip". Didnt supose to take from threre?

**Comment by nickthegamer5** [comment]
Inside the safe arm 9 loader hax zip there is a arm9.bin and arm11.bin replace it with the ones are your ad card.

You took the arm9 and arm11 files from OTPhelper witch you are not suppose to do.

On Jul 25, 2016, at 10:25 PM, 3dsm <notifications@github.com<mailto:notifications@github.com>> wrote:


I took the files from the "SAFEA9LHinstaller zip". Didnt supose to take from threre?

-
