### ISSUE TITLE
Some quick notes about the DSiWare downgrade using redNAND

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#261]
When I started going through the DSiWare downgrade steps on redNAND, I noticed that it was not necessary to back up the SD contents before performing a system format on redNAND. Also, I don't know if this is a redNAND thing or not, but whenever I go through initial setup on my old3ds (I got it at Christmas after the price cut) it never tells me or even mentions setting up a NNID. So, I had to setup a new NNID via NNID settings in System Settings instead. Those difference could possibly be noted in the guide to reduce confusion.

**Comment by Plailect** [comment]
That's odd, it definitely should prompt you for an NNID. You sure you didn't miss it?

**Comment by jaxrogers2** [comment]
Nope, the setup just asks me for the time and date, goes through the 3D test, then asks me to create a profile (which is NOT a NNID-it's just general system info like country, region, etc), set up an Internet Connection, and then gives the option to set up Parental Controls. There is no option or even a NNID icon in sight during the entire process. I think it's because I have an original old3DS (not XL) that was released prior to the NNID, but that is just my theory.

**Comment by jaxrogers2** [comment]
It could also be that my usual NNID is also linked to my Wii U, but that shouldn't matter since that NNID would be unlinked after the format.

**Comment by jaxrogers2** [comment]
My redNAND is also updated to 11.0, so overall I'm not sure why it wouldn't prompt me for an NNID either. Maybe the whole NNID prompt is old3dsXL/2DS/New3DS exclusive? I have no idea.

**Comment by jaxrogers2** [comment]
According to this support page this is completely normal (?) http://en-americas-support.nintendo.com/app/answers/detail/a_id/2221/~/how-to-create-a-nintendo-network-id-on-nintendo-3ds

**Comment by Ev1lbl0w** [comment]
I also have an O3DS that never asked for a NNID during formats. I thought that was normal, but apparently it's not. I have also done A9LH on my friend's O3DS XL and it also didn't ask for a NNID.

**Comment by Plailect** [comment]
Fixed.

**Comment by willkof2** [comment]
I installed arm9 in 24 consoles, old, oldxl and new xl (never received a regular new 3ds or 2ds) and they NEVER asked for NNID in the initial setup (sorry poor english)
