### ISSUE TITLE
(Question) Why translate was removed?

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#263]

**Comment by Plailect** [comment]
They're constantly out of date.

**Comment by mariogamer2** [comment]
It can be difficult to update a guide like this.... but most translate are updated (like french)

**Comment by nickthegamer5** [comment]
They where always out of date

On Jul 27, 2016, at 3:52 PM, mariogamer2 <notifications@github.com<mailto:notifications@github.com>> wrote:


It can be difficult to update a guide like this.... but most translate are updated (like french)

-

**Comment by mariogamer2** [comment]
Not really,look latest commit..
