### ISSUE TITLE
Very important DSiWare Downgrade note for emu/redNAND users

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#264]
If you are performing the DSiWare downgrade using an emu/redNAND on 3DS number 1, after buying a legitimate copy of either Fieldrunners or Legends of Exidia via the eShop, you must attain a copy of the same game on your sysNAND (it can be pirated or legitimate) or else your game will boot directly to the "an error has occurred" screen on emu/redNAND.

Also, for injecting the hacked save, you can use God/SafeMode9 because you can specifically select "emuNAND TWL FIRM" while FBI does not have this option.

**Comment by Plailect** [comment]
This isn't that important.

You don't need to launch the game, just install the save and it will transfer just fine.

The guide uses FBI, which (if launched from emunand/rednand) will look in emunand twl.
