### ISSUE TITLE
Health & Safety Injection issue.

### ISSUE THREAD

**Issue by aroth-khashar** [Plailect/Guide#265]
In Part 4, Section II, step 6, you direct the readers to copy `FBI_inject_with_banner.app` to the root of the SD card.

However in the latest release of Decrypt9WIP, this file needs to be placed in the `\decrypt9\` folder on the SD card (the same place that the `hs.app` file is placed during the dumping step) in order to be discovered by Decrypt9. 

It might also be worth updating step 4 of the same section to inform readers that the `hs.app` file is located in said folder to avoid confusion.

**Comment by akirayuki** [comment]
I actually modded a n3ds xl not so long ago, 3 days ago to be exact and I can say that hs.app is in the root. And also, Decrypt9WIP looks for .app files on the root. Are you sure you're using the latest Decrypt9WIP? It was released on June 27 as per Github, https://github.com/d0k3/Decrypt9WIP/releases/

**Comment by aroth-khashar** [comment]
I did download and copy the new files over, overwriting the existing ones. Maybe it saved there for me because the `/decrypt9/` folder existed on the root?

**Comment by akirayuki** [comment]
Yes, that's probably the reason.

**Comment by aroth-khashar** [comment]
One it finishes doing the One Time Setup thing and I get my sysnand back to 9.2 and emunand back to 11.0, I will play around with it and see what happened.

**Comment by aroth-khashar** [comment]
Ok so I just finished the a9lh/luma initial setup and tried dumping hs.app again after removing `\decrypt9\ from the root of the sd card. The file was dumped to the root of the sd card as the guide expects. 

In light of this, perhaps a better suggestion (instead of my initial one) would be a disclaimer directed at existing CFW users reminding them to remove all preexisting files/folders related to Decrypt9WIP prior to starting that part of the guide? (A similar disclaimer exists in Part 5 informing readers to delete any pre-existing files related to Emunand9 before continuing)

**Comment by Plailect** [comment]
fixed
