### ISSUE TITLE
TMD not found or Corrupt

### ISSUE THREAD

**Issue by NewBowlCut** [Plailect/Guide#27]
I've been following the tutorial the best I can, and I haven't bricked my system yet, but I've tried a lot of the troubleshooting doesn't really fix this error. (Probably because I'm the only person who's gotten it lol)

I've double checked the steps I took, redid the formatting steps, etc etc, and still get the following error.

Checking title 0004001000024000... TMD not found or corrupt
![certwsrwwaa4ico](https://cloud.githubusercontent.com/assets/17969936/14010575/5d4b43c2-f164-11e5-8ab5-534761bdc496.jpg)

Could someone help me with this? Thanks in advance!

**Comment by NewBowlCut** [comment]
Nevermind! I'm a dumbass and didn't have the latest version of OTPHelper. I hope no one makes the same mistake as me!

**Comment by Plailect** [comment]
I was about to suggest that, glad you've got it sorted.

**Comment by MalikOussalah** [comment]
hello i have the same problem but the title i have is already corrupted ( checked on godmode9 and it has gibberish all over how do i do to fix this? )
