### ISSUE TITLE
part 3 10.  Overwrite boot.3dsx and starter.bin or not?

### ISSUE THREAD

**Issue by ayurai** [Plailect/Guide#271]
in part 3:
10. Put your SD card in your computer, then copy all your files back into it

you didnt explain if i've overwrite all files, i think not . i mean ever after use emunand , will left 2 files (boot.3dsx and starter.bin)

and if I overwrite, and boot in a home menu, this home menu will be identical to the normal home menu?

**Comment by aroth-khashar** [comment]
If the guide says to copy all files back to the sd card, then you should copy all files back to the sd card. Tbh I'm not 100% sure about the starter.bin file as I already had CFW set up and started on step 4 (and thus do not know what the file is used for), but a boot.3dsx file is definitely going to be needed later as it is what is loaded by whichever *hax method you use to access things like Decrypt9WIP

**Comment by ayurai** [comment]
the boot.3dsx is inside the sd has near to 9mb, what I have backup has 400kb, I found it extremely strange and it does not explain if any of these files are rednand, where is rednand? in the internal memory of the video game? why is not in the sd ... I'm pretty confuse about that. 
The only reason why I did not continue without a second thought here is why I fear brick since it is the nand, and because I like to understand the process.

**Comment by aroth-khashar** [comment]
RedNand is a hidden partition on your SD card that all nand reads/writes generated by the 3ds firmware are redirected to.

As for telling it apart from sysnand, the only 100% sure way is to load your system settings and look at the version sting. Most CFWs replace the "Ver" text with something else when using rednand/emunand. 

Alternatively, you can change the theme in rednand to something unique (or place a folder named "rednand" on the home menu, and look for those. This only works if your nands are not linked (which if you are following the guide, they should not be.)

**Comment by ayurai** [comment]
well fuck i screwed it ;/ , cause update is a little slow i let update and just press in next and things like that, when i back i read that part:
 (Once you exit System Settings / SD Card Management you will be returned to SysNAND, make sure to enter back into RedNAND before updating!)

and figured I screwed everything, know i'm really depressed.

**Comment by mockatoy** [comment]
You should always fully read a guide before starting and read all the required steps again fully when following each part,  I have a friend who did the same thing but the dsiware downgrade corrected the issue, next time just take your time and follow it.
