### ISSUE TITLE
Add guide for Korean O3DS users

### ISSUE THREAD

**Issue by d3m3vilurr** [Plailect/Guide#272]
Since a month ago, Korea region O3DS users can downgrade to 9.0.
So, many users try to downgrade and also try to change sysnand region to E, U or J for install A9LH.
BTW, I heard brick reports about sysnand region changing,
If @Plailect add new guide page about this for the Asia region users, they will reduce brick risks.

**Comment by d3m3vilurr** [comment]
few minute ago, I saw guide scope about this wiki on frontpage, but i think,  downgrade information can add to the part 2 page

**Comment by Plailect** [comment]
You can't change region on sysnand without patching signature checks...

You'd just brick.

**Comment by d3m3vilurr** [comment]
no. actually not need patch signature for this. just need valid secureinfo_a of target region.
many users already changed device region and installed a9lh.
