### ISSUE TITLE
I can't finish section 3 of part 5! My device's screen is black!

### ISSUE THREAD

**Issue by duskmoon314** [Plailect/Guide#275]
After I finished section 2, I tried to turn it on. But it's screen was black. So I read the Troubleshooting page, found that I don't have `/luma/firmware.bin` in my SD card. Then I tried the fourth one in it:

> Try this test payload (mirror).
Rename /arm9loaderhax.bin, if it exists, to something else.
Place the arm9loaderhax.bin from the archive linked above in your SD root.
Insert your SD card into your 3DS and power on.
Press A. Your 3DS should power off; this means arm9loaderhax is working and something else is broken; your device is not bricked.

I just placed this file in the SD card, replace the one before. And the problem came, when I try to turn 3ds on with SD card in it, the LED is on. And if I press any buttons, it shut down! When I try to turn it on without SD card, the LED is lighted at first, then it shut down.

I need someone's help.

**Comment by ihaveamac** [comment]
your device isn't bricked (arm9loaderhax is working) so you can continue with the guide as normal.

**Comment by duskmoon314** [comment]
@ihaveamac
Thank you for answering. As I am a Chinese students, I followed a Chinese guide translated by an enthusiastic person. However, that guide is a bit of out of date. So now I have solved this problem.
XD

**Comment by SuperStuck** [comment]
I have the same issue, could you tell me how you solved it?

**Comment by Ev1lbl0w** [comment]
Can you open up a menu when you press SELECT while booting?

Because no CFW can boot a 2.1 NAND. That's why it's not booting. Just continue following the guide, you will restore your original NAND backup with all your games and saves.

**Comment by SuperStuck** [comment]
I already used the guide, imported my old nand backup and A9LH is working
fine, I can open hourglass9 with start, luma settings with select, decrypt9
with x etc.

This is the 5th 3DS I've installed A9LH on. I think I'm just going to try
restoring my old nand with decrypt 9 (deleting A9LH) and then re-install.

**Comment by duskmoon314** [comment]
I just followed the guide in English...
