### ISSUE TITLE
"Updating arm9loaderhax" markdown issue

### ISSUE THREAD

**Issue by Ev1lbl0w** [Plailect/Guide#276]
In the section "What you need:"

Normal way:
* data_input_v2.zip (mirror) (mirror)
* The latest release of arm9loaderhax
* The latest release of SafeA9LHInstaller

How it is now:

* data_input_v2.zip (mirror) (mirror)* The latest release of arm9loaderhax
* The latest release of SafeA9LHInstaller

**Comment by Plailect** [comment]
Fixed
