### ISSUE TITLE
No emu in front of version number on part 3.

### ISSUE THREAD

**Issue by rodrigocqb** [Plailect/Guide#277]
I have followed the guide strictly but when i open luma3ds after reinstalling menuhax it says Sys 9.2.0-20U and i don't know what could be wrong since the guide says: "DO NOT UPDATE, FIND WHAT WENT WRONG". Please help.

**Comment by mockatoy** [comment]
Did you copy the Luma folder? I had the same issue when I saw I didn't have
the Luma folder.

Part 3

1.  Copy the Luma3DS.dat file, the 3ds folder, and the luma folder from the
Luma3DS zip to the root of your SD card

**Comment by rodrigocqb** [comment]
Yes, i had copied it.

**Comment by rodrigocqb** [comment]
So, what should I do? My files are gone(i have them backed up in the pc from that emunand backup before creating rednand) and my rednand doesn't seem to work.

**Comment by mockatoy** [comment]
Try replacing the folder and the dat file from step 1

**Comment by rodrigocqb** [comment]
Just done it, nothing has changed.

**Comment by rodrigocqb** [comment]
Someone at least tell me how to recover my data(i have the backup)

**Comment by rodrigocqb** [comment]
Oh god, I had marked auto boot sysnand on luma

**Comment by mockatoy** [comment]
then hold select then you start luma3ds or delete the config file

**Comment by rodrigocqb** [comment]
Yeah, just fixed it. gonna update it now

**Comment by mockatoy** [comment]
Cool good luck!
