### ISSUE TITLE
Special Case for 10.7: New BrowserHax Usable ala TubeHax DNS

### ISSUE THREAD

**Issue by cheatfreak47** [Plailect/Guide#279]
I would like to propose 2 changes to Part 1 the guide.
<hr>
Because there is a new Browserhax that works for 10.6 and 10.7. 10.6 can use the new BrowserHax by using Yellows8's Bypass method, as that wasn't patched until 10.7.

> 9.9.0 - 10.5.0: Follow this guide as written.

should be changed to

> 9.9.0 - 10.6.0: Follow this guide as written.

<hr>
As for 10.7, in many cases, users rarely use the 3DS Internet Browser, and since this is often the case the update nag may not have been triggered yet, it's probable that users with 10.7 could run the new BrowserHax if they enable the old TubeHax DNS on their internet connections before proceeding to scan the BrowserHax QR code, followed by using the new MenuHax 3.0 to install the new MenuHax, and then removing the TubeHax DNS before proceeding with the guide. (To prevent future issues with blocking the update servers and what not in the event of a softbrick)

How this should be phrased is up to you, but I actually can confirm this works as a viable entrypoint for free homebrew access on 10.7, as I myself just yesterday helped my friend downgrade from 10.7 this way.

**Comment by cheatfreak47** [comment]
Oh, one more tidbit: It's also important that you mention that if the user does get the nag, than they will have to seek alternative entrypoints, since there's really no way to stop that nag once you get it the first time.

**Comment by arromdee** [comment]
jaxrogers2 mentioned in another ticket that as far as browser goes, 10.7 is considered the same as 11.0 and so blocking the update servers is not necessary,  https://3dbrew.org/wiki/Internet_Browser doesn't list any browser changes from -32 to -33.

**Comment by Plailect** [comment]
Fixed
