### ISSUE TITLE
Another problem: I can't use FBI to install .cia file

### ISSUE THREAD

**Issue by duskmoon314** [Plailect/Guide#280]
I'm such an idiot.

When I got to the section 5 of part 5, there must be a mistake in my action. So I don't have all the files before I format the SD card. Now I can turn my 3ds on with SD card in it, I can also open Luma3ds with select button. But I can't use FBI to install .cia file, there are just four selection: delete, rename, copy and paste.

What should I do?

**Comment by nickthegamer5** [comment]
Redownload FBI.cia it got corrupted.

On Jul 29, 2016, at 9:51 PM, duskmoon314 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm such an idiot.

When I got to the section 5 of part 5, there must be a mistake in my action. So I don't have all the files before I format the SD card. Now I can turn my 3ds on with SD card in it, I can also open Luma3ds with select button. But I can't use FBI to install .cia file, there are just four selection: delete, rename, copy and paste.

What should I do?

-
