### ISSUE TITLE
Part 4 issue SD card not big enough 

### ISSUE THREAD

**Issue by Name-The-Best** [Plailect/Guide#281]
Because I can't afford anything else I use the standard 4 Gb micro SD that comes with my new 3ds. When I tried to do the emuNAND backup it said it didn't have enough space. What should I do?

**Comment by ayurai** [comment]
Hmm, if u cant delete any other files to gain space, the only thing i can think is buy a 8 gb sd card.

**Comment by Plailect** [comment]
Redo Part 3 with a larger SD
