### ISSUE TITLE
End of part 5, move to sd card issue

### ISSUE THREAD

**Issue by ayurai** [Plailect/Guide#282]
"There is no DSiWare on this SD Card. Inset the SD Card to which the source system's DSIware is saved, and then try again. 

I should put SD Card fom 3DS #1 in 3DS#2 ? cause its not write on tutorial.

**Comment by Plailect** [comment]
Did you move the DSiWare to the SD before transfer?

**Comment by ayurai** [comment]
Instead of change sd cards for their respective consoles, i did as 3ds ask me and put source sd in target sd, after some steps i changed back the sd's nd it worked. =)
