### ISSUE TITLE
Problem after part 2, step 16

### ISSUE THREAD

**Issue by Instandhaltung** [Plailect/Guide#283]
Hey Guys, 
sorry, 3ds noob here... I tried to downgrade my n3ds from 9.4 to 9.2. Everything seemed fine, but I got an Error during the downgrade. So I thought I had what is called a "partial downgrade", but after rebooting, the screen stays black. the menu to shut down the device can be seen if I press the power button, but if I try to go to the home menu, the device won't go to the home screen. Is it kinda softbricked? 
If yes, I need to try to go on with the steps seen here: "Black screen on SysNAND boot after downgrading", right? What happens if I can see the menu when my SD-Card is pulled out? Should I try to downgrade again? Or should I boot to recovery and install 11.0.0? 
Any help would be greatly appreciated. 

Thanks in advance,
Manuel

**Comment by Plailect** [comment]
Boot with SD removed, put it back in once on, downgrade again.
