### ISSUE TITLE
Suggestion to prevent 2.1 downgrade on sysnand

### ISSUE THREAD

**Issue by ericchu94** [Plailect/Guide#284]
Seeing users downgrade sysnand to 2.1 daily on #3dshacks is really irking... 

If we delete all *sysupdater from sdmc:/3ds, it'll prevent users downgrading sysnand through homebrew.

I suggest adding a step to nuke the sdmc:/3ds folder, or delete and unzip from starter.zip, or just to delete *sysupdater from sdmc:/3ds

Edit: This may also be achieved in PlaiSysUpdater by detecting if the user is trying to downgrade from 9.2 -> 2.1 and outputing a warning (o3ds) or error (n3ds)

**Comment by Plailect** [comment]
Fixed
