### ISSUE TITLE
<3.0 Browser OTP and Cubic Ninja OTP FBI injection on SysNAND

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#285]
The browser OTP and Cubic Ninja OTP pages say "Do Part 4 - 2.1.0 Downgrade (Section II - Injecting FBI Only)"  This should say something like "Do Part 4 - 2.1.0 Downgrade (Section II - Injecting FBI Only), but using SysNAND options instead of EmuNAND options"

**Comment by Plailect** [comment]
Fixed
