### ISSUE TITLE
Stickerhax uses a Powersaves?

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#287]
"stickerhax (requires Paper Mario: Sticker Star and either a powersaves or another 3DS which has the HomeBrew Launcher)"

The stickerhax page says "Gamecard save-images for powersaves are not available as of July 29, 2016, due to the newer save-crypto this game uses."  Now, that is worded poorly (mentioning a date makes it sound like it might change at a later date), but I think it's trying to say that it just can't work with Powersaves at all.

**Comment by Plailect** [comment]
Fixed
