### ISSUE TITLE
SafeSysUpdater: More unstable than the normal

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#29]
According @Mrrraou , SafeSysUpdater is more unstable (as it is bigger,or I don't know why....).

If the normal can be used....

**Comment by Plailect** [comment]
GPU based memchunkhax2 (which PlaiSysUpdater *always* uses for *all* versions) is **far** more stable than standard CPU based memchunkhax2 (which the original sysUpdater uses all the time and the original SafeSysUpdater uses for all versions <10.4).

**Comment by mariogamer2** [comment]
Ok,I didn't viewed your commit,sorry....
