### ISSUE TITLE
Guide says 5.x works with rxtools, user reports it does not

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#291]
https://www.reddit.com/r/3dshacks/comments/4v7yqa/3dshacking_qa_release_the_kraken_edition/d5xxhv8

He could not run rxtools 3.0 at all.  rxtools 2.5.2 would run but would not work in devmode (same behavior as in https://github.com/Plailect/Guide/issues/132 ).  He solved his problem by cart updating to 7.x and then using rxtools.

I would hesitate about just changing this, however, depending on the source of the existing information in the guide.  Is there someone who could use 5.x with rxtools 3.0, leading to that guide entry? 

Also, this means that when the guide says "+ 6.X.X Cart Update then rxTools 2.5.2" it should say "+ 6.X.X or 7.X.X Cart Update then rxTools 2.5.2".  I wonder whether an 8.X.X cart update would also work.

Edit: A user commented about 5.1.0-10 in https://github.com/Plailect/Guide/issues/131 .  It may or may not be the same user, since the one on Reddit also has 5.1.0-10.

**Comment by Plailect** [comment]
Made irrelevant with commit #1e9d5da

**Comment by arromdee** [comment]
Because rxtools is back in, this needs to be reopened.  Although the specific case of 5.1.0-10 can't come up, as per https://github.com/Plailect/Guide/issues/132 , 5.1.0-4 is still a problem with rxtools.

Therefore:
-- 2.x and 3.x column 2 should say "+ (4.X.X or 6X.X to 8.X.X) Cart Update then rxTools Browser"
-- 5.x column 2 should say "(6.X.X to 8.X.X) Cart Update then rxTools Browser"
