### ISSUE TITLE
Menuhax crashes if the downgrade to 9.2 gives a Nintendo error

### ISSUE THREAD

**Issue by akirayuki** [Plailect/Guide#292]
So I've done this a couple of times on New 3DS XLs and most of them, when downgrading to 9.2, it gives an error on the last part(It's always the NFIRM that causes this issue). But it can be fixed by booting without the sd card and redowngrading. Browserhax seems to have an issue when you use Plaisysupdater to downgrade so I always use Menuhax to downgrade/redowngrade. But it seems when you got this error, you won't be able too boot to HBL using menuhax, at first, it will give you the static screen, then it will boot to home screen with an error, and if you try to move or do anything, the device will stop working/hang up(this happens when the SD card is plugged in). So I tried removing the menuhax folder, formatting the sd card, deleting the menuhax via menuhax manager 3.0 and still same result. Until I figure out that it always occurs in the same situation on every N3DS that I downgrade. The only thing you can do is use another entrypoint primary or secondary except for Menuhax to redowngrade again and install the missing .cia, in my case, NFIRM. So I think it's worth adding this info on the guide just in case someone has the same issue.

EDIT: another way to boot into Menuhax, apparently, is by deleting the Nintendo 3DS folder.

**Comment by Plailect** [comment]
Just switch themes to uninstall it, then reinstall it...
