### ISSUE TITLE
rxtools 3.0 page redirects you to part 3

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#295]
The rxtools 3.0 page ends with "You can now follow the rest of this guide from Part 3 here."  The rxtools 2.5.2 page tells you to go to "Get Started" which is the correct place.  Going to Part 3 is wrong because this skips installing Menuhax.

This confused a user at https://www.reddit.com/r/3dshacks/comments/4vht59/3dshacking_qa_participation_award_edition/d61pfew

Also, I'm not sure if rxtools leaves FBI on your system, but if it does, part 4 "Injecting FBI" should say that this can be ignored if you already have it from the 9.2 update.  Likewise for "Browser OTP" and "Cubic Ninja OTP".    Edit: Now that I think of it' since you're doing an update, does the update recognize that this isn't the original Health and Safety and restore it?

**Comment by Plailect** [comment]
Made irrelevant with commit #1e9d5da
