### ISSUE TITLE
Freeway browser changes for 9.2.0 update page

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#298]
1) The second column doesn't make sense for 2.x because the column is for >= 5 but 2.x is associated with the -4 browser and does not have the -5 browser.   Since [3dbrew](https://3dbrew.org/wiki/Internet_Browser) doesn't list any browser change between -4 and -5, I suspect the solution is just to rename the columns "0-3" and ">= 4".
2) If the correct fix to 1) is *not* to rename the columns "0-3" and ">= 4", and if -4 really doesn't work with Freeway, then you need to bring back rxtools, since MSET requires a DS cart, but rxtools works with -4 and does not.
3) If the correct fix to 1) *is* to rename the columns "0-3" and ">= 4", then the second column for 2.x should not say "4.x or 6.x cart update + Freeway browser", it should say "3.x to 8.x cart update + Freeway browser" and "+ (9.0.0-0 to 10.7.0-0) Cart Update then Part 1 - Homebrew (with Cubic Ninja)"  (The only alternate entry point that doesn't let them upgrade to 3.x-8.x anyway is Cubic Ninja.)
4) Everything in the first column needs to have the additional option "+ (9.0.0-0 to 10.7.0-0) Cart Update", since MSET requires a DS cart and 9.x-10.x cart update works without one, so it is possible that a user can do the latter but can't do the former.
5) One of the questions I raised earlier happens in a new context: Does the Freeway browser 9.2 upgrade leave the FBI around or does it overwrite it?  If it leaves it around, the user would not need to install it in later steps.

**Comment by Plailect** [comment]
Reverting the changes that were made, some info I went off was wrong.

**Comment by Plailect** [comment]
1) Fixed
2) Fixed
3) Fixed
4) "For all versions you can instead do a (9.0.0 to 10.7.0) Cart Update then start on Part 1 - Homebrew (you will need an alternate entrypoint!)" at the top
5) It is installed later in the guide if it is missing.
