### ISSUE TITLE
Freeway browser to upgrade to 9.2

### ISSUE THREAD

**Issue by VietTPham** [Plailect/Guide#299]
The freeway browser upgrade to 9.2 does not work on 6.6.
I had to use the old guide with launcher.dat to get it to install fbi and upgrade to 9.2

**Comment by Plailect** [comment]
Reverting the changes that were made, some info I went off was wrong.

**Comment by Plailect** [comment]
what browser version?

**Comment by Plailect** [comment]
Fixed
