### ISSUE TITLE
Installing FBI into SysNAND

### ISSUE THREAD

**Issue by zeruel85** [Plailect/Guide#30]
When I launch Decrypt9WIP and try to dump Health&Safety app, it gives me this error:

Searching title "Health&Safety (N3DS)"...
Method 1: Search in title.db...
NAND CID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
TWL Customer ID: xxxxxxxxxxxx
0x03 KeyX: xxxxxxxxxxxxxxxxxxxx
0x03 KeyY: xxxxxxxxxxxxxxxx
0x05 KeyY: not set, slot0x05KeyY.bin not found
Method 2: Search in file system...
Failed!
Health&Safety Dump: failed!

Obviously I have slot0x05Key.bin in the root of SD card, but it is not detected anyway.

**Comment by Plailect** [comment]
This is not an issue with the guide and is most likely due to a corrupted or missing file. 

The issues section is not for troubleshooting steps.
