### ISSUE TITLE
Hold off 9.2.0 Update/Freeway Browser?

### ISSUE THREAD

**Issue by EnragedViper** [Plailect/Guide#302]
Hey, sorry for asking but since you're busy updating the links on [9.2.0 Update](https://github.com/Plailect/Guide/wiki/9.2.0-Update) and [rxTool-3.0](https://github.com/Plailect/Guide/wiki/9.2.0-Update-(rxTools-3.0)) while issues such as #299 have arisen, shall I carry on following the 9.2.0 Update, or shall I hold off until you update the new Freeway Browser page?

**Comment by EnragedViper** [comment]
Edit: Ah, you've removed the rxTool-3.0 (and 2.0 + other pages). Shall I wait for you to sort out issues and keep updating it, maybe I'll come back later?

**Comment by Plailect** [comment]
Finished updating the chart, you can follow it now.
