### ISSUE TITLE
Part 4.III.2: Launching latest FBI through H&S doesn't work

### ISSUE THREAD

**Issue by EmuAGR** [Plailect/Guide#305]
Injected correctly, as I've done that several times.

Latest version: 2.4.1
Error: "Failed to open text color config: No such file or directory"

**Comment by EmuAGR** [comment]
Falling back to 1.4.17 seemed to work. I've encountered this problem with 2.x before, but I think it worked on May (2.x, unknown sub-version).

**Comment by Plailect** [comment]
https://github.com/Steveice10/FBI/issues/67
