### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by d4rkred** [Plailect/Guide#307]
So in the boot right after the menuhax instalation i tried and i was able to launch the homebrew with the D-pad key but after i downloaded the files from the tinytype, luma and emunand to the sd card,  i put it back in the 3ds I tried to launch the homebrew channel with the D-pad key but i got a black screen i stoped trying and i still got the black screen so i launched the 3ds without the sd card and it launched normally i put the sd card back in the 3ds and tried to launch homebrew with browser hax and i got the update message.

**Comment by Plailect** [comment]
Try again, this time in English.

**Comment by d4rkred** [comment]
I launched homebrew channel with browserhax.

I installed menuhax, with d-pad down has the shortcut has it said in the guide.

I shutdown and turned the 3ds back on, to test, worked just fine.

Took the sd card from the 3ds plugged it in the computer and put the Luma, emunand and tinyformat in it like it said in the guide.

Put the SD card back on the 3ds, and turned it on to continue the process pressed the down key on the dpad, the power and wifi light turned on but  both screens stayed turned off.

I tried a couple more times and the same thing happened, so i tried to remove the sd card from the 3ds, and the screens turned on.

I put the sd back on the 3ds and tried to launch the browsrerhax and i got the update message,

Version: 10.3.0

**Comment by Plailect** [comment]
Are you holding the button while booting?

**Comment by d4rkred** [comment]
Yes

**Comment by Plailect** [comment]
Change your theme then redo Part 1
