### ISSUE TITLE
Check update integrity error on 2.10 Downgrade when using PlaiSysUpdater.cia

### ISSUE THREAD

**Issue by EnragedViper** [Plailect/Guide#309]
I'm on step 10 of "Section V - Downgrading" of guide [Part 4 (2.1.0 Downgrade)](https://github.com/Plailect/Guide/wiki/Part-4-(2.1.0-Downgrade)) and I run into an error trying to downgrade to 9.20, here's the full output.
```
HAX INIT...
HAX SUCCESS

Init -> GOOD
Check device -> o3DS USA
Check update info -> o3DS USA

Check update integrity...

MD5 -> id: 0004001000021000 - ver: 01027 -> FAIL
press (A) to exit...
```
I've re-downloaded the 9.20 firmware .zip with MEGA instead of Google Drive, still the same problem. 
I don't think it's a NFIRM error but I've taken note of the information just above the "Overview of steps" anyway, but I don't believe I have changed RedNAND SecureInfo_A at all, I'm downgrading with the correct pack for my console region (USA) and I don't use ReiNand.
One thing I did do however was skip step 8 in "Section IV - RedNAND Prep" referring to removing TWL_FIRM modifications, is that what I should have done? If it is, shall I maybe uninstall PlaiSysUpdater.cia, do the step I missed and carry on from there?

**Comment by Plailect** [comment]
Delete the updates folder and copy it from the zip again

**Comment by EnragedViper** [comment]
Fixed so far, thanks! :+1: I'll let you know if further issues arise.
