### ISSUE TITLE
Can't boot after restoring N3DS on 2.10 

### ISSUE THREAD

**Issue by bludud101** [Plailect/Guide#310]
Right now I'm on part 5, section 4 and after restoring using the 3DS emuNAND_original.bin I'm not able to boot. If the sd card is inserted it just goes to a black screen, and if there's no sd card it doesn't boot at all.. (The blue light flashes for a brief second, but that's it.) I can still access the tools like Hourglass9 and Luma3DS settings. I've also tried restoring a few more times but still to no avail. Any help would be appreciated!

**Comment by Plailect** [comment]
All your settings are set properly in luma?

**Comment by bludud101** [comment]
Yep, all settings in Luma3DS were double checked. I just did this exact guide with little problems a few days ago on my O3DS. Is there maybe something here in part 5 of the guide I missed that's specific to the N3DS? (Other than the Clock+L2(x) setting.)

**Comment by bludud101** [comment]
Figured out the issue! It ended up being the Luma3DS version. Apparently 5.5 doesn't work too well right now with the N3DS, but when I downgraded to version 5.2 it worked perfectly.
