### ISSUE TITLE
Part 3 Step 14-16 - Failed to boot RedNAND, Unable to Boot Luma

### ISSUE THREAD

**Issue by Spadra27** [Plailect/Guide#311]
Hello All,

I was able to successfully go back and complete Part1 after updating my firmware and moved into part 3. I was able to get to step 16 when after 15 minutes my unit failed to boot into homepage under RedNAND. I had an indefinite black screen. I restarted the unit. Now I boot into homebrew and my Luma gets stuck on a black screen. I have attempted to boot it 10 times.

EDIT:
Attempted Part3 from the beginning. Same Result. Does this mean there is something wrong with my Luma package? Should I use a lower version?

EDIT:
Also noticed on Part 3 Step 13 upon restarting the unit it automatically launches Homebrew

**Comment by Plailect** [comment]
Delete the /luma/config.bin file and try again

**Comment by Spadra27** [comment]
Hi Plailect,

As always thank you for all the help and support! Unfortunately, that did not seem to resolve the issue. I am now however able to boot into Luma without issue though. Still cannot complete step 16.

**Comment by Krysisalcs** [comment]
I'm not going to be of any help to you but you may feel better knowing I haven't been able to load the homebrew channel myself either... I followed these steps last week successfully but after a day I ran into the homebrew channel hang... Black screen and won't go away without a forced power off... To this very moment I haven't been able to get it to load... Instead I use "homebr3w"... I only know how to follow directions well in this scenario so maybe plai can find a workaround for you using homebr3w

**Comment by Spadra27** [comment]
UPDATE: I examined the luma folder after my last failed attempted and sure enough the config.bin file was there. I noticed at that time the payload folder was empty. Should there be something in it?

**Comment by Spadra27** [comment]
I went back to Part2 to see if there was any steps different from the upgrade section. I noticed the steps from 22 to the end in Part 2. My process was using the upgrade section first to get access to the theme menu. I then went back to Part1 which completed successfully. I then started Part3. Which went successfully until step 16. I attempted to go back to Part2 to do the steps I missed assuming it was the issue. I noticed I was unable to back up SYSnand onto the SD card. Is my SYSnand gone after completing REDnand in Part3 Step8? Could this be my issue? Why Luma cannot load me back into the home screen in Part3 Step16?

**Comment by Spadra27** [comment]
Just a check in to let you all know I al still working on figuring this out. Anything I find out I will share here. If anyone finds out anything I would like to hear as well.

**Comment by Spadra27** [comment]
UPDATE:

I have completed step 16 of Part3! I think my major failing point is that my 3DS when powering on autos into HomeBrew Launcher. I have to hit down on the pad to load into the 3DS Homepage upon booting up. Is this a major concern? Do you have any suggestions for changing this? My concern would be continuing to step 17 and so forth with this setup and run into a major issue.

Thanks !

**Comment by Spadra27** [comment]
UPDATE:

I was able to redo my menuhax and Step 16 worked!

**Comment by PokeRonMaster710** [comment]
Spadra27 thnx for answering to your own thread, you helped me a lot i was stuck in the same step 
may the gods bless your soul!!

**Comment by james-d-elliott** [comment]
You can stop it auto booting to homebrew by changing the menu theme (if you're using menuhax).
