### ISSUE TITLE
Black screen on SysNAND boot after downgrading

### ISSUE THREAD

**Issue by khang2293** [Plailect/Guide#313]
So, I'm currently at this black screen and i can't seem to do anything. I can't go into recovery and with or without sd card works. During the downgrading process everything said successful until the one click setup and i encountered the, "TPHelper fails to verify my NAND" but i followed the instructions correctly step by step and it said success. I have no idea what went wrong and completely sad i might have to buy a new 3ds.
Specs: New 3ds USA with 9.0 fw
all help is appreciated thanks.

**Comment by khang2293** [comment]
Repeat steps 1 through 6, this is not optional (in other words, you must TinyFormat your RedNAND twice - if you do not, your device may brick when you downgrade), ah shit. i didnt do this and read it as optional. is there anything i can do with this brick n3ds?

**Comment by akirayuki** [comment]
So with or without sd card "doesnt" work? It seems you need to hardmod your device. As long as you have nand back ups, you can try doing a hard mod or let some one do it for you to flash the working nand back into the 3ds.

**Comment by khang2293** [comment]
thanks for the reply, i do have my previous nands' from before the brick, so hard modding still works even after bricking?

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
