### ISSUE TITLE
Final Steps, BootNTR

### ISSUE THREAD

**Issue by kieranlane** [Plailect/Guide#315]
Hi,

I've gone all the way through with an Old Nintendo 3DS XL that was on 9.9.0, the guide is amazing went through everything and all steps, never really had any issues :D Got to the very last step, and done everything it says including cleaning up the SD Card, but when I run BootNTR from the homescreen it says this firmware isn't supported? Am I missing anything? 

**Found the issue, there's an updated BootNTR, the link takes you to an old one - going to the github directly they have a release supporting v11**

**Comment by nickthegamer5** [comment]
Download the firmware.bin from the guide and put it in the Luma folder

On Aug 6, 2016, at 10:18 AM, kieranlane <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I've gone all the way through with an Old Nintendo 3DS XL that was on 9.9.0, the guide is amazing went through everything and all steps, never really had any issues :D Got to the very last step, and done everything it says including cleaning up the SD Card, but when I run BootNTR from the homescreen it says this firmware isn't supported? Am I missing anything?

-

**Comment by Margen67** [comment]
You no longer need a firmware.bin.
Use the latest version of NTR and Luma.
