### ISSUE TITLE
11.0.0 DSiWare Downgrade Section II fails

### ISSUE THREAD

**Issue by veekdot** [Plailect/Guide#317]
The inject of the `FBI_inject_with_banner.app` fails with this message:
![healthsafetyfail](https://cloud.githubusercontent.com/assets/5453361/17463082/1f418e6c-5cbf-11e6-85cb-118c24e03591.jpg)

The 3DS #1 was handled by the letter of this guide.

**Comment by ThalesEu** [comment]
> Well, that's what GW and/or rxTools does sometimes, fragmenting the CTRNAND... There's no way Decrypt9 can handle fragmentation, but there's a way around. Read this post carefully, and decide if you want to do it. As I wrote in that post, Decrypt9's injection routines are known to work reliably, and there was never a single case were anyone complained about failures. The code for that in Decrypt9 being pretty simple and mainly constisting of safety clamps also helps. Still, the normal advice for people without a NANDmod is to stay away from bigger (or even any) SysNAND modifications.
[https://gbatemp.net/threads/release-inject-any-app-into-health-safety-o3ds-n3ds-cfw-only.402236/page-6](url)
>
