### ISSUE TITLE
Black screen on SysNAND boot

### ISSUE THREAD

**Issue by ezgamerx** [Plailect/Guide#32]
part 5, aureiNAND, on Finalising setup step number 5 i reboot and i get nothing but a black screen. I can press L+R to get to decrypt9 and LRY for emunand9 but other than that nothing. I do the Black screen on SysNAND boot after injecting CTRNAND troubleshoot since that seems to be my issue but then i get an error: aurei/firmware(90).bin doesnt match this console, or its encrypted. im at an impasse at what to do.

**Comment by Plailect** [comment]
Redownload and recopy the file. 

This section is for issues, not troubleshooting.

**Comment by ezgamerx** [comment]
is this not a damn issue? nowhere in your guide does it help with this or mention this happening at all

**Comment by Plailect** [comment]
I will block you if you keep swearing at me.

There are more appropriate channels for troubleshooting, the github issues
section is for actual issues with the guide such as incorrect instructions
or typos

Your *personal* issues do not belong here, try asking on GBAtemp, Reddit,
IRC, messaging me, or even emailing me (my email is on my profile page).
