### ISSUE TITLE
Luma on low firmwares?

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#320]
[A Reddit thread](https://www.reddit.com/r/3dshacks/comments/4wlla9/how_to_downgrade_to_21_without_updating_to_9x_on/) claims that Luma could always boot low SysNANDs and additionally in a recent nightly can boot SysNANDs below 7.0 with EmuNANDs that are not below 7.0.  This allows people with firmware below 9.0, and at least a -6 browser, to skip the 9.2 update.

This would be a substantial improvement for people with low firmwares if true.

**Comment by maorninja** [comment]
I guess you forgot about menuhax and people on 1.0 to 3.1.

Sent from my Remix OS PC

On Aug 7, 2016, at 2:57 PM, arromdee <notifications@github.com<mailto:notifications@github.com>> wrote:


A Reddit thread<https://www.reddit.com/r/3dshacks/comments/4wlla9/how_to_downgrade_to_21_without_updating_to_9x_on/> claims that Luma could always boot low SysNANDs and additionally in a recent nightly can boot SysNANDs below 7.0 with EmuNANDs that are not below 7.0. This allows people with firmware below 9.0, and at least a -6 browser, to skip the 9.2 update.

-

**Comment by arromdee** [comment]
People on 1.x and 2.x cannot have at least a -6 browser.  It would still be an improvement for people with 3.x and at least a -6 browser because instead of cart update --> update to 9.2 --> create RedNAND --> downgrade RedNAND to 2.1 they would be able to directly do cart update --> create RedNAND --> downgrade RedNAND to 2.1.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
