### ISSUE TITLE
Small changes that make the process more fluid

### ISSUE THREAD

**Issue by HenryLeonheart** [Plailect/Guide#322]
- Menuhax_manager v3.0 changed the text a bit.

After pressing A on the Install option, it asks if you want to skip ropbin-payload setup. The option selected should be B. At the end, instead of "Success", it says "Install finished successfully."

- At the end of Part 1, the last point should be outside of the list as mere information and not a part of the steps

- At the start of all Parts after 1, it should instruct the user to remove the SD card from the 3DS and put it on the computer to transfer the files in the beginning

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
