### ISSUE TITLE
rxtools doesn't work on 5.x

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#323]
We have established that rxtools [doesn't work with 5.x](https://github.com/Plailect/Guide/issues/291).  Although this is no longer a problem for -10 browser because you are using Freeway, it is still a problem for -4 browser.  The 9.2.0 update page column 2 for 2.x and 3.x should say "+ (4.X.X or 6.X.X to 8.X.X) Cart Update then rxTools Browser".  Column 2 for 5.x should say "+ (6.X.X to 8.X.X) Cart Update then rxTools Browser".

**Comment by trbocode** [comment]
To 9.2.0, not to 8.X.X

**Comment by trbocode** [comment]
You don't need an alt entrypoint on 9.0-8 tho, only on 9.9 and up

**Comment by arromdee** [comment]
He means an entrypoint aside from the browser.  If you cart update to 9.0 the browser won't be useful.

**Comment by trbocode** [comment]
It will.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
