### ISSUE TITLE
Black screen on arm9loaderhax even though it worked before

### ISSUE THREAD

**Issue by P4ine** [Plailect/Guide#325]
Hey all,
following the tutorial, I installed arm9loaderhax on my old 3DS XL a couple of months ago. Everything worked and I managed to install CIAs, which worked fine as well.

Yesterday, I wanted to play a game after not having played for a couple of months, my 3DS booted normally and so did the game (Theatrythm Final Fantasy), after which I played for half an hour or so. I then flipped my 3DS shut without shutting the system down because I needed to attend something else. Today, 16 hours later or so, I flipped my 3DS open to continue the game, but all I got was a black screen. 

After this, I shut my 3DS down and rebooted, still a black screen. I went through all the troubleshooting steps which are listed below "Black screen on SysNAND boot after installing arm9loaderhax", but it all didn't help. My 3DS did turn off however after pressing the A button with the test payload, which would mean my 3DS isn't bricked.

What can I do about this? Is it really only because I flipped my 3DS shut without shutting it down properly? In the past before installing arm9loaderhax I did this all the time and it never caused any trouble, the game just continued where I left.

Thanks for your help and all the best,

P4ine

**Comment by uniQ168** [comment]
Can confirm this problem exists. Following the guide, I managed to successfully install A9LH on 3 different N3DS XL. Two of them seem to have the same problem on boot and it takes 3-4 tries to start the DS. Any ideas on this?

**Comment by jaxrogers2** [comment]
I would try reinstalling A9LH using the newest version of SafeA9LH installer since this could be a bug from an old installer version.

**Comment by uniQ168** [comment]
Already installed using the latest SafeA9LHInstaller. The screen was glitched during the installation and I did the workaround mentioned in the troubleshooting section to install anyway. This might be the only difference between the two not properly working devices and my own 3DS, which did the installation like it was intended.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.

**Comment by louie1105** [comment]
cant seem to play mon hun games and super smash bros,
