### ISSUE TITLE
Update aeskeydb.bin file used in the guide for Decrypt9 to include slot0x24keyY.bin for GBA VC savegame dumping.

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#329]
Would be nice. This new Slot key is on pastebin, could easily be added to the aeskeydb.bin file throughout the guide, along with the use of the new Decrypt9 release and all that brings, with direct on 3DS .3ds to .cia conversion, DS game dumping, and more.

**Comment by Plailect** [comment]
Updated.
