### ISSUE TITLE
Firmware Downgrade does not cover 2DS and EU/JP regions

### ISSUE THREAD

**Issue by limyz** [Plailect/Guide#330]
https://github.com/Plailect/Guide/wiki/Firmware-Downgrade does not cover downgrades from 11.0.0 to 10.4.0 for the 2DS. I assume the guide only specifically covers for US and not for EU/JP consoles (Be it 3DS or new 3DS).

**Comment by mockatoy** [comment]
Pretty much everything related to OLD 3DS applies to the 2DS

**Comment by Plailect** [comment]
What?

Old 3DS = 2DS, and it covers all regions...
