### ISSUE TITLE
Part 3 Step 26 - Luma loads but Firmware does not show EMU; Luma fails to load after

### ISSUE THREAD

**Issue by Spadra27** [Plailect/Guide#331]
In Part 3 I am able to successfully complete up to step 26 without issue. When I reach step 26 Luma will load into the home screen but the version does not reflect with EMU. I will load back into Homebrew and launch Luma but Luma will fail to load. I have tested this to 12 failures on load for Luma. The only thing that resolves this is deleting the config.bin file in the Luma folder. This will allow me to repeat step 26 but I am still receiving the same results. I have checked in Nintendo 3DS folders and I have 3 folders. So I am assuming I have Rednand and Emunand. Any thoughts?

EDIT:
For clarity in Step23: Boot RedNAND the protocol for this to go to homebrew > luma > activate show nand and press start, correct?

**Comment by pbanj** [comment]
try the newest ver of luma that came out today and see if it still does it

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
