### ISSUE TITLE
Aeskeydb.bin links are broken

### ISSUE THREAD

**Issue by gwicks** [Plailect/Guide#332]
It looks like the links have all been taken down to that file, right now I'm in the midst of step 4, but I'm not going to actually downgrade till I have all the files for sure.
'
Just wondering if the one I can dump from Decrypt9WIP will work or not? I tried the build key database option but it produced a file that was 0 KB in size.

**Comment by uniQ168** [comment]
Links are working for me.

**Comment by gwicks** [comment]
Huh, strange, they just started working again. Maybe they were re-upped.

**Comment by KradwinterVII** [comment]
it dissapointed not having aeskeydb.bin to download? only torrents left? how can i install A9LH now? without this binary...

**Comment by Plailect** [comment]
Use the torrent...
