### ISSUE TITLE
11.0.0-33 Browserhax possible now?

### ISSUE THREAD

**Issue by uniQ168** [Plailect/Guide#333]
Hi there,
some guy on reddit just wrote, that browserhax is now usable on fw 11.0.0-33.
Is this really working now?

https://www.reddit.com/r/3dshacks/comments/4uxqcm/browserhax_menuhax_for_1100_released/

**Comment by Bullsquid** [comment]
They just literally explain everything in the comments. You can run homebrew with Browserhax on 11.0.0, but you can't downgrade to 9.2.0 and install A9LH.
https://www.reddit.com/r/3dshacks/comments/4uxqcm/browserhax_menuhax_for_1100_released/d5v0sm3

**Comment by uniQ168** [comment]
My bad, sorry. ^^'
