### ISSUE TITLE
Decrypt9 not booting

### ISSUE THREAD

**Issue by MathieuLegras** [Plailect/Guide#335]
Hello, I've been trying to boot decrypt9 for the past hour and nothing seems to work. I'm trying to update from 7.2.0-10 to the 9.2 following the freeway browser procedure. I have everything needed on the root of my sd card with the right name, but when I go to https://dukesrg.github.io/?Decrypt9WIP.dat it displays ¨Decrypt9WIP.dat loading...¨ and then the browser exits saying it has encountered an error. I think I've tried about a hundred times. Am I trying for nothing?

**Comment by ihaveamac** [comment]
try copying `Launcher.dat` for Decrypt9, then go to http://www.reboot.ms/3ds/load.html?launcher.dat

**Comment by MathieuLegras** [comment]
It worked like a charm, thanks. Now I have the same problem several steps further with the freeway.dat link and following the troubleshooting guide hasnt worked as of now :\
