### ISSUE TITLE
Can't load freeway (9.2.0 update)

### ISSUE THREAD

**Issue by squeezed2** [Plailect/Guide#336]
I'm trying to do the freeway browser method for updating, but I just can't seem to launch freeway. It always give me an error. I've been trying for many hours, following the troubleshooting guide too, but it just doesn't want to load.. is there any alternative? Freeway.dat is already on the root of my sdcard. Thanks.

**Comment by ihaveamac** [comment]
what's your system version?

**Comment by trbocode** [comment]
If all else fails, soon there will be a new guide which only needs decrypt9, so you are set if you can launch that.
Anyway, try using rxtools update.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
