### ISSUE TITLE
Add O3DS to N3DS CTRNAND transfer process for part 4 (2.1) downgrades and OTP acquisition

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#339]
This. Decrypt9 is ready, the guide should be too.

**Comment by Plailect** [comment]
I'm working on it, which is why there's 10 issues open and unaddressed. It'll be ready when it's ready.

**Comment by dark-samus** [comment]
by all means, if you think you can write a comprehensive guide which covers all methods, all regions, you can gather all of the files and know everything that there is to know about how the process works, then go ahead. Write the guide yourself. Then, once you've actually done it, made it as foolproof as possible and dealt with all of the issues, come back we'll integrate your guide right in... Other wise, be patient, wait. We're all working and doing our parts to help move the guide along. Opening issues and telling us what to do isn't going to help, in fact it's only going to annoy us. So please, it'll be done when it's done

**Comment by jaxrogers2** [comment]
Cool.
