### ISSUE TITLE
Region change guide

### ISSUE THREAD

**Issue by lprot** [Plailect/Guide#34]
Can you add region change guide to your great manual?

**Comment by lprot** [comment]
You could just integrate steps from https://gbatemp.net/threads/release-3ds-nand-secureinfo-tool-for-region-change.383792/ to the guide. For example I got US O3DS XL which I want to convert to EU with A9LH...

**Comment by lprot** [comment]
Specifically to A9LH https://gbatemp.net/threads/a9lh-on-a-region-changed-n3ds.420192/#post-6195629

**Comment by Plailect** [comment]
Good idea, I'll add it sometime soon

**Comment by Plailect** [comment]
Added

**Comment by lprot** [comment]
Great, thank you. Can you also add info if it's safe to go to eShop with changed region and if yes what requirements. I heard something about that ctcert is checked by eShop...
