### ISSUE TITLE
Latest Decrypt9 uses sd:/files9 folder, not sd:/Decrypt9/

### ISSUE THREAD

**Issue by kageurufu** [Plailect/Guide#342]
The guide frequently references sd:/Decrypt9/, which is now no longer used. 

It should probably be updated to say files9, just for sanity and ease of use's sake

**Comment by sora10pls** [comment]
Decrypt9 still uses SD:/Decrypt9/, it's just preferred to use SD:/files9/

![screenshot_1](https://cloud.githubusercontent.com/assets/17801814/17721248/e02a3870-63f6-11e6-9d1b-1d690056135f.png)
