### ISSUE TITLE
Part 5, Section VI, Point 9. H&S App is not FBI, what happened ?

### ISSUE THREAD

**Issue by deathwebo** [Plailect/Guide#344]
Hi there! First of all thank you very much for this awesome guide. I've been following this guide with not much problem till now.

When I get to point 9 from Secion VI from Part 5 it says I should access FBI through the H&S app, but the H&S is the original app and not FBI.

Any idea on how to get pass this step ? Thanks!

**Comment by james-d-elliott** [comment]
Hold X on boot, and re-inject the hs.app that has the FBI with banner.

**Comment by deathwebo** [comment]
Thanks @james-d-elliott! I end up doing that, couldn't figured out how I ended up without the original FBI injection.
