### ISSUE TITLE
Rxtools

### ISSUE THREAD

**Issue by UnseenThreat** [Plailect/Guide#347]
When trying to us the rxtools website to start the rxtools.dat file in the sd card on my 6.3.0-12u old 3ds it just crashes and says an unknown error has occurred.

**Comment by ihaveamac** [comment]
on this system version, you should be trying "[Freeway Browser](https://github.com/Plailect/Guide/wiki/Freeway-Browser)" instead.

**Comment by UnseenThreat** [comment]
ty
