### ISSUE TITLE
Injection FBI, Part 4, Section II, can't select FBI_inject_with_banner.app.

### ISSUE THREAD

**Issue by Isalani** [Plailect/Guide#349]
Hi,

I'm having a problem with the last part of the FBI's injection.
I was on a n3ds E 9.0.8 successfully downgraded, with an updated RedNand 11.XX

In the Section 1 I did all that was asked, i didn't have a Decrypt9 folder on the root of my sd card, just a Decrypt9WIP on the 3ds folder (so didn't touch it)
my Wi-Fi is on.

I've then dumped to hs.app (the file is dated from 29/02/2016, has a size of 0,99Mo and localized in files9).
I've extracted the Universal Inject Generator and copy the hs.app previously mentioned and the fbi.cia in the updates folder on my computer.
Launched the go.bat which created some files.
Copied FBI_inject_with_banner.app in the root of my sd card.
I've gone to the Health & Safety Inject option, but I can't press down to select the FBI_inject_with_banner.app.
Instead I have to press left, right, down, up, A then I can only choose hs.app, the D-pad doesn't change this option.

I'm using FBI 2.4.2 and Decrypt9WIP-20160814-201618.zip.

Any idea of what went wrong?

**Comment by WorkingWarrior** [comment]
Hi, copy FBI_inject_with_banner.app to files9 folder.

**Comment by Isalani** [comment]
Thanks, it worked.

**Comment by ducquynhnguyeninfo** [comment]
Hello, I'm following this instruction _[https://3ds.guide/installing-arm9loaderhax](https://3ds.guide/installing-arm9loaderhax)_ and got the same issue.
I did put the file FBI_v2.4.2_O3DS_EUR_injectable.app inside **files9** folder but seems didn't help.
Somebody please help! 
Many thank!
