### ISSUE TITLE
Part 5 suggestions

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#350]
I suspect these will apply even with the new Decrypt9-based version of the guide.  

Section III
Hold select on boot to enter the Luma3DS menu.
**- If you see an error message about  firmware.bin, that probably means you held down "select" too late.  Reboot and make sure you're holding down "select" while booting.**
(This problem has turned up several times and I just saw another one on IRC today.  The problem is worse now because of the new message about firmware.bin introduced for Luma 6.0, which can be confusing.)

Also, section III step 2 needs to be updated for Luma3DS 6.0 config options.

Section III step 5 needs to say "Following this, booting to an error message about firmware.bin is normal (Luma3DS cannot boot a 2.1.0 NAND)."

**Comment by whatisdav** [comment]
Hi I am running into this problem right now. o3ds, US.

on Section III, I was able to hold select on boot to enter Luma3DS menu but I still see the firmware.bin error message after pressing START to save my settings. Is there a way to work around this? Thanks

**Comment by arromdee** [comment]
If you see the firmware.bin error message after pressing START to save your settings, that is normal.  The guide just hasn't been updated to say that you will see an error message at that point, because Luma only had the message added recently.

Using a firmware.bin will only help for firmware that is at least 3.0, which 2.1 is not.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.

**Comment by arromdee** [comment]
Please reopen this; it still applies to the new guide.
