### ISSUE TITLE
Luma instructions out of date?

### ISSUE THREAD

**Issue by Kered13** [Plailect/Guide#351]
The current instructions don't appear to match what I see in the newest version of Luma (6.0):

*There is no luma folder in the .zip.
*These options are not in the Luma menu:
-"SysNAND is updated"
-"Force A9LH detection"

I've just skipped these steps, and everything has worked fine. But the instructions should be updated to reflect these changes.

**Comment by Margen67** [comment]
The luma folder is no longer needed.
Luma creates it automatically.

**Comment by Isalani** [comment]
I did the same ting and it worked too.

**Comment by Conno123009** [comment]
I believe "SysNAND is updated" is now called "Use SysNAND FIRM if booting with R (A9LH)".
It's in the 6.0 changelog. As for "Force A9LH detection", I'm not sure when it was removed, or if it's even needed.

**Comment by james-d-elliott** [comment]
@Conno123009 is correct. The update is for when holding the R button on boot, I believe. I think it's meant to swap between SysNAND and EmuNAND boot modes quickly. https://github.com/AuroraWright/Luma3DS/commit/8d1befea9ec79adee0a0d52c7f0afe648cefd2d6

Force A9LH Detection is no longer needed as per: https://github.com/AuroraWright/Luma3DS/commit/e7b8a0ef394b56fbb85cafd641e366513a003688

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
