### ISSUE TITLE
Part 5, Section V, #20; hs.app can't be found

### ISSUE THREAD

**Issue by Isalani** [Plailect/Guide#352]
Hi again,

I have some doubts, I'm on the last part, I have to Go to SysNAND Backup/Restore, then select Health&Safety Inject and then select hs.app.
But there is no hs.app, there is nothing.

My hs.app is localized in files9 with hs.enc, FBI_inject_with_banner.app.

Should I create a new folder "input" in the root of my SD card like in part 4, or copy it into the root of the SD card?

Maybe this is because the hs.app is not the original one, but I'm unable to find the original one, I've looked in all my backups and all the .zip

**Comment by smiley2billion** [comment]
You don't have to restore that file, you can leave it as the FBI injector.  The only thing you'd miss is not being able to launch the heath and safety app.

**Comment by Isalani** [comment]
Thanks, i've finally tried to put it in my SD card root and it's ok.

**Comment by nightgrey** [comment]
Yeah. I also had this problem. The hs.app is in the "files9" folder at this point, but it should be at the SD card root.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
