### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by UnseenThreat** [Plailect/Guide#353]
When my sd card was unmounted in emunand9 my 3ds turned off, then when i turned it on and tried to access fbi and sysupdater the system said something about them not being on the system anymore. So i restarted my 3ds and found fbi and sysupdater icons gone.

**Comment by Margen67** [comment]
Are you using the same SD card?
Did you modify the Nintendo 3DS folder in any way?
Did you format the SD card or the system?

**Comment by UnseenThreat** [comment]
no

**Comment by UnseenThreat** [comment]
im using the same sd card, i dont belive i modified it except for backing up the sysnand but didnt remove it, and i didnt format it.

**Comment by Ev1lbl0w** [comment]
If you're using menuhax 3.0, try removing it just to see if that's the problem.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
