### ISSUE TITLE
Stuck on Part 2 (Downgrading to 9.2.0)

### ISSUE THREAD

**Issue by Hotkirby100** [Plailect/Guide#355]
So, I have gone through all of the steps to downgrade the firmware of the N3DS to 10.4. I used dgTool, bla bla bla, okay. So I have a N3DS that is on 10.4 (Though it doesn't say that it settings, I've been told it's normal). Basically, whenever I try to downgrade to 9.2.0 Plaisysupdater gives the error "can't get a:mu service" and tells me to try again. Does anyone have a fix for this here? I have tried running FTPD before accessing the updater, and I have tried reinstalling all the files from different download sources.

**Comment by Hotkirby100** [comment]
Nevermind, I managed to fix it.

**Comment by Odebaer** [comment]
I have this exact problem. How did you manage to fix it?

**Comment by Hotkirby100** [comment]
It turns out I wasn't actually downgraded to 10.4, even though I went through the process of downgrading. Either way, I just ran the downgrader again and it worked. Sorry if this isn't any help.

**Comment by Odebaer** [comment]
Yea that was the problem for me too, thanks.
