### ISSUE TITLE
Decrypt9 RedNAND Issues

### ISSUE THREAD

**Issue by Plailect** [Plailect/Guide#36]
Decrypt9 can have issues with several RedNAND related functions, an update will be out soon.

**Comment by Plailect** [comment]
The temporary workaround for this problem is to use EmuNAND9 to backup redNAND, backup SD card, format SD for GW EmuNAND, and restore redNAND backup to emuNAND, then complete all instructions using EmuNAND where the guide says RedNAND.

**Comment by bctaucsd** [comment]
I'm running into an issue with the workaround where it tells me that there isn't enough space for GW type EmuNAND.  I'm using a fresh 64gb SD card, so space shouldn't be a problem. Any ideas on what's wrong?

**Comment by akirayuki** [comment]
Same thing is happening to me with the work around.

**Comment by SPMelly** [comment]
I'm having the same issue with the work around. Not enough space for GW type emunand when trying to convert rednand to emunand. I'm now stuck at step 11 of this guide https://github.com/Plailect/Guide/wiki/Part-4-%28Getting-the-OTP%29

Any help? Really looking forward to tinkering with a9lh

**Comment by richardparker800** [comment]
dude i tried the latest testing release of decrypt9 but im still getting the same problem pls do something fast!

**Comment by Naph** [comment]
Just checking that this is the same problem as not seeing "redNAND Options" in the menu screen.

**Comment by Plailect** [comment]
This should fix any RedNAND related Decrypt9 issues.

**Comment by Naph** [comment]
This has fixed my issue where "No EmuNAND" was displaying at the bottom. The menu item still relates to "EmuNAND Options" but proceeding allows me to use RedNAND and dump H&S.
Good work on the hotfix

**Comment by Plailect** [comment]
D0k3 takes credit for this

**Comment by richardparker800** [comment]
What should fix all the issues related to rednand and decrypt9?

**Comment by KubbaYioka** [comment]
Glad I found this issue. Just want to confirm some stuff so I don't brick or something.
I'm on Part 4, Section I, Step 11.
When I access Decrypt9 when on sysNAND, I get no redNAND Options in the main menu. Are emuNAND Options the same thing as redNAND Options?

**Comment by Plailect** [comment]
Yes

**Comment by bctaucsd** [comment]
I'm running into an issue on Part 4, Section IV, Step 5.

5.Restore RedNAND from RedNAND_original.bin

It doesn't look like the version of OTP that opened can restore for RedNAND.  Any ideas on how to fix this?

**Comment by Plailect** [comment]
And we're back to EmuNAND until the bugs are sorted. Closing this issue.

**Comment by Plailect** [comment]
Restore SysNAND then restore RedNAND using OTPHelper

**Comment by jaxrogers2** [comment]
Decrypt9WIP just had a new version released today that fixes the redNAND issues, so we should be good to go back to using redNAND for the guide.
