### ISSUE TITLE
Part 4 - Section V - #18

### ISSUE THREAD

**Issue by soulburner** [Plailect/Guide#360]
Please, note in Part 4 - S.5 - n.18 that getting a black screen when booting with SD is totally normal and you shouldn't worry.

Because when I encountered it, n.18 says "try loading without SD card and then inserting it". I've made it. And then thought "ok, now it is fixed", tried to reboot with SD card and got a black screen again. I even thought of restoring from the backup.

So just mention that everything is OK when you can't boot with a SD card inserted.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
