### ISSUE TITLE
Part 5 - Section III - Configuring Luma3DS (Luma 6.0 is a bit different)

### ISSUE THREAD

**Issue by soulburner** [Plailect/Guide#361]
Here is how Luma3DS configuration tool looks for me (6.0.1).
Some menu items are different from that are described in the article.

![lumacfg_6](https://cloud.githubusercontent.com/assets/1810723/17837673/a9dfc306-67c1-11e6-9c6b-8b3058eaa259.jpg)

Also, I've got a console freeze when trying to save a config by pressing "start". But it seems to be OK - it saved the config and freezed after that.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
