### ISSUE TITLE
Emu Ver. 9.2.0-20U Disappears

### ISSUE THREAD

**Issue by jinxist** [Plailect/Guide#362]
When I launch Luma into redNAND, I go into system settings to check and make sure that it is in Emu...However, when I exit this screen and come back it reverts to just the regular Ver. 9.2.0-20U 

(as an example...i was at the point in the steps for setting up rednand where it asks you to make sure it says emu in the system settings, and set dns to auto obtain)

Is it still in redNAND? Or do I need to enable something for it to stay in redNAND. I'm too nervous to continue with the process until I find out that i am doing this properly.

Please help!

**Comment by Ev1lbl0w** [comment]
If you enter Data Management or leave System Settings while on Emu/RedNAND, the system will put you back to SysNAND. That's why you should be careful when using System Settings. If you wish  to update your Emu/RedNAND, **YOU SHOULD ONLY UPDATE IF IT SAYS "EMU 9.2XXXXXX", BECAUSE IF NOT, YOU'LL BE UPDATING SYSNAND AND YOU CAN'T CONTINUE THE GUIDE WITHOUT DSIWAREHAX OR HARDMOD**

**Comment by jinxist** [comment]
Ok cool. I just read past a little and it says that...

"Update your RedNAND to the latest version using System Settings by going to the last page of "Other Settings" and selecting "System Update" (Once you exit System Settings / SD Card Management you will be returned to SysNAND, make sure to enter back into RedNAND before updating!)"

So here is what i see after booting luma and entering system settings...

![image1](https://cloud.githubusercontent.com/assets/21159029/17838983/692e0f54-67b5-11e6-9c8c-0529adbdc58b.png)

So am I good to go update from this point? In the instructions it says to check and make sure that your DNS is set to auto obtain...I think this should be rephrased or something because when you come out of the internet settings its back to sysNAND...and some people might not be as cautious as i am and follow through the update at that point... i dunno. All i need to know now is if im okay to update from this point.

**Comment by Ev1lbl0w** [comment]
Wait just a sec. I'm using a poor public wi-fi and the image is literally taking minutes to load...

**Comment by Ev1lbl0w** [comment]
Finally...

Ok, you're safe to update.

And one more thing: next time use this IRC client: https://qchat.rizon.net/?channels=3dshacks&uio=d4
You can get help faster and ask things way easier. Github issues are normally for more difficult matters.

**Comment by jinxist** [comment]
Ok thank-you so much!

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
