### ISSUE TITLE
Rednand shows "Sys 9.2.0" Not "Emu 9.2.0"

### ISSUE THREAD

**Issue by SlipperySkater** [Plailect/Guide#363]
After following everything on Plailect's guide on part 3 up to step 26, I am stuck on this step. I open homebrew via menuhax on boot of my 2ds and open luma, I've selected "Show current nand in system settings" and I after that I press start and it then loads into the home menu successfully, however, after that is done I open system settings and it just shows "Sys 9.2.0-20U" and I'm not really sure if I'm on rednand or not or if I should update.

**Comment by khang06** [comment]
That is not RedNAND, that is SysNAND.

**Comment by SlipperySkater** [comment]
So how do I solve this then?

**Comment by Xavyrr** [comment]
I had this problem with a 2DS I did a couple days ago. Seems like Luma was booting into sysNAND. I fixed it by deleting the Luma folder and luma.dat from the SD root, the luma folder in /3ds/, and then recopying the Luma 3ds folder back onto the /3ds/. Then relaunching Luma and and being sure that boot into sysNAND is NOT checked. Hope this helps.

**Comment by sora10pls** [comment]
Or alternatively, just delete config.bin in the luma folder lol

**Comment by Xavyrr** [comment]
Well yes. I think it's a Luma 3DS bug tbh, since I've downgraded many consoles, and it only happened to me on the latest version of luma when I did it. Just to be absolutely sure, I removed every Luma related file, despite it being a config issue :V

**Comment by SlipperySkater** [comment]
Deleting just the config bin doesn't fix it and Xavyrr I'm sort of confused on how you fixed it with what you said. I am using luma v6.0.1 and so I deleted what you said to delete and I just recopied the 3ds luma folder in the 3ds folder then launched it then up comes a screen where I need the luma 3ds.dat and then I put that in the root and so the luma menu loads and by "boot into sysNAND is NOT checked" you mean not to check Autoboot sysnand?

**Comment by james-d-elliott** [comment]
@SlipperySkater correct. If you have "Autoboot SysNAND" checked it will boot SysNAND not RedNAND.

**Comment by SlipperySkater** [comment]
Well it was never checked in the first place and it still says Sys 9.2.0?

**Comment by Xavyrr** [comment]
Delete all the Luma related files and try 5.5.

**Comment by Xavyrr** [comment]
I really think it's a bug with the latest Luma release. I must have just been lucky.

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
