### ISSUE TITLE
o3ds 8.1-19u stuck on 9.2 upgrade decrypt9 wont load

### ISSUE THREAD

**Issue by m3rrkk** [Plailect/Guide#365]
Hello all, 

I have a stock 03ds on 8.1-19u, I did a reset with the sd in the 3ds, i followed the guide and started with the freeway method. 

so basically i had a stock fresh 03ds on 8.1-19u, i added the files to the root of sd, popped it in and went to the link provided to launch decrypt, and i just end up with the bottom screen black with colored pixel artifacts. ( how long is it supposed to take to load decrypt? ) ive tried the decrypt launcher .dat and get a black screen flash then white screen on the bottom and nothing.

Ive tried the rx tools method with all of them flashing the bottom screen to white but never loading enything.

Am i missing some step required to have a stock 8.1-19u launch decrypt through a browser? does it take more than a few minutes to load decrypt?

I bought this 3ds secondhand, i dont believe any mods were done, but is it possible some softmods were done and then i reset through settings and did something to block the browser from launching decrpyt?

thanks

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
