### ISSUE TITLE
All firm.bin links are down (need update)

### ISSUE THREAD

**Issue by skoomaeater** [Plailect/Guide#366]
This is the error I am recieving, however, the firm.bin links are down.  How can I go about acquiring one?

**Comment by Ev1lbl0w** [comment]
Let me see if I can get the torrent of your file. Wait just a sec...

**Comment by Ev1lbl0w** [comment]
Can't find it. Wait for Plailect to update the links.

**Comment by iuzwpr2p39rh7w** [comment]
Use one of these links until Plailect updates this guide.
[#1](https://mega.nz/#!5cFU1AjJ!2mUQ0_1v4m6ejiJO9RRfusRQ1VnoFZi7OH3f-6SO62Q)
[#2](http://www.mediafire.com/download/hgawmzh87mo5zg5/firm.7z)
[#3](http://www.multiup.org/download/24bc523b415b206f136b5217554c74ba/firm.7z)

**Comment by skoomaeater** [comment]
brilliant! thanks for the help!  downgrading now!

**Comment by Plailect** [comment]
New guide is up and all currently open issues are being closed. If you feel your issue still applies to the new guide, you can request for it to be re-opened by replying to it.
