### ISSUE TITLE
Homebrew Launcher (Browser) page links to wrong link

### ISSUE THREAD

**Issue by fwn212** [Plailect/Guide#368]
At the bottom of [the page](https://github.com/Plailect/Guide/wiki/Homebrew-Launcher-(Browser)), it says "You can now continue from 9.2.0 Downgrade (even if you are already on a version from 9.0.0 to 9.2.0).", but the link linked on 9.2.0 Downgrade is to the 2.1 downgrade, not the 9.2 downgrade

**Comment by Plailect** [comment]
Fixed
