### ISSUE TITLE
[Enhancement] Torrent rss

### ISSUE THREAD

**Issue by ChaosTherum** [Plailect/Guide#369]
So I am perfectly happy seeding the torrents for you and I was thinking it would be great if you could create an rss feed for people to drop in their torrent clients so that we can automatically download the torrents and then seed them without us having to pay attention to it.

**Comment by sickness0666** [comment]
this would be a good idea for me also. dropped all torrents onto my 1gbps seedbox to seed from

**Comment by james-d-elliott** [comment]
I'd be willing to setup some space for this and give the relevant parties access to modify it (if needed).

**Comment by ChaosTherum** [comment]
Well I'm glad I'm not the only one interested.

**Comment by Plailect** [comment]
@james-d-elliott if you could make one, I could host it on the gh-pages repo

**Comment by james-d-elliott** [comment]
Sure, writing a simple generator for it in python3 so it can easily be maintained.

**Comment by james-d-elliott** [comment]
Should work fine, I've tested via uTorrent if anyone else wants to test it. Didn't work in Vuze, but not sure how that system even works.

https://raw.githubusercontent.com/james-d-elliott/Guide/gh-pages/rss.xml

**Comment by sickness0666** [comment]
works well with rutorrent

**Comment by Plailect** [comment]
@james-d-elliott could you pull request this? I will merge after testing

**Comment by james-d-elliott** [comment]
It's done. The BEP standards are not clearly documented but I think it matches. Would be nicer with more examples.

**Comment by james-d-elliott** [comment]
@sickness0666 if you could verify it still works for you I'd appreciate. @ChaosTherum if you could check it in your tor client. c;

**Comment by Plailect** [comment]
Reverted PR, got errors in the XML:

>error on line 13 at column 96: Namespace prefix media on content is not defined
error on line 14 at column 27: Namespace prefix media on hash is not defined

**Comment by sickness0666** [comment]
@james-d-elliott using the xml located at: https://raw.githubusercontent.com/james-d-elliott/Guide/gh-pages/rss.xml, rutorrent still picks it up as valid and lists 38 torrents
