### ISSUE TITLE
Uncart is GPL

### ISSUE THREAD

**Issue by chaoskagami** [Plailect/Guide#37]
You link to an uncart binary in your guide. Not only is this not an upstream build - it lacks source code. I can't find any forks on github for it, which means it came from elsewhere. Look, hate to be THAT guy, but...

Uncart is GPL. I'm not saying to pull it - I'm not even a dev of uncart, but it is a license violation.

Not to mention I find trimming undesirable, and would like to disable it. Can't do so without source.

**Comment by Plailect** [comment]
This build of Uncart was ported by Gelex (#Cakey dev member), who has
promised to release the source once he received authorization from the
company he works at. If you have issue with this, take it up with him.

**Comment by chaoskagami** [comment]
Okay, cool. At least nice to know steps are being taken.

Sorry if that came off rude at all. :/

**Comment by Plailect** [comment]
See citra-emu/uncart#16
