### ISSUE TITLE
Comments on new guide

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#370]
Homebrew Launcher (No Browser):
-- BASICSploit and smilehax require different versions of SmileBASIC so it may be useful to mention what they are
-- Ninjhax should not be listed as always needing a browser.  Ninjhax 1 needs a browser and Ninjhax 2 doesn't, and they work on different firmware.   OOT3dhax should not be listed as requiring a browser,  (I don't know why smea's page requires that the user input a browser version for Ninjhax 2 and BASICSploit.)
-- smashbroshax should say that it requires a version of Super Smash Bros. that [doesn't have 1.1.4 update on the cart](https://www.reddit.com/r/3dshacks/comments/4tqso0/new_smash_bros_3ds_cartridge_with_114/).

Homebrew Launcher (Browser):
-- "9.9.0 - 10.6.0: Follow this guide as written." "11.0.0: You MUST have downgraded your firmware already.", completely leaves out 10.7.
-- 10.7 and 11.0 should include the old instructions for setting your DNS.  Although currently this is not necessary because their browser is up to date, it should be done for safety because you can't know that Nintendo won't release a 11.1 with a new browser before the next time you update the guide.

Part 1 Decrypt9:
-- No Cubic Ninja OTP entry for 1.x/2.x.
-- 9.2.0 with browser suggests doing a 9.2.0 downgrade.  This is even odder considering that 9.2.0 without browser does *not* suggest doing one.

Part 3:
-- "This guide uses "Updated SysNAND" mode, in which we copy our RedNAND to SysNAND (to keep games and such)".  No it doesn't any more, except in edge cases where someone already has a RedNAND.
-- The three items I suggested in https://github.com/Plailect/Guide/issues/350 .
-- Troubleshooting guide for black screen on SysNAND boot should contain a link to https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-get-a-black-screen-on-boot-with-an-old3ds-which-was-downgraded-from-the-gateway-menu-in-the-past

**Comment by Plailect** [comment]
> Homebrew Launcher (No Browser):

Fixed all

>Part 1 Decrypt9:

Cubic Ninja OTP was worthless because you couldn't get off of those versions without cart updating (unless you were on 2.1, in which case you can dump OTP with the browser), and if you cart update you can just use the current method

Reworked 9.2 update page handling with 9.0 versions

>Part 3:

Fixed all
