### ISSUE TITLE
o3ds 8.1-19u stuck on 9.2 upgrade decrypt9 wont load

### ISSUE THREAD

**Issue by m3rrkk** [Plailect/Guide#371]
Hello, 

i have O3ds 8.1.0-19u that will not load decrypt9

I have been trying all week,

stock 3ds, drop files on root of sd, load broswer link and the bottom screen either flashes to black with multi colored artifacts/pixels, or flashes black then white. either way nothing happens after that.

what am i doing wrong, im getting super frustrated. 

I have tried resetting the 3ds with the sd inside, clearing cookies, history, and clear save data

**Comment by Plailect** [comment]
Have you tried each URL?

**Comment by james-d-elliott** [comment]
My first time installing A9LH browserhax worked the first time; however I've done a few for friends recently and a single device took somewhere in the order of 30 attempts. Also I'd try moving or renaming the profile folder under Nintendo DS (the profile folder is a seemingly random long string, about 32 characters long, and I think it's hex only; A through F, 0 through 9).

**Comment by MelonGx** [comment]
8.1.0-19U should be compatible with both GW Spider + Launcher.dat and CakeHax Spider + Decrypt9WIP.dat.
Please be sure you have tried both and not messing up both URL addresses.

**Comment by MelonGx** [comment]
If you really did everything right, then it might be a factory SysNAND issue.
This may be unfixable until you upgrade the SysNAND to another version.

**Comment by m3rrkk** [comment]
Thanks for your responses everyone, im not sure what i should do from here :( probably going to give up this 3ds has a bad card reader that i replaced and was working for a bit, but isnt anymore so cart upgrade is out the window
