### ISSUE TITLE
Crash trying to configure Luma.

### ISSUE THREAD

**Issue by PrfctPrfct** [Plailect/Guide#372]
After doing everything up to the part I have to configure luma to this part...

Use the (A) button and the D-Pad to turn on the following:
"Autoboot SysNAND"
"Show current NAND in System Settings"
"Show GBA boot screen in patched AGB_FIRM"
If you are using a New 3DS, you should also enable the following:
    Toggle "New 3DS CPU" to "Clock+L2(x)" for improved game performance
Press Start to save and reboot

After I reboot I'm getting this crash.

https://postimg.org/image/c6zfebibt/

**Comment by Plailect** [comment]
Have you restored your original backup?

**Comment by PrfctPrfct** [comment]
Not yet... I just tried and I can get to hourglass fine... the problem only comes up when trying to boot after Luma... I'm gonna recheck everything again but what is your guess?

**Comment by dark-samus** [comment]
Our guess? You mean, why won't Luma boot a FIRM it doesn't support? I don't know man, that's a tough one...

**Comment by Plailect** [comment]
You downloaded the "dev" version of luma instead of the regular one. Fix that, it still won't boot until you continue with the guide though.

**Comment by PrfctPrfct** [comment]
Oh yeah... I downloaded the dev file... you should put a disclaimer there... I thought both files were the same... sorry about that.

**Comment by Plailect** [comment]
Just added one

**Comment by PrfctPrfct** [comment]
So... if I overwrite the files it should work NP or do I have to restore NAND and do everything again?

**Comment by Plailect** [comment]
Overwrite...

**Comment by PrfctPrfct** [comment]
Perfect I think that did it, thank you very much! Now I'm restoring my nand... I will update you if everything goes well :)

**Comment by PrfctPrfct** [comment]
Everything went perfect after that, thank you :)
