### ISSUE TITLE
Small questions

### ISSUE THREAD

**Issue by Autz64** [Plailect/Guide#375]
1- What version of Decrypt9 should be used? Can Plailect post a link to the latest release?

2.- The [CTRNAND fix](https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-get-a-black-screen-on-boot-with-an-old-3ds-which-has-been-downgraded-from-the-gateway-menu-in-the-past) should be used if i'm going to use a [redNAND backup](https://github.com/Plailect/Guide/wiki/Move-RedNAND) instead of the sysNAND backup? My sysNAND was downgraded with Gateway, but not the redNAND. Should i follow the steps?

**Comment by tommai78101** [comment]
1. You need to click on the link of what you accomplished when upgrading/downgrading your SysNAND version. The Decrypt9 link will be given to you once you click on the links in the chart/table.

2. I don't know about this.

**Comment by james-d-elliott** [comment]
Decrypt9WIP by D0k3, 2016/08/23 (verify in the main menu of Decrypt9WIP). https://github.com/d0k3/Decrypt9WIP/releases/latest

**Comment by Autz64** [comment]
And also, that /file9/ folder on Step 2, should be created by the user? Or is a special folder that has some archives aside from this guide?

**Comment by Plailect** [comment]
2\. Only do it if you can't boot.

All links have been updated to use the /releases/latest url.
