### ISSUE TITLE
Part 2 Step 5-8. Is sysnand backup integrity auto checked?

### ISSUE THREAD

**Issue by ultimatespirit** [Plailect/Guide#376]
In part 2 we dump sysnand and then proceed to writing the 2.1 ctrnand immediately without manually checking sysnand backup integrity. Does the installer check this? If so then step 8's warning on sysnand integrity is unneeded. If it doesn't then step 8's suggestion to redump sysnand would just dump a sysnand with the 2.1 ctrnand.

**Comment by james-d-elliott** [comment]
Important note on this, currently D9 will continue if the backup fails due to lack of space. It's reasonable to assume it currently does not verify? May be worth adding a note to do the backup manually till then for recovery in the event of something going wrong.

**Comment by Autz64** [comment]
You can do the backup before doing the CTRNAND step and save it with another name (to check if the backup is good), then follow the steps as stated.

**Comment by Plailect** [comment]
Adjusted the steps.

Relevant: https://github.com/d0k3/Decrypt9WIP/issues/83

**Comment by Plailect** [comment]
Adjusted the steps.

Relevant: https://github.com/d0k3/Decrypt9WIP/issues/83
