### ISSUE TITLE
More comments on new guide

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#377]
Homebrew Launcher (Browser) probably should suggest using the DNS change with 10.7 and 11.0 (even though it is not necessary currently).

Changing the date and time and initializing savedata should be skipped for 10.7 and 11.0 (for different reasons than for 9.0-9.8).

Part 2 tells you to copy NANDmin.bin and NANDmin.bin.sha from the files9 folder to your computer.  Part 3 then tells you to copy everything from the files9 folder to your computer; these are redundant instructions.  Part 3 also tells you to copy the NANDmin.bin and NANDmin.bin.sha to the files9 folder , which should be unnecessary since they started already in there.  (Instead of telling people to copy, you could say something like "Be sure that the NANDmin files are in the files9 folder.")

This is a nitpick, but part 3 section 2 step 6 should probably say to turn off your console first.

**Comment by Autz64** [comment]
The idea of those redundant instructions is to backup the files and for newbies to tell if they have the correct files on it. Maybe Plailect can modify that for better understanding. And about the part 3 section 2 step 6, i noticed that too, but at that point it tells you that Luma can't boot 2.1 CFW, so is safely to assume that the console should be off.

**Comment by arromdee** [comment]
Having two sets of instructions which tell you to copy the same files from the same folder is not useful redundancy.  It's a mistake.

**Comment by Plailect** [comment]
>Homebrew Launcher (Browser) probably should suggest using the DNS change with 10.7 and 11.0 (even though it is not necessary currently).

If you read the comments in the markdown files by cloning the repo, they're in there waiting for future updates

>Changing the date and time and initializing savedata should be skipped for 10.7 and 11.0 (for different reasons than for 9.0-9.8).

added

>Part 2 tells you to copy NANDmin.bin and NANDmin.bin.sha from the files9 folder to your computer. Part 3 then tells you to copy everything from the files9 folder to your computer; these are redundant instructions. Part 3 also tells you to copy the NANDmin.bin and NANDmin.bin.sha to the files9 folder , which should be unnecessary since they started already in there. (Instead of telling people to copy, you could say something like "Be sure that the NANDmin files are in the files9 folder.")

fixed

>This is a nitpick, but part 3 section 2 step 6 should probably say to turn off your console first.

fixed
