### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by 11dbz11** [Plailect/Guide#378]
After restoring the sysnand I have been getting a black screen on boot. But I'm still able to access both luma and hourglass is there a way to fix this?

**Comment by james-d-elliott** [comment]
Load your SD card into your card reader, and MOVE the folder with 32 chars from the Nintendo DS folder, to your PC. You can delete it safely probably, but, just in case.

You may alternatively boot without the SD inserted. You'll need to put it back in if you're going to use browserhax but do it after the browser is open.

**Comment by TheAquaSheep** [comment]
I have this same issue.
I started with an old small black 3ds on OFW 7.1.0-16E and followed the guide exactly up to Part 3 Section IV - 5, where I should be able to reboot after restoring sysNAND with Hourglass9.

I instead get a black screen upon boot but can still access Luma settings and Hourglass9 if holding the respective buttons during boot.

Deleting the 32 character folder from the Nindendo 3DS folder on the root of the SD card does not help.

**Comment by james-d-elliott** [comment]
Check you're running the latest Luma (6.0.1) and that the settings are correct. Should be auto boot sysnand, use sysnand firm if booting with R, show current nand, and show gba boot screen.

**Comment by TheAquaSheep** [comment]
Luma 6.0.1 is indeed being used and is configured as stated. (originally without the hold R option but also tested with).
It still just boots to black screen.

**Comment by 11dbz11** [comment]
Followed the guide to a T. I also cannot access recovery mode either

**Comment by TheAquaSheep** [comment]
11dbz11, can you give any more details? eg Firmware version, whether you are on emunand/sysnand or what type of console you have.

I take it what worked for me does not help you?
As you can access luma and hourglass, It means that a9lh is successfully installed and working so it could be a Luma issue.
A quick Google did not manage to find me a minimum required firmware to use Luma (I'm working so can't really look harder) but I assume, in my case, that 7.1.0 was loo low for Luma.
If this is true then the guide should mention to update (to 9.2.0?) somewhere.

**Comment by Plailect** [comment]
Fixed the Decrypt9 issue for 9.2.0-ctrtransfer.

Luma3DS should work on all SysNAND versions  >=4.0.0 as far as I am aware.

Do https://github.com/Plailect/Guide/wiki/Troubleshooting#ts_sys_a9lh

**Comment by TheAquaSheep** [comment]
Plailect,
Thanks for fixing that, and for the guide to start with.

I performed all of the troubleshooting steps before trying the 9.2.0 ctrtransfer.
Nothing on that list fixed the black screen but the test payload did work as expected.

Is it fine to continue using the system now?
As I understand it, it has had all of my personal details injected so it is still my system NAND and not an image everyone is sharing?

**Comment by Plailect** [comment]
It is

**Comment by kembangkol** [comment]
@TheAquaSheep,
I'm having exactly the same issue as you.  My old 3DS XL had an OFW of 7.1.0-16U and after followed the guide perfectly, I ended up booting to black screen.  Troubleshooting section doesn't help, other than knowing that it's not bricked and it's because of error on "other things" which I totally have no idea which thing.  
However you mentioned that you solved the issue by doing 9.2.0 ctrnand.   Could you elaborate in this, please?   Where can I download the ctrnand?   Did you launch Decrypt9WIP as a Luma payload?   What to do next after a succesful boot on 9.2.0?

**Comment by TheAquaSheep** [comment]
I'm using a phone so won't be checking the guide for exact references or updates in this response.
Soon after the guide says to restore your NANDmin.bin file it gives a link to a troubleshooting page and a link to the 9.2.0 ctrtransfer page. You want the latter page, where you will find instructions to use Decrypt9WIP as a Luna payload and the necessary ctrtransfer images.
If you can successfully boot to 9.2.0, just continue with guide from where you initially black screened.
I'm not sure what the cause of this error is but, as we are on the same firmware, it looks like a bug in Lima 6.0.1 for firmware 7.1.0.
Good luck

**Comment by kembangkol** [comment]
After booted to black screen, I deleted arm9loader.bin from Luma 6.0.1 and replaced it with the one from Luma 5.5. I deleted config.bin inside Luma folder and launched the Luma 5.5 setup afterwards.  And I still booted to black screen.  It must be something else that cause this.

Anyway, really appreciate your prompt response and I'll follow your path.

**Comment by RayMafnas** [comment]
@TheAquaSheep I had the same issue and did the same steps but my 3ds freezes when i try to access Nintendo DS Connections on Internet setting could you try it on your end?

**Comment by TheAquaSheep** [comment]
Confirming that 3ds freezes (black screen) upon opening Nintendo DS corrections.
I updated to 11.0.0-33E after the 9.2.0-20E ctrtransfer and transferred my Nintendo account to this console in preparation for downgrading my other 3ds - so testing may be limited right now.
Eventually I'll try uninstalling a9lh and restoring my 7.1.0 sysnand, then update to 9.2.0 without ctrtransfer before reinstalling a9lh
