### ISSUE TITLE
Convert from previous guide?

### ISSUE THREAD

**Issue by uniQ168** [Plailect/Guide#379]
I already hacked my 3DS with the previous guide and was wondering, if there is anything I should do with the new guide. I'm pretty new to the scene and not yet into the details. Sorry, if this is a stupid question. ^^'

**Comment by james-d-elliott** [comment]
Nope, it just makes the process quicker and easier. I'd update your sd:/luma/payloads/ folder if you're confident in doing so. Just need the new .bin files to replace the old ones as noted in part 3.
