### ISSUE TITLE
Please help with the region changing step 23

### ISSUE THREAD

**Issue by genehung2003** [Plailect/Guide#38]
After I fully change my 3DS region from Japan to USA,
I launch the downgrade check.

Besides title that does not match the expected versions,
I still have Extra title and Missing title
And the desktop have alot of duplicated apps
After I use FBI to delete those title that does not match the expected versions,
My console gets brick when I try to update it.
Then I have to restore the a9lh NAND again from the decrypt9

what did I do wrong?

Heres the check 

Title ID 0x0004003020008802
  Extra title

Title ID 0x000400300000c302
  Extra title

Title ID 0x000400300000c602
  Extra title

Title ID 0x0004003000008202
  Extra title

Title ID 0x000400300000bc02
  Extra title

Title ID 0x000400300000c102
  Extra title

Title ID 0x000400102002c800
  Extra title

Title ID 0x0004001020020300
  Extra title

Title ID 0x000400100002bf00
  Extra title

Title ID 0x0004001000020a00
  Extra title

Title ID 0x0004001000020000
  Extra title

Title ID 0x0004001000020900
  Extra title

Title ID 0x0004009b00012202
  Extra title

Title ID 0x000400db00017202
  Extra title

Title ID 0x000400db20016202
  Extra title

Title ID 0x0004009b00015202
  Extra title

Title ID 0x0004009b00013202
  Extra title

Title ID 0x0004009b00011902
  Extra title

Title ID 0x0004009b00010602
  Expected version 0x0002
  Installed version 0x0400

Title ID 0x000400302000c003
  Extra title

Title ID 0x000400300000c402
  Extra title

Title ID 0x000400300000c002
  Extra title

Title ID 0x0004003000009502
  Extra title

Title ID 0x0004003000008e02
  Extra title

Title ID 0x0004003000008d02
  Extra title

Title ID 0x0004003000008702
  Extra title

Title ID 0x0004003000008602
  Extra title

Title ID 0x0004003000008402
  Extra title

Title ID 0x0004003000008302
  Extra title

Title ID 0x000400102002cb00
  Extra title

Title ID 0x000400102002ca00
  Extra title

Title ID 0x000400102002c900
  Extra title

Title ID 0x0004001020023100
  Extra title

Title ID 0x0004001020020d00
  Extra title

Title ID 0x0004001000020f00
  Extra title

Title ID 0x0004001000020e00
  Extra title

Title ID 0x0004001000020b00
  Extra title

Title ID 0x0004001000020800
  Extra title

Title ID 0x0004001000020700
  Extra title

Title ID 0x0004001000020500
  Extra title

Title ID 0x0004001000020400
  Extra title

Title ID 0x0004001000020200
  Extra title

Title ID 0x0004001000020100
  Extra title

Title ID 0x0004013000001b02
  Expected version 0x0800
  Installed version 0x0c01

Title ID 0x0004013000001a02
  Expected version 0x1400
  Installed version 0x1801

Title ID 0x0004009b00015302
  Missing title

Title ID 0x0004009b00011e02
  Missing title

Title ID 0x0004009b00011d02
  Missing title

Title ID 0x0004009b00011602
  Missing title

Title ID 0x0004009b00011402
  Missing title

Title ID 0x0004001000021f00
  Missing title

Title ID 0x0004001000021e00
  Missing title

Title ID 0x0004001000021b00
  Missing title

Title ID 0x0004001000021800
  Missing title

Title ID 0x0004001000021700
  Missing title

Title ID 0x0004001000021500
  Missing title

Title ID 0x0004001000021200
  Missing title

**Comment by Plailect** [comment]
Edited to be more clear, refresh.
