### ISSUE TITLE
Luma3DS emuNAND doesn't boot

### ISSUE THREAD

**Issue by LioMajor** [Plailect/Guide#380]
Using emuNAND9 to create an emuNAND and booting Luma3DS latest commit doesn't boot.
Luma3DS dev build gives the following error: aes, LDR R3, [R12], r12 = 0x04010000
A previouse full backup of NAND.bin injecting works and Luma3DS boots emuNAND.

**Comment by Autz64** [comment]
1.- Don't use Luma's DEV version.
2.- Why would you create an emuNAND using emuNAND9 on this guide?

**Comment by LioMajor** [comment]
1. Since Luma3DS didn't boot, TuxSH wanted to investigate > Crashdump
2. Not on this guide, i don't want to use sysNAND only
3. If this methode can't produce a working emuNAND, then there is something wrong

**Comment by Plailect** [comment]
This is unrelated to this guide entirely, make an issue for Luma.
