### ISSUE TITLE
New3DS 9.2.0-20X ctrtransfer image torrent files not found

### ISSUE THREAD

**Issue by TheAquaSheep** [Plailect/Guide#383]
The torrents here (https://github.com/Plailect/Guide/wiki/9.2.0-ctrtransfer) for the New3DS images are not found.

**Comment by iuzwpr2p39rh7w** [comment]
Which is odd considering their existence in the [torrents archive](https://github.com/Plailect/Guide/archive/gh-pages.zip)...

**Comment by Plailect** [comment]
Fixed, the "DS" in the link was capitalized when they should not have been.
