### ISSUE TITLE
Stupid question about the 3ds fodder

### ISSUE THREAD

**Issue by SerGeorgious** [Plailect/Guide#385]
Hello,

I am not quite experianced, so I ran into an issue.
I am afraid of bricking the 3ds or having issues later so I prefer to look stupid than to make a mistake.

In the third part of the tutorial the second step of the preping up is to delete the 3ds fodder (does that mean the Nintendo 3DS fodder) and what mostly confuses me is that the last step is about putting DspDump.3dsx to the /3ds/ fodder. Should I create one?

I am sorry for the stupid post I made. It is probably quite simple. Thank you in advance!

**Comment by Plailect** [comment]
You delete the 3ds folder, then recopy the stuff out of starter.zip, then copy in dspdump
