### ISSUE TITLE
Section 4

### ISSUE THREAD

**Issue by SerGeorgious** [Plailect/Guide#387]
I finished doing all of the section 4 and now the 3ds was supposed to boot but all I am getting is an error.

Then I tried doing the 9.2.0 ctrtransfer as was said in the tutorial but I cant boot into Decrypt9 by holding  X and powering on. Am I doing something wrong?

**Comment by Autz64** [comment]
https://github.com/Plailect/Guide/wiki/Troubleshooting#ts_sys_a9lh
