### ISSUE TITLE
CTRBootManager is a good option?

### ISSUE THREAD

**Issue by Autz64** [Plailect/Guide#388]
I'm on sysNAND 9.2 and i can access to the Homebrew Launcher on CTRBootManager via HomeMenuHax.

That still counts as an entrypoint for Decrypt9?

**Comment by dark-samus** [comment]
Why wouldn't it?

**Comment by Autz64** [comment]
The guide doesn't specify the use of CTRBootManager. My fear confuses me.

**Comment by Plailect** [comment]
It'll work
