### ISSUE TITLE
Please help with the region changing step 23 (edited)

### ISSUE THREAD

**Issue by genehung2003** [Plailect/Guide#39]
After I fully change my 3DS region from Japan to USA,
I launch the downgrade check.

Besides title that does not match the expected versions,
I still have Extra title and Missing title
And the desktop have alot of duplicated apps
After I use FBI to delete those title that does not match the expected versions,
My console gets brick when I try to update it.
Then I have to restore the a9lh NAND again from the decrypt9

what did I do wrong?

check log attached
[check.zip](https://github.com/Plailect/Guide/files/195735/check.zip)

**Comment by Plailect** [comment]
Refresh, it should say delete the extra titles

**Comment by genehung2003** [comment]
How do I refresh ><?
FBI or downgrade check?

Sorry for these NOOB question><

**Comment by genehung2003** [comment]
How about missing titles and wrong expected titles?
Should I just leave it alone? or try to fix it ><?

**Comment by Plailect** [comment]
Refresh the page...

Leave them alone.

**Comment by genehung2003** [comment]
I got some great findings when I am deleting the title one by one 
Just for you to know that I change my region from Japan to US

1. Almost all title that are CTR-X-XXXJ , which ends with J are extra title
2. Some title CTR-X-XXXP, whuch ends with P are extra title
3.The rest of extra titles can be found in N/A

4. The extra titles are from the former 10.7.0 or 9.2 or 2.1.0 version

At last, thanks again for your splendid guide =)

**Comment by genehung2003** [comment]
I'm so sorry that I have to bother you again ><

Don't know why, but whenever I try to create a new folder or try to name a folder,

My console crashes and tells me to power off by holding the power button

Could you please help me out ><?

**Comment by Plailect** [comment]
Not a clue

**Comment by genehung2003** [comment]
I solve it
Looks like we need to install the missing titles back by FBI.
I download the missing titles from 3DSUS, from old 3ds firmware

These are what I do

delete the extra titles, ignore the unexpected version titles, and install the missing titles

And wala! Region was changed smoothly!
