### ISSUE TITLE
A9LH can now boot without an SD card

### ISSUE THREAD

**Issue by TheKoopaKingdom** [Plailect/Guide#396]
[This page](https://github.com/Plailect/Guide/wiki/Part-3-(arm9loaderhax)) says you won't be able to boot without an SD card, but that's now possible.

**Comment by ihaveamac** [comment]
[there are no releases of AuroraWright's arm9loaderhax that have this though.](https://github.com/AuroraWright/arm9loaderhax/releases)

**Comment by fwn212** [comment]
having people have to compile a9lh for the guide will cause far much more trouble than booting without sd is worth

**Comment by ihaveamac** [comment]
it's not that users would have to compile it (just give the payload stages), it's that the SD-less a9lh is not finished yet and has some issues (reboot patches I think).

**Comment by Margen67** [comment]
https://github.com/TuxSH/arm9loaderhax/commits/dev ?

**Comment by ihaveamac** [comment]
it's better to wait for a proper tested release that removes any of the major known bugs. giving an untested/unstable build to noobs is probably not a good idea.

**Comment by Plailect** [comment]
The guide doesn't take unstable beta software and throw it at end users.

**Comment by mariogamer2** [comment]
This is not unstable at all...

Also,there is a release by @RShadowhand : https://github.com/RShadowhand/ShadowNAND/releases/tag/v0.85

**Comment by RShadowhand** [comment]
My releases are alpha, so they should not be installed freely. There's more work to be done on that front.

**Comment by dark-samus** [comment]
Release is not equal to stable. Sure, that is how /most/ people do things, but not everyone (as shown by Shadowhand)

**Comment by RShadowhand** [comment]
I've always said that it was not a full release. There's a reason why it's 0.85, and not 1.x+

**Comment by Autz64** [comment]
Well, i followed the steps of this guide and i can boot without the SD. How can this be?
