### ISSUE TITLE
A9LH installer glitched screen / no reboot

### ISSUE THREAD

**Issue by Bullsquid** [Plailect/Guide#397]
The [manual](https://github.com/Plailect/Guide/wiki/Troubleshooting#ts_safe_a9lh_screen) says that if you get a glitched screen, you should press select and wait till the console reboots. I did so, however it didn't reboot for me, I had to do it manually, as I thought that browserhax didn't work at all. I removed the SD and was expecting to boot 2.1, but got nothing. For a second I thought that my console was bricked, until I found that it actually installed A9LH successfully. I've set up everything with no further issues.
So the guide should probably mention, that sometimes you have to reboot manually after waiting some time and still getting this glitched screen (mine actually looked totally frozen).

**Comment by Plailect** [comment]
Fixed
