### ISSUE TITLE
im on FW 10.7.0-32U which one should i use?

### ISSUE THREAD

**Issue by TsukiRyori** [Plailect/Guide#398]
no browser or browser? im confused as hell sorry

if its no browser im fucked i dont have any of the games listed

**Comment by ihaveamac** [comment]
this is not a support forum.

that being said, start with "[Homebrew Launcher (Browser)](https://github.com/Plailect/Guide/wiki/Homebrew-Launcher-(Browser))" then go to "[9.2.0 Downgrade](https://github.com/Plailect/Guide/wiki/9.2.0-Downgrade)".

**Comment by TsukiRyori** [comment]
sorry how cani delete this
