### ISSUE TITLE
Decrypt9

### ISSUE THREAD

**Issue by Duckbuster** [Plailect/Guide#4]
In part four of the guide regarding the H&S inject.
You need the Decrypt9 folder in the root of your SD otherwise Decrypt9 won't boot. 
Also need to place the "FBI_inject_with_banner.app" file to the Decrypt9 folder in the root, otherwise you can't select that file (it's also where the extracted file is).

**Comment by Plailect** [comment]
Decrypt9 Folder: That's not true, it works fine without the folder.

.app file: It should use the root of the SD card if you are using the latest version
