### ISSUE TITLE
Help Please 

### ISSUE THREAD

**Issue by raptordmg** [Plailect/Guide#40]
When I downgrade everything is fine when I check it in OTPHelper "Checking title 0004013800000102...
TMD not found or corrupt". I have now downgraded and then reset to NAND_emu_formatted.bin 5 time now and it's always the same error and it doesn't show up in godmode9.

Sorry if I have missed an instruction.

**Comment by Plailect** [comment]
You must install a stock TWL_FIRM, try installing the 0004013800000102.cia file found in the 9.2.0 downgrade pack for your region.
