### ISSUE TITLE
clarification - (if your device is not from one of these regions, just pick one):

### ISSUE THREAD

**Issue by Leerz** [Plailect/Guide#400]
If my 3ds is J, can i Use a U region to directly region change?

**Comment by Ev1lbl0w** [comment]
there's no need, there is a jpn region package for you.

**Comment by Leerz** [comment]
my apologies, maybe I did not make my question clearer.
if my Region is J, (and wish to regionchange it later after the guide) 
can I use the U region during the 2.1 transfer?  - saves 1 batch of transfer.

also, for example, my region is K, can I use the U also to get my OTP? won't I need to change the secureinfo too?

**Comment by Ev1lbl0w** [comment]
I believe you can't, or else you'll brick. If I were you, I would do the 3 steps using JPN packages, because in the older guide (I don't know if this happens in this one) was filled with phrases saying "You must use the correct package of your system's region, or YOU'LL BRICK".

**Comment by Ev1lbl0w** [comment]
Also, the quote "if your device is not from one of these regions, just pick one" just really matters for China Korean and Taiwan consoles which couldn't do A9LH before.

**Comment by Plailect** [comment]
You really shouldn't since then you'd end up with someone else's secureinfo permanantly, and thus their serial number registered to be used multiple times on Nintendo's servers. They may start taking action and issuing network bans for this in the future.

**Comment by Margen67** [comment]
Couldn't you region swap, dg to 2.1, then install A9LH using the original secureinfo/sysnand?
