### ISSUE TITLE
nintendo screen error twice during downgrade N3dsXL

### ISSUE THREAD

**Issue by maximus298** [Plailect/Guide#401]
I've followed the downgrade tutorial by the T.  However, i have receive the nintendo screen error twice in a row, which should not happen and thus having to install the latest update and ruining homebrew.  I used the links in the guide to download the updated programs and I have successfully upgraded O3ds and install arm9loader so i am not exactly clueless, but I can't figure out what is going on with the error screen.  I'm using the sysdowngrader that is in the guide.

**Comment by Ev1lbl0w** [comment]
This is written on the top of the 9.2.0 Downgrade page:

"All variations of sysUpdater, not just sysDowngrader, have a very small chance of causing a "soft brick" once the downgrade is complete and the device reboots. This will cause the system to boot directly to the Nintendo error screen instructing users to power off the device."

It was not your fault nor anyone's fault. You were just very unlucky.
