### ISSUE TITLE
Followed the new guide, but get these "Sys 9.2.0" Not "Emu 9.2.0" #

### ISSUE THREAD

**Issue by gotaquestion** [Plailect/Guide#403]
I followed the NEW guide, did everything he said except updating in the System Settings because I was unsure about what it meant. That was the only thing I skipped in the whole guide.

While I was downloading some games from free shop, everything was working fine, I got a bunch of them up and running, but later I got an error on one of them, and the reason was that I had to update the system.

After searching I found that I shouldn`t update unless I had "Emu 9.2.0" showing in System Settings. Instead I`m stuck with "Sys 9.2.0" when I go there.

What do I do? Did something change on the new guide? Is it not necessary to have it show "Emu"
How do I see if I`m on SysNand or Emunand.

Please can someone tell me how I can update....

**Comment by leo60228** [comment]
you don't have an emunand. updating is fine.

**Comment by james-d-elliott** [comment]
Sys means Luma patched Sys nand. Which means if you followed the guide you have a9lh installed and booting via luma, updating is no problem as you're in a very well hacked environment. Trust the guide! c;

**Comment by gotaquestion** [comment]
Thank you guys, updated and it`s working perfect! You guys are awesome! Double thanks!
