### ISSUE TITLE
No step "really" prompt the user to format his 3ds

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#404]
In "Homebrew" or "9.2.0 downgrade" no step really prompt the user to format two time his 3ds.

I know,there is the text,but some user can pass it without reading it.... So I was wondering if the text can be moded or adding a step for this?

Note: user can receive error when formatting in system setting,so they can use Tinny format.

**Comment by Plailect** [comment]
...what?

**Comment by mariogamer2** [comment]
Well I explained.... There is no step for formatting the 3ds....

**Comment by Plailect** [comment]
Why would you need to?

**Comment by ihaveamac** [comment]
the "two formats" thing was when rednand was still used for the 2.1 downgrade.

if you mean https://github.com/Plailect/sysDowngrader/issues/1 that's an issue we still don't know how to fix. also formatting isn't so easy for some people.
