### ISSUE TITLE
Question about 9.2.0 CTRtransfer

### ISSUE THREAD

**Issue by MelonGx** [Plailect/Guide#415]
We know that injecting movable.sed to an unmatched console can make the console unable to access e-shop and other network services, with a unique error code (it's not 002-0102, but another one gives almost the same explanation which means your console's network function has been restricted). Only restoring a NAND backup without any movable.sed injection can fix this.
Doesn't 9.2.0 CTRtransfer do the same thing above?

I mean, the movable.sed, secureinfo_A etc. files inside 9.2.0 CTRtransfer image, are all unmatched to any console other than where it's extracted.
If it's true, then every console performed 9.2.0 CTRtransfer without restoring their own movable.sed/secureinfo_A etc. will be unable to access those network services.

I'm also asking d0k3 for help with this question.

**Comment by d0k3** [comment]
If you paid attention to the on-screen output during CTRNAND transfer, you would know that these files are in fact taken over from your current CTRNAND. Does that answer your question?

**Comment by MelonGx** [comment]
You're right. Step 2 dumps the console's movable.sed etc. files. Step 4 injects them and fixes CMAC. Nothing doubtful about this now.

**Comment by MelonGx** [comment]
You're right. Step 2 dumps the console's movable.sed etc. files. Step 4 injects them and fixes CMAC. Nothing doubtful about this now.
