### ISSUE TITLE
SysDowngrader freeze

### ISSUE THREAD

**Issue by zkabuto** [Plailect/Guide#416]
I have an Old 3ds LL 11.0.0-33 version, already hardmod, dumped NAND.bin, injected 10.4 Nattive FIRM successfully, but when i downgrade using SysDowngrader or Plaisysupdater, it get an error:
Checking for am:u...
Did not get am:u handle!

Attemting svchax...

And freeze. I tried about ~10 times, re-inject Native FIRM but it always freeze.
How can I fix it?

**Comment by leo60228** [comment]
keep trying, it took me like 15 minutes. the longest i've heard about is 85 tries, though that is really rare

**Comment by zkabuto** [comment]
Checking for am:u...
Did not get am:u handle!

Attemting svchax...

20 times

**Comment by zkabuto** [comment]
Downgrade success
I forgot create file9 folder so it cant downgrade
My fault
Thanks so much!
