### ISSUE TITLE
Add µTorrent as a suggested torrent client

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#418]
This might be a good idea as the current suggested client (Transmission-Qt) is Windows only. µTorrent supports Windows, Mac, Linux, and Android, is smaller than Transmission-Qt, and it supports RSS feeds.

**Comment by mariogamer2** [comment]
Nope,transmission support linux...

Also utorrent is not open source.... https://en.wikipedia.org/wiki/Comparison_of_BitTorrent_clients

And as you see in the same link,Transmission support more system than utorrent,add more advantage,and other.

So no,there is no reason to change this.

**Comment by ihaveamac** [comment]
https://www.transmissionbt.com is the main site, where you can find downloads for mac/linux/etc. the windows (Transmission-Qt) version is in "add-ons".

**Comment by Margen67** [comment]
>uTorrent

>good

You're referring to an old version without ads.. right?

If not, ew.

**Comment by ihaveamac** [comment]
in any case, still not better to give users older versions of software when there are more up to date better alternatives out there.
