### ISSUE TITLE
System update removes FBI

### ISSUE THREAD

**Issue by quantumcat1** [Plailect/Guide#419]
If you update your system after injecting FBI (which is the order in the guide: Part 3 Section V then VI) the FBI inject gets removed and you have to do it again. FBI inject should happen after updating the system.

**Comment by ihaveamac** [comment]
depends what system version you're updating from. 6.0.0__-11__ is the last time H&S got updated, so updating at any point after that won't remove the inject.

in any case, injection should happen after updating, due to cases like this.

**Comment by Plailect** [comment]
Fixed
