### ISSUE TITLE
sysNAND backup restore failure

### ISSUE THREAD

**Issue by TheDgtl** [Plailect/Guide#42]
During Part 4, Section IV, restoring the sysNAND_Original.bin is failing on an o3ds running with redNAND. Same section succeeded on an o3ds running emuNAND.

I believe the latest OTPHelper is creating mangled sysNAND backups when you're running redNAND instead of emuNAND.

**Comment by marilleo** [comment]
Can confirm, happened to me as well. Had to update my SysNAND to 10.7, downgrade to 9.2 and then use Decrypt9 to force restore my SysNAND backup.

**Comment by jonatan-branting** [comment]
I'm about to try this step on a N3DS. Will report back later.

**Comment by Plailect** [comment]
Use v0.84 of OTPhelper.
