### ISSUE TITLE
Clearing up DSiWare Downgrade Process

### ISSUE THREAD

**Issue by trinhno** [Plailect/Guide#420]
I've seen quite a number of people not getting their DSiWare game transferred to the target system because they did not transfer the SD card or its content over. Therefore it might be good to add that to the guide.
When you restart the target system, it will check online and find DSiWare in the SD card. If it doesn't find anything the process will finish and display the message "This system cannot participate in another system transfer for another 7 days", at which point you're screwed.
It may be better to ask people to take out the SD card from the source system when it prompts it will format and restart and put it in the target system when it prompts that it will restart to finish the process.
If for some reason the process is not completed and the message is not displayed, you can still try again by going into System Settings -> System Transfer. It will try again.

Another point, in my experience, it never prompts for deleting the target system's SD contents, just automatically do it. Also no harm there, so probably "Do NOT delete the target system's SD card contents if prompted" is not needed.

**Comment by james-d-elliott** [comment]
This is a little confusing so let me see if I can summarize what you're trying to say:

1. Add a warning about the 7 day restriction on transfers
2. Add a warning about making sure you swap the SD card when prompted
3. Add a note about failed transfers and that it's sometimes possible to start them again
4. Add a warning to NOT wipe the 'target system' SD card (the one that is in the target system at the START of the transfer)

Please let us know if this is accurate.

**Comment by trinhno** [comment]
Hi. Thanks for the reply.
1. I think most people know this so it's probably fine.
2. Yes, this is most important.
3. Yes, if the message has not appeared, it's still possible to continue.
4. The warning is already in the guide but is probably not needed. (In my case it did not even appear. It just proceeded wiping straight away after you press Transfer). You can also start the transfer without any SD card in the target system if you don't need to transfer any legally purchased game and saves.
