### ISSUE TITLE
Few people getting stuck on Part 3.

### ISSUE THREAD

**Issue by JumperGerald** [Plailect/Guide#421]
I just helped a few people in the irc with the same issue. They were all on Part 3 - Section 4. Basically when they went to restore to NANDmin.bin they were coming up with the black screen still but had a9lh access. After a bit of trouble shooting we had them do the 9.2.0 ctrtransfer to get them up and running. This worked for all three of them. It seems that there NANDmin.bin may have been 2.1 but I couldn't say for sure.

**Comment by Xavyrr** [comment]
I had to do this with the 2DS I just did, it's no big deal, you just have to look a little for the instructions. I'm guessing it's because quite a few things can cause the blackscreen (like no payloads or firmware bin etc.)

**Comment by Ev1lbl0w** [comment]
These guys here: https://github.com/Plailect/Guide/issues/412 also had black screen, did the 9.2.0 ctrtransfer, and now they TWL_FIRM seems corrupted. So there might be a big problem with this ctrtransfer.

**Comment by jaxrogers2** [comment]
Yeah, starting the guide on 2.1 seems to be a problem on this new method overall

**Comment by Plailect** [comment]
Consolidating into https://github.com/Plailect/Guide/issues/438
