### ISSUE TITLE
Issue while downgrading

### ISSUE THREAD

**Issue by DaniMan12** [Plailect/Guide#424]
When trying to downgrade from 9.90 to 9.20, it says: "titleException: main.cpp:150: Result: 0x0 Installing 03DS pack >7.0 on N3DS will always brick!" Anyone know what I need to do?

**Comment by Margen67** [comment]
Did you download the right downgrade pack for your region/model?

**Comment by Plailect** [comment]
^

**Comment by willkof2** [comment]
oh man, your answer lies in your question...
