### ISSUE TITLE
an error has occurred

### ISSUE THREAD

**Issue by roy827** [Plailect/Guide#426]
Hi, first of all, thank you for everything.

Here is my problem. after Finalizing setup, I switched to a new microSD 128gb and copied all the files onto it, then powered my 3ds up, when i opened "tile manager" it showed "an error has occurred, forcing the software to close, the system will now restart", i tried several times but same message. Then i returned to my old SD and it worked.

Any idea why i couldnt use the larger sd card? plz help.

**Comment by dark-samus** [comment]
Sounds like it isn't an issue with the guide, sounds like something else. This isn't a support forum, there are other places with people willing to help out, go there. Not here
