### ISSUE TITLE
Troubleshooting guide refers to OTPHelper

### ISSUE THREAD

**Issue by sora10pls** [Plailect/Guide#427]
As far as I can remember, the new guide doesn't use OTPHelper at all. I believe this should be referring to Hourglass9/Decrypt9WIP, rather than OTPHelper

![image](https://cloud.githubusercontent.com/assets/17801814/18073000/a5e13742-6e30-11e6-8f57-f3bc583e4b3e.png)

**Comment by Plailect** [comment]
fixed
