### ISSUE TITLE
Need Clarification on Part 3 Section IV

### ISSUE THREAD

**Issue by Gonzo75** [Plailect/Guide#429]
Awesome guide and was able to finish.  The only step that wasn't clear to me, so I skipped it, was:

10) Update your CFW SysNAND to the latest version using system settings (if it is not already)

If I were to do this now, I read this as boot up my device and go to Settings and perform a regular system update.  Is that correct?

**Comment by JumperGerald** [comment]
Correct, It is good practice to do a nand backup before the upgrade though.

**Comment by Gonzo75** [comment]
Hmmm...so did the upgrade and when I go to System Settings, it shows Sys 11.0.0-33U.  When booting up with R held down, I see the exact same thing. Is this expected?

Followed the installation instructions...am I missing something?

**Comment by JumperGerald** [comment]
I am unsure what you mean by holding R. The objective of this tutorial is to overwrite your system nand with a modifiable system nand. So since your on 11.0.0-33U. When holding select on boot do you boot into a9lh and do you still have fbi installed on your home menu? If so you have succeeded

**Comment by Gonzo75** [comment]
Thanks....closing this issue.
