### ISSUE TITLE
japan 9.2.0 n3ds files incompatible

### ISSUE THREAD

**Issue by Scrxtchy** [Plailect/Guide#430]
upon using the supplied files for the system specified.
A 'too few titles found' error is given from sysdownloader

**Comment by iuzwpr2p39rh7w** [comment]
Incorrect hash [map](https://github.com/Plailect/sysDowngrader/blob/master/include/hashes.h#L1095), [again](https://github.com/Plailect/sysDowngrader/issues/3#issuecomment-242414708). I fixed it [here](https://gist.github.com/iuzwpr2p39rh7w/f7690ea18b218865beec50b5ee544111).
@Plailect: I assume you have all firmware packs. Could you please check the other hash maps as well?
Also, the mega.nz [mirror](https://mega.nz/#!VxcF3TIK!Bm5LgFxo5V4Nepe9ZlWnx7bichE1V7p7pR_HqwimU5M) of `9.2.0-20J(Full)_n3DS.zip` is down.

**Comment by Plailect** [comment]
Fixed both of these

**Comment by mattylase** [comment]
@Plailect I am still running into this issue with what I think is the latest. Do you know if perhaps the torrent/mega links haven't been updated?

**Comment by Plailect** [comment]
Use latest sysDowngrader
