### ISSUE TITLE
Issue regarding loading browser hacks

### ISSUE THREAD

**Issue by DaniMan12** [Plailect/Guide#431]
I'm hacking my 2.10-4E old 3ds, following [this guide](https://github.com/Plailect/Guide/wiki/9.2.0-ctrtransfer). According to this guide I have to complete the "Part 3 (arm9loaderhax)" guide first, but when connecting to the website of **section II**, my screen freezes. Clicking select, or anything for that matter, doesn't do anything. When restarting and clearing save data the same thing occurs. Anybody know what might be the problem?
Thanks in advance.

**Comment by dark-samus** [comment]
Might take awhile, just keep trying

**Comment by jaxrogers2** [comment]
Make sure you clear your browser save data after every attempt.
