### ISSUE TITLE
No usable file found, Auto CTRNAND Transfer: failed!

### ISSUE THREAD

**Issue by Awooo** [Plailect/Guide#432]
Step 5, part 2. Everything was going well up until this point. How to get past this please? Thank you.

**Comment by sora10pls** [comment]
Make sure that:

- Your CTRNAND image is in the /files9/ directory on your SD Card
- Your CTRNAND image is named `2.1.0-4X_ctrtransfer_o3ds.bin` (X = U/E/J, depending on region)
- The `.sha` file is also in the `files9` directory
