### ISSUE TITLE
How to transfer/copy my sdcard?

### ISSUE THREAD

**Issue by rexbuster** [Plailect/Guide#433]
Forgive me for this noob question. Is it simply copy and paste procedure? I already searched many forums, but i just want to hear it from you. Because I want to use this guide to cfw my old 3ds. I only have 8 gig card. I want to transfer my sd card to bigger one in the future.. So how do i copy files from sd card. Thank you for any respond. :)

**Comment by sora10pls** [comment]
If you followed the guide to a T and are using SysNAND CFW, then yes, you can simply drag/drop (or copy/paste) the contents to your new SD Card when you get it.

**Comment by iuzwpr2p39rh7w** [comment]
From the [FAQs](https://github.com/Plailect/Guide/wiki/FAQ#user-content-faq_movesd):
>Q: How do I move to a new SD card at the end of this?
A: Just copy all the files to the new SD card.

**Comment by dark-samus** [comment]
Question is answered in the FAQ, closing
