### ISSUE TITLE
Stuck on Sysnand 2.1 with no NANDmin.bin to restore from.

### ISSUE THREAD

**Issue by universerule** [Plailect/Guide#434]
I do have backups of my barebones 9,2 sysnand from menuhax / cakes, but dont have the Nandmin file that was supposed to be created during ctr transfer, Is there anyway to get another of that file?

**Comment by sora10pls** [comment]
You have 2 options.

1. Do the [9.2 CTRNAND transfer](https://github.com/Plailect/Guide/wiki/9.2.0-ctrtransfer)
2. Restore the 9.2 SysNAND backup you currently have using Hourglass9

**Comment by universerule** [comment]
What is an entry point I can use?
