### ISSUE TITLE
11.0.0 -> 9.2, Reformat after Downgrade to 10.7?

### ISSUE THREAD

**Issue by AlexisTorres97** [Plailect/Guide#435]
Im following the guide to downgrade my second n3ds which was on 11.0. I finished the dsiware downgrade tutorial and moved onto downgrading to 9.2. The intro says to format in order to avoid a softbrick. Would I/ Should I reformat? I'm not sure if it will affect the initial downgrade is all

**Comment by jaxrogers2** [comment]
Having DSiWare on your console increases the chances that the softbrick will happen, but if you format, then you essentially only have one shot to downgrade to 9.2. I suggest that you try without formatting a few times (redowngrading your NATIVE_FIRM every time the downgrade fails and you have to update to 11.0 again, if this happens) and if it fails repeatedly (as in, 100+ times) format and then downgrade.
