### ISSUE TITLE
Issue with NNID working, but not showing up in system settings.

### ISSUE THREAD

**Issue by L10nH3ArT** [Plailect/Guide#437]
I recently finished the guide this morning on an O3DS with the intention to do the transfer downgrade for my N3DS. After reading everything I could, and searching the issue list here among other places, I can't quite find solid information for a handful of things.

I should say that I followed the guide entirely only deviating on Part 3, Section 4, Step 9 to the troubleshooting steps for a black screen (9.2.0 ctrtransfer worked smooth). Starting between 6.0-6.3 via Decrypt9 (Browser). Have not even cleaned up SD card after completion.

I can access the store (purchased Fieldrunners, and all account history is present) and don't seem to be having any actual issues with general operation of the device, however the NNID tool in system settings acts as if no NNID is set up. I've yet to summon up the courage to start the transfer process since I've got much backing up/double checking I'd like to do first, however am concerned about whether a system transfer would happen properly to an OFW N3DS with the NNID menu acting as it is.

Also if I could receive some clarification with a few things, I'd be more than grateful. 

First, is there a way to find at least the O3DS' NNID name? I should have wrote it down, didn't really think far enough ahead since the account can practically be thrown away, this is more for curiosity's sake. Also should I instead set up a new NNID after a system format and repurchase FR? Also does a system format clear an NNID that doesn't show up in system settings?

Secondly, if I understand correctly, with my N3DS I should be able to system format once I'm completed with the guide entirely to then relink my currently used/known NNID. Correct me if I'm wrong, but this part sounds deceivingly simple, however I'm "fresh off the boat" so to say so I'd like to take the least chances I can if someone else has had hands on experience with the entire process.

Thanks for any help and thanks much for the guide. It's gotten me this far, just hoping to smooth out some details before I start messing with the piece of hardware I truly want CFW'd.

**Comment by Plailect** [comment]
1) If you bought the game without creating an NNID, it uses a unique ID specific to the console, which is then transferred. You don't need to repurchase, it'll work as-is.

2) You can't system format, you must either transfer back or call nintendo to have them allow your NNID to be logged into on another system, which is in the instructions.
