### ISSUE TITLE
TWLN partition nonfunctional after ctrtransfer

### ISSUE THREAD

**Issue by Plailect** [Plailect/Guide#438]
This only seems to happen when transferring between certain version ranges, which are so far unknown. It seems to be a problem caused by a TWLN/CTRNAND partition mismatch, and once the exact cause is found should hopefully be easy to fix.

If you did the ctrtransfer version of the guide and got the issue of DSi/DS related functionality breaking, just sit tight and wait for a fix.

**Comment by dark-samus** [comment]
Issue has been solved, guide will soon be updated to reflect the needed changes and this issue will be closed once the guide is updated to reflect these changes

**Comment by Plailect** [comment]
The fix for DSi/DS functionality breaking after a ctrtransfer for some people *(which may or may not happen due to device / version differences)* is to **install [`Nintendo DS Cart Whitelist - v11264.cia`](https://plailect.github.io/Guide/Nintendo%20DS%20Cart%20Whitelist%20-%20v11264.torrent) ([mirror](https://mega.nz/#!IxsnkTgT!bJ25Ne23-U5YX02gjQflKXTcKmffLLxuz0r4yQO7lrI)) ([mirror](https://drive.google.com/uc?export=download&id=0BzPfvjeuhqoDVTc3cW9QRmIxRDQ)) with [FBI](https://github.com/Steveice10/FBI/releases/latest)** at the end of the guide.

These instructions have been added to the guide for all future users, but for people who currently encounter this issue after doing the guide, just install it with FBI now.
