### ISSUE TITLE
DS(i) mode still non-function despite new cia

### ISSUE THREAD

**Issue by TheAquaSheep** [Plailect/Guide#439]
Tested with Brain Training (cart), Four Swords, Exidia and Nintendo DS settings (nand).
The game boots to black screen even after installing the whitelist cia given in https://github.com/Plailect/Guide/issues/438

**Comment by dark-samus** [comment]
A few things to try. 
Reinstalling TWL_FIRM as a CIA (use 3dnus to download title 0004013800000102 and make sure to check the "pack as CIA" check box.)

Reinstalling the version data for TWL (I doubt this has changed, but is worth a shot) title 00048005484E4C41

Reinstall any remaining TWL titles if none of the above work, titles 0004800542383841 and 00048005484E4441

From there, report back what worked, if anything

**Comment by RayMafnas** [comment]
Mine is working now.

**Comment by RayMafnas** [comment]
Mine is working now installed the CIA on 2 of my 2DS and was able to play DS games and configure DS connections, thanks guys!

**Comment by jaxrogers2** [comment]
Yeah, perhaps the guide should include reinstalling TWL_FIRM/version/titles too along with the whitelist in case this happens.

**Comment by doug34** [comment]
I can't get 3dnus to work for me, I have no idea what I'm doing wrong. Can you post the TWL_FIRM as a CIA file like you have with the original problem?

**Comment by iuzwpr2p39rh7w** [comment]
| Title ID         | Version | Description      |
|------------------|---------|------------------|
| [0004013800000102](https://mega.nz/#!VcMj2TpD!ubEhL5-iL9WVw5LK4Rsgzwpp0ZDVcOWgFJSAHf78dCg) | v8817   | Old_3DS TWL_FIRM |
| [0004013820000102](https://mega.nz/#!kQkCEZSY!UAmUixl5BtfslkV9itNIkDTLb7zSYllpqQvC8GCn1dQ) | v9936   | New_3DS TWL_FIRM |
| [0004800F484E4C41](https://mega.nz/#!pBMHDL7L!PDwZUzhxMpF4sD6__j31b4p_0qKBNkPCdTOB9D7zXlg) | v0      | Version Data     |
| [0004800542383841](https://mega.nz/#!JQFDyLrA!Lgrk424yrVwxMSr3csgoyCPNi5LGIP8Echhalg1y07o) | v2048   | DS Internet      |
| [00048005484E4441](https://mega.nz/#!dcUCUD7Y!7C_JjHw7VukuJaa0Ps51ZAwm4C7SPzXFnvVThac31VQ) | v1024   | Download Play    |

**Comment by doug34** [comment]
Thanks @iuzwpr2p39rh7w!!!! 'Old 3DS TWL_FIRM' or 'Version Data' didn't work after installing them but I tried the other two together and my DS carts booted up as they should. I may have needed all of them? Hard to tell. Anyways, cheers everyone! Love this community!

**Comment by dark-samus** [comment]
Since it worked for @doug34 this issue will be closed, installing all of the TWL cias will be added to the guide

**Comment by TheAquaSheep** [comment]
DS Internet was the last thing I installed and was necessary for Pokemon Black to load.
Thanks a lot

**Comment by dark-samus** [comment]
FBI would have reported the correct title version... What's going on here is, TWL titles are installed in two places, one in CTRNAND (where the version number us read from), which you transfered, and the other in TWLN... What this means is, while the one in CTRNAND got updated, the one in TWLN did not. So the system seems to get stuck in some sort of loop. Installing the correct CIAs installs it both to TWLN and CTRNAND, fixing the issue

**Comment by Plailect** [comment]
Added all titles to the guide.
