### ISSUE TITLE
Cannot name emuNAND backup according to guide

### ISSUE THREAD

**Issue by jonatan-branting** [Plailect/Guide#44]
In part 4 step 22 the guide says the following:
Backup EmuNAND to redNAND_original.bin (you can use Up and Down / Left and Right to change the name)

However, redNAND_original.bin was not a possible option. red* was basically not available. I've been following the guide from the beginning, so I do have redNAND, if that could be the cause.

I assume this won't cause problems, but just wanted to report this!

**Comment by Plailect** [comment]
Guide has been fixed
