### ISSUE TITLE
Confused about updating CFW sysnand

### ISSUE THREAD

**Issue by sylen2** [Plailect/Guide#440]
I have been following the guide: https://github.com/Plailect/Guide/wiki/Part-3-(arm9loaderhax)

Up to section IV step 10 ("Update your CFW SysNAND to the latest version using system settings, if it is not already"), but in system setting my firmware is read as "sys" 9.2.0.  Everything I've read advised against updating the sysnand, only the Emunand. 

Am I actually safe to update here?

**Comment by Plailect** [comment]
Of course, or else it wouldn't tell you to.
