### ISSUE TITLE
cant upgrade SysNAND after installing al9h

### ISSUE THREAD

**Issue by penciluser** [Plailect/Guide#441]
Im stuck trying to update through this step:

"Update your CFW SysNAND to the latest version using system settings (if it is not already)
If you copied a firmware.bin to /luma/ earlier, delete it after updating or you won't be able to boot"

Retrying the update makes the bar go little by little everytime, but just stops at this error "An error has occured. Unable to update.  The system will now be restarted."

Any recommendations? Is there anyway to update offline?

**Comment by penciluser** [comment]
ok it actually finally was able to finish it surprisngly. just really odd it was also having trouble connecting to the internet.

**Comment by Margen67** [comment]
You might have been using the Tubehax DNS or some other method of blocking updates.
