### ISSUE TITLE
Done with downgrade(hardmod)

### ISSUE THREAD

**Issue by rexbuster** [Plailect/Guide#442]
Im done with downgrading 11 to 10.4, i follow the harmod linked from this guide. Can just cut the wires and taped it electrical tape inside the 3ds? cause i didnt use or have a male/female connector. I dont want to desolder it because it gives me hard time ti do it again in the future if i need to do it again. Is it ok to cut and just tape the wire inside the unit

**Comment by james-d-elliott** [comment]
I have not personally even hardmodded so I can only think of this logically, there's no reason it should not be fine, as long as they are individually wrapped with electrical tape to avoid shorting I can't see a problem.

**Comment by rexbuster** [comment]
Thank you very much, im new in this cfw and hardmod thing but i carefully follow and study all the guide i read. I think my heart will burst everytime i think something will go wrong..  I think i will now proceed to the part 1 of this guide. Thanks again..
