### ISSUE TITLE
Region Change

### ISSUE THREAD

**Issue by BeardlessMichigander** [Plailect/Guide#443]
Hey!  Love the guide, THANK YOU SOOOO MUCH!  Just one bit to add to the "Region Change" portion... I went from the Japanese version to the USA version and realized I no longer had FBI or LumaUpdater installed, so, I tried to inject FBI, but was unable to get a Health and Safety dump...  I'm checking right now if the H&S dump needs to be done before the update or what...

will update soon

**Comment by Plailect** [comment]
This is not a support forum, ask on reddit or contact @d0k3

**Comment by BeardlessMichigander** [comment]
Just tried again with a fresh CTRNAND transfer and the same error persists.  Here's an unnecessarily large picture of the error ...
![20160901_053027](https://cloud.githubusercontent.com/assets/21558386/18162756/b399a276-7005-11e6-8755-eed7c116fe1f.jpg)

**Comment by dark-samus** [comment]
How about we read the screen, it clearly says what the issue is

**Comment by BeardlessMichigander** [comment]
That's my problem though... It says that it won't work on O3ds <7.x, which I'm not on, or A9LH.  In the guide, the H&S dump is done after the A9LH install....so, I guess I'm not sure how/what/where the difference is between now and then?  Should i dump then restore nand (keeping a9lh)? or..?

**Comment by BeardlessMichigander** [comment]
NVM...I'm sorry.  I'm a fucking moron.  ...smh...

**Comment by Autz64** [comment]
Yes, you're indeed a moron...

**Comment by dark-samus** [comment]
The error mentions slot0x25keyX, there's a file with a similar name you need
