### ISSUE TITLE
Issues after downgrade from 11 to 10.4 (hardmod)

### ISSUE THREAD

**Issue by rexbuster** [Plailect/Guide#444]
I get error occured. Sometimes it dissappear. Sometimes blackscreen at boot. The themes disappear. Sometime bootrom error 200, cant read sd card. Im i f*cked up? I thinl the backup nand succesfully and flashed 10.4 correctly based on this guide.. What can i do now.. I just a little more i gonn cry now. :((

**Comment by rexbuster** [comment]
For now i think i fixed the bootrom error and my 3ds is reading sd card again. But the error occured please contact nintendo still shows up after few seconds or minutes.. What should i do.. :(

**Comment by Plailect** [comment]
This is not related to this guide and is related to your attempted hardmod, ask elsewhere
