### ISSUE TITLE
decrypt9 won't load on new 3ds

### ISSUE THREAD

**Issue by kpan123** [Plailect/Guide#445]
I have try to  boot the decrypt9 via homebrew severals time and it won't boot I have restored to the original 9.2 firmware and still won't go it just get stuck on the black screen as soon as I load up the decrypt9

**Comment by Ev1lbl0w** [comment]
Are you already running A9LH or not? If yes, just run it at boot by putting the payload and renaming to the button you want. If not, you can only run Dec9 at version 9.0-9.2 iirc.

Try copying back the Dec9 files for homebrew.

**Comment by Plailect** [comment]
This is not a troubleshooting forum

**Comment by kpan123** [comment]
So I update the hourglass move it to the start button?  as for DEC9 I cant
launch it just show blackscreen and i launch it via homebrew
