### ISSUE TITLE
Instruction unclear about updating sysnand

### ISSUE THREAD

**Issue by ScuttleSE** [Plailect/Guide#446]
I just followed the instructions on my 3DS and everything worked fine. I did not have an old emunand, so I am currently at version 9.2.0

The instructions are unclear on whether or not I can upgrade to the latest sysnand or not

Section IV mentions upgrading to the latest version, but section IV is skipped if you're doing a "clean" install.

**Comment by Ev1lbl0w** [comment]
If you have already A9LH installed and are running Luma3DS CFW with the settings in the Guide (hold Select on boot and confirm), you're safe to update your SysNAND.

This is also stated in the guide:

"Update your CFW SysNAND to the latest version using system settings (if it is not already)
- **Yes this is safe, stop opening Github issues about it.**
- If you copied a firmware.bin to /luma/ earlier, delete it after updating or you won't be able to boot"

Also, where does it say you should skip Section IV for a clean install? Section IV is when you restore your original backup from the beginning, containing everything you had previously to the guide (games, saves, nnid, etc...).

**Comment by ScuttleSE** [comment]
https://github.com/Plailect/Guide/wiki/Part-3-(arm9loaderhax)

Under section IV it tells me to go to https://github.com/Plailect/Guide/wiki/9.2.0-ctrtransfer if I don't have an existing emunand I want to restore

At the end of that instruction it tells me:

Press Start to reboot
Do Part 3 - arm9loaderhax - Section V - Injecting FBI
Do Part 3 - arm9loaderhax - Section VI - Finalizing setup
Read the remainder of Part 3 - arm9loaderhax

I.e, jump back to the previous document and start at Section V, skipping over section IV

**Comment by Ev1lbl0w** [comment]
You should only do the 9.2.0 ctrtrasnfer if you don't have any NAND backups. From what you're saying, you're doing it becasue you don't have an existing EmuNAND.

**Comment by ScuttleSE** [comment]
Either way, say I don't have a usable NAND backup and I do follow that link, that still skips all of Section IV

**Comment by Ev1lbl0w** [comment]
Not completely. What you do in the 9.2.0 ctrtrasnfer is similar to section IV. However, in the section IV, you restore your original backup with all games, saves and other stuff. In the 9.2.0 ctrtransfer, you basically update your system to 9.2. So either way, you can update to the latest version w/o problems.

**Comment by ScuttleSE** [comment]
Either way, the only reference to updating sysNAND to latest version is in Section IV, and only there.

If you do the ctrtransfer you never get to a point that tells you to update sysNAND

**Comment by Ev1lbl0w** [comment]
I agree with your point. @Plailect please take a look a this.

**Comment by Plailect** [comment]
This has been fixed.
