### ISSUE TITLE
Inconsistent information as to whether guide covers "KOR / CHN / TWN New 3DS" or not

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#447]
Hi. On the home page (https://github.com/Plailect/Guide/wiki) there is the paragraph:

> This guide will work on New 3DS, Old 3DS, and 2DS in ALL regions on firmware 11.0.0 or below (except KOR / CHN / TWN New 3DS).

But lower down it says:

> ALL regions are now compatible thanks to the new method of installation!

This seems to be inconsistent to me. Which statement is true?

**Comment by jaxrogers2** [comment]
Well, all regions are supported, as you can do the guide with a KOR/CHN/TWN old 3DS but since the New 3DS shipped at 9.6 in those regions the guide won't work because there is no 9.0-9.2 firmware for those regions for the New 3DS.

**Comment by JohnVeness** [comment]
Thanks. Maybe it would be best to just remove the line "ALL regions are now compatible thanks to the new method of installation!" and leave the first line.

**Comment by Plailect** [comment]
Fixed
