### ISSUE TITLE
Add SaltFW as a secondary CFW

### ISSUE THREAD

**Issue by Ev1lbl0w** [Plailect/Guide#448]
I think SaltFW should be added as a secondary choice of CFW, mainly because it's better for users who have no idea how A9LH/Luma3DS/CFW works, and it provides a safer environment (no payloads, no Emu/RedNAND, automatic signature and reboot patches, etc...), especially for consoles that belong to kids.

**Comment by Ennea** [comment]
Luma has automatic signature, reboot and firm write patches as well. If you're technically illiterate, this guide isn't for you anyway.

**Comment by Ev1lbl0w** [comment]
Luma allows to use Emu/RedNANDS, payload chainloading and changing settings on boot. These things, in the wrong hands, could harm the console. **And there is no need for you to be rude**.

**Comment by OTFree** [comment]
Why would kids be running CFW anyway? The guide shouldn't be tailored to
that audience...

**Comment by Ev1lbl0w** [comment]
@OTFree I used kids as an obvious example. I did A9LH to 2 consoles and the owner's have no idea how hacking works. This is why I installed them a safe CFW (SaltFW) so they wouldn't mess with the wrong tools/configs. I just thought it would be nice to add steps to add a harmless CFW when these situations can happen and the user doing A9LH wants to avoid them.

**Comment by OTFree** [comment]
Ahhh, I see. Sorry for the confusion! But yeah, I could understand wanting
to avoid them potentially bricking their console by mistake. I've never
heard of SaltCFW myself, but I don't see why it couldn't be offered as an
alternative.

**Comment by Plailect** [comment]
If a user wants it, they can read the SaltFW installation page. I decided quite a while ago (when CakesFW was removed) that there would be exactly one CFW in the guide at a time, and right now that's Luma.
