### ISSUE TITLE
Use text instead of image for "You can remove any extra files from the root of the SD card that are not..."

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#450]
At the end of https://github.com/Plailect/Guide/wiki/Part-3-(arm9loaderhax) you say to clear up files/folders on the root of the SD that aren't in an image, the image being from Windows 10 File Explorer. I think those would better be in just a text list, i.e.:

- 3ds
- files9
- hblauncher
- luma
- Nintendo 3DS
- arm9loaderhax.bin
- boot.3dsx

My reasons include is that it's easier for you to maintain the list as text than it is as an image, people who don't use Windows won't be put off by the Windows-specific image, and that the text in the image is slightly small so plain text would be easier to read.

**Comment by Plailect** [comment]
Done
