### ISSUE TITLE
Add Homebr3w to Part 3 Section VI

### ISSUE THREAD

**Issue by RansomWareZ** [Plailect/Guide#451]
Instead of downloading all things one by one, my friends and me just use Homebr3w to install all the recommended programs in the end. It's very easy.

**Comment by ihaveamac** [comment]
Homebr3w uses titledb.com, which FBI already does since 2.4.0.

**Comment by RansomWareZ** [comment]
FBI's implementation is not that good though. No search, no automatic update check

**Comment by RansomWareZ** [comment]
Why was this closed?
