### ISSUE TITLE
Always bricked..

### ISSUE THREAD

**Issue by rexbuster** [Plailect/Guide#452]
Sorry for this noob question, i think o3ds always  brick after downgrading. I dont why, i followed the guide carefully. Even formatting my o3ds. But this time, it softbrick exactly when downgrading to 9.2 process.. I dont know if my 3ds have dsi wares or ambassador. I willing to format it all. My question is can i reformat again for the 2nd time.? Because it needs internet connection for the 3ds to format.. Can they detect me formatting again. Tnx.

**Comment by MelonGx** [comment]
Is it JPN?
If yes, #453.

**Comment by rexbuster** [comment]
nope its not jpn, i forgot to tell. it is USA version.. im hardmod from v11.. i already format my o3ds again right now. let see if im lucky enough to not get bricked again,.

**Comment by Ev1lbl0w** [comment]
This is just a matter of luck. But since you did a hardmod, redo the process of injecting NFIRM, just in case.

**Comment by rexbuster** [comment]
Thanks. Beacuae im new to this cfw. Im always over reacting to the error i see.. Thanks guys. You me hope.
