### ISSUE TITLE
9.2.0 Downgrade - 000400100002CA00.CIA should be deleted in JPN O/N3DS downgrading or it will result a BRICK

### ISSUE THREAD

**Issue by MelonGx** [Plailect/Guide#453]
Only downgrading JAPANESE O/N3DS should delete 000400100002CA00.CIA.
USA, EUR do not require it.
This issue has already existed since the downgrade method was being discovered.
But I don't know why this guide does not mention it.

**Comment by MelonGx** [comment]
Just checked the downgrade packs provided on this guide.
Both of O3DS JPN 9.2.0 & N3DS JPN 9.2.0 didn't pre-delete 000400000002CA00.CIA.

**Comment by Ev1lbl0w** [comment]
It's probably because PlaiSysUpdater prevents this. Noone was ever bricked by downgrading with Japanese packs on this guide. So don't fix what's not broken.

**Comment by jaxrogers2** [comment]
Yeah, this would only be a problem if you used something other than sysdowngrader or Plaisysupdater to downgrade.

**Comment by Autz64** [comment]
And why you would use other thing aside from the guide to downgrade?

**Comment by ihaveamac** [comment]
I still think it would still be a good idea to delete regardless, it's useless to keep it there.

**Comment by Plailect** [comment]
That's because `000400102002CA00.cia` is the one that has to be deleted, not `000400100002CA00.cia`...
