### ISSUE TITLE
Brick after downgrade 2.1.. 

### ISSUE THREAD

**Issue by rexbuster** [Plailect/Guide#454]
"Putting a New 3DS on 2.1.0 in sleep mode is known to cause an UNRECOVERABLE brick! You should avoid closing your device ..."

I dont know if it just me. But after i turn off my o3ds. Then try to continue to part 3. Error pop up when typing the http://dukesrg.. Im not n3ds. But as far as i know the only thing i did is turn off my unit aftet 2.1 successfully installed. Think i shoudnt turn off my unit.. But the warning message is only for new 3ds. But im o3ds
 Maybe they should add more specific instruction wheter we turn off or not the unit wheter n3ds or o3ds.. For the newbie like me. Btw thanks, i will again start from part 1.. :(

**Comment by Ev1lbl0w** [comment]
No. You can run 2.1.0-4 just fine on an Old3DS. Just try clearing cache and cookies on browser and try going to the link again. It's not a brick. You're fine.

**Comment by rexbuster** [comment]
Woah.. So im just fine!?. I started all over again. Im already in part 2 ctrnand transfer again.. But thanks again. Now i know.
