### ISSUE TITLE
Thank you.. My unit now is cfw.. 

### ISSUE THREAD

**Issue by rexbuster** [Plailect/Guide#456]
Honesty..it takes me 3 days to complete this guide. I dont know. I think because im not following the guide carefully. So a small mistake can brick your 3ds. I think its 8 times i brick my system..haha. I look like an idiot. But thank you all who help me here. I dont know if it just ok to write this in this issue page. Sorry..

I know how to install games using cia. But can i use the eshop? To download without pay. Or do i need another application for this? Thank you

**Comment by xy2iii** [comment]
Issue tracker, not 'how do I get games' recommendation forum.

**Comment by chaoskagami** [comment]
*cough*freeShop*cough*
