### ISSUE TITLE
Sd is not formatted for EmuNAND for Section V - Injecting FBI

### ISSUE THREAD

**Issue by noobkun** [Plailect/Guide#457]
when i try to dumb health & safety 
2. Go to "SysNAND Backup/Restore", then select the "Health&Safety Dump" option to dump Health & Safety to hs.app (you can use Up and Down / Left and Right to change the name)

it says that the sd is not formatted for emunand 
health & safety dumb failed!
i am using SanDisk 32 GB SDHC class 4 formatted to fat32 32k using the tool provided

**Comment by ihaveamac** [comment]
you probably chose "EmuNAND Options" instead.

**Comment by noobkun** [comment]
thank you
