### ISSUE TITLE
Memes

### ISSUE THREAD

**Issue by Trollinglord69** [Plailect/Guide#458]
Instructions unclear, dick stuck in cartridge reader
Help plox

**Comment by dankzegriefer** [comment]
Wow 2 funni super ultimate kek II turbo

**Comment by trbocode** [comment]
The cartridge reader isn't used at all during the guide, unless you need an alt entrypoint.

**Comment by kitling** [comment]
Oh NO! Does this mean the MEMZ trojan has infected everyone?

**Comment by DeckOfNoobs** [comment]
You have it all wrong, you're supposed to stick your dick in the SD reader, not cartridge reader

**Comment by dankzegriefer** [comment]
EVERYONE WHO HAS USED THIS GUIDE

SYSDOWNGRADE HAS A DANGEROUS TROJAN INFECTION CALLED MEMZ
THE ONLY WAY TO FIX IT IS TO UPGRADE TO WINDOWS 10 EDUCATION

**Comment by Plailect** [comment]
This has been an incredibly insightful issue. A fix has been included in the guide, and you have been banned. Have a wonderful day!
