### ISSUE TITLE
trying to boot emunand results in black screen

### ISSUE THREAD

**Issue by shahmirn** [Plailect/Guide#459]
hello,

i followed the new guide and sys a9lh works fine, but emunand results in black screen.

on my other n3ds that followed the old guide, emunand works fine

**Comment by jaxrogers2** [comment]
EmuNAND does not work with A9LH sysNAND, you need to use redNAND instead.

**Comment by shahmirn** [comment]
It worked OK with a9lh sysnand following the old guide

**Comment by Margen67** [comment]
If you want to use Gateway you can use the A9LH payload or load from a 9.2 redNAND
