### ISSUE TITLE
FAQ Question mentions emuNAND rather than redNAND

### ISSUE THREAD

**Issue by Favna** [Plailect/Guide#46]
Nitpicky thing but in the FAQ it states:

Q: Can I do this without a computer (e.g. an Android phone)?
A: You may be able to complete up to part 3 of the guide (getting emuNAND running). However, part 4 as of now requires a computer to inject FBI into Health & Safety.

emuNAND should be replaced with redNAND since part 3 strictly talks about redNAND now.

**Comment by Plailect** [comment]
EmuNAND and RedNAND refer to slightly different variations of the same thing and can almost always be used interchangeably.
