### ISSUE TITLE
Keep getting an error in step 11. Installation fails

### ISSUE THREAD

**Issue by Aguchoso** [Plailect/Guide#462]
I am following Plailect's guide. Everything was going fine until I reached stepp 11: _"Press (A) to install, it may show some errors but that's fine as long as it shows "Install finished successfully" towards the end"_
![img_20160904_221726](https://cloud.githubusercontent.com/assets/21993112/18235160/cb81b7d0-72ed-11e6-9218-0424f46487ea.jpg)

I tried many times replacing the starter file in the sd but it keeps going.

**Comment by Plailect** [comment]
You should have the **contents of** the starter folder (`boot.3dsx` file and `3ds` folder) on your SD card.
