### ISSUE TITLE
Region Changing problem

### ISSUE THREAD

**Issue by srwgin** [Plailect/Guide#465]
I have NNID on my jap O3DS
if I use Region Changing to USA and everything works fine (do not use NNID)
then I backup nand rename usanand.bin
then use h9 restore japnand.bin(which backup in region changing process)
is my jap nnid work fine
or it will error 002-2634
because NNID unlinked when region changing

**Comment by lifez** [comment]
I got this error too

my JP O3DS is work fine with eshop

but when i change region to USA. It cannot access e-shop

**Comment by srwgin** [comment]
OK after region changing
I found when I see notification goback to homemenu
it is freeze
you should format system
but remember when you format before yes take out SDcard
or you lost your files for original nand
I think after region changing it use your original nand /Nintendo 3DS/(32 Character ID)/(32 Character ID)/
if you format system these files delete so you should take out SDcard before format
after format system will create new /Nintendo 3DS/(32 Character ID)/(32 Character ID)/ for your new region

**Comment by Plailect** [comment]
It will be fine.

**Comment by helmergoza** [comment]
i have the same problem with 50 3ds japan to USA, did you get any solution to go to eshop after the change.??
