### ISSUE TITLE
FBI Cert signature or hash check failed

### ISSUE THREAD

**Issue by warmano7** [Plailect/Guide#466]
hi i follow your guide till finish, my 3ds already running with a9lh and luma3ds CFW. but when i want to install .cia file with fbi i often get this error.

Failed to install CIA file.
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module : AM (32)
Desc: Cert signature or hash check failed (106)

am i missing a step? i thought installing luma cfw will let you install unsign cia? or its because something else, hope someone can help.

**Comment by Margen67** [comment]
What are you trying to install?

**Comment by warmano7** [comment]
i'm trying to install 3ds software (games) , before a9lh i use emunand with reinand and all my 3ds games .cia can install just fine with fbi

**Comment by Plailect** [comment]
Not a piracy support forum, take this question elsewhere.
