### ISSUE TITLE
DSiWare Downgrade, save manager on 3DS #2

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#467]
Hi. On https://github.com/Plailect/Guide/wiki/DSiWare-Downgrade you say, referring to 3DS#2 which is on stock firmware 11.0.0:

> Use a save manager to backup any saves you care about on 3DS #2 (it will be formatted!)

linking to JKSM. It would be a great enhancement to the guide if you could flesh out exactly how to do this. Given that 3DS#2 is stock at this point, it will not be obvious to many how to run JKSM on it.

**Comment by sora10pls** [comment]
There's this really handy thing called Google. I understand that it'd be nice to have everything on this one guide, but it's just too much of a hassle to add here when there are already plenty of video tutorials and text tutorials out there that people can find in the matter of **one** Google search

**Comment by Plailect** [comment]
Try reading the JKSM page or googling like @sora10pls said.
