### ISSUE TITLE
arm9loaderhax section 1 issue

### ISSUE THREAD

**Issue by Gunblade08** [Plailect/Guide#468]
On Section 1 bullet point 3 it says to Delete the 3ds folder from the root of your SD card if it exists. but then to Copy DspDump.3dsx to the /3ds/ folder on your SD card a couple steps down which one is it?

**Comment by Autz64** [comment]
17. Copy DspDump.3dsx to the /3ds/ folder on your SD card

Indeed. Fix!

**Comment by Gunblade08** [comment]
so do i delete the 3ds folder or no?

**Comment by Onoitsu2** [comment]
You delete it, and then recreate it. Don't want any extra items in there that might interfere with the process.

**Comment by Gunblade08** [comment]
ok thanks. im having trouble loading the dukes site. i keep clearing saveddata and just get sent to google searches of the issue im having lol

**Comment by Gunblade08** [comment]
when i clear it with my sd card inside it freezes at the home menu pop up it doesnt actually get to the menu. but i take my sd card out and it powers off and powers on properly.

**Comment by Onoitsu2** [comment]
are you using the URL item to type it in, and making sure you are using a .io address, not a .com. I made that mistake once.

**Comment by Gunblade08** [comment]
Exactly how it's posted is how I am typing it.

**Comment by Autz64** [comment]
The guide should say:

3- Delete ALL THE CONTENT of the the 3ds folder.

**Comment by Gunblade08** [comment]
4-Copy the contents of the starter folder in starter.zip to the root of your SD card

the contents of the starter folder are a 3ds folder which contains a bunch of stuff and file boot.3dsx on it

**Comment by Gunblade08** [comment]
so do i delete all that stuff to? and only keep the dump.3ds file on their? still not working for me

**Comment by Plailect** [comment]
Delete the 3ds folder, then copy the one from the starter folder. This is not difficult.
