### ISSUE TITLE
9.2 CTRNAND Transfer no longer required if you have no NAND backups

### ISSUE THREAD

**Issue by sora10pls** [Plailect/Guide#469]
Luma3DS v6.1.2 now has 1.x and 2.x NATIVE_FIRM support in SysNAND, with FIRM write patches. Users who got to 2.1 without a NAND backup don't need to do the 9.2 CTRNAND Transfer anymore, because they can simply update from 2.1 to 11.0 with the latest version of Luma3DS.

The 9.2 CTRNAND Transfer could still come in handy to some users though, so if you want to keep its page on the Wiki, it's totally up to you :P

**Comment by exegg** [comment]
This would only apply to o3DS users right? Updating a 2.1 New 3DS doesn't sound good.

**Comment by ihaveamac** [comment]
@exegg luma can't boot 1.x/2.x on New3DS anyway, so yes.

**Comment by TheAquaSheep** [comment]
I could not boot 7.1.0 with Luma v6.1.0, which apparently it should support, and only had a functional 3ds again thanks to the 9.2.0 ctrtransfer process. So it should be kept, at least, for troubleshooting.

**Comment by Plailect** [comment]
Fixed
