### ISSUE TITLE
All CIA installs fail from injected FBI after guide completion

### ISSUE THREAD

**Issue by ricardy007** [Plailect/Guide#47]
I have everything working up to the last step. Every time i tried to install hblauncher_loader i get the following error: 
Install failed!
hblauncher_loader.cia
source:SOURCE_FSFILE_WRITE (OX1c)
module: MODULE_NN_FS (0x11)
level: LEVEL_PERMANENT (0x1b)
Summary: SUMMARY_WRONG_ARGUMENT (0X8)
description: DESCRIPTION_AES_VERIFICATION_FAILED (0X1)
Did i miss a step?

**Comment by Plailect** [comment]
Make sure you have signature check patches enabled in the CakesFW menu, this is an error that will result from having this off.

**Comment by ricardy007** [comment]
As a beginner I installed: AuReiNAND. i don't see signature check patches in AuReiNAND menu

**Comment by Plailect** [comment]
Try redownloading the CIA and copying it to your SD card again.

**Comment by ricardy007** [comment]
no help :( i re-downloaded it. i downloaded the previous version V1.0 nothing works so far

**Comment by ricardy007** [comment]
Can you send me the one you use in this tutorial and know is working please?

**Comment by Plailect** [comment]
It's straight off of github. Do other CIA files install fine?

**Comment by ricardy007** [comment]
Frankly I do not know. Do you have a suggestion of something i can try to install? Got the 3ds yesterday first time exposed to arm9loaderHax and stuff... my next question, if everything worked fine, was going to be what's next?

**Comment by Plailect** [comment]
Try installing sysUpdater.cia and see if it works.

**Comment by ricardy007** [comment]
did not install, same error. should i try to reinstall FBI, by going to the previous step?

**Comment by ricardy007** [comment]
I skipped installing FBI because it was already installed once i open SysNAND, is it safe to overwrite the install by recreating the hs.app?

**Comment by Plailect** [comment]
Should be

**Comment by ricardy007** [comment]
did not work, anything else you can think of?

**Comment by FenrirWolf** [comment]
Install NASA or BBM or some other CIA installer and see if that will install it.

Or make sure that you're choosing to install to SD and not to NAND.

**Comment by ricardy007** [comment]
Fixed:
https://www.reddit.com/r/3dshacks/comments/3fwf8c/can_anybody_help_with_my_first_setup_and_install/

"Whenever FBI doesn't install cia's, it mostly always means that you never installed any Eshop titles and there's just no database setup.

Just follow this FAQ from the official FBI thread:

Q: I'm getting a "Database does not exist" / "Invalid database" error!

A: You likely haven't installed anything from eShop or other locations before. You will need to go to the "Nintendo 3DS/<id0>/<id1>/dbs/" directory on your SD card and create empty "title.db" and "import.db" files. Then, go to System Settings -> Data Management -> Nintendo 3DS -> Software on your 3DS and let it repair the database files."
