### ISSUE TITLE
Question about the downgrade 

### ISSUE THREAD

**Issue by raymonders** [Plailect/Guide#472]
my version is 11.0.0-33E
I assume I should use the browser version for 11.0.0? despite 33e not being specified in the "To" column?
Thank you!

**Comment by iuzwpr2p39rh7w** [comment]
Do you see any version with a dash suffix in the `From` or `To` columns? Also:
> **The two columns of the chart refer to the last number of your version (which corresponds to the browser version installed to the system). If the version is -0 then you do not have a browser, while any number above -0 indicates a browser is installed.**

So yes, follow the steps on the field in the `11.0.0` row and under the `Browser` column.

**Comment by AgentScarlet** [comment]
cant get the arm11.bin to launch at least i think thats what im supposed to be doing

**Comment by AgentScarlet** [comment]
http://dukesrg.github.io/2xrsa.html?arm11.bin<< this is the site the step says. ive loaded this more times than i care to. ugh.
