### ISSUE TITLE
Injected FBI on H&S app fails to open on A9LH 11.0.0-33E

### ISSUE THREAD

**Issue by MODUSMusic** [Plailect/Guide#473]
Hello, I had a problem while finishing the A9LH install guide.

Just to clarify, I followed every single step of the guide carefully, from start to finish. And there was nothing wrong with the actual installation of A9LH, but instead, with one of the last steps, which is injecting FBI to the Health & Safety app.

After injecting the modified .app with FBI on it using Hourglass9, the system boots up, nothing wrong. But when I try to start FBI to install the aforementioned .cia's, the screen goes black for a couple seconds, and then the console (which is an O3DS) tells me this:

"An error has occurred. Please save your data in any software currently in use, and then restart the system."

The FBI I'm injecting is the latest version and has the banner, so it shouldn't really be a problem.

Due to FBI failing to boot up I'm stuck at this step. Does anyone have a solution for this?

Thanks in advance.

**Comment by Plailect** [comment]
Completely redo your injection using you hs.app file.
