### ISSUE TITLE
how to downgrade the 10.3.0 tw o3ds 

### ISSUE THREAD

**Issue by theocmath** [Plailect/Guide#474]
I tried browserhax but failed.
you said new guide worked on all regions o3ds.
really need your help

**Comment by jaxrogers2** [comment]
Since you have 10.3.0-0 rather than, say, 10.3.0-27 or something), that means that your 3DS has no browser. You need to follow the instructions on this page instead. https://github.com/Plailect/Guide/wiki/Homebrew-Launcher-(No-Browser)

**Comment by ihaveamac** [comment]
TWN doesn't have a browserhax or *hax at all right now.

**Comment by theocmath** [comment]
It's 10.3.0-23T

**Comment by jaxrogers2** [comment]
I think OoT3DHax would work, but I'm not positive.

**Comment by theocmath** [comment]
the yellows8 says" KOR and CHNTWN support is currently broken somehow."

**Comment by Plailect** [comment]
Updated the chart to match
