### ISSUE TITLE
Post luma3ds config, sysNAND fails to update via sysSettings

### ISSUE THREAD

**Issue by CryoBolt** [Plailect/Guide#475]
2DS [10.5.0-33U origin]

Successfully proceeded to the following step:

> Part 3 - Section IV - 10. Update your CFW SysNAND to the latest version using system settings (if it is not already)

After a reboot from Hourglass9, I go:
System Settings > Update System > I Agree
It will load to about 70% and then display 'An error has occurred. Unable to update.' and reboots.

I have tried with and without firmware.bin. Looked at previous issues, cannot really find any solutions there.  
Is there anything else I am missing?
Looking at /r/3dshacks, others seem to be affected.  Perhaps add this to the guide as well.

Thanks for all your hard work.

**Comment by Ev1lbl0w** [comment]
This also happenned to me, but I simply put the 3DS only ~1 meter away from the router and it worked. It might sound stupid, but it worked for me. Doesn't hurt trying xD

**Comment by jaxrogers2** [comment]
Does anybody know if manually updating to 11.0 through sysupdater on Luma3DS works too? Or does that not work?

**Comment by creedda** [comment]
I also seem to be stick in Part 3, Section IV, Step 10. I downgraded from a 10.x.x firmware, followed all of the instructions so far. The update will just not go through. I have tried to update via several different wireless networks (different houses) and have tried standing next to my router, restarting my router, turning off my firewall, and several other tricks I have found on the web.Nothing seems to work. The update gets to about 60-75% before erroring out every time. I would be very interested in knowing if I can just update to 11 via sys updater or some other tool...

Let me know if there is any data I can gather that would help you troubleshoot...

**Comment by jaxrogers2** [comment]
You might want to try booting into recovery mode to update instead, since it still has FIRM protection in Luma3DS.

**Comment by creedda** [comment]
Thanks for that suggestion. Recovery mode is one of the strategies I tried. I get an error when booting into recovery mode:
_An error has occurred: 
SAFE_MODE is not supported on 1.x/2.x FIRM 
Press any button to shutdown_

**Comment by Plailect** [comment]
https://github.com/AuroraWright/Luma3DS/issues

**Comment by TuxSH** [comment]
The fact that it errors out itself shouldn't be a Luma3DS issue, as only firmprot is applied on 1.x/2.x.
