### ISSUE TITLE
Luma can boot 1.x and 2.x

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#476]
At a minimum this makes things easier for people who start on 2.1.0-4.   No 9.2.0 ctrtransfer is needed--just get OTP, install a9lh, install Luma, use normal system update.  (This applies to O3DS--N3DS will still require the ctrtransfer.)

It also means that Cubic Ninja OTP is at least useful for 2.0, 2.2, and 2.1.0-2 (get OTP using CN, install Luma using browser, install a9lh from within Luma, system update).  I don't know if there are paths that make Cubic Ninja OTP useful on 1.x since that doesn't have a browser so there's no way to either install a9lh or run Luma.   Is there a way to boot Luma using CN?

Also, part 3 of the guide currently says "If you are on Old 3DS and do not have any usable NAND backups, you can just Update your CFW SysNAND to the latest version with the System Settings. Yes this is safe."  Is there ever a reason why they *should* use the NAND backup (assuming it is O3DS and the backup is not from EmuNAND)?  (The only possibility I can think of is if the ctrtransfer trashes NAND saves, which I know nothing about.)

**Comment by ihaveamac** [comment]
#469

dunno if cubic ninja otp is still useful because you still need a way to get into SafeA9LHInstaller. unless you can do that through cn

**Comment by arromdee** [comment]
Although 469 was closed, it hasn't actually been fixed.  The Part 1 (Decrypt9) page has a link from 2.1.0-4 to 9.2.0 ctrtransfer.  We do need to keep the 9.2.0 ctrtransfer as an emergency page for people with N3DS without a backup, but 2.1.0-4 OLD should link to a page without it.

I think you are right that Cubic Ninja OTP is still useless.  I thought that Luma could be booted using 2xrsa browser, but even if it can, it's probably still limited to 2.1.0-4 so that wouldn't help.

**Comment by Plailect** [comment]
Restoring a backup is still the preferred method because ctrtransfer does remove many NAND saves and other files. Cubic Ninja is worthless because you can't boot safea9lhinstaller or d9 with it. Also, see https://github.com/Plailect/Guide/issues/469

**Comment by arromdee** [comment]
Okay, for those two items.  I still believe the #469-like issue is not solved.

The problem is that the page "https://github.com/Plailect/Guide/wiki/Part-1-%28Decrypt9%29" contains the link "+ ALL - OLD - 2.1.0-4: 9.2.0 ctrtransfer".

This means that if a user dug his old O3DS out of the closet which has 2.1.0-4 already on it (which is the firmware that existed for the longest period of time, so they are more common than you think), you will tell him to do a ctrtransfer.  He should not do a ctrtransfer--he should get his OTP using the browser, then install a9lh and Luma using the browser, then system update.

There are cases where you need to tell someone to do a 9.2.0 ctrtransfer.  The user who starts on 2.1.0-4 O3DS is not one of those cases.  Yes, someone stuck on a N3DS on downgraded 2.1 should do his ctrtransfer, so you still need a 9.2.0 ctrtransfer page, but this part should not link to it.

[This turned up on gbatemp recently.](http://gbatemp.net/threads/possible-brick-o3ds-2-0-1-a9lh.440778/)
