### ISSUE TITLE
Finalizing setup (double confirm is it got anything missing)

### ISSUE THREAD

**Issue by jasontwk85** [Plailect/Guide#477]
![20160908_032116](https://cloud.githubusercontent.com/assets/22019893/18325768/55effaf6-7575-11e6-913b-db87343c87d1.jpg)

Hi. And sorry if asking silly question..
As picture i share. After i finish final setup,this is all i get. It is normal or am i missing something?
I only get: luma3ds updater, Fbi, and hb launcher only..and my homebrew got nothing new app or tool.
Cos I thought luma3ds is an app.😆

Thanks,
And sorry for inconvenience cause.

**Comment by jasontwk85** [comment]
And i using n3ds and after all step my device become 11.0.0-33j

Thanks

**Comment by Ev1lbl0w** [comment]
Yes. You're fine. You ended the guide. Congratz!

**Comment by jasontwk85** [comment]
Ok.. thank you very much.. 👍
Good job for giving clear guide.. thanks..
