### ISSUE TITLE
Can't restore O3DS after System Transfer to N3DS

### ISSUE THREAD

**Issue by jeffdincht** [Plailect/Guide#480]
Well, finished the Transfer and my N3ds is good to go. Already hacked and working 100%.
But my O3ds is now "blocked", tried to do the "Section V - Restoring 3DS #1" of DSiware Downgrade 
but it says "Failed" when trying to restore Sysnand from NAND.bin in Hourglass9. When it reads the NAND.bin.sha says failed because the file is corrupted. 
Can I restore my O3ds any other way?

**Comment by sora10pls** [comment]
You can always try to restore any other backups you have, but if you're ballsy, you can delete NAND.bin.sha and restore without the validation

**Comment by Plailect** [comment]
Deleted the other guy's comment because installing a NAND backup **that you know is corrupted** is a ***terrible*** idea.

Try reading Part 3...

>**If you are on New 3DS and do not have any usable NAND backups, [follow 9.2.0 ctrtransfer](9.2.0-ctrtransfer) starting on Step 4**
