### ISSUE TITLE
Is the ctrtransfer_03ds.bin correct for my N3DS?

### ISSUE THREAD

**Issue by snyoz** [Plailect/Guide#481]
In Part 2 -https://github.com/Plailect/Guide/wiki/Part-2-(2.1.0-ctrtransfer),
you listed the ctrtransfer images... 
"What you need: The 2.1.0 ctrtransfer image for your device and region"

But when I click on one of those mirrors the file name is called : **2.1.0-4E_ctrtransfer_o3ds.zip**
"New 3DS or Old 3DS or 2DS 2.1.0 - EUR - ctrtransfer (mirror) (mirror)"

Is this really the right Image for my Decrypt9 process or will I need another for my N3ds?

Im a bit confused about the "**_o3ds**" string in this filename and careful.
Thanks for help and a very nice tutorial!

Last Question: Is it okay to running this steps through with an 4GB Micro SDHC Class4 Card? I planing to clone those files later to a bigger SD Card when I have finished these steps.

**Comment by ihaveamac** [comment]
yes, you can use it New3DS

> Last Question: Is it okay to running this steps through with an 4GB Micro SDHC Class4 Card? I planing to clone those files later to a bigger SD Card when I have finished these steps.

if you have enough space.

**Comment by snyoz** [comment]
Thanks for the fast response!!

**Comment by snyoz** [comment]
Sorry one last question:

on page 2 - step 9:
https://github.com/Plailect/Guide/wiki/Part-2-(2.1.0-ctrtransfer)

"Delete the 2.1.0 ctrtransfer image .bin and .bin.sha from the /files9/ folder on your SD card"

Tells me to delete those files.

And on page 3 - Section I - step 5:

"Ensure NANDmin.bin and NANDmin.bin.sha are in the /files9/ folder on your SD card. If you do not have this backup, keep reading, there are instructions in Section IV for you to follow."

Its a bit confusing. Do I have to backup them only to my PC and delete them?

**Comment by sora10pls** [comment]
Once you do the CTRNAND Transfer, it'll prompt you to make a SysNAND backup.

After doing the backup, `NANDmin.bin` and `NANDmin.bin.sha` will be in the `/files9/` folder on your SD Card.

What you do after the CTRNAND Transfer is completed is delete `2.1.0-4E_ctrtransfer_o3ds.bin` and `2.1.0-4E_ctrtransfer_o3ds.bin.sha` from the `/files9/` folder, and keep the NAND backup there (as well as the corresponding .sha file) to restore via Hourglass9 after installing A9LH.

**Comment by snyoz** [comment]
Thanks @sora10pls that makes sense to me.

**Comment by sora10pls** [comment]
You're welcome. Hopefully all goes well :)
