### ISSUE TITLE
No hs.app in the sd-root after dumping 

### ISSUE THREAD

**Issue by snyoz** [Plailect/Guide#482]
Everything went very well unti "**Section V - Injecting FBI**" in step **2**:

"Go to "SysNAND Backup/Restore", then select the "Health&Safety Dump" option to dump Health & Safety to hs.app (you can use Up and Down / Left and Right to change the name)"

The process succeeded without any problems but after all Im not able to find the "hs.app" in the root of the sd. I also checked the other folders - no dump.

Thank you for you help!

**Comment by snyoz** [comment]
already solved! found it in the "files9" folder

**Comment by Ev1lbl0w** [comment]
If it's solved just close the issue already.

**Comment by GuiguiPH** [comment]
Does it work for new 3ds 11.0.0-33E ?

**Comment by Ev1lbl0w** [comment]
@GuiguiPH what do you mean does it work? If you're asking for A9LH yes, you can on 11.0.0-33.
