### ISSUE TITLE
Unable to access Decrypt9

### ISSUE THREAD

**Issue by aceking01** [Plailect/Guide#483]
I able downgrade my new 3ds USA from 9.9.0 to 9.2.0
to 2.0 but failed to install arm9loaderhax 

after browsing to http://dukesrg.github.io/2xrsa.html?arm11.bin
screen become glitched and freeze my new 3ds
then failed to boot (seems bricked)

I able to recover my 3ds using Hourglass9 back to 9.2.0
i retry the said instruction but unlucky to access Decrypt9
Im stuck on 9.2.0

**Comment by sora10pls** [comment]
Hold SELECT and then press POWER to turn on the 3DS. Does it load the Luma3DS configuration menu?

**Comment by aceking01** [comment]
yes it load

**Comment by ihaveamac** [comment]
you already have arm9loaderhax. your system isn't bricked.

**Comment by aceking01** [comment]
but i wasnt able to finish the 2.1.0 ctrtransfer i was back to 9.2.0 
Dont know what's next.

**Comment by ihaveamac** [comment]
you already have arm9loaderhax so that's not necessary...? what are you trying to do?

**Comment by aceking01** [comment]
i was following the guide but i was stuck, if im able to used the arm9loaderhax and luma am doing fine? Im just confused after freezing on my 3ds. ill continue then Section III - Configuring Luma3DS..  thanks for the replies

**Comment by aceking01** [comment]
done perfect all done thanks!

**Comment by mikevasileiadis** [comment]
Hello! pleas some help here! i have followed the same guide (https://3ds.guide/installing-arm9loaderhax) done everything successfuly until section iv but was never able to boot hourglass9 on boot... i continiued with upgrading the system and im on 11.2 now with arm9 installed an luma running on boot properly but how do i fix the hourglass and decrypt 9 issue to finish the guide and intall hombrew(menuhax,fbi etc)?

**Comment by cubecubec** [comment]
have you put the payload into luma/payloads/start_hourglass9.bin?
