### ISSUE TITLE
Can't CTRTransfer to 2.1.0

### ISSUE THREAD

**Issue by thanik** [Plailect/Guide#484]
I did hard mod on New 3DS LL (JP region) and downgraded to 9.1.0 by this guide. Then I got into Decrypt9 and tried to do CTR transfer 2.1.0 to sysNand. I got stuck by these messages after some passed checks.

```
Switching out NAND header first...
Auto CTRNAND transfer: failed
```

**Comment by ihaveamac** [comment]
make sure you're actually using the latest Decrypt9

**Comment by thanik** [comment]
Yes, I'm using from Decrypt9WIP-20160823-224532.zip

**Comment by thanik** [comment]
Here is full Decrypt9.log
https://gist.github.com/thanik/4db84b8997ec002fd21cf264c212f0c9

**Comment by exegg** [comment]
Did you find a solution? I can recommend trying another SD card.

**Comment by thanik** [comment]
No. I tried 2 different SD card and still got same error.

**Comment by Margen67** [comment]
What are the size of the SD cards? How much free space do they have?
What is the allocation unit size of the SD card?

**Comment by Margen67** [comment]
If you solved the issue you should post the solution so that you can potentially help anyone who stumbles upon it.

**Comment by thanik** [comment]
I can't solve it and I don't have access to that N3DS now. Sorry.
