### ISSUE TITLE
Broken DSi functionality

### ISSUE THREAD

**Issue by test1926** [Plailect/Guide#485]
Does installing the cia's to fix this issue leave bad tickets in the ticket.db?

**Comment by dark-samus** [comment]
No. The problem is a simple mismatch, the titles in TWLN don't match the
titles in CTRNAND, which causes some sort of issue... There are no bad
tickets, the tickets were never the issue

**Comment by Margen67** [comment]
This is covered here: https://github.com/Plailect/Guide/wiki/Troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

If you want to delete the tickets just use FBI.
