### ISSUE TITLE
People who start on 2.1.0-4 don't need to ctrtransfer

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#486]
I mentioned this inside another ticket, but I think that this is a special case that has been overlooked even if, general, you need to transfer.

Someone who *starts* on 2.1.0-4 O3DS, which is more common than you'd think since that firmware was around for five months (the longest of any 3DS firmware), doesn't need to do a ctrtransfer at all, but the page https://github.com/Plailect/Guide/wiki/Part-1-%28Decrypt9%29 still has ""+ ALL - OLD - 2.1.0-4: 9.2.0 ctrtransfer".

If you start on 2.1.0-4, what you should do is get your OTP using the browser, then install a9lh and Luma using the browser, then (since Luma now boots 2.x) directly system update to 11.0.  ctrtransfer is unnecessary and gains you nothing.  (Remember that users who started on 2.1.0-4 don't have 9.x NAND saves or a 9.x backup.)

The 9.2.0 ctrtransfer page still needs to be kept around for people who downgraded to 2.1, especially on N3DS, but it should not be used for users who started on 2.1.

**Comment by Ev1lbl0w** [comment]
The page linked to the 2.1.0-4 version already instructs the user to install A9LH. You should read the instructions before creating a possible issue.

**Comment by arromdee** [comment]
It instructs the user to install a9lh as part of a series of steps that includes a 9.2.0 ctrtransfer.  Someone who starts on 2.1.0-4 does not need to do a 9.2.0 ctrtransfer.

**Comment by Ev1lbl0w** [comment]
The 9.2.0 ctrtransfer prevents people from N3DS from doing the error of updating in the System Settings. If the guide had 2 options: one for O3DS and one for N3DS, it would only be confusing and could lead some people in the wrong direction. So, doing the 9.2.0 ctrtransfer prevents noobs from bricking.

**Comment by arromdee** [comment]
It isn't really "are they on N3DS", it's "did they start with 2.1.0-4".

**Comment by quantumcat1** [comment]
Ev1lbl0w, a console on 2.1.0-4 cannot possibly be an N3DS!!!!

**Comment by pbanj** [comment]
you guys are missing his point -_-. he is saying if it was split it would confuse people. also some of the people i have helped on discord have not been able to update their o3ds from 2.1 using system update. both starting on 2.1 and those who downgraded to it. they all had to do the 9.2 ctrtransfer. so the guide is just fine how it is.

**Comment by arromdee** [comment]
If people who started on 2.1 can't update their o3ds using system update, that should be reported as a Luma bug.

**Comment by Plailect** [comment]
I made it so that now they start on Part 3, which will let them do either the update or the ctrtransfer.

**Comment by Dudin91** [comment]
Just to be sure: I got a new "old 3ds" with preinstalled firmware 2.1.0-4E. So can I simply start with Part 3 - arm9loaderhax without doing any of the steps in part 1 and 2? What do you mean by "getting your OTP using the browser"? Do you mean "Section II - Installing arm9loaderhax"?  I cant find any other mentions of the OTP in Part 3, thx.

**Comment by Ev1lbl0w** [comment]
"+ ALL - OLD - 2.1.0-4: 
Part 3 - arm9loaderhax"

That's already in the guide.
