### ISSUE TITLE
Question about region swapping

### ISSUE THREAD

**Issue by HoobertDoobert** [Plailect/Guide#487]
Hello! I recently imported a small n3ds from Japan. It's brand new and has obviously never connected to the internet before. Would it be possible to region swap this to an USA n3ds and give it eShop access?

**Comment by ihaveamac** [comment]
region change on New3DS will break eshop. there is no known workaround.

**Comment by HoobertDoobert** [comment]
Really? I remember asking this before and someone showed their region swapped 3DS on the eShop.

**Comment by ihaveamac** [comment]
was it *New* 3DS? because *Old* 3DS can access eShop after region change after doing certain steps. https://github.com/Plailect/Guide/wiki/Region-Changing

**Comment by HoobertDoobert** [comment]
https://github.com/Plailect/Guide/issues/162

I had to do a little search but I found my old issue thread. He posted a picture if that helps. I can't screenshot it because I can't get it to fit properly with the text on screen and yes it was on a New 3DS

**Comment by Plailect** [comment]
Added this info
