### ISSUE TITLE
about FBI inject

### ISSUE THREAD

**Issue by david-zzj** [Plailect/Guide#488]
after A9LH succeed（11.0J，old 3ds，no emunand），i dump H&S and inject the FBI，it display “succeed” . but when i reboot，the “Health&Safety” app didnot change ，it still ”Health&Safety“ app . what can i do ？

**Comment by ihaveamac** [comment]
just run it anyway, it should be FBI.

**Comment by david-zzj** [comment]
i have run the H&S ，but it still H&S...

**Comment by Ev1lbl0w** [comment]
Keep it as it is. The objective of the guide is that in the end you restore your original H&S app and have FBI as a separate app.

However, if you're doing this to install FBI as a separate app, then try redoing the steps again.
