### ISSUE TITLE
change to part 3

### ISSUE THREAD

**Issue by pbanj** [Plailect/Guide#490]
step 7 of section 4
 If you started Part 1 with a NAND between 4.0.0 and 4.5.0, make sure you have copied the following firmware.bin file to /luma/

can you please change that to say firmware or something more clear for people. i am sick of having to answer peoples question about it

https://cdn.discordapp.com/attachments/179314431010799616/225062445587234816/unknown.png

i and others have to answer that over and over again everyday. so maybe saying firmware instead of nand will help clear up the confusion

**Comment by Plailect** [comment]
Done, thanks for the github issue, I kept forgetting when it was only mentioned on IRC
