### ISSUE TITLE
black screen brick

### ISSUE THREAD

**Issue by moking1987** [Plailect/Guide#494]
In part3, section IV, setop 10(update sysnand to 11) in a friend nn3ds didn't work, always have an error y the beginning process, so we tried to force the update through the FieldRunners restore firmware, but we failed and now we have a black screen brick :'(, we already tryed every method of the Troubleshooting guide bur didn't work, thanks in advance for any idea!

**Comment by Plailect** [comment]
I'm going to need more details than that.

**Comment by moking1987** [comment]
sorry for the lack of information, this last monday I'm follow your guide step by step, part 1(nn3ds with 11.0 firmware, downgraded with FieldRunners method) and 2 done successfully but when I restore my Sysnand Backup(9.2) the instruction in the section IV step 10 its update to the last version(11.0, 11.1 now.), I tried like a hour but update process always fail and my friend(the nn3ds owner) decided to "force" the update with the backup that we made with field runners, that was a big mistake and we brick(black screen) the nn3ds, we tried every troubleshoting method but all failed and the console didn't reponse :/, thanks in advance for any idea!

**Comment by Ev1lbl0w** [comment]
Do you have A9LH already installed? If yes, can you boot any payloads?

**Comment by moking1987** [comment]
In theory I have it, but I only triedto load Hourglass but didn't work, do you recommend try with another payload?

**Comment by Ev1lbl0w** [comment]
Try booting Decrypt9

**Comment by jaxrogers2** [comment]
It sounds like he reflashed his 11.0 NFIRM backup to his sysNAND or used dgtool while having A9LH installed

That's a hard brick right there either way.

**Comment by Ev1lbl0w** [comment]
I agree @jaxrogers2. Personally, @moking1987, you shouldn't have tried anything which the guide doesn't say.

Try booting w/o the SD card.

**Comment by Plailect** [comment]
Running dgTool while on a9lh = guaranteed brick.

Congrats, you wrote garbage to your firm0.
