### ISSUE TITLE
o3dsxl System stuck on 2.1

### ISSUE THREAD

**Issue by Sinvanor** [Plailect/Guide#495]
Apologies in advance as I'm very new to this. 
I've followed the guide to the letter up until the point where it said to use system update to update the system. 
Now I can't get to homebrew to install FBI, Luma etc. 
I'm at a loss on what to do.

I have a o3sdxl and have followed all the steps on "Section IV - Restoring the System" Thing is, the system restore failed. 
I thought maybe it was supposed to (that's what I get for doing this at 3am)
and moved on to "Section V - Injecting FBI" Everything seemed to be working fine, except health and safety just crashes. I've figured out (hopefully) that I'm supposed to be able to get the system back to 9.2 in order to continue with section V, but I don't know how to do this or if this is infact what the system update should of done.

**Comment by trbocode** [comment]
Update normally if you are on 2.1 and can't restore the nand backup.

**Comment by Sinvanor** [comment]
Does update normally mean turn on the wifi and click system update?
I have a NAND backup like the guide said to make. I just don't know what to do with it. 
I followed the whole 9.2.0 ctrtransfer part to get the NAND back up then followed the rest to get FBI injected. Either it failed to inject, or the system update didn't work, maybe both.

**Comment by trbocode** [comment]
Yeah, click system update
