### ISSUE TITLE
Changing of NNID

### ISSUE THREAD

**Issue by AnonAgent** [Plailect/Guide#496]
Hi,

Was wondering is there any way to change NNID or is formatting the 3DS the only way to remove the current NNID? If formatting is the only way, is it safe to format the 3DS that I've modded with the guide, (example; will anything be gone or do i have to re-mod the 3DS again after formatting)?

Thanks in advance and regards.

**Comment by jaxrogers2** [comment]
Formatting the system via system settings is the only way to unlink your NNID from your 3DS. In certain cases, Nintendo support can also unlink a NNID from a 3DS (such as when the NNID on a 3DS is used for a Fieldrunners downgrade on a New3DS and you need to call support to get your NNID settings on your 3DS reset). You can also delete your NNID, but that both unlinked your NNID and deletes it from existence on their servers entirely, so don't do that.

It is perfectly ok to format an A9LH system through system settings, A9LH will still be there after the format. If you want to keep your digital game saves, back them up with JKSM (or decrypt9 for GBA save games) before formatting.

**Comment by Blackwigg** [comment]
Maybe injecting a blank NNID with decrypt9?

**Comment by Plailect** [comment]
#### What you need

* The latest release of [GodMode9](https://github.com/d0k3/GodMode9/releases/)

#### Instructions

1. Copy `GodMode9.bin` from the GodMode9 zip to the `/luma/payloads` folder on your SD card and rename `GodMode9.bin` in `/luma/payloads` to `up_GodMode9.bin`
6. Boot holding (Up) to reboot into arm9loaderhax GodMode9
**(Be VERY careful with this tool, it can brick you if you misuse it, even with arm9loaderhax installed!)**
14. Navigate to `SYSNAND CTRNAND` -> `data` -> (32 Character ID) -> `sysdata` -> `00010038`
15. Hold down the (R) trigger, then press X on `00000000` to rename this file
16. Press Up once to change the name to `10000000`
17. Press (A) to save changes
18. Press (A) to unlock SysNAND writing, then input the key combo given
18. Navigate back to the Main Menu
16. Press Start to reboot
