### ISSUE TITLE
11.1 Update

### ISSUE THREAD

**Issue by Webbeh** [Plailect/Guide#498]
Since very lately (today if I'm not mistaken), update 11.1 rolled out.

Obviously, I didn't know about it and updated my new N3DS as asked in Part 3, after seeing that "Yes, it's safe, stop asking".

Please add a warning !

**Comment by deew3e** [comment]
It is safe because you can go back to your old firmware. But the questions now are these: "Is there another way to DSP DUMP/how important is the DSP DUMP? Can we skip it?"

**Comment by Webbeh** [comment]
I don't know what a DSP dump is actually, and I'm for now letting the system run "as is" without trying an update for the next days.

I can install CIAs fine, the system runs smoothly.

**Comment by mockatoy** [comment]
It allows homebrew games/applications to have sound/music If your not gonna use homebrew games or applications that have sound you can skip it.

**Comment by Webbeh** [comment]
Thank you !

**Comment by M0ir** [comment]
if you have finished the guide it is safe to update to 11.1, right? or are there some problems if i do that

**Comment by Ev1lbl0w** [comment]
Guys, update 11.1 rolled out only yesterday! Give time for @Plailect to see what changed and update the guide! He needs to wait for the homebrew developers (smea and/or yls8) to update the entrypoints. So please be patient!

**Comment by Webbeh** [comment]
I ran into some issues with Menuhax not loading past the "parsing config" line.

Had to copy/paste an older version from another console to get it working.

Otherwise everything runs smoothly. I'm currently installing dozens of CIAs with FBI (tested both the Health&Safety and the homebrew direct from menu, both work fine).

I can say you can update.

**Comment by Ev1lbl0w** [comment]
There is a problem updating to 11.1 and that is, ATM, the homebrew launcher doesn't work. This should be a problem only for a matter of days and should be fixed soon, as said in this [GBATemp post](http://gbatemp.net/threads/11-1-0-34-firmware-update-out.441519/)

**Comment by Webbeh** [comment]
Right, actually forgot to mention that....

**Comment by jaxrogers2** [comment]
Yeah that's why dspdump and any other Homebrew app will be useless- there's no 11.1 payload for HBL so HBL doesn't boot on 11.1 yet.

**Comment by DimSpirit** [comment]
So if I updated am I screwed? Is there a way to downgrade back to 11 and have the homebrew launcher work?

**Comment by Ev1lbl0w** [comment]
DimSpirit, as I said earlier wait for for @Plailect update the guide and the homebrew developers to update the payloads.

**Comment by Plailect** [comment]
https://twitter.com/smealum/status/775915581379706880
