### ISSUE TITLE
HBloader freezes inside emuNAND

### ISSUE THREAD

**Issue by Delphi79** [Plailect/Guide#5]
I have followed all the steps from part 1-3 without a problem. When I get to step 24 under part 4 "Open TinyFormat" Hb loader freezes. I can't launch any home brew while inside of emuNAND. It works fine in SysNAND. I have tried going over this step for hours with the same result. My emunand is running firmware 10.6.0.30U as step 29 states in part 3 "Update your EmuNAND to the latest version using system settings"

Have you seen this before?

**Comment by Plailect** [comment]
I updated the guide to directly use the TinyFormat CIA instead.

**Comment by Delphi79** [comment]
That worked great! Thank you!

**Comment by Delphi79** [comment]
Just an update. After moving on, following your update of the .cia for tiny format I was able to complete all the steps. This whole guide worked beautifully and I wanted to thank you again for this. I have never done any of this stuff before and the result was amazing. I am super grateful for your time and effort in updating this guide. Everything works! =)

**Comment by Plailect** [comment]
Good to hear, cheers!
