### ISSUE TITLE
9.2.0 Update

### ISSUE THREAD

**Issue by ephzee** [Plailect/Guide#50]
I have tried many times to update, but get hung up on the health and safety dump(step 11. Go to SysNAND File Options, then select the Dump Health & Safety option to dump Health & Safety to  hs.app)  .  Here is the error log.

Searching title "Health&Safety"...
Method 1: Search in title.db...
System version 4.x
Found title 0004001000021300
TMD0 found at 15BD8000, size 2868b
APP0 not found or fragmented!
Health&Safety Dump: failed!

**Comment by Plailect** [comment]
Do the steps here:

https://github.com/Plailect/Guide/wiki/Troubleshooting#validation-stage-1-success-and-validation-stage-2-failed

**Comment by ephzee** [comment]
Thank you.  After dumping, mounting, and defragging, how do I replace my CTRNAND partition with the defragged version?

**Comment by Plailect** [comment]
Inject the CTRNAND partition file that has been defragmentated..

**Comment by ephzee** [comment]
Thanks.  Sorry I saw that option after I finished dumping.
