### ISSUE TITLE
9.2 Downgrade "Did not get am:u handle"

### ISSUE THREAD

**Issue by Odebaer** [Plailect/Guide#501]
I went through the dsi ware downgrade with a n3ds xl on 11.1 and used oothax to get into sysdowngrader. But every time, it gives me a red text "Did not get am:u handle, please reboot" Ive tried replacing all the update files but nothings worked.

**Comment by Ev1lbl0w** [comment]
I'd say try injecting NFIRM to the NAND again. Maybe something went wrong and didn't work?

**Comment by Odebaer** [comment]
Thanks pal.  I tried the downgrade to 10.4 with dgtool again and sysDowngrader worked immediately. I thought I tried that once before but i guess not.
