### ISSUE TITLE
NTR on 11.1 (for part 3)!

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#504]
BootNTR works with 11.1 home menu now! However, it requires the latest dev build of Luma3DS, an 11.0 firmware.bin, and BootNTR from the zip file on this thread (https://gbatemp.net/threads/bootntr-11-1-0-34-homemenu-support.441566/).

I have provided a download of the 11.0 NFIRM firmware.bin for USA old3DS here:
https://drive.google.com/open?id=0B5iNZ1D1UhiNVkI1bkFDemZJaXc but it can also be found on the Luma3DS installation and upgrade wiki page (although that firmware.bin was corrupted when I downloaded it, so I dumped it from D9 instead).

Once NTR supports 11.1 NFIRM in its latest release, which sounds like will be soon, the firmware.bin and dev version of Luma will no longer be necessary.

**Comment by dankzegriefer** [comment]
NTR won't fully support 11.1 firm. This is just a mod that modifies the bootntr program, the patches won't be updated because cell9 is a baby.

**Comment by jaxrogers2** [comment]
NTR itself is closed source and is no longer being worked on because cell9 quit and deleted the source code. BootNTR is an open source porgram that just launches NTR, so yes it is being updated to support newer FIRMs. It was recently updated to work with 11.0 NFIRM, 11.1 NFIRM support isn't far away.

**Comment by Plailect** [comment]
https://github.com/astronautlevel2/BootNTR/releases/tag/3.4
