### ISSUE TITLE
Folder help

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#505]
Navigate to /Nintendo 3DS/(32 Character ID)/(32 Character ID)/extdata/00000000/ on your SD card
EUR Region: Delete 00000098
JPN Region: Delete 00000082
USA Region: Delete 0000008f
KOR Region: Delete 000000A9
TWN Region: Delete 000000B1 

I am on this step of downgrading, my system is on 9.2 now. I took out the sd card and put it in my computer to delete USA region :000008f. Put it back in my 3ds and it reconfigured home menu for some reason so I reput it in my computer to check if it put the folder back and it did. Is that folder suppose to be permenently deleted?

**Comment by Gelums** [comment]
Nevermind! I am almost done, restoring NAND after 2.1 firmware

**Comment by Ev1lbl0w** [comment]
That step is just do delete menuhax. So it's normal the console creates that folder again.
