### ISSUE TITLE
decrypt9 cant be startet ?!

### ISSUE THREAD

**Issue by denjid** [Plailect/Guide#506]
hey,
decrypt9 (latest version) via hbl (QR) does not start. only a black and a red square appears .
then automatically the hbl start again.
for example cant open emunand9 too..
any idea ?
fw 9.2

**Comment by Ev1lbl0w** [comment]
what is your entrypoins? can you load other homebrew apps? have you tried copying back the Decrypt9 files? Do you have the aeskeydb.bin file on the root of your SD card? (or in the files9 folder?)

**Comment by Plailect** [comment]
>If sysDowngrader crashes at any point during the downgrade (which can happen occasionally), you can power off the system by holding the power button. You will be left with what's called a "partial downgrade" or "partial", which is recoverable.

>Although a partially downgraded system may show 9.2.0 as the system version, you are not done. You must restart from the beginning of this page and downgrade a second time to install any files that were not installed. Browserhax will work for partial downgrades as long as you are using the recommended version of sysDowngrader.
