### ISSUE TITLE
can't inject fbi

### ISSUE THREAD

**Issue by sE4dUck** [Plailect/Guide#507]
I followed all the step and stuck at fbi inject, it said injected successfully but when i boot again, it's still a normal h&s app. I've tried to download some vers of fbi, put in "input" folder of Universal-Inject-Generator-master with hs.app dumped and run go.bat several times but it didn't work. Can anyone give me some advices? The firmware: Sys 11.1.0.34

**Comment by Plailect** [comment]
You're using it wrong, follow instructions exactly.
