### ISSUE TITLE
Just want to say thank you Plailect!

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#508]
Finished the steps, everything in the guide is perfect and went flawlessly. With the guide I was able to downgrade from 10.7.0-32 to 9.2.0 then 2.0.1 and back up to the lastest 11.1 with arm9 installed. I was also able to backup NAND before the arm9 installation which was awesome. Thanks Plailect! I would pm you if I knew how.

**Comment by dankzegriefer** [comment]
nice blogpost.
also stop misusing issue you 'tard.
