### ISSUE TITLE
Using 11.1 to downgrade?

### ISSUE THREAD

**Issue by codystar55** [Plailect/Guide#509]
Hello, so recently i borrowed my friends o3ds so i can use it to downgrade my n3ds xl (i had to cfw his for him)
But the DAY BEFORE i did so, N decided to roll out 11.1 so now my a9lh o3ds is on 11.1 and im skeptical to purchase filedrunners until i know it works on 11.1. OR is there a possibility of an 11.0 ctrtransfer image anywhere because that would help me out

**Comment by Plailect** [comment]
This is not an issue.

Try reading.
