### ISSUE TITLE
A little confused about instructions

### ISSUE THREAD

**Issue by Bassist3** [Plailect/Guide#510]
Hello, Im new to this stuff and not tech savvy but Im trying to undo the region lock on a 3ds but one of the steps says move payload_stage1.bin and payload_stage2.bin to a folder. In this download I can not find the .bins, I only see payload folders. Is that what is meant here? Any help is much appreciated. Thank you in advance.

**Comment by aceking01** [comment]
part 3 of section I at No 7.
7. Copy payload_stage1.bin and payload_stage2.bin from the arm9loaderhax zip to a9lh folder on your SD card
download the arm9loaderhax zip unzipped it, :)

**Comment by Bassist3** [comment]
Hello, Thank you for the response!  I did download that and extracted the files but it have payload folders not .bins.  Maybe am I doing that wrong?

**Comment by aceking01** [comment]
see my folder files its a bin file data
![capture](https://cloud.githubusercontent.com/assets/17075135/18574721/93d0fbd4-7c02-11e6-83e2-28a6266743de.PNG)

**Comment by Bassist3** [comment]
Weird mine doesnt have that.  I wonder why?  I just have folders :(

**Comment by aceking01** [comment]
could you post a screenshot? thats the file from noscreeninit.

**Comment by Bassist3** [comment]
![image](https://cloud.githubusercontent.com/assets/22227241/18574823/4c3da7f2-7b96-11e6-9f20-a95cf430a9a4.png)

![image](https://cloud.githubusercontent.com/assets/22227241/18574826/598a0c48-7b96-11e6-8c1f-d20424e8569f.png)

**Comment by aceking01** [comment]
could you download from the link that i gave you. i redownload the file and i got the same file inside of it

**Comment by Bassist3** [comment]
all 4 things in the link you sent or just a particular one?

![image](https://cloud.githubusercontent.com/assets/22227241/18575178/4cfb5afa-7b9a-11e6-9c04-46c993dbb31b.png)

**Comment by Bassist3** [comment]
![image](https://cloud.githubusercontent.com/assets/22227241/18575297/b29b574c-7b9b-11e6-8069-ac991e18637f.png)

when I download the noscreeninit and screeninit this is what it looks like for me

**Comment by aceking01** [comment]
ohh seems you need a win rar application to unzipped the files you have to extract it from the nosreeninit

**Comment by Bassist3** [comment]
ah ok!  Is there a good free one you would suggest?  By the way, thank you for your help!

**Comment by mockatoy** [comment]
http://www.7-zip.org/

Is a good one.

**Comment by Bassist3** [comment]
Thanks for the help everyone!!!!!  If I have any more questions Ill come back but its really appreciated!!  I have been waiting to play Dragon Quest Monsters Joker 3 haha.

**Comment by aceking01** [comment]
Dragon Quest VII Forgotten Past just got released :) play it hehe

**Comment by Bassist3** [comment]
Oh I will!

**Comment by Bassist3** [comment]
Just out of curiosity, I just finished that first section of step 3.  Am I allowed to turn my 3ds off without the finishing all of these steps if I did steps one and 2 and only working on three?  I have it plugged in so it wont hurt it to be on over night and while im at work but just wanted to know if it was safe to turn off with out finishing EVERYthing.  Like I said Im not to tech savvy, I just want to make sure it wont mess anything up if I dont full complete everything first before powering off.

**Comment by jaxrogers2** [comment]
Turning your 3DS off won't do anything, but you will have to boot it without the SD if you want to turn it back on in 2.1 at all. Sleep mode will brick New3DSes, probably because the NAND padgen and the NCSD header switch really confuses Streetpass and such (this is my personal theory on why sleep mode on 2.1 bricks New3DS, it's certainly not proven or anything). Sleep mode with an old3DS is probably ok but just as a precaution don't put an old3ds in sleep mode and just leave the console on and charging while on 2.1 so your battery doesn't die or anything.

Also, if you exit out of system settings on 2.1 you will get a black screen as a "soft" (MCU) reboot requires the SD to be in the console to complete but 2.1 cannot run boot functions with the SD inserted. Overall, 2.1 is very unstable even on old3ds so if it hangs or blackscreens on something NOT related to homebrew (like exiting out of system settings) it's ok to turn your console off and back on (taking the SD out to boot).

**Comment by Bassist3** [comment]
well, I have a new problem.  I got through the step listed below and now the 3ds wont even start up :(.  so did I just permanently destroy this 3ds?

Shut down your console, hold the power button until it turns off if necessary

**Comment by Bassist3** [comment]
now again I have questions.  Im on this step: Extract Universal Inject Generator, then copy both hs.app from your SD card and FBI.cia from the FBI zip to the input folder

First: Does extract universal inject generator mean extract to your computer or your SD card?
Second:   the only hs.app I can find on my SD card now is in the files9 folder.  Is this the on I need to move?

**Comment by aceking01** [comment]
if you can open the luma3ds your fine.

**Comment by Bassist3** [comment]
I got it and Im currently playing my game!!!! Thank you for all of your help!!!!!
