### ISSUE TITLE
Make sure 3DS charged

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#512]
Although it may be obvious to most, is it worth adding a warning to make sure the 3DS is fully charged? I can see much possibility of breakage if it runs out of battery in the middle of a downgrade, for example.

**Comment by the100guy** [comment]
It seems like a good idea, but why not just have the warning of keeping the 3ds plugged in for as much of the process as possible?

**Comment by Plailect** [comment]
Added
