### ISSUE TITLE
fw 11.1 & emunand backup 

### ISSUE THREAD

**Issue by matt09ad** [Plailect/Guide#513]
I may be the only one but when I updated to 11.1 I can no longer backup my emunand in hourglass9 v1.2
it gives an error as sd is not formatted for emunand
emunand backup: failed
how can i fix this?

**Comment by Margen67** [comment]
If you already have A9LH switch to updated SysNAND

**Comment by Plailect** [comment]
You don't have an emunand anymore.

**Comment by matt09ad** [comment]
so should i restore nandmin that i made on 11.0? my cfw (homebrew menu, games, luma3ds) still works. how can i resolve this. the only thing that doesn't work is my emunand backup option in hourglass9. i can make backups of my sysnand fine. i used this current guide to hack my 2ds on 10.7 then updated fine to 11.0. how can i restore emunand. thanks
