### ISSUE TITLE
Add guidance on where we can take breaks

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#514]
As you say in the intro, the whole process can take several hours. It would be good to add some guidance as to where someone could take a break, if they can't do it in one go.

Is it the case that anywhere the 3DS is being rebooted, that it could be powered off instead? What about the n3DS while it's on 2.1.0 and not safe to sleep - is it OK to power off then? Probably best to suggest that, if you need to take a break, ideally do so at the end of a page or a section, but whatever you do, make a good note on exactly where you got to.

**Comment by dark-samus** [comment]
You can take a break pretty much at any point in the process... As long is
nothing is currently doing something (like the downgrade is going, or the
ctrtransfer happening) then it is safe to simply power the device off and
leave it until next time... I wouldn't recommend sleep mode at any point,
as n3ds users on 2.1 can brick simply by putting it in sleep mode (hence
why I suggest just powering off)

**Comment by JohnVeness** [comment]
Thanks. Although I was asking the questions here, what I really meant was for the guide to say something. It seems to me that it is slightly easier to say that the 3DS can be switched off instead whenever it is being rebooted, because otherwise you may have to explain how to get back to where you were after power on, which can vary depending where you are in the process.
