### ISSUE TITLE
Add QR code for dukesrg URL?

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#516]
In Part 3, Section II, is it possible for the guide to have a QR code for the dukesrg page, to save manual entry?

**Comment by ihaveamac** [comment]
camera applet didn't get QR code scanning until 3.0.0-5 I think.

**Comment by JohnVeness** [comment]
Oh, fair enough then! I admit I didn't actually check while I was in 2.1.0, I just assumed that QR code scanning had been there forever.
