### ISSUE TITLE
Explain a particular deletion

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#517]
In a few places, you have a section like:

- Navigate to /Nintendo 3DS/(32 Character ID)/(32 Character ID)/extdata/00000000/on your SD card
- EUR Region: Delete 00000098
- etc.

I think this is to clear the Home Menu's extra data. Although it isn't crucial, I feel it is nice to let the user understand roughly what they are doing, so I think it would be good to replace the word "Navigate" with "Clear the Home Menu's extra data by navigating".

**Comment by Plailect** [comment]
Fixed
