### ISSUE TITLE
Decrypt9/Hourglass9 return to main menu before pressing Select

### ISSUE THREAD

**Issue by JohnVeness** [Plailect/Guide#518]
In Part 3, Section IV, you correctly say to return to the Hourglass9 main menu before pressing Select.

However, in Part 3, Section V (after dumping hs.app), and in Part 2 (after backing up to NANDmin.bin), you miss out saying the you have to return to the main menu first.

I suggest that all such occurences should have consistent text, which I suggest slightly improving by saying something like "Press (B) to return to the main menu, then press (Select)..." etc.

**Comment by Ev1lbl0w** [comment]
There's actually no need to go back to the main menu to unmount the SD card, so I think the line of text saying to go back to the main menu would be the only one to be rewritten.

**Comment by Plailect** [comment]
Fixed
