### ISSUE TITLE
Collection of spelling and style corrections.

### ISSUE THREAD

**Issue by Hellrespawn** [Plailect/Guide#52]
This is a collection of spelling errors, style inconsistencies and general recommendations for clarity. 

AFAIK there is no way for Wikipedia-style collaborative editing, otherwise I would've done that. If there is a way I don't know about, feel free to let me know, and I'll make the changes myself before submitting them for approval.

I hope you find this useful!

### Home:
- Paragraph 6: Only mentions arm9loaderhax + CakesFW, not AuReiNand.
- Paragraph 7: nnid -> NNID

### FAQ:
- **Q: How do I update CakesFW / AuReiNAND?** Inconsistent spacing around '/'
- **Q: Can I use this to play games from other regions?** enable -> enables
- **Q: How do I switch from the old guide to Updated SysNAND + Cakes?** Only mentions CakesFW, not AuReiNand
- **Q: What about System Transfers?** dlc -> DLC

### Troubleshooting:
- **OTPHelper/Decrypt9 won't restore / can't find my NAND backup** Inconsistent spacing around '/'
- **Blue screen on boot (bootrom error)** Step 2: Inconsistent spacing around '/'

### Get Started:
- Consider adding a note to explain that people with an existing EmuNAND and CFW can follow the guide from Part 4 without a RedNAND.
- Paragraph 3: Inconsistent spacing around '/'
- Paragraph 8: dpad is properly referred to as D-Pad

### Part 1 (Homebrew):
- Paragraph 4: OOTHAX is properly referred to as oot3dhax, according to the [official documentation](https://github.com/yellows8/oot3dhax)
- Paragraph 6: Inconsistent spelling/capitalization of Homebrew Launcher
- Step 17: dpad is properly referred to as D-Pad, inconsistent spelling/capitalization of Homebrew Launcher

### Part 2 (Downgrading):
- Except for two occurrences, in the 2nd ("This version of sysUpdater...") and 4th ("...version of sysUpdater") paragraph, all references to sysUpdater refer to PlaiSysUpdater specifically and should be updated as such.
- Step 6: dpad is properly referred to as D-Pad
- Step 18: Inconsistent spelling/capitalization of Homebrew Launcher

### Part 3 (RedNAND):
- Step 29: Consider changing the warning, e.g. "Once you exit System Settings you will be returned to sysNAND, make sure to reboot into RedNAND first!" Currently, the instructions can be seen as contradictory (use system settings to update, but don't exit system settings.)
- Step 30: Consider changing this to creating an empty title.db + import.db, then repairing the DB. In my experience this seems more consistent than waiting for the eShop, especially if your WiFi connection isn't great.

### Part 4 (Getting the OTP):
- Consider adding a note to explain that people with an existing EmuNAND and CFW can follow the guide from Part 4 without a RedNAND.
- Paragraph 3: Inconsistent spelling of arm9loaderhax, Arm9 -> ARM9
- Paragraph 4: "...ensure we don't partial downgrade..." -> "...ensure we don't partially downgrade..."

Section I:
- Step 5: Inconsistent spelling of Start
- Step 7: Consider changing the warning, e.g. "Once you exit System Settings you will be returned to sysNAND, make sure to reboot into RedNAND first!" Currently, the instructions can be seen as contradictory (use system settings to update, but don't exit system settings.)
- Step 9: Perhaps mention that this only applies to N3DS, N3DSXL and 2DS?
- Step 11: Inconsistent spacing around '/'
- Step 28: Inconsistent spelling of Start
- Step 29: Consider changing this to creating an empty title.db + import.db, then repairing the DB. In my experience this seems more consistent than waiting for the eShop, especially if your WiFi connection isn't great.
- Step 37: Consider changing this to creating an empty title.db + import.db, then repairing the DB. In my experience this seems more consistent than waiting for the eShop, especially if your WiFi connection isn't great.

Section II:
- Step 2: Inconsistent spelling of NAND.
- Step 6: leftover -> left over
- Step 11: Inconsistent spelling/capitalization of Homebrew Launcher

Section III:
- Step 1: Inconsistent spelling of 3DS

### 3DS Stuck (2.1.0 Without Functional Browser):
"NAND Backup bin" (Step 9) and "A valid NAND backup of some kind" are vague, sysNAND_original.bin should exist at this point.

### Part 5 (arm9loaderhax):
- Considering the current state of AuReiNand vs CakesFW, this entire section could probably use a rewrite, but that is beyond the scope of this list.
- Paragraph 2: arm9 -> ARM9, "They other wise..." -> "They..." or "Apart from this, they..."
- Paragraph 3: Consider mentioning DSiWare along GBA Virtual Console and DS Homebrew.

### Part 5 (arm9loaderhax & AuReiNAND):
- Consider numbering the sections, like in Part 4.
- Paragraph 7: permanant -> permanent
- Since the latest version of the guide always injects RedNAND into SysNAND, "Installing FBI into SysNAND" and Step 6 of "Finalising setup" are not strictly necessary anymore.
- Step 10: Inconsistent spelling/capitalization of Homebrew Launcher

### Part 5 (arm9loaderhax & Cakes):
- Cakes is properly referred to as CakesFW, change page title?
- Consider numbering the sections, like in Part 4.
- Paragraph 5: permanant -> permanent
- Since the latest version of the guide always injects RedNAND into SysNAND, "Installing FBI into SysNAND" and Step 6 of "Finalising setup" are not strictly necessary anymore.
- Step 10: Inconsistent spelling/capitalization of Homebrew Launcher

### 9.2.0. Update:
- Step 1: Inconsistent spelling of menuhax. ThemeHax is properly referred to as themehax.

### Donations:
- "at through the following" -> ?

### Multiple occurences:
Most of these are in the list above, but I might have missed some and didn't notice AuReiNAND -> AuReiNand until later, so a more thorough search might be useful.

- dpad is properly referred to as D-Pad
- Inconsistent spacing around '/'
- Inconsistent spelling/capitalization of Homebrew Launcher
- AuReiNAND is properly referred to as AuReiNand, according to the [official GitHub page](https://github.com/AuroraWright/AuReiNand).

**Comment by Plailect** [comment]
Damn! You're amazing man, I've been meaning to clean up all of the minor things for some time but could never justify the time sink.

I'll fix these soon.

**Comment by Plailect** [comment]
The inconsistent spacing around / is due to the way github displays italics, and it is correct in my source files. Additionally, I'll leave the CakesFW page as it is since changing the title also changes the URL.

Otherwise, all of these have been fixed.

**Comment by Hellrespawn** [comment]
Homebrew Launcher does not capitalize the B in the [official website.](http://smealum.github.io/3ds/)

You were a bit overzealous with the "3DS" search and replace in Part 4, the folder on the SD is called "3ds", all lowercase.

You probably did not mean to change references to the original sysUpdater with PlaiSysUpdater in "Region Changing."

"Black screen on SysNAND boot after installing arm9loaderhax" under Troubleshooting still instructs AuReiNand users to press L+R for booting default.bin, which has since been replaced by Start.

**Comment by Plailect** [comment]
Thanks, everything seems to be fixed now
