### ISSUE TITLE
About DSiware Downgrade - Section V - ctr-httpwn

### ISSUE THREAD

**Issue by exegg** [Plailect/Guide#521]
Has this been tested?

I did a normal transfer recently and I remember the console rebooting, then connecting online before finalizing the process. It's like a soft reboot but as the screens reinitialize and everything, I think ctr-httpwn effect lifts at this point. Check this video where is described what I say https://youtu.be/8OoGCpAV2dE?t=7m44s

I don't know if anyone has succesfully tried it yet but sounds like a potential bootloop to me unless you use safe mode to update to 11.1

**Comment by Ev1lbl0w** [comment]
It it wasn't safe, it wouldn't be in the guide.

**Comment by Plailect** [comment]
It has been tested already, see [this](https://www.reddit.com/r/3dshacks/comments/52u0bo/)

**Comment by exegg** [comment]
I saw that @Plailect but he used ctr-httpwn in the source console. The target does a reboot and connects again online to finalize the process. Here https://youtu.be/8OoGCpAV2dE?t=7m44s

As the OP in that thread had the target in 11.1, this is no issue. However, he didn't test what would happen if the target is on 11.1, I asked him directly https://www.reddit.com/r/3dshacks/comments/52u0bo/psa_you_can_use_ctrhttpwn_in_order_to_transfer/d7pz6cu

That's why I'm asking, since I think you didn't try it either. I could but I don't have a hardmod in my vanilla 11.0 that I'm willing to try
