### ISSUE TITLE
Do I need fieldrunners on both systems?

### ISSUE THREAD

**Issue by rpalmon** [Plailect/Guide#522]
Hello, when downgrading the n3ds using a 2ds, do I need fieldrunners on both systems (hacked and unhacked)? Also, how much does fieldrunners cost? Thanks.

**Comment by Ev1lbl0w** [comment]
Fieldrunners costs 5$. You only need to buy the game in the CFW 3DS. Note, however, that you'll be unable to transfer system from n3ds to 2ds in the end of the guide. Which means, the NNID will stay in the n3ds.
