### ISSUE TITLE
Is it possible to keep NNID while doing DSiWare hax?

### ISSUE THREAD

**Issue by Ev1lbl0w** [Plailect/Guide#523]
Since this hax will transfer the NNID of the user and, considering it's possible for the user to be unable to get it back (due to, for example, n3ds to o3ds transfer not possible), is it possible to "save" the NNID in some way?

I thought of creating an EmuNAND, move SysNAND to EmuNAND then start with a new SysNAND w/o NNID. Then, at the end, restore EmuNAND to SysNAND.

Would this be possible?

**Comment by Plailect** [comment]
No, a System Transfer will unlink any NNIDs associated to the device hardware on the server side.

**Comment by Kidel** [comment]
What if you format the downgraded 3DS#2?
Will you be able to log back in on 3DS#1?
