### ISSUE TITLE
Add Ryuzaki-MrL's Custom map XML downloader to guide

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#527]
Since some steps of the guide direct users to use a save manager, adding this mmmap XML downloader (found at https://github.com/Ryuzaki-MrL/Custom-mmap-XML-Downloader/releases/) which runs through HBL would help a lot for people who don't know about seed encryption, etc and just want to back up their digital savegames.

**Comment by Plailect** [comment]
I don't believe that JKSM (which is recommended) is even compatible with this

**Comment by ihaveamac** [comment]
it is compatible, if the game boots under *hax.

**Comment by jaxrogers2** [comment]
Yeah, the .3dsx version of JKSM boots titles individually through the HBL title selector, so these are compatible. But true, they aren't compatible with the .cia version most people are familiar with.
