### ISSUE TITLE
Possible bricked 3DS

### ISSUE THREAD

**Issue by Mstrodl** [Plailect/Guide#528]
I have O3DS that may have been bricked from following the guide... The console will only boot if I hold select but that's only for Luma3DS config. Otherwise, it just shows a black screen (with the backlight on) I tried starting with holding start as well...

**Comment by FrozenChen** [comment]
You should be able boot payloads, make sure you didnt name incorrectly the luma/payloads folder and that hourglass9.bin is named start_hourglass9.bin

**Comment by Mstrodl** [comment]
Thanks! I think that was it! The guide didn't say to do that, so I didn't :)
You guys are awesome :+1:

**Comment by Mstrodl** [comment]
Nope, I renamed luma/payloads/Hourglass9.bin to luma/payloads/start_hourglass9.bin but it still isn't working :(.

**Comment by Mstrodl** [comment]
Never mind. Thanks a million. I still had the test arm9loaderhax.bin on my SD card (the one that you push any button and the 3DS shuts off)

**Comment by Mstrodl** [comment]
Never mind. I was able to boot the payload, however, I cannot boot from sysnand. :(

**Comment by FrozenChen** [comment]
You did the restoring your system section and have autoboot sysnand selected in luma config?

**Comment by Mstrodl** [comment]
Yes

**Comment by Mstrodl** [comment]
I have made some progress... I'm not sure what I did though. The 3D light now comes on. I tried [this](https://github.com/Plailect/Guide/wiki/9.2.0-ctrtransfer) because I thought something was wrong with my backup.

**Comment by Mstrodl** [comment]
NEVERMIND. It just was taking a long time to boot. I really appreciate you. \*hug\*

**Comment by Mstrodl** [comment]
I'm updating it to the latest version now :)
