### ISSUE TITLE
Never told to remove tubehax dns from settings

### ISSUE THREAD

**Issue by dyerseve** [Plailect/Guide#529]
It's possible I missed it, and if so, I apologize.
I was updating an old3ds 10.7 using stickerhaxx and then following the guide, downgrade to 9.2 fine, everything going well until I get to update firmware to 11.1, i knew i had nus blocked on my router so removed that, after some head scratching i remembered the DNS setting on the wireless, removed the tubehax dns and now the update is running. Perhaps I missed something that would have cleared that, but maybe a note around the section about updating to the latest firmware would help, you might also mention the settings screen shows "sys" rather than "Ver." because as much as I wanted to believe I was in custom firmware from the home screen I couldn't tell any difference at that point and upgrading the firmware is slightly terrifying...

**Comment by Plailect** [comment]
Fixed
