### ISSUE TITLE
Part 3, Section iv, 10

### ISSUE THREAD

**Issue by tahu3530** [Plailect/Guide#531]
I have followed all previous steps and when I go to update system it gives me an error. My DNS is already set to auto I don't know what to do. I am doing this on a 2ds with firmware 6.0.0

**Comment by pbanj** [comment]
do the 9.2 ctr transfer and then update

**Comment by Ev1lbl0w** [comment]
This is probably a Luma3DS issue. Other people have had this issue before.

**Comment by tahu3530** [comment]
I already did the 9.2 ctr transfer and all other previous steps

**Comment by Plailect** [comment]
This is either user error or Luma related.

https://github.com/AuroraWright/Luma3DS/issues
