### ISSUE TITLE
Part 3 Section 2 Flashcart Issue

### ISSUE THREAD

**Issue by xxbilxx** [Plailect/Guide#535]
Hey there, Plailect! I was following your guide and found an issue with my downgrade that didn't seem to be documented anywhere else. 

I recommend you include this somewhere in your guide (possibly directly before Part 3 Section 2).

In my case, I just completed the CTRNAND transfer to 2.1 on my N3DS and was able to boot into the homemenu. While I was able to boot, I was unable to navigate with the d-pad or use touch input without my console freezing. This was after I inserted my SD card into my console, but the insertion of the SD card did not cause the console to freeze. I was able to reproduce this issue 5-6 times with a 100% success (or failure) rate. To fix the issue, I figured my R4i Gold flashcart may be causing the problem because of its long string of characters for a name. 

After removing the cartridge, I was able to reboot and continue with the guide as normal.

If you have any other questions for me, my email is wbonanno@kent.edu. Thanks and I appreciate all your work on the guide.

**Comment by xxbilxx** [comment]
Also, I am unsure if this incident is isolated to the N3DS nor the R4i flashcart.

**Comment by Plailect** [comment]
Added to the troubleshooting section
