### ISSUE TITLE
issue with 9.2 partial downgrade

### ISSUE THREAD

**Issue by SSJRyu1** [Plailect/Guide#536]
so I downgraded to 9.2 from my new 3ds on 10.7, but the menuhax didn't work afterward when I tried to access homebrew, I just get a must update message for browserhax and my OOT hax also seems to not work on what I assume is a partial downgrade, albeit I may have the wrong setup on OOTHAx now that the firmware is partial.

I am not really sure what to do at this point, so if you are able to help that would be great.

**Comment by pbanj** [comment]
you need to setup oothax for 9.2. it should then work
