### ISSUE TITLE
Use of Steelhax in DSiWare downgrade  

### ISSUE THREAD

**Issue by quantumcat1** [Plailect/Guide#537]
Getting Steel divers on 3DS #2 will not help because you will have to format before the system transfer, and you can't download free stuff without an NNID.

**Comment by jaxrogers2** [comment]
This is why Steel Diver Sub Wars is purchased (it's free) on 3DS #1 and then system transferred along with Fieldrunners.

**Comment by quantumcat1** [comment]
The guide says this: If 3DS #2 is on 11.1.0, you will also need the following
Download a legitimate copy of Steel Diver: Sub Wars

**Comment by Plailect** [comment]
???
