### ISSUE TITLE
Can't load SD card after CTR Transfer

### ISSUE THREAD

**Issue by nitzors** [Plailect/Guide#538]
So I completed part 2 successfully, backed out after the ctrtransfer and hit select to unmount my SD card. Now when I plug it back into my computer it's telling me I need to reformat it, am I missing something?

Edit: I've come to the conclusion that the card is defected and decided to shit out halfway through tyring to do this, in no way shape or form am I able to format the drive at all. So next comes a new question, is there anyway to continue the process with a new SD card? I currently have the 3DS running 2.1.0-4u but now I don't have any of the files on that I was using to do the hack. Do I just format everything and start from scratch? Thanks.

**Comment by Plailect** [comment]
Just recopy all the files to it that you were told to, don't format the device.
