### ISSUE TITLE
Though about sysNAND backup during part #2

### ISSUE THREAD

**Issue by Majickhat55** [Plailect/Guide#539]
Wouldn't it be a good idea to add a line after/before "Backup SysNAND to NANDmin.bin when prompted by pressing (A)" advising people to check the integrity of the NAND dumps prior to continuing with the guide? I know Decrypt9 checks the integrity upon a restore but it doesn't when dumping.

I think it would save a lot of people trouble from losing data, if they were prompted to validate the NAND dump before continuing.

**Comment by Plailect** [comment]
There isn't any point for users to remove the SD card in between them agreeing to the backup and the ctrtransfer proceeding. Decrypt9 verifies the backup as it is created.
