### ISSUE TITLE
Other *hax

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#54]
BArowserhax is patched on a lot of firmware...

**Comment by Plailect** [comment]
What?

**Comment by kitling** [comment]
> If you are between versions 10.6.0 and 10.7.0, you can find instructions for using ninjhax (requires Cubic Ninja) here, or instructions for using oot3dhax (requires Ocarina of Time 3D and either a powersaves or another 3DS which has the HomeBrew Launcher) here. Browserhax and menuhax were patched with 10.6.0 and will no longer work.

I think that's already covered.

**Comment by mariogamer2** [comment]
Yeah sorry
