### ISSUE TITLE
CTRTransfer 2.1.0 Error

### ISSUE THREAD

**Issue by souleater98** [Plailect/Guide#541]
I was following the guide and when I installed 2.1.0 on the latest version of Decrypt9, I got this:

Initializing SD card... success
Build: Decrypt9WIP (2016/09/19)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: not found
0x1B KeyX: not found
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: success!

You selected [Auto CTRNAND Transfer].

This feature writes to the SysNAND.
This may overwrite important data!

If you wish to proceed, enter:
<Left>, <Up>, <Right>, <Up>, <A>

(B to return, START to reboot)

Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin
Image size is: 794624000 byte

Step #0: Optional NAND backup
Press <B> to skip and continue without backup
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
NANDmin.bin
Creating NANDmin.bin ...
NAND dump SHA256: B5798252...
Store to NANDmin.bin.sha: ok

Step #1: .SHA verification of CTRNAND image...
Checking hash from .SHA file...
Step #1 success!

Step #2: Dumping transfer files
Searching for SecureInfo_A...
Found at 0E788000, size 273b
Creating B95C44CF_SecureInfo_A ...
Searching for movable.sed...
Found at 0E748000, size 320b
Creating B95C44CF_movable.sed ...
Searching for LocalFriendCodeSeed_B...
Found at 0E6D0000, size 272b
Creating B95C44CF_LocalFriendCodeSeed_B ...
Searching for configsave.bin...
Found at 0F258000, size 256kB
Creating B95C44CF_configsave.bin ...
Step #2 success!

Step #3: Injecting CTRNAND transfer image
Switching out NAND header first...
Auto CTRNAND Transfer: failed!

Press B to return, START to reboot.

**Comment by souleater98** [comment]
I rebooted the 3ds and now it stays on a black screen, doesn't do anything.

**Comment by Plailect** [comment]
You read "Auto CTRNAND Transfer: failed!" and thought to yourself "that can't be any kind of problem" and just rebooted?

Excellently done, you probably just bricked yourself.

Read [this](https://github.com/Plailect/Guide/wiki/Troubleshooting#ts_sys_down)
