### ISSUE TITLE
2.1 ctrtransfer issue

### ISSUE THREAD

**Issue by pbanj** [Plailect/Guide#543]
in part 2 the link to troubleshooting a failed transfer is now gone

**Comment by Plailect** [comment]
What exactly are you referring to?

**Comment by pbanj** [comment]
There use to be a troubleshooting link for people to click if the ctr transfer failed, It's gone. Had someone message me last night because his failed. I went to grab the link for him to read and it was gone. He was smart and didn't shut it off when it happened, so I was able to walk him through fixing it.

**Comment by Plailect** [comment]
Could you find it in an old commit? I don' t know what you're talking about.

**Comment by akirayuki** [comment]
I think he's talking about the 9.2 ctrnand transfer:

https://github.com/Plailect/Guide/wiki/9.2.0-ctrtransfer

**Comment by Plailect** [comment]
Searching the `Troubleshooting.md` file history for the phrase "ctrtransfer" does not yield what you're referring to

```
dev /mnt/e/3ds/Guide.wiki (master) $ git grep ctrtransfer -- Troubleshooting.md $(git rev-list --all)
Troubleshooting.md:9. Try following [9.2.0 ctrtransfer](9.2.0-ctrtransfer) starting on Step 4.
```

___

Searching `Part-2-(2.1.0-ctrtransfer).md` for the phrase "failed" yields no results

```
dev /mnt/e/3ds/Guide.wiki (master) $ git grep failed -- Part-2-\(2.1.0-ctrtransfer\).md $(git rev-list --all)
```
