### ISSUE TITLE
this doesnt work 107.211.140.065 ?

### ISSUE THREAD

**Issue by TsukiRyori** [Plailect/Guide#545]
i tried using this and it says i need to update fw to use browser any other dns i can use

**Comment by Davidosky99** [comment]
Once you opened the browser one time and it gave you the update prompt, the DNS won't save you. The DNS is now useless, you should have set it before you opened the browser as there is no way of removing the nag even with formatting. Use a hax game entrypoint now.

**Comment by TsukiRyori** [comment]
i did it before opening the browser but still same , anyway going to a game

**Comment by TsukiRyori** [comment]
i alsto tried pinging it in cmd and its request timed out

**Comment by mockatoy** [comment]
Just cause ping results in a time out doesn't mean its online, for all my
systems ICMP echo is disabled. (ping)

To confirm a DNS server is online use nslookup (
https://technet.microsoft.com/en-us/library/bb490950.aspx) and set the
server to the IP address of the DNS server in question (107.211.140.65)
The address is working fine for me.

Sorry Plailect as this is unrelated to the guide.

**Comment by Plailect** [comment]
Switched to use `104.236.072.203` instead

**Comment by TsukiRyori** [comment]
-_- it didnt work now i got the nag and bought oot3d instead
