### ISSUE TITLE
Suggestion regarding NTR CFW

### ISSUE THREAD

**Issue by sora10pls** [Plailect/Guide#546]
At the end of Part 3, Section VI, the user is told to download `ntr.bin` from [here](https://github.com/44670/BootNTR/releases/latest) which links them to the latest build of v3.2.

However, if the user is using a New 3DS, this version doesn't have video streaming included, and many users go through this entire guide just for that.

Perhaps have two separate links, one for Old 3DS ([v3.2](https://github.com/44670/BootNTR/releases/latest)) and one for New 3DS ([v3.4 Preview 2](https://github.com/44670/BootNTR/releases/tag/3.4preview2))? That way people can get the appropriate `ntr.bin` for video streaming, rather than having to do extra searches.

**Comment by Plailect** [comment]
I just changed it to the entire releases page
