### ISSUE TITLE
Health&Safety Dump: failed!

### ISSUE THREAD

**Issue by GreenMonsters** [Plailect/Guide#548]
I am having issues on **Section V - Injecting FBI**
I am on a N3DS Japan Set.
When I select Health&Safety Dump I am getting this error:

Code / Crypto: CTR-N-HACJ / Secure3
slot0x25Keyx not set up
This won't work on O3DS < 7.x or A9LH
Health&Safety Dump: failed!

**Comment by srwgin** [comment]
do you use gw downgrade to 4.x before
try to update to 11.1 then redump hs

**Comment by GreenMonsters** [comment]
Nope, it's a brand new N3DS and started on 9.7 and followed the guide. But was having issues with dumping HS.app when I got to **Section V - Injecting FBI**. And I am on 11.1 currently though.

**Comment by GreenMonsters** [comment]
After updating and restoring back to 9.1 a couple of times, I finally got it working for some weird reasons...
