### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ephzee** [Plailect/Guide#55]
Everything went great until Section VI of Part 5.  I had Deleted my emuNAND original.bin from the root of my SD Card.  I backed up my SD card.  I reinserted my SD card.  I hold Y on boot and just boot into RedNAND.
RedNAND is the only thing I can boot into no matter what button I hold on reboot.

**Comment by mariogamer2** [comment]
Whats the problem exactly?

**Comment by ephzee** [comment]
I can't boot into EmuNAND9 to format my SD.

**Comment by ephzee** [comment]
I can't boot into anything but RedNAND.

**Comment by Plailect** [comment]
Hold Y before starting the boot

**Comment by Plailect** [comment]
This is not the place for asking for troubleshooting help.

**Comment by ephzee** [comment]
I did hold Y.  Where can I ask for troubleshooting help?

**Comment by Plailect** [comment]
IRC, reddit, gbatemp, anywhere but here
