### ISSUE TITLE
Downgrade FIRM from 11.1 to 10.4

### ISSUE THREAD

**Issue by omegaburner** [Plailect/Guide#550]
My System: 
N3DS XL, 11.1.0-34E, FIRM 2.51-2

Problem: 
only downgrade FIRM to 2.51-0

Solution: 
First downgrade normally to FIRM 2.51-0
Then exchange Firmware and dgtools files for version 11.0
Do another downgrade to 2.50-11

worked for me
please update guide!

**Comment by Plailect** [comment]
I don't have the slightest clue what you did, but you didn't follow instructions. You should have used the dgTool zips provided as is, which will give you a 10.4.0 firmware (aka 2.50-11).

You went from 11.1.0 (2.51-2) to 11.0.0 (2.51-0), which isn't possible unless you did something I didn't tell you to do.

**Comment by omegaburner** [comment]
I followed the instruction and downloaded everything from the links and ended up with 2.51-0 everytime. 
https://gbatemp.net/threads/3ds-kernel-and-firm-version-please-help.442530/
I'm not the only one with this Problem.

After System Transfer
Downloaded dgtool + Firmware for 11.1
Used fieldrunners entrypoint and used downgrade to 10.4(after I did a backup of current firm)
After downgrade it showed that there wasn't any error but in the homebrew tool it was FIRM 2.51-0
I thought at first i did something wrong and formated my 3ds.
One week later followed every step from your guide again and still had the problem.
I found the link from gbatemp and it solved the problem.
