### ISSUE TITLE
9.2.0 downgrade N3DS stuck on 11.0.0

### ISSUE THREAD

**Issue by Black-Magician** [Plailect/Guide#551]
I am currently at the downgrade to 9.2, everything has been going well and I can open everything
however when I press (Y) to downgrade I get

Checking for am:u...
Did not get am:u handle!

Attemting svchax...
Initted svchax...

Innited services...
Checking for am:u...

Got am:u handle!

Beginning downgrade...

Updates installed; rebooting in 10 seconds...

however when i check for my system version it says I am still on 11.0.0-33U on both the system settings and the 3dsident

What's going on here?

**Comment by Plailect** [comment]
Delete and recopy the updates folder to your SD.

**Comment by Black-Magician** [comment]
I just retried it with replacing the updates folder on the SD card, it gave me the same problem.

**Comment by Ev1lbl0w** [comment]
Inject the NFIRM again to your NAND backup then flash it again to the 3DS (hardmod/dsiwarehax). Other people had this issue and redoing the injection part worked for them.

**Comment by Black-Magician** [comment]
that would be doing
Section VIV - Flashing 3DS #2's firmware (dsiwarehax)
again?

**Comment by Black-Magician** [comment]
I'm sorry I just don't remember where I injected the NFIRM into the NAND backup
