### ISSUE TITLE
Wrong 11.1 firm in "Old 3DS 11.1.0 to 10.4.0" pack

### ISSUE THREAD

**Issue by piratesephiroth** [Plailect/Guide#552]
yep it's wrong

**Comment by Plailect** [comment]
![image](https://cloud.githubusercontent.com/assets/16979510/18793258/e464422e-8187-11e6-9ca7-30aa8bba20d1.png)

?

**Comment by piratesephiroth** [comment]
I think the one for new 3ds was wrong as well

**Comment by Plailect** [comment]
What the hell are you talking about?

**Comment by piratesephiroth** [comment]
The 11.1 firm bin file is wrong (or was, if the file has changed in the last 10 hours).
FIRM swapped NANDs will result in a blue error screen.

I'm not sure if it was happening only on some consoles but at least it was an issue at least on some of them.
We had to dump new firm partitions with decrypt9.
