### ISSUE TITLE
DSiWare Downgrade - Question about N3DS

### ISSUE THREAD

**Issue by playful** [Plailect/Guide#555]
Hi all and thanks for the super guide for downgrading and installing arm9loaderhax,

**N3DSXL#1 (Source System) system transfer** -> **N3DS#2 (Target System)**  = worked and system transfered.

By any chance can I redo downgrading to 9.2 and installing arm9loaderhax on the N3DSXL#1, which would give me the opportunity to play online with both of 3DS's or also using two different NNID's at the same time? 
Seems like there is something linked between both 3DS's and blocking me to play e.g Monster Hunter, because everytime I try to create a room with N3DXL#1 and at the same time I try to join with N3DS#2, it keeps disconnecting one N3DS and an error code "006-0612".

So I basically just want to use both of N3DS normally with two different NNDID's.
N3DSXL#1 is a brand new one, so there are no any important stuffs on it. 

Is there a restore way?

Hope you guys understand, thanks in advance.

**Comment by jaxrogers2** [comment]
All you'll need to do is system transfer back from 2 to 1 after formatting 3DS #1. Once the transfer is complete, create a new NNID on 3DS #2.

**Comment by playful** [comment]
Aight, thank you so much.
