### ISSUE TITLE
DNS to block browser update nag not working

### ISSUE THREAD

**Issue by gauravg11** [Plailect/Guide#556]
I'm on 10.7.0-32U and trying to follow the guide. Using the given DNS and browser QR code I keep getting the following message: "The Internet browser cannot be used at this time"

This has been reported a number of times on the /r/3dshacks QA thread as well:
https://www.reddit.com/r/3dshacks/comments/548rc3/3dshacking_qa_general_sleep_schedule_edition/

**Comment by Ev1lbl0w** [comment]
AFAIK, you should have added the DNS before the browser could find out it was outdated. Otherwise, I think it's impossible.

**Comment by LuxXx** [comment]
I also get this message, but this is another message. I just think the DNS is down.

**Comment by gauravg11** [comment]
It was a brand new 3ds, browser launched for first time.

**Comment by Plailect** [comment]
I was misinformed and have removed those instructions.

**Comment by LuxXx** [comment]
The guide is now misleading for 10.7 users. Can't 10.7 users just use nonbrowser entrypoints?
