### ISSUE TITLE
Can't open Fieldrunners on 3DS#1

### ISSUE THREAD

**Issue by jeffdincht** [Plailect/Guide#557]
Did all of the steps, bought the game, deleted the .sav and pasted the downloaded .sav archive but the game just goes to a blackscreen.
I can listen to the main menu theme in the background but it's just black. Can't go back with Home button, just stuck in here. What can I do? 
My 3DS#1 were hacked with this guide, and i'm trying to use it to hack my New3ds, Already did with one New3ds and worked just fine, did the same steps, can't understand what's going on now...

**Comment by akirayuki** [comment]
Are you sure you injected the specific save for your region?

**Comment by jeffdincht** [comment]
Absolutely sure. Downloaded and tried to copy/paste twice from "Fieldrunners USA Region" since my O3DS (3DS#1) is NA.
Maybe if i buy another game? I'm just not doing it already because I want to really try whatever I need to do with this game, since i've done it before(when i Hacked one of my New3ds, and i'm trying to hack another New3ds), but now its not working.

**Comment by Armastan** [comment]
Try this: https://github.com/Plailect/Guide/wiki/Troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by youb62** [comment]
I m exactly in the same case! but for me it s the EUR region

**Comment by theocmath** [comment]
https://github.com/Plailect/Guide/wiki/Troubleshooting#twl_broken

**Comment by Plailect** [comment]
@theocmath that's 100% unrelated

**Comment by theocmath** [comment]
but it seem like there is something wrong with his twl partition.
one of my friend have the same case on old 3ds,and sloved by update luma and follow the troubleshooting.

**Comment by jeffdincht** [comment]
Is it safe to do without knowing this is the real problem? I'm about to try this tomorrow, when I get home. If it Works I'll just reply here.

**Comment by theocmath** [comment]
do you have a9lh on your old 3ds?

**Comment by jeffdincht** [comment]
Yup, did everything according to this guide here so, i believe its there xD I have my Nand.bin backup as well

**Comment by theocmath** [comment]
if you have one i think install those five CIAs would be save. and for safty reason maybe you can make a backup first.

**Comment by Plailect** [comment]
My apologies, I read it as he system transfered already and it won't work on the target 3DS.

You can try the CIA installations.

**Comment by jaxrogers2** [comment]
Yeah, sounds like a TWL error.
If you're doing this on redNAND or emuNAND though, this is normal. You will need to install the game (legit or not) on sysNAND in order for it to run in emuNAND or redNAND.
