### ISSUE TITLE
Injecting FBI to Health & Safety app error 

### ISSUE THREAD

**Issue by rouken09** [Plailect/Guide#559]
Hi, I really need help with this because I'm kinda stuck with this part of the guide and searching for answers in google does not really give a straight answer.

I'm currently on the Section V - Injecting FBI part, and I just can' dump the H&S app because it keeps giving the error - app0 not found or fragmented.

I think I messed up because I installed FBI before doing the guide to upgrade my o3ds to 9.2 using sysupdater and rxtools pasta mode.

So my question is, how do I fix the H&S app so that I can inject the FBI into it?

Also an unrelated question, if I restore the backup I made using the nand_emu.bin, will I lose the emunand/rednand I moved to the sysnand? I have GW emunand previously andI'm afraid of erasing it if I restarted the guide again. Thanks!

**Comment by Plailect** [comment]
https://github.com/d0k3/Decrypt9WIP/issues
