### ISSUE TITLE
(WIP) French

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#56]
- [x]
Home
- [ ] 
FAQ
- [ ] 
Troubleshooting
- [x] 
Get Started
- [x] 
OTP Info
- [x] 
NAND Size
- [x] 
Device Info
- [ ] 
Part 1 - Homebrew
- [ ] 
Part 2 - Downgrading
- [ ] 
Part 3 - RedNAND
- [ ] 
Part 4 - Getting the OTP
- [x] 
Part 5 - arm9loaderhax
- [ ] 
9.2.0 Update
- [ ] 
Region Changing
- [x] 
Donations
- [x] 
Credits
- [ ] 
3DS stuck (2.1.0...)
- [x] 
Hardmode downgrade
- [ ] 
Part 5 - a9lh & cake
- [ ] 
Part 5 - a9lh & AuReiNAND

**Comment by mariogamer2** [comment]
Why there is 22 things and not 21?

**Comment by Plailect** [comment]
I don't understand the question

**Comment by HoloryTV** [comment]
http://prntscr.com/apo94x
 3DS stuck (2.1.0...) is missing there

MarioGamer, je peux t'aider pour la traduction ?
On s'est croisé plusieurs fois sur GitHub et Logic-Sunrise.
Si tu as skype contacte-moi : HoloryTV

**Comment by mariogamer2** [comment]
Oui

On pourrait s'entendre sur diviser la tache en deux.

J'essaies de te contacter cette après-midi.

**Comment by Plailect** [comment]
Downgrade repeated failure page has been removed due to being unreliable and not working properly

**Comment by Plailect** [comment]
https://github.com/Ginkyway/Guide/wiki/Accueil
