### ISSUE TITLE
Typo in decrypt9 chart?

### ISSUE THREAD

**Issue by TLuigi003** [Plailect/Guide#561]
In the 10.7 and following versions in the "Browser" column it says(and links, which is the real problem) "Homebrew Launcher (No Browser)"
I suppose it is just a typo, but you should fix it to avoid confusion.

BTW, Thanks for the awesome guide

**Comment by Plailect** [comment]
It is not a typo, it is impossible to use browserhax on >=10.7.0 because of the forced browser update.

**Comment by TLuigi003** [comment]
My bad, Thanks for the info
