### ISSUE TITLE
Different error on DSiWare Downgrade.

### ISSUE THREAD

**Issue by Armastan** [Plailect/Guide#562]
After installing the public.sav I get this message (fieldrunners):
http://i64.tinypic.com/1z4cx1u.jpg
Should I proceed?

**Comment by jaxrogers2** [comment]
The error is related to the SD card not being inited by the hacked save. Try using a different SD card or redownload the hacked save and try to install it again.

**Comment by Armastan** [comment]
Changing the SD worked. Thanks!
