### ISSUE TITLE
[Suggestion - needs testing] Use Down (D-Pad) + L + R + B while turning on to delete Home Menu settings instead of taking the SD card out and deleting folders to avoid menuhax issues (black screens)

### ISSUE THREAD

**Issue by exegg** [Plailect/Guide#563]
So, in the guide, after a few downgrade steps we're recommended to delete de Home Menu extdata. I think this key combo, which is done while booting the console, can work for this purpose, since it would delete Menuhax as it restarts the Home Menu management. This extra step of deleting the folder in a PC wouldn't be required. I don't know if the combo is available in 2.1, but it should be.

![sin-titulo-1](https://cloud.githubusercontent.com/assets/19347211/18897121/4dbf3c68-84f5-11e6-9cd6-991d38f521b5.jpg)

**Comment by ihaveamac** [comment]
this also deletes home menu layouts and several other things the user probably doesn't want to lose. deleting SD extdata is the better option.
