### ISSUE TITLE
N3DS OTP-Less Method

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#564]
This is probably being worked on already, but I don't know for sure.

Since SafeA9LHInstaller has added an OTP-less A9LH version (separate from the regular version), the OTP-Less A9LH install method (New 3DS only) has now been confirmed as safe. To accommodate this, the guide would remain the same on Part 1, but Part 2 and 3 would have to be split up with old3DS and New3DS. The homepage would also have to be updated to mention this difference.

Also, this is a separate issue, but you might want to edit the "Can I keep my NNID?" question on the FAQ to account for DSiWare Downgrades.

**Comment by Plailect** [comment]
More work than just that has to be done in order to structure it properly. It's coming, just be patient.

**Comment by Plailect** [comment]
Done.
