### ISSUE TITLE
Access to OTP version of guide for N3DS is not available

### ISSUE THREAD

**Issue by samadsajanlal** [Plailect/Guide#565]
Please restore access to the steps to get OTP on a N3DS. Currently, only O3DS OTP and N3DS OTPless guides are available.

**Comment by Plailect** [comment]
1. Why?

2. Older commits.

3. You can do part 2 on n3ds if you really want

**Comment by samadsajanlal** [comment]
1) Because we get an OTP file with the other way, and that is supposedly more future proof than without it.
2) Wiki has no commits of previous versions - the oldest versions all reference OTPless. See https://github.com/Plailect/Guide/wiki/Part-2-(2.1.0)/_history  oldest commit is  	"otpless :D" 3 hours ago 	ead79e0 
3) I recall needing to fix the dumped firmware of a 2.1 system, maybe from a much older version of your guide. is that still required? No way to tell right now.

**Comment by Plailect** [comment]
The OTP is worthless for just about anything other than a9lh installation. "3DSafe" uses it arbitrarily, but that's a decision on the part of whoever wrote it, and it's not actually needed.

Clone the repo and `git checkout` and older commit.

It's done by Decrypt9 automatically.
