### ISSUE TITLE
System Updates

### ISSUE THREAD

**Issue by snyoz** [Plailect/Guide#568]
Hi @all,

I was successful with the whole tutorial progress and everything went well. thank u!
Now I wanted to create and connect a new Nintendo Network ID to my device (N3DS).
But to create the ID it requires to update my 3ds system again.

one short question:

will it be always safe to install system updates in future when someone has done this tutorial?
Or should I be aware of some processes?

Thank you!

**Comment by jaxrogers2** [comment]
Yes it's safe with A9LH installed. If you use any apps like NTR that have to be updated every time a new NFIRM or Home Menu comes out then you might want to wait until those applications are updated to support the new version.
