### ISSUE TITLE
region change, GodMode9 is not required now?

### ISSUE THREAD

**Issue by Jimmy-Z** [Plailect/Guide#569]
I followed the guide to do a JP->US region change and in the GodMode9 step, the byte @0x100 is already what I wanted(01), Decrypt9WIP did that?

**Comment by Plailect** [comment]
GodMode9 should only inject the SecureInfo in the image if it does not detect a9lh being installed. Do you have a New 3DS and by chance did you do the OTPless install?

**Comment by Jimmy-Z** [comment]
Yes it's a New 3DS, and I'm region changing an emuNAND, A9LH installed following your older guide, before ctrtransfer.

**Comment by Plailect** [comment]
If you region change an EmuNAND then it will use the existing SecureInfo_A inside the ctrtransfer image. The serial in the file will be from another console, but it shouldn't really matter. You can copy the SecureInfo_A file from your SysNAND to your EmuNAND then edit it, if you really want.

**Comment by Jimmy-Z** [comment]
Thanks for the clarifying.
