### ISSUE TITLE
NNID unlink?

### ISSUE THREAD

**Issue by daChosen** [Plailect/Guide#57]
First at all, thx for this awesome guide!
everything went fine, currently i'm on CakesFW and everything runs smooth.
My only problem is that i've bought a used O3DS from some random guy, is there a save way to unlink the old NNID? is it save to do a factory reset or does it destroy everything?? (dont know if this formats the sd card :D
Or is the id fixed to my console? 
greetings...

**Comment by mariogamer2** [comment]
NNID is unliked when formatting, yes.

But you will not be able to use software who are in the SD card.

**Comment by daChosen** [comment]
So formatting is the way to go, recopy sd backup and my CFW is still fine?
Then just create a new NNID and that's it? Or did i missed something...
thx for the help!

**Comment by Plailect** [comment]
Yes, that's it
