### ISSUE TITLE
A9LH Black Screen after DSiware Downgrade

### ISSUE THREAD

**Issue by MattLovesMax** [Plailect/Guide#570]
Hi, this guide is amazing but i ran into an issue and cant seem to solve it(Someone save me).

I have:
2DS with arm9haxloader(from the guide) 
N3DS(11.1.0-34)

goal: 
install arm9haxloader on my N3DS(11.1.0-34) via DSiware Downgrade.

issue:
Selecting SafeA9LHInstaller in homebrew gives me blackscreen.

What I did:
Followed the DSiWare Downgrade Guide via steelhax(no problem, **kernel** and **firm** both show up as 2.50-11)
Then it directed me to Part 3 because i dont need OTP since I have N3DS.
I did all the Prep work in Part 3(Section 1).
Then in Part 3(Section 2), I get into homebrew via Steel Diver: Sub Wars. I try to lunch the SafeA9LHInstaller and it gives me blackscreen.

Let me know, if you need more information.

Thank you,
Matt

**Comment by theocmath** [comment]
are you in9.1/9.2?

**Comment by MattLovesMax** [comment]
From DSiWare Downgrade Page:  Section VIV - Flashing 3DS #2's firmware
"Select "Downgrade FIRM to 10.4" and confirm to flash the 10.4.0 firmware bin to 3DS #2"

I am in 10.4. I been following the guide

**Comment by Plailect** [comment]
You're certain you have all the needed files in `/a9lh/`?

**Comment by MattLovesMax** [comment]
these are my files in a9lh:
firm0.bin, firm0_100.bin,firm1.bin,payload_stage1.bin,payload_stage2.bin,secret_sector.bin

**Comment by Plailect** [comment]
Did you downgrade to 9.2 like you were told? It doesn't work from higher versions.

**Comment by MattLovesMax** [comment]
I cant believe i missed that. I apologize, thank you for your help.
