### ISSUE TITLE
Luma Updater 6.3.1

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#571]
So I recently updated to Luma3DS 6.3.1-b3e3a293 using Luma Updater app on 3ds. After finished installing it booted to the Luma3DS screen and I enabled the functions on this guide:
Use the (A) button and the D-Pad to turn on the following:
"Autoboot SysNAND"
"Use SysNAND FIRM if booting with R (A9LH)"
"Show NAND or user string in System Settings"
"Show GBA boot screen in patched AGB_FIRM"
This may cause crashes for some injected GBA Virtual Consoles
If some games do not work properly, disable this option and try again
If you are using a New 3DS, you should also enable the following:
"New 3DS CPU" to "Clock+L2(x)"
This will increase the framerate of many games, but may cause instability in others
If some games do not work properly, disable this option and try again
Press Start to save and reboot
If it freezes, hold the power button until it shuts down, then continue with the instructions

For some reason I tried booting up the console holding R and it didn't bring me to the Hourglass9 or whatever it was like it used to. Am I missing something here? Should I just use the "Restore backup" option in Luma Updater?

**Comment by mockatoy** [comment]
If you followed the guide, to get in to hourglass9 would be holding start
on start up.
Holding select will bring up the Luma Configure screen.

**Comment by Gelums** [comment]
Oh you are correct! Thanks for the quick response, I am not sure why I thought it was R. Stupid mistake. Thanks!

**Comment by mockatoy** [comment]
Welcome! Have fun!
