### ISSUE TITLE
After configuring Luma some people get a blackscreen

### ISSUE THREAD

**Issue by JezRdz** [Plailect/Guide#573]
So in the tutorial i couldnt update because i got a black screen after the setup of luma(i wasnt the only person with this issue), i fixed the issue with restoring the backup from part 2 with hourglass, for some reason the tutorial didnt said to do this, so just leaving this so you guys add that to the tutorial

**Comment by maorninja** [comment]
N3DS or O3DS?

Also, what step?

**Comment by aosjtajojkdsjakdjkas** [comment]
I think I encountered this problem too. I am stuck midway through part 3 section 3. I was on an old 3ds 10.2.0U without any previous hacks on it. I installed arm9 after doing everything in the preconfig section. I then booted in while holding select, and I can access luma's options. However, whenever I hit start to save my settings (the 4 I was told to activate in the guide) luma never properly shuts the device down, and on bootup I am greeted by a never-ending black screen. I can still get into luma's options by holding select on startup, but this seems to be all I can do for now.

**Comment by JezRdz** [comment]
this part on Section III

"4. Press Start to save and reboot
If it freezes, hold the power button until it shuts down, then continue with the instructions

5. Update your 3DS again by going to System Settings, then "Other Settings", then going all the way to the right and using "System Update" "

btw i was using an old 3DS, i fixed the problem as i said with just restoring the backup i made on Part 2, i think thats what i was supossed to do after configuring Luma but for some reason the tutorial dont said this, hope it helps

**Comment by Plailect** [comment]
Added instructions for this
