### ISSUE TITLE
KOR/CHN/TWN New 3DS can now be supported (kind of)!

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#574]
Since the hardware method for A9LH has been released here (http://douevenknow.us/post/151129092928/throwback-k9lhax-by-bruteforce), any console on 9.6 can get A9LH with the hardware method. This method would probably not be included in the guide, as it is very complicated and requires a lot of hardware, but it does make 9.6 KOR/CHN/TWN New 3DS support and 9.6 old3DS KOR/CHN/TWN support possible. Since these regions shipped on 9.6, these units cannot be updated at all, except for KOR which can be updated up to 10.7 or below and then downgraded to 9.6 from the Homebrew Launcher.

**Comment by Plailect** [comment]
This is not a new method, it's been public since early 2016. There still is no public software or specific instructions to do this.
