### ISSUE TITLE
GBA VC Save lost 

### ISSUE THREAD

**Issue by Luciano-Gert** [Plailect/Guide#575]
If you previously used menuHax + emuNand and has GBA VC games installed, be aware that these games save the progress in SysNand. So, when the guide prompt you to move your contents from a previous emuNand to Sysnand, you lose all GBA VC saves. 

The guide should, **at least**, alert people about this, or link to a section where they can make a backup of these saves. 

Recover these saves are really boring and time consuming.

**Comment by Plailect** [comment]
Added temporary warning, will add backup steps soon.

**Comment by jaxrogers2** [comment]
Yeah Decrypt9 can back up GBA saves, but you have to do it individually since the save backup feature for GBA only backs up the last played GBA game, so it would take a lot of rebooting to get all of the GBA saves backed up.

**Comment by pbanj** [comment]
iirc you can dump the entire partition with decrypt9. its how we use to move emunand over before keep a9lh was added. might be easier than dumping each games save

**Comment by pbanj** [comment]
ya agbsave dumb and inject in decrypt9. would be a hell of a lot quicker for people

**Comment by dark-samus** [comment]
@pbanj agbsav is a temporary storage place for only a single save. GBA saves end up on the SD card, not in agbsav permanently
