### ISSUE TITLE
Black Screen with Fieldrunners

### ISSUE THREAD

**Issue by Gusanito** [Plailect/Guide#576]
After transfering the game to the New 3ds with version 11.1 from the Old 3ds also in 11.1 and open the game and then clicking on "Scores" I get everytime a black screen. I've done all steps many times but still getting this error.

**Comment by Plailect** [comment]
You used the correct region?

**Comment by MrDarius125** [comment]
when you downgrade it  it may not boot if that happens shut it down wait like 1 minute power it on without the sd wait like 10 seconds then hold the power button for 3 second then the normal power off menu shold apper click the home button and it should work then just plug the sd card back in and install arm9loaderhax

**Comment by Gusanito** [comment]
Yes, I've use EUR, which is for my region

**Comment by Plailect** [comment]
Almost certainly user error as this has been tested many times, you'll need to do it again.

**Comment by Gusanito** [comment]
I did it two times :(
