### ISSUE TITLE
Section II - Part 2 Freezing

### ISSUE THREAD

**Issue by rb-26** [Plailect/Guide#578]
Hi,

When I visit the URL it starts to load then freezes. I have tried around 5-6 times with the same issue each time. Am I missing something?

Thanks in advance.

**Comment by Plailect** [comment]
Part 2 does not even have a Section II, what are you talking about?

**Comment by rb-26** [comment]
Apologies, I should have been more clear.

Part 3 - A9LH
Section II
Part 2

_Do the steps for installing arm9loaderhax on your device:
Old 3DS
You should be on 2.1.0
Go to http://dukesrg.github.io/2xrsa.html?arm11.bin on your 3DS_

**Comment by Plailect** [comment]
Do the troubleshooting steps.

**Comment by rb-26** [comment]
Thanks for the useless help. I obviously wouldn't have posted if I hadn't already tried them.
