### ISSUE TITLE
Will system transfer affect region changing?

### ISSUE THREAD

**Issue by anth4m** [Plailect/Guide#583]
If I want to downgrade a brand new N3DS (11.1) for A9LH with DSiWare hax, and I have to do system transfer. Will this affect accessing to a different region e-shop at all?

**Comment by Armastan** [comment]
What do you mean? 

You can't system transfer with consoles from different regions.

**Comment by anth4m** [comment]
I will probably do a region change AFTER A9LH's installed. But I have to do the system transfer to make it downgraded.

**Comment by Plailect** [comment]
No.
