### ISSUE TITLE
Fieldrunners loads blank screen on 3DS #1

### ISSUE THREAD

**Issue by anthus1** [Plailect/Guide#588]
Hello all. Thanks for making these tools, and allowing us to viciously hack into our 3DSs. :dagger: 

I have been following the steps from the very first section, and have managed to get this far, but I have run into my first process-stopping issue. The problem lies within section 2, preparing the save. I bought Fieldrunners, and did the steps to get the public.sav onto the system, but when I boot up the game, it just goes to a black screen. I have to do a hard power-off to get out of it. Oddly enough, you can still hear the home menu music, if that matters.

I have tried my own trouble shooting which included uninstalling, and reinstalling the game, and removing public.sav, but even with a clean download, and no modifications, the game still won't load. I'm afraid I won't be able to finish the steps to make it so I can mod my other, -new- 3DS XL which is version 11.1.X. The 3DS in question is an original launch 3DS, and I have done everything in part 2, including upgrading to the latest firmware, so I'm hoping you guys can help me out here.

Any help is greatly appreciated, thank you for your time :)

**Comment by CyHo** [comment]
https://github.com/Plailect/Guide/wiki/Troubleshooting#after-system-transfering-steelhax-it-crashes-to-a-black-screen-on-3ds-2

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/wiki/Troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide
