### ISSUE TITLE
3ds wont turn on

### ISSUE THREAD

**Issue by checa2321** [Plailect/Guide#589]
Hi, i was doing the part 3 tutorial and when i was doing the update it gives me an error, so i follow the guide to do the update but when i was going back to the 3ds to put the sd card there's a blue light that blinks once and do nothing, so i press the power button again and the blue light blinks once and thats it unless i press the power button but it keeps doing the same thing, what can be the problem? 

![img_8622](https://cloud.githubusercontent.com/assets/20796280/19137928/a7a433d6-8b45-11e6-898f-a8fc35220473.GIF)

**Comment by iuzwpr2p39rh7w** [comment]
https://github.com/Plailect/Guide/wiki/Troubleshooting#black-screen-on-sysnand-boot-after-installing-arm9loaderhax

**Comment by checa2321** [comment]
the 3ds does not have the sd card inside....

**Comment by Plailect** [comment]
Perhaps try reading?

>You will no longer be able to boot without the SD card in, that is normal.   

 \- [Part 3 - A9LH](https://github.com/Plailect/Guide/wiki/Part-3-(A9LH))

**Comment by checa2321** [comment]
I know that, all i am saying is that with the sd card inside or without it the ds just blink the blue light once like in the GIF and dont do anything more

**Comment by checa2321** [comment]
Its like the ds does not have battery or something like that but the only light that flash is the blue one and I let it charging all night long so i dont think the battery its the problem, also i opened to remove the battery but nothing.

**Comment by checa2321** [comment]
Lol guys ok nevermind now this thing is ok, i feel like an idiot, thanks anyways
