### ISSUE TITLE
SD is not formatted for EmuNAND, EmuNAND backup failed!

### ISSUE THREAD

**Issue by TheAzure289** [Plailect/Guide#59]
I'm using a 16 GB SANDISK SDHC because I ran out of room on nintendo's default 2gb card. I moved the whole process (content of my 2gb card) of this guide: https://github.com/Plailect/Guide/wiki/Part-4-%28Getting-the-OTP%29 to a new folder on my desktop then moved it to the memory card listed above. Was that ok to do? 

I made sure to format the card first to 32k using this tool linked by Plailect : http://www.ridgecrop.demon.co.uk/index.htm?guiformat.htm

Help me, been up all night struggling with browserhax lol...

Edit: I'm using a 2ds for all of this. Won't take another step with out your say so.

**Comment by Plailect** [comment]
You can't just copy all the files since emunand is on a separate partition. Use [emuNAND Tool](https://gbatemp.net/threads/emunand-tool-release-and-support-thread.359239/) to move it between SD cards.
