### ISSUE TITLE
DSIWare Downgrade, small issue / question

### ISSUE THREAD

**Issue by mozvip** [Plailect/Guide#591]
In the DSIWare downgrade section :

Section I - Prep Work
Use a save manager to backup any saves you care about on 3DS #2 (it will be formatted!)

**I think you want to refer 3DS #1 here, not 3DS #2, right ?**

**Comment by Terathiel** [comment]
No.

While 3DS 1 will be formatted in the transfer, a) all of the saves on 1 will be transferred to 2, and b) you should probably have a NAND backup of 3DS 1 as well. 3DS 2's saves, on the other hand, will just be plain gone forever if you haven't backed them up yourself.

**Comment by mozvip** [comment]
OK thanks. The question that remains then is how I can use this save manager on 3DS #2 when it is not hacked or anything. Thanks again for your work!

**Comment by Plailect** [comment]
JKSM has a .3dsx
