### ISSUE TITLE
internet connection

### ISSUE THREAD

**Issue by Ento0n** [Plailect/Guide#595]
After setting up the hack, I wasnt able to get into the internet menu, so I followed the troubleshooting guide. This made the menu work but it is pretty sure a dsi menu. The solution on the top screen isnt right and I cant connect to WPA/WPA2, only WEP is acceptable.

**Comment by Plailect** [comment]
This is almost 100% unrelated to this guide.

**Comment by Margen67** [comment]
You are using the DS connections menu.
You need to use internet settings.
