### ISSUE TITLE
"could not access SD card" during system transfer 

### ISSUE THREAD

**Issue by hypershun** [Plailect/Guide#596]
Hi I'm currently using the guide to downgrade an old 3DS XL using an old 3DS I've gotten to the system transfer section and its giving me "could not access SD card" when its on the moving Nintendo DSIWare to the SD card part

please help 
thanks

**Comment by sora10pls** [comment]
Is write-protection enabled?

**Comment by hypershun** [comment]
no

**Comment by Plailect** [comment]
This is not a help forum.
