### ISSUE TITLE
OTPLess A9LH Install may cause brick

### ISSUE THREAD

**Issue by gnmmarechal** [Plailect/Guide#598]
It seems yet another person randomly bricked with OTPless SafeA9LH installer.

I recommend the guide to be reverted back to the tried&true OTP-based installation method.

I have no idea how to submit PRs to a wiki in GitHub, however.

**Comment by mockatoy** [comment]
I have done 8 units since it came out and had no issues :(

**Comment by Plailect** [comment]
This was due to SD card corruption, which is now checked for in SafeA9LHInstaller 2.5.1, which will be added to the guide shortly.
