### ISSUE TITLE
Page 3 Emunand

### ISSUE THREAD

**Issue by Nickelbawker** [Plailect/Guide#6]
Spent about 4 hours on a 9,8.0 2DS got it to 9.2.0. Followed everything correctly slowly and carefully. The sysNAND folder was NOT displayed when I ran the system update at the end of it and I'm positive I was on emuNAND yet with nintendos newest update it still found and over wrote sysnand now my 3DS is ruined and can't be hacked without ocarina of time. This is seriously unfortunate.

**Comment by Plailect** [comment]
System settings completely reboots your console when you exit either it, or enter and exit the data management menu which expressly says "your sonsole will be rebooted."

Rebooting the console places you on SysNAND.
