### ISSUE TITLE
error while downgrade to 9.2.0

### ISSUE THREAD

**Issue by fuba777** [Plailect/Guide#600]
hello,

while downgrading from 9.9.0 to 9.2.0 i got an error and had to power off. No i cant boot again. With sd card inserted i only get a black screen and without i can boot but when i start browser (delete cookies and settings) and navidate to url (yls8...)  i get an error, that an error occured with my software title....

what to do?  ;(

**Comment by Committee** [comment]
Probably an incomplete downgrade, does it show 9.2 as the firmware in system settings?

**Comment by fuba777** [comment]
yes it shows 9.2.0-20E

how can i solve this so that i have a full downgrade to 9.2.0?

**Comment by PsikoBlock** [comment]
If it crashes on the gray screen, you can try downloading the correct ropbin from [the Homebrew Launcher webpage](http://smealum.github.io/3ds/) and putting it on the SD card as "browserhax_hblauncher_ropbin_payload.bin"

**Comment by fuba777** [comment]
works now. thanks
