### ISSUE TITLE
Black Screen right after SafeA9LHinstaller

### ISSUE THREAD

**Issue by red-storm** [Plailect/Guide#601]
Hello

I Have a N3dsXL FW 9.4 with menuhax, i followed all the steps on the guide, as soon as i start SafeA9LHinstaller to begin the process, all it shows is a black screen and nothing happens, and i have to reboot the 3ds again...

What to do ?

Thank you

**Comment by hunteralves** [comment]
Hi mate. Did you learn what happened? I'm running on the same problem

**Comment by Ev1lbl0w** [comment]
_"If you are above the version 9.2.0, continue to **9.2.0 Downgrade**"_
