### ISSUE TITLE
Cant mount sd card

### ISSUE THREAD

**Issue by red-storm** [Plailect/Guide#602]
After a succesful downgrade from 9.4 to 9.2 (New 3dsXL) i launch SafeA9LHInstaller, after i press select for a full i install i get the message "Cannot mount the sd card... press any key to shut down" 
what to do ?

Thanks

**Comment by CyHo** [comment]
I think need to change another sd card or format the sd card you use. Do a backup before you do it

**Comment by DeckOfNoobs** [comment]
How are you booting SafeA9LHInstaller? That may be causing the issue.

**Comment by Plailect** [comment]
Check your SD card for errors, or backup the files and format it.
