### ISSUE TITLE
Typo/logical error on Homebrew Launcher/Browser page

### ISSUE THREAD

**Issue by PsikoBlock** [Plailect/Guide#604]
Hi,
I think I found an error. Shouldn't you first copy the files before putting the SD card back? Not a big deal, but could confuse some people.

> 1. Copy the contents of the starter.zip to the root of your SD card**, then put the SD card back into your 3DS**
> 2. Create a folder named files9 on the root of your SD card if it does not already exist
> 3. Copy the Decrypt9WIP folder from the Decrypt9WIP zip to /3ds/ on your SD card

**Comment by Ev1lbl0w** [comment]
What? I don't understand you.

The instructions says to copy the contents of the .zip file to the root of the SD card, and then putting it back on the 3DS.

I'm pretty sure it's a clear instruction.

**Comment by james-d-elliott** [comment]
He means step 2 doesn't seem logical considering step 1 tells you to put it back in.

**Comment by Ev1lbl0w** [comment]
Oh ok, I got it now. Sry for misunderstanding.

**Comment by Plailect** [comment]
Fixed.
