### ISSUE TITLE
Decrypt9 not available

### ISSUE THREAD

**Issue by fuba777** [Plailect/Guide#605]
Hi,
i just followed this tutorial to install homebrew on my DS.

But after this i can't find the Decrypt9 App in Homebrew Launcher anymore? How can that be?

**Comment by Armastan** [comment]
If you followed the guide your 3DS should be on 11.1, so you can't launch Decrypt9 from the Homebrew Launcher. You'll need to download the latest version of Decrypt9 and rename the .bin file according to Luma3DS' payload chainloading: https://github.com/AuroraWright/Luma3DS/wiki/Other-features-and-notes#payload-chainloading

**Comment by fuba777** [comment]
this works, thanks.

if i now open "NCCH Padgen" i get the message:

opening seeddb.bin ...
could not open seeddb.bin
9.x seed crypto will fail
opening ncchinfo.bin ...
could not open cchinfo.bin
NCCH Padgen: failed

;(
