### ISSUE TITLE
I'm confused

### ISSUE THREAD

**Issue by blargheon** [Plailect/Guide#609]
When doing the final step to configure Luma3DS (updating the 3DS), it updated my system to the newest firmware. Was this supposed to happen, or was that an error?

**Comment by Margen67** [comment]
You're supposed to update after installing A9LH.

**Comment by Ev1lbl0w** [comment]
It's stated in the Guide:

"_Update your 3DS again by going to System Settings, then "Other Settings", then going all the way to the right and using "System Update_". **_Yes this is safe, stop asking about it._**"

**Comment by pedrxd** [comment]
yes is necesary, dont' worry,  i do that 30 minutes ago and all go correctly.

PD: Thanks to all developers that do this possible, is a very hard work.
