### ISSUE TITLE
Can i update to 9.2?

### ISSUE THREAD

**Issue by CyHo** [Plailect/Guide#611]
Now my console is in 7.2, and i wanna update to 9.2, can i use the 9.2.0 ctrtransfer directly?

**Comment by snowcrshd** [comment]
Why would you want to update to 9.2? Do you wish to unlock your 3ds?

AFAIK, if you are on firmware 7.2 you would only have to use Decrypt9 and would be good to go.

**Comment by ihaveamac** [comment]
no need to go to 9.2, unless you don't have a browser, then you'd go to 9.0 - 10.7 and downgrade to 9.2 (if you updated above 9.2).

**Comment by CyHo** [comment]
just curious because Decrypt9 can downgrade to 2.1 using Ctrtransfer, if i using the 9.2 Ctrtransfer with using Decrypt9, will it become version 9.2 with no problem?

**Comment by snowcrshd** [comment]
I don't see why that should not work.

You could try backing up your SysNAND and then doing the Ctrtransfer to 9.2.
If something goes wrong, you have a way to restore your system to 7.2

**Comment by ihaveamac** [comment]
it can, though I don't see why you would want to do that.

**Comment by CyHo** [comment]
ok, Thanks alot, haha

**Comment by ihaveamac** [comment]
why did you want to go to 9.2 anyway?

**Comment by CyHo** [comment]
just wanna give a try, haha, i mod alot of console already, just not sure whether i can do like that or not
