### ISSUE TITLE
10.7 problem

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#612]
Part 1 (ARM9) lists 10.7 browser as "Homebrew Launcher (No Browser)".  I thought that browserhax works on 10.7 as long as the browser version check has never been triggered in the past, and you set up the DNS so that it won't be triggered now.

**Comment by jaxrogers2** [comment]
Tubehax DNS no longer works, so browserhax can't be used on 10.7 unless you go through a LOT of hassle with your router DNS settings.

**Comment by theocmath** [comment]
If your enter browser as fast as possible after console booting, there is still a low successful rate to by-pass the version check even if it has been triggered. But the successful rate is lower than 10% so it's not recommend to do.
