### ISSUE TITLE
Re-wording suggestion for updating A9LH

### ISSUE THREAD

**Issue by sora10pls** [Plailect/Guide#613]
Now that `release.7z` has the following files:
- `payload_stage1.bin`
- `payload_stage1.bin.sha`
- `payload_stage2.bin`
- `payload_stage2.bin.sha`

The instructions should say:
"Copy _the contents of_ the arm9loaderhax zip to `a9lh` folder on your SD card".

This is only in regards to the [Updating A9LH](https://github.com/Plailect/Guide/wiki/Updating-A9LH#instructions) page. [Part 3](https://github.com/Plailect/Guide/wiki/Part-3-(A9LH)#section-i---prep-work) has the wording down correctly.

![image](https://cloud.githubusercontent.com/assets/17801814/19395884/f5d1f876-920d-11e6-857a-a3270dffd117.png)

**Comment by Plailect** [comment]
Fixed
