### ISSUE TITLE
Unable to copy DSiWare save from 3DS #1 to 3DS #2

### ISSUE THREAD

**Issue by BatteryPine** [Plailect/Guide#614]
I'm stuck on this part of the troubleshooting guide: https://github.com/Plailect/Guide/wiki/Troubleshooting#ts_dsiware

When I get to step 5, the DSiWare doesn't show up in the menu when I put the microSD card from 3DS #1 to 3DS #2. When I manually move the DSiWare data from the microSD card in 3DS #1 to the microSD card in 3DS #2, a question mark icon is displayed instead of the game's icon, there's no name given to the DSiWare, and the DSiWare has a block size of 0. I'm able to copy back the DSiWare on 3DS #1, but even after restoring my previous NAND backup and getting the NNID back on 3DS #1 I can't copy the DSiWare to 3DS #2.

EDIT: If it helps, 3DS #1 is a N3DSXL and 3DS #2 is a N3DS from the Super Mario 3D Land bundle.

https://i.imgur.com/ydhPrYF.jpg
https://i.imgur.com/SHoyzrc.jpg

**Comment by Plailect** [comment]
I've amended https://github.com/Plailect/Guide/wiki/Troubleshooting#ts_dsiware, try again.

**Comment by BatteryPine** [comment]
I tried again and it didn't work.

**Comment by Plailect** [comment]
Delete the game and redownload it, then try the troubleshooting again.

**Comment by BatteryPine** [comment]
I deleted the game from 3DS #1, redownloaded it through the E-Shop, and went through troubleshooting again and it didn't work. I'm not sure if this is completely helpful, but when I moved the save data manually, I moved it from "Nintendo 3DS\2e35beedb07b3482f0bb9ace2d9a9b0b\0fa400e94707b885534530340002544d\Nintendo DSiWare" to either "Nintendo 3DS\d750d6171cf1ca8bd4bb516b436ce678\cdd300f54780432a534c333200035344\Nintendo DSiWare" on the microSD card from 3DS #1 or to "Nintendo 3DS\d750d6171cf1ca8bd4bb516b436ce678\41a700f94707bd13534530340002544d\Nintendo DSiWare" on the microSD card from 3DS #2. Also, when I called Nintendo to transfer the NNID back to 3DS #1 they stated that the pre-installed software on 3DS #2 would remain on 3DS #2.

**Comment by nedron92** [comment]
Maybe I can help. 
Did you restore a backup on 3DS#1 right before the system-transfer?
If yes, than you should be able to exchange the saves.
From 3DS#1:/Nintendo 3DS/<32-char-id>/.... to 3DS#2:/Nintendo 3DS/<same-32-char-id-like-3DS#1>/...

Or easily swap the sd-cards, that also should be possible. :)
