### ISSUE TITLE
Can't do system update after installing arm9

### ISSUE THREAD

**Issue by l11on** [Plailect/Guide#615]
I tried on 2.1 and got error, then i restored 9.2 nandmin and still can't update, any recommendation ?

**Comment by Margen67** [comment]
Are you blocking updates on your router or using a DNS like tubehax?

**Comment by l11on** [comment]
I'm not using any DNS, I'm on auto-obtain DNS. I guess i will report again tomorrow after trying to update from another router.

**Comment by pbanj** [comment]
If you have an updates folder on the SD card delete that.

**Comment by CyHo** [comment]
Pls update to 9.2 with using ctrtransfer

**Comment by l11on** [comment]
Sorry it looks like it was my connection, there's something wrong with it. Tried on other WiFi and worked, sorry for bringing this up.
