### ISSUE TITLE
After selecting downgrade FIRM to 10.4, and trying to reboot the console...

### ISSUE THREAD

**Issue by blargheon** [Plailect/Guide#617]
After selecting downgrade FIRM to 10.4, and powering off the console to reboot it, I found that the console will not boot back up. This is a New 3DS, on 11.1.0-34U by the way.

Edit 1: This is in Section VIII of the DSiDowngrade guide, btw.

Edit 2: In order to try and salvage it, I tried replacing the F0F1_N3DS.bin in the dgTool folder. This, obviously didn't work.

**Comment by blargheon** [comment]
This is in Section VIII of the DSiDowngrade guide, btw.

**Comment by blargheon** [comment]
In order to try and salvage it, I tried replacing the F0F1_N3DS.bin in the dgTool folder. This, obviously didn't work.

**Comment by Davidosky99** [comment]
Did you use the right files on the first try?

**Comment by blargheon** [comment]
Yes, I think I did. Maybe it could have been that I had extra files on the console's microSD card?

**Comment by Plailect** [comment]
Boot with the SD removed

**Comment by blargheon** [comment]
I've done this. Still doesn't work. Soooo, hardbrick?

**Comment by Plailect** [comment]
Hardbrick. 

Did you run this on an a9lh device?

**Comment by blargheon** [comment]
I had previously installed a9lh on it, but I formatted the n3ds. However, I did have the a9lh files on the sd card.

**Comment by james-d-elliott** [comment]
If the device powers on for a moment then shuts off (blue light on, then off) try putting the arm9loaderhax.bin from Luma3DS onto the root of the SD.  If you previously had A9LH on there then a format doesn't remove it. You have to use the SafeA9LHInstaller to remove it from memory.

**Comment by pbanj** [comment]
He wrote garbage to his nand, he will need a hardmod to fix this

**Comment by Plailect** [comment]
Formatting your device does not remove A9LH, and your FIRM partitions were modified. You wrote garbage to your FIRM partitions and will need a hardmod.

**Comment by blargheon** [comment]
RIP that n3ds, basically.

On 23/10/2016, at 05:18 a.m., "pbanj" <notifications@github.com<mailto:notifications@github.com>> wrote:


He wrote garbage to his nand, he will need a hardmod to fix this

-

**Comment by blargheon** [comment]
If it keeps on (the light), the screen doesn't turn on, and it only powers off when I turn it off using the power button, is there no saving it?

On 22/10/2016, at 07:18 p.m., "James Elliott" <notifications@github.com<mailto:notifications@github.com>> wrote:


If the device powers on for a moment then shuts off (blue light on, then off) try putting the arm9loaderhax.bin from Luma3DS onto the root of the SD. If you previously had A9LH on there then a format doesn't remove it. You have to use the SafeA9LHInstaller to remove it from memory.

-

**Comment by james-d-elliott** [comment]
@blargheon You will need to hardmod, it only requires a bit of soldering technique really. Pretty sure there is a link in the guide in the 11+ downgrade section.
