### ISSUE TITLE
About New3ds done A9LH OTP file

### ISSUE THREAD

**Issue by david-zzj** [Plailect/Guide#619]
My new3ds have done A9LH use the new method (no need to downgrad 2.1) .
But after finish it, i found TF card [a9lh] Folder don't contain OTP.BIN file.....
I remember before that , OTP file is in the [a9lh].
Now i want to know, is it  necessary to  obtain this file after i done A9LH ? And how ?

**Comment by ihaveamac** [comment]
the new method for setting up a9lh on New 3DS doesn't use OTP, hence "otpless". if you really want your console's OTP, you need to go to 2.1.

**Comment by david-zzj** [comment]
thanks, when i done a9lh. OTP file is useless ?
what situation i need this files ?

**Comment by Plailect** [comment]
You don't need it.
