### ISSUE TITLE
JPN ESHOP CANT ENTER

### ISSUE THREAD

**Issue by Ivoyko** [Plailect/Guide#620]
After this process, only New 3DSs which have never accessed the eShop before and any Old 3DSs will be able to access the eShop after creating a new NNID on their new region. Region changed New 3DSs that have already accessed the eShop on their original region cannot create a new NNID and access the eShop on their new region!
I have a OLD with region changed and i cant enter D:

**Comment by Committee** [comment]
Have you tried creating a NEW NNID for the JPN Eshop?
