### ISSUE TITLE
Brick with OTPless in New 3DS

### ISSUE THREAD

**Issue by Keizel** [Plailect/Guide#621]
I follow the complete tutorial of Plailect and I made OTPless in my New 3DS: Brick.

I have a copy of sysNAND and with HardMOD I will can recover the New 3DS.

**NOT USE OTPless YET**

**Comment by DeckOfNoobs** [comment]
"NOT USE OTPless YET"
wut

Also, what did you do during the installation? That might help find out what caused the brick.

**Comment by Keizel** [comment]
Only follow the guide. When I try power on the New 3DS, only LED display on blue but not load payloads, Luma3DS, etc. Without or With SD, the same result. Total brick.

**Comment by james-d-elliott** [comment]
OTPless has been used by many. Either there was a mistake when following the guide or something device specific caused your issue.

May want to see if you can get Luma to open with holding select. Also can try booting with nothing in your Nintendo DS folder on the SD, back it up first.

**Comment by Keizel** [comment]
"May want to see if you can get Luma to open with holding select. Also can try booting with nothing in your Nintendo DS folder on the SD, back it up first."

I tested it and nothing: brick.

**Comment by Margen67** [comment]
>bricks
>uses barely eligible english
>telling people not to use it

seems legit

**Comment by Keizel** [comment]
Sorry, English is not my mother tongue.

I was trying to put Arm9LoaderHax with the method of OTPless saying Plailect guide, having made a downgrade from 9.6.0 to 9.2.0-XXE, I tried to put Arm9LoaderHax directly with program SafeA9LHInstaller 2.5.1 and the following payloads: https://github.com/AuroraWright/arm9loaderhax/releases/tag/17%2F10

After running Ninjhax 2.7 9.2 sysNAND in my New 3DS european version, I pressed Select for full installation of Arm9LoaderHax with the program. He was a blackscreen, and after a few seconds I turn off the console.

Now the console will not start any payload and does not operate with or without SD, I also tried to remove battery among other things and the result is the same: the LED is blue and not turn anywhere else. Recovery mode has not fixed the problem: the recovery cannot even boot.

**Comment by Jerry-Shaw** [comment]
Weird. I just did it a day ago with my JPN New 3DSLL, and was successful. Downgrade from 10.7 to 9.2, did it twice because there was a partly downgrade progress, and than did the OTPless A9LH. All was successful.

**Comment by Plailect** [comment]
SD corruption is the only known way this can happen, and the guide instructs you to only use good ones.

**Comment by Keizel** [comment]
My SD is NEW. I bought a new SD only for do this method: the SD works correctly, I can downgrade since 9.6 to 9.2.

**Comment by theocmath** [comment]
But Aurora said in the 2.5.1 installer that"SD card is no longer initialized after the reboot during OTPless installs (might fix corner case bricks where the SD is corrupted)"

**Comment by cubecubec** [comment]
i just have this kind of issue after i UPDATE ARM9LOADERHAX.i think i can help you,hope it works,

my situation is,i updating new version of arm9loaderhax,all was fine,but after i installing arm9loaderhax,i reboot,then its on,only blackscreen,try to load hourglass,or luma setting,all failed,only blackscreen.and then i read troubleshooting,using plailect guide see below.

Try this https://mega.nz/#!YxMiGDhB!VZLv2XPSqFFzEhf4kGMXAdQtSpIGvnp2vu2W1j4o7cc/

i read the troubleshooting section,and i try that payload,and it works,means my 3ds not brick,just the payload failed.change another payload like older payload. hope it works.

try using another arm9loaderhax.bin file.

**Comment by cubecubec** [comment]
strange thing happen to me as well,i did the same on plailect guide update arm9loaderhax,and i use all new file i just download from the content,after press select on installing safeA9LH,i reboot and yes,only blue light on 3ds,but black screen.something must wrong in the compability of my old arm9loaderhax.bin won't load after i update into new update of arm9loaderhax.

**Comment by Keizel** [comment]
> Try this test payload:
https://mega.nz/#!YxMiGDhB!VZLv2XPSqFFzEhf4kGMXAdQtSpIGvnp2vu2W1j4o7cc/

I tested it and nothing happen: I tested also other payloads and nothing. The New 3DS only blue light. If the problem would the payload, the New 3DS will power off if I had the SD inserted without the arm9loaderhax.bin file but I tested it (SD inserted without arm9loaderhax.bin file) and the console will not power off.

**Comment by Keizel** [comment]
Other brick thanks the "safe" and "fast" method "OTPless": https://github.com/AuroraWright/SafeA9LHInstaller/issues/27

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/73249331a2c6de0c38390b138df6efde04335de5

**Comment by Altairseven** [comment]
Hi, I'm the one who open that issue report in Aurora Wright's SafeA9LHInstaller, I had the same brick that OP had, and I CAN confirm that the issue was not a bad SD.
I used a 4gb Micro SD from another brand new n3ds that I softmoded days ago without any issue, it was only used once, and because the console i was installing had a 32gb sd with emunand, and months of use, I figured using the 4gb it was the safest bet, i dont know what the hell caused the issue, but it wasnt the sd, there must be something glitchy about the installer.

PD: I used 2.6.1 installer with dataimputv3, and latest arm9loaderhax payloads from Aurora Wright.

**Comment by Keizel** [comment]
Other brick thanks to OTPless with https://github.com/AuroraWright/SafeA9LHInstaller/releases/tag/v2.6.2

**Comment by dark-samus** [comment]
@Keizel we have become aware of the issue, and possibly have solved it
(there was an interesting chat about it the other day) continuously
pointing out these is just getting annoying (I get an email every time you
people reply to these >.> I normally don't mind that, but you aren't
exactly bringing any new information to the table ) please, stop posting
these here, we are usually aware before you post them, so it's redundant
anyways

**Comment by pbanj** [comment]
@dark-samus has Aurora Wright contacted you? i had sent her a bricked nand backup and the xorpad for firm0/frim1. not sure if it is of any help to you guys

**Comment by patodox** [comment]
Same brick as OP here, using 2.6.6 SafeA9LHInstaller on New3DSXL

**Comment by mockatoy** [comment]
Odd I have done 5 the past two days and close to 25 using the optless and had no issues. :-/

**Comment by AuroraWright** [comment]
@patodox Could you upload the SafeA9LHInstaller.dat and the a9lh folder from the SD card and paste a link here?

**Comment by patodox** [comment]
@AuroraWright https://mega.nz/#!rBp2lbhT!xkKzjZqARFIbeYm0ghmiJ-fvBUzctCxrlVBt0krIHmE
