### ISSUE TITLE
dgTool error (failure opening sd files)

### ISSUE THREAD

**Issue by chesnaughtii** [Plailect/Guide#622]
It's able to backup the firmware, but for so reason it can't downgrade due to being unable to read the sd files...apparently. It doesn't make sense when it uses the boot.nds to work in the first place. What can I do to resolve this issue?

**Comment by CyHo** [comment]
Change another SD card....just copy and paste then test again

**Comment by theocmath** [comment]
have you put the 11.1firm(or 11.0 frim) and 10.4firm in the dgTool?

**Comment by CyHo** [comment]
Gonna put a correct firm also

**Comment by Plailect** [comment]
Probably SD card corruption. Try fixing it or using another SD card.
