### ISSUE TITLE
Black Screens

### ISSUE THREAD

**Issue by ArturoPerezP** [Plailect/Guide#624]
Hello, 
I have a N3ds, and according to people on the ３ＤＳＨＡＣＫＳ chat, i bricked my console. I have a  NANDmin.bin backup file from a previous step on this guide, but since mi n3ds just shows me black screens i can't do anything.

I followed the steps of this guide, including downgrading from 10.6 to 9.2. Everything went smooth up to section II of the Part 3. I did everything, except changing Hourglass9.bin to start_hourglass9.bin (which i realized later).
Then i performed the steps:

> Launch SafeA9LHInstaller
>Press (Select) to Full Install

After this my screens went to black. Since then, my n3ds wont start with or without sd card/N3ds game. The blue light does not blink. Recovery/safe mode does not work.

If anyone has any idea for a remote posibility fix this, i would appreaciate it.

Thanks for reading.

**Comment by pbanj** [comment]
you need a hardmod and flash that nand backup

**Comment by pbanj** [comment]
@Plailect I think this may need more looking into, there was just another person with this same issue. I'm going to bring it up to aw and tux

**Comment by ArturoPerezP** [comment]
I agree, just read the other person's problem and seems quite similar to mine. That said, this is a many-step guide, lots of things could go wrong, and his issue was not well redacted and/or detailed (maybe mine looks the same to you, sorry if that is the case).

I re-did all of the steps where i might have screwed  up (Part 3 of the guide) and the only thing that i failed to do was changing Hourglass9.bin to start_hourglass9.bin.

**Comment by pbanj** [comment]
Just had another person with this issue. The one from last night was able to hardmod and restore it. He's going to send his bricked nand to me so I can pass it onto tux to look at. The person last night just restored the nand backup and reran the installer, didn't change anything and it worked. So I don't think its user error.

**Comment by pbanj** [comment]
nand backup has been passed onto tux, so maybe something good will come from this

**Comment by ArturoPerezP** [comment]
Glad you guys are working on this. I will be asking someone to hardmod my n3ds, i don't trust myself to do it (yet). When i get it done maybe i can send you the NAND of my bricked console.

Thanks for keeping me posted.

**Comment by pbanj** [comment]
Well the person gave the nand backup but didn't grab the xorpads that were needed. So we are still stuck without answers. I need to get my hands on a system with one of these bricks so I can just dump everything needed.

**Comment by pbanj** [comment]
@ArturoPerezP do you happen to live in the us?

**Comment by ArturoPerezP** [comment]
No, i do not, i live in south america at the time. Still haven't done hardmod for my n3ds either.
