### ISSUE TITLE
Transfer Question 

### ISSUE THREAD

**Issue by ZalexZTK** [Plailect/Guide#625]
Was wondering about system versions and transferring. Say I've got a 10.7 cfw Ds and an 11.1 stock Ds. If I transferred that 10.7 to the 11.1 Ds, would that stock Ds retain its 11.1 or will it get the 10.7? What if I did the opposite, and transferred 11.1 to the 10.7?

**Comment by pbanj** [comment]
no transferring doesn't downgrade/upgrade the firmware, nor will transferring also wont transfer cfw. both systems need to be on the newest fw to do a system transfer or use ctr-httpwn
