### ISSUE TITLE
Add a warning to the DSiWare Downgrade guide

### ISSUE THREAD

**Issue by BatteryPine** [Plailect/Guide#626]
I think a warning should be added to the DSiWare Downgrade guide telling the user to format their 3DS if it came with any pre-installed software. I had an issue where I couldn't transfer the DSiWare during the system transfer and I think it was due to the fact that the target system happened to have some software bundled with it. When I formatted the target system and attempted to do another system transfer, I was able to copy the DSiWare to the target system and successfully do the downgrade.

**Comment by pbanj** [comment]
the transfer process is kind of a shit show. has nothing to do with pre-installed stuff.
