### ISSUE TITLE
Old 3DS region changing issue - EShop error 007-2001

### ISSUE THREAD

**Issue by Musasimaru1979** [Plailect/Guide#627]
I have region changed Japanese to European old3DS.
Please help me to fix error 007-2001
What I've tried:
1-st try: Made all by guide from a to z. All went ok, I got Euro region console with 11.1.0-34E! Then tried to open EShop - got error 007-2001 and have issue when exiting by HOME button from notifications - console hangs on it.
Then created new euro NNID, still have error 007-2001 when trying to open ESHOP and still have HOME button issue.
OK, then
2nd try: I've  made transfer from Euro to Jap back, then opened Japanese ESHOP - it works fine, then I've deleted ESHOP account in setting, console asked me to push power button after delete complete. I turned console off. Then I made transfer back to Euro by guide, and tried to open ESHOP - still 007-2001 error. I tried to format console thru settings, and it fixed HOME button issue! But error 007-2001 still present
And third try
3-d try: I've  made transfer from Euro to Jap back third time, then opened Japanese ESHOP - its works fine, then again deleted ESHOP account in setting. Then I made transfer back to Euro by guide, then when console got to 11.1.0.34E I've formatted it and linked my NNID from first step, then... still got 007-2001. 
What I've done wrong? What should I do to have working ESHOP on my region changed old3DS Euro? (pardon for my bad english, it is not my native language)

**Comment by Plailect** [comment]
Sometimes it will inexplicably not work, but there isn't much I can do about it. It's entirely determined by Nintendo's servers.

**Comment by helmergoza** [comment]
i have the same problem with 50 3ds japan to USA, did you get any solution to go to eshop after the change.??
