### ISSUE TITLE
oothax doesnt work anymore after downgrade

### ISSUE THREAD

**Issue by Kungaw** [Plailect/Guide#628]
hey guys,

like the title says, i cant acces homebrew via oot anymore since i (succesfully?) downgraded to 9.2. also i dont get into homebrew by holding d-pad down on boot. i still get into it by using browserhax and i went on to do the nand backup.
does somebody know if this is a problem? i had no crash/freeze during the downgrade and did it a 2nd time without any problems...

**Comment by Margen67** [comment]
The oothax save used before the downgrade isn't compatible with 9.2.

You don't boot into homebrew by holding dpad down because you don't have menuhax installed and properly configured for 9.2. That applies to oothax as well.

**Comment by Ev1lbl0w** [comment]
Adding to what @Margen67 said, you should install menuhax/oothax again for 9.2.

**Comment by Kungaw** [comment]
yeah, afterwards i supposed it would be something like that. its been a while since i installed the oothax and im not much into this stuff ^^´. thanks guys for the reply!
