### ISSUE TITLE
Question on Decrypt9

### ISSUE THREAD

**Issue by AdryelPinguuu** [Plailect/Guide#629]
I'm setting up my 3DS SD Card. the instruction said that I should create a files9 folder, will I only create it and keep it empty? anmd just put Launcher.dat and Decrypt9WIP.dat to the root of the SD Card?

**Comment by AgentEpsilon** [comment]
Whenever you are told to put a file on your SD card, the guide will also tell you where to put the file. Make sure you follow each instruction and you should be fine.
