### ISSUE TITLE
2.1.0 ctrtransfer image wont fit

### ISSUE THREAD

**Issue by DerekS2** [Plailect/Guide#630]
Due to the large file size (794.6 MB) it is impossible for me to fit this file in my /files9 folder.  I have a 4 GB SD Card.

First, is the file suppose to be this large?  If so, is it mandatory that I have an 8 GB SD Card?  I feel even if I deleted all extraneous files from my card I still would not have room.

EDIT: After grabbing a backup and trying again there was plenty of room to spare.  Odd, because I had just made the backup and it should have been the exact same size.  Problem solved I suppose..

**Comment by AgentEpsilon** [comment]
If you've solved your problem, feel free to close the issue.
