### ISSUE TITLE
Can't download ctrtransfer

### ISSUE THREAD

**Issue by Magicrider** [Plailect/Guide#631]
I think nobody is seeding this torrent, or it's something else, but the torrent is not downloadable.
I've launched the torrent since 40 minutes and I'm at 3Mo only, for his 734Mo size..

Does anybody have a DDL link for this? Thank you

**Comment by Ev1lbl0w** [comment]
What is the exact filename? I'll see if I can seed it for you.

**Comment by Magicrider** [comment]
2.1.0-4E_ctrtransfer_o3ds.zip

For some odd reason, sometimes my torrent is going up to 1 Mb/s, then falls again to nothing. In 1 hour and 20 twenty minutes, I'm actually at 50Mo downloaded..

**Comment by Ev1lbl0w** [comment]
Try a different torrent client, and check your internet connection.
