### ISSUE TITLE
Unable to install arm9loaderhax

### ISSUE THREAD

**Issue by DerekS2** [Plailect/Guide#632]
I finished the ctr transfer steps (https://github.com/Plailect/Guide/wiki/2.1.0-ctrtransfer) for my 2ds.  

On step 12, when I selected reboot, it froze, so I manually turned the system off.  I booted without my sd card.  I completed section 1 of installing a9lh.  I cannot progress to installing a9lh because neither http://dukesrg.github.io/2xrsa.html?arm11.bin, nor http://yls8.mtheall.com/3dsbrowserhax_auto.php work.  They both freeze on my browser (Yes, I've reset my time/date & browser).  I tried both because I do not know if I'm successfully on 2.1.0.  I cannot check because I have screen distortions that zoom my top screen.  I do not know how to get these to go away "once I restore my backup", but I do have the backup NANDmin.bin on my sd card.  I tried turning my system on with the sd card already in (guide claims this wont work in 2.1.0) and it boots fine.

**Comment by Plailect** [comment]
Browserhax (http://yls8.mtheall.com/3dsbrowserhax_auto.php) does not work on 2.1.0.

Did you delete the home menu's extdata? This should allow it to boot with the SD inserted still.

You also need to have arm11.bin and arm9.bin on your SD card...

**Comment by DerekS2** [comment]
Ah, so safe to say Im in 2.1?  I've deleted the menu's extdata.  I'm missing both those files however; which step are they derived from?  I dont have them anywhere on my computer.
