### ISSUE TITLE
This.

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#633]
"You will no longer be able to boot without the SD card in, that is normal."
This is no longer the case. Finally.

Still requires Luma nightly though, so this will probably be added once a new official Luma3DS release comes out...

**Comment by pbanj** [comment]
Why does this need an issue opened? The luma that works for it is still a nightly.... I'm sure once it comes out the guide will be updated for it even though it is pointless.

**Comment by Plailect** [comment]
This will be added when it's included in a release.
