### ISSUE TITLE
Unsure about EUR console (PAL)

### ISSUE THREAD

**Issue by lukasz-kotlinski** [Plailect/Guide#636]
I have old 3DS XL SPR001 (EUR) I did the hardmod, read, modified and flashed nand without complications. But because i have nag about update in browser i can't use browserhax. So i decided to buy "Ocarina of Time" and powersaves, but here I have a problem - what versions do I need? Is it safe for me to buy NTSC when my console is PAL? The game and powersaves must be both from the same region?

**Comment by Plailect** [comment]
Updated https://github.com/Plailect/Guide/wiki/Homebrew-Launcher-(No-Browser)
