### ISSUE TITLE
Unable to restore saves after 11.1 downgrade system transfer

### ISSUE THREAD

**Issue by Her02** [Plailect/Guide#637]
Hi, 

I was setting up a friends New 3ds and used the downgrade method to transfer my CFW old3ds onto his new 3ds. I followed through with the rest of the steps and it worked successfully, but I noticed his old save files wouldn't load. I have looked on various websites and it seems like his save files are encrypted in the /Nintendo 3DS/ sub folders underneath the 00040000 folder in a .sav file. Is there anyway to restore them or am I truly out of luck since I didn't use a save manger to decrypt and backup his save file? I only have a backup of his SD card before the hack and post system transfer. 

Thank you!

**Comment by AndyTheGeeky** [comment]
If there isn't a NAND backup to go with those encrypted files, you're truly out of luck, sorry.
