### ISSUE TITLE
.zip/.7z Instructions Issue when starting A9LH installation 

### ISSUE THREAD

**Issue by GravyBoat458** [Plailect/Guide#638]
When I began to install files I contacted some help from the server and I found that step 6. has a flaw in that it says to copy over the contents of SafeA9LHInstaller.zip file instead of the .7z file. Was told to let you know Plailect. :)

**Comment by Plailect** [comment]
It says zip as an overarching term that would include things like RAR and 7Z. The more accurate description would be archive, but that may be too obscure of a word use for some people.
