### ISSUE TITLE
Minor inconsistency in DSiWare-Downgrade Wiki

### ISSUE THREAD

**Issue by CudB** [Plailect/Guide#639]
The following issue is found at [DSiWare-Downgrade Wiki page](https://github.com/Plailect/Guide/wiki/DSiWare-Downgrade)

- In Section I of the guide, step 5 says to perform a SysNAND Backup to "NAND.bin"
- In Section VI of the guide, step 4 tells the user to restore SysNAND from "NANDmin.bin" instead of "NAND.bin."

**Comment by Plailect** [comment]
fixed
