### ISSUE TITLE
N3DS freezed after pressing home button.

### ISSUE THREAD

**Issue by Duonglevu** [Plailect/Guide#64]
Hi, I've followed all your steps and change my New 3DS region successfully from Jap to US. However, when I'm in any games or apps, if I press home button to go back to main menu, the 3DS freeze and I have to hold power until it's off. I've used Downgrade check and install all missing titles. What could be wrong here? Thank you for your help!

**Comment by Duonglevu** [comment]
![dsc_0039](https://cloud.githubusercontent.com/assets/18373703/14408006/69e1af54-ff0b-11e5-8a94-5a11ceb8a700.JPG)
This is the results when I used Downgrade check.

**Comment by Plailect** [comment]
Try formatting with tinyformat (have a backup just in case)

**Comment by Plailect** [comment]
It means use the one linked, it's different on n3ds from the one in Part 4.

[This seems to be a common issue with region changing in general](https://gbatemp.net/threads/387326/).

**Comment by Duonglevu** [comment]
@Plailect: How did you create "New 3DS 9.2.0 (Region Change) - USA" folder? Thanks.

**Comment by Duonglevu** [comment]
I've found the solution. In my case (N3DS Japan to USA), I must delete all titles that end with J using FBI, not optional. After that update to the latest system via system setting. And it's fine now.
