### ISSUE TITLE
Cant download data_input_v3.zip

### ISSUE THREAD

**Issue by nightslashs** [Plailect/Guide#640]
Where can i find this file!

**Comment by james-d-elliott** [comment]
There is a torrent, is it not working?

**Comment by nightslashs** [comment]
No the torrent is saying 0 out of 0 connected peers on all computers/networks i have tried

**Comment by james-d-elliott** [comment]
I'm seeding now. Is it working?

**Comment by nightslashs** [comment]
still not working :/ http://imgur.com/a/8c6hd

**Comment by nightslashs** [comment]
I can torrent some other files but this one isnt working

**Comment by james-d-elliott** [comment]
Give me a minute. We'll sort it out! c;

**Comment by nightslashs** [comment]
ok thanks!

**Comment by james-d-elliott** [comment]
I've seeded it at multiple locations but it doesn't seem like anyone is connecting. Do you know how to verify a file has the correct hash against a .torrent file?

**Comment by james-d-elliott** [comment]
Also I just checked, it downloaded almost instantly for me when I deleted the file and torrent and started over.

**Comment by nightslashs** [comment]
How odd i will take another look at it the hash mine is showing is a1195c9f7ab650fa7c7bf020b51fc19ea8d9440c

**Comment by james-d-elliott** [comment]
Well, I was considering hopping on IRC with you and just sending it. But ideally you should verify the file I send you matches the hash of the torrent. I can just do it if you trust me but that is unwise. :c

**Comment by nightslashs** [comment]
I got it to start working my ISP was blocking the torrent connection than you for all your assistance!

**Comment by james-d-elliott** [comment]
No worries c;

**Comment by nightslashs** [comment]
Sorry for bothering you again but for some reason anytime I launch my SAFEA9lhinstaller from homebrew the screen does the normal startup app flash of red then proceeds to go black. While the device is in this state ive tried waiting and pressing select like troubleshoot suggests both without success

**Comment by nightslashs** [comment]
i have also tried reinstalling the files several times and have verified md5
im on version 11.1 fresh non modded ds using the cubic ninja hack to get the homebrew menu

**Comment by pbanj** [comment]
-_- it can't be run on 11.1. You need to follow the guide

**Comment by gnmmarechal** [comment]
lol
