### ISSUE TITLE
Mistake on the NAND Size page.

### ISSUE THREAD

**Issue by Xarec** [Plailect/Guide#641]
https://github.com/Plailect/Guide/wiki/NAND-Size

This text, "Note that a min size NAND will always be the smallest possible size for the purpose of saving space, and may not match the size of other NAND backups from your device. This is fine, just make sure that it matches one of the sizes on this page.", links to the RedNAND FAQ page for no apparent reason.

**Comment by Ev1lbl0w** [comment]
This is probably a leftover from the previous guide.

**Comment by Xarec** [comment]
Probably.

**Comment by Plailect** [comment]
Fixed
