### ISSUE TITLE
[Resolved] Unable to Update 8.1.0 to 9.2 using NTR + Cubic Ninja

### ISSUE THREAD

**Issue by ntrcu** [Plailect/Guide#642]
I have a N3DS (non-XL) JPN version on firmware 8.1.0-0J. So I was following the guide for NTR & Cubic Ninja.

However, when I reached the last step (Step 11: Update the 3DS from 8.1.0 --> 9.2 using private server) of the guide, my 3DS does not want to update at all. The system update progress bar remains empty and I waited until it gets an error message and it reboots back into the main menu (still on 8.1.0). Does anyone know what is the issue?

If it helps here are some info:
> • I can confirm I followed every single step in the guide. All the stuff downloaded are the correct version (WAMPSERVER 2.5, NTR v3.2).

> • One of the thing I noticed is after Step 7, it will create a bunch of new folders with the original CIA titles names AND the GetSystemUpdate.partial.xml in C:\wamp\www\updates, is that normal or do I need to delete them? Screenshot: http://imgur.com/gErN36N

> • I am using a Sky3DS with the Cubic Ninja ROM

> • The SD card of the 3DS contains some Gateway leftover files (from the previous owner) but it still have 1GB free (size is 4GB)

> • I have tried everything, factory reset the 3DS, repeat the whole guide, try connecting via Mobile Hotspot and over WiFi network, none of them works :( It will always show an error message after confirming to update the system, the progress bar never moves a bit.

> • The error message basically says "An error has occured and cannot be updated. Please restart." (Rough translation)

**Comment by ntrcu** [comment]
# **Resolved.**
Many thanks to /u/AnalogMan on /r/3dshacks

Solution:
> Copy GetSystemUpdate.partial.xml back to your updates folder again. Then reboot the 3DS and redo the NTR and debugger command steps. Then try and system update. 

Suggestion to Plailect:
Can you edit point #8 in the guide for NTR & Cubic Ninja
> 8. Move node.exe, CdnCiaUnpack.js, and GetSystemUpdate.partial.xml back to C:\wamp\www\
to 
> 8. Move node.exe and CdnCiaUnpack.js back to C:\wamp\www\ + Copy GetSystemUpdate.partial.xml back to C:\wamp\www\ (Aka leave a copy of GetSystemUpdate.partial.xml in the C:\wamp\www\updates)

The full Q/A is here: https://www.reddit.com/r/3dshacks/comments/58io0j/3dshacking_qa_general_bait_and_switch_edition/d943l0f/

**Comment by Plailect** [comment]
fixed
