### ISSUE TITLE
Page 9.2.0 Downgrade could be improved

### ISSUE THREAD

**Issue by nbzwt** [Plailect/Guide#643]
In the end of the page, it writes:

Redo either Homebrew Launcher (No Browser) or Homebrew Launcher (Browser), depending on which one you came here from.

Actually, by this point, it doesn't matter "which one you came here from", because full 9.2.0 system is already installed, browserhax can be used now. And actually, for some users (including me) who came from a method that is only compatible with higher system versions (my smashhax cartridge require 9.9.0), this could be quite confusing.

**Comment by Plailect** [comment]
Redid that entire set of pages to be not cancer
