### ISSUE TITLE
Official Firmware updated

### ISSUE THREAD

**Issue by CyHo** [Plailect/Guide#644]
11.2.0-35 is now available, is okay we upgrade the firmware?

**Comment by Plailect** [comment]
This is not an issue, nor do I know yet.

**Comment by Margen67** [comment]
If you have A9LH, yes.

**Comment by CyHo** [comment]
Means that A9LH can support all the latest firmware which will release in future?

**Comment by Margen67** [comment]
Yes.

**Comment by CyHo** [comment]
Thanks, but testing is required isn't? haha

**Comment by Margen67** [comment]
https://twitter.com/mattyoukhana_/status/790706664802443264

**Comment by CyHo** [comment]
Thanks!!

**Comment by webgem8** [comment]
I noticed in that Twitter post that the FW version lists "AL9H" before the "11.2." My DS doesn't show "AL9H" before my FW version (9.2), but just says "Sys." Does this mean I am somehow not booted in AL9H? I just don't want to upgrade all the way into 11.2 just to lose my Homebrew/FBI/everything else! Thanks for the help

**Comment by Margen67** [comment]
If you already have A9LH there's no point having a 9.2 SysNAND unless you're a developer or something.
EmuNAND is a waste of space in most cases.

**Comment by CyHo** [comment]
@Margen67 , i think what @webgem8  means that why the picture show the firmware name with A9LH in front and people who follow the guide here is sys in front of firmware. But that just a name isn't? as long as we install the A9LH install in step 3 then will be alright.

**Comment by webgem8** [comment]
Well that is my question. I'm a bit of a noob at this stuff so I want to make sure I did everything right. Everything else works on my DS now, and I have CIAs installed for hb, fbi, etc, the only thing I am suspicious of is "Sys 9.2.0-28U" instead of what I would assume shoudl be "AL9H 9.2.0-28U" on the system settings screen.

**Comment by CyHo** [comment]
@webgem8 just a name in my understanding

**Comment by deadair3210** [comment]
Latest stable Lima added custom version string support. Go look at the readme for more info
