### ISSUE TITLE
Health&Safety Inject issue,

### ISSUE THREAD

**Issue by edmond2k2** [Plailect/Guide#645]
I followed the guide and everything went smooth till the section IV **step 4 - Select the FBI injectable .app for your region.**
Once I went into "Health&Safety Inject" option, it didn't allow me to select any .app but only ask for pressing "up down left right A" to proceed, or press "b" to return or "start" to reboot. 
If I press "A" it will stuck at loading 20%...
My console is N3DS - Jap version, Is anything I did wrong? 
I did copy all the .app file from fbi-2.4.2-injectable.zip to the /files9/ folder on the SD card
Appreciate if anyone could give me some hint. thanks!

**Comment by cubecubec** [comment]
you suppose to dump first,and then inject.health and safety dump success??

**Comment by edmond2k2** [comment]
Yes. The dump process was successful

**Comment by edmond2k2** [comment]
Ops... I found out that I need to follow the keys stoke to continue...
