### ISSUE TITLE
firmware zips in wiki

### ISSUE THREAD

**Issue by brentblend** [Plailect/Guide#647]
New 3DS 11.2.0 to 10.4.0
Old 3DS 11.2.0 to 10.4.0

Both link to 11.1 versions

**Comment by brentblend** [comment]
Linik is https://plailect.github.io/Guide/11.1.0_to_10.4.0_n3ds.torrent
should be https://plailect.github.io/Guide/11.2.0_to_10.4.0_n3ds.torrent

**Comment by Plailect** [comment]
Fixed.

**Comment by brentblend** [comment]
great work @Plailect
