### ISSUE TITLE
Add warning

### ISSUE THREAD

**Issue by Niloy28** [Plailect/Guide#65]
If you close the lid while the sd card is unmounted in otphelper on 2.1(after dumping otp and unmounting the sd for copying it to pc), the screens turn black. I had to hard reset at this point. And when I turned the 3ds back on, wifi had been disabled. Luckily mine is an old one so I could just re-enable it. But n3ds users would have been screwed at this point. So you should add a warning for them.

**Comment by Plailect** [comment]
Wifi shouldn't be disabled by this, it doesn't make any sense as we don't even have a wifi driver for o3ds implemented in any arm9 payloads and the switch should do nothing...
