### ISSUE TITLE
Safe to update to 11.2?

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#651]
Just go prompted to update to 11.2 firmware.. would updating delete my game cias?I'm running armloader9 on 11.1.

**Comment by Armastan** [comment]
It is safe. Nothing will happen.

Instead of downvoting him at least tell him.

**Comment by Gelums** [comment]
Thanks Armastan! Really appreciate it. I'm still new to this 3DS stuff. Thanks!
