### ISSUE TITLE
typo in new autofirm.bat

### ISSUE THREAD

**Issue by pbanj** [Plailect/Guide#653]
![image](https://cloud.githubusercontent.com/assets/17306233/19719721/2b4c4824-9b39-11e6-9e2a-7d42f4d3d559.png)

causing this
this is from a user on discord
 ![image](https://cdn.discordapp.com/attachments/196635695958196224/240760898413658122/20161026_151743.jpg)

**Comment by Plailect** [comment]
Fixed
