### ISSUE TITLE
What hapenned to the Parts pages?

### ISSUE THREAD

**Issue by hbdfreitas** [Plailect/Guide#655]
I've successfully installed luma 3ds on a 2ds and O3ds before and was looking forward to try it again on a 10.3 firmware one I got. But the parts pages seem to be missing? Home doesn't link to any other parts of the tutorial anymore. What happened?

**Comment by Ev1lbl0w** [comment]
The Guide was restructured. You only need to go to the [Get Started](https://github.com/Plailect/Guide/wiki/Get-Started) page, and from them select your console's type, region and version.

Basically, it became simpler and nicer xD
