### ISSUE TITLE
2xrsa not working on N3DS

### ISSUE THREAD

**Issue by monreal** [Plailect/Guide#656]
I followed some outdated guide which let me to downgrade my N3DS to 2.1 and now I am stuck. I found your guide and learned that I did not have to downgrade to 2.1 after all. Following the steps from your guide (Installing-arm9loaderhax, the part where xrsa.html?arm11.bin gets loaded in the browser) I can not get the a9lh to install. All I get is a frozen N3DS. I rebooted, cleared browser data multiple times but it always freezes. Is this part not meant to work on N3DS at all?

**Comment by Plailect** [comment]
It works, but you need the arm11.bin and arm9.bin on your SD card. Do https://github.com/Plailect/Guide/wiki/Installing-arm9loaderhax as if you had a n3ds, it'll fix it.

**Comment by monreal** [comment]
I assumed I would need to follow the O3DS path to Get A9LH. If I follow the N3DS path I get stuck at "Get into the homebrew launcher through the entrypoint of your choice" because for that I would need to be on 4.0 (?)

**Comment by monreal** [comment]
Or did you mean I have to copy arm11.bin and arm9.bin to the SD (root?) and follow the O3DS path?

**Comment by pbanj** [comment]
ya follow it as if you had a o3ds. the older safea9lhinstaller works on both systems.

**Comment by monreal** [comment]
> but you need the arm11.bin and arm9.bin on your SD card

How can I download those and where on the SD do I have to put them?

**Comment by monreal** [comment]
Nevermind I got it... Of course I had to use the older safea9lhinstaller... Thanks anyone!
