### ISSUE TITLE
DSiWare Downgrade not downgrading FIRM

### ISSUE THREAD

**Issue by sora10pls** [Plailect/Guide#657]
I've tried everything I can think of. I've tried re-downgrading FIRM from 11.1 to 10.4, deleting and re-writing the files to my SD Card, using different SD Cards, nothing is working. I've done three DSiWare Downgrades in the past, so I'm sure that this is not due to user failure.

Every time I check my kernel version and FIRM version (after attemtping to re-downgrade my FIRM) with 3DSIdent, they fluctuate between these two:
- 2.51-2
- 2.52-0

Info regarding my 3DS:
- Old 3DS
- Firmware version 11.1.0-34U
- Using Fieldrunners

**Comment by tianweiliu** [comment]
Make sure you have the correct release of dgTool for 11.1 and the correct 11.1 to 10.4 firmware zip. I tried to use 11.1 bin for my 11.2 bin before 11.2 zip was release and I got the same problem. I have successfully downgraded my 11.2 o3dsxl with the correct release of dgTool and 11.2 to 10.4 firmware zip. If you would like, you can update to 11.2 and try again.

**Comment by sora10pls** [comment]
Yep, I'm using the 11.1.0 compatible release of dgTool, as well as the correct FIRM package (11.1.0 to 10.4.0 o3DS). Still not working :/

**Comment by sora10pls** [comment]
Alright, I did as @tianweiliu suggested. Updated to 11.2 and downgraded FIRM through that, and it did downgrade properly. I'm not sure if you'd wanna look into this, Plailect, because 11.0 and 11.2 have worked for me, but not 11.1.

Thanks again @tianweiliu :)
