### ISSUE TITLE
DSiWare Downgrade issue

### ISSUE THREAD

**Issue by AdryelPinguuu** [Plailect/Guide#659]
trying to do System Transfer downgrade. my o3ds has been formatted 4x. and still keeps getting an error "The region information on this system has been changed. Please connect to Nintendo eshop and try again." However if I connect to eshop, I'm force to create my NNID which will make me unable to receive the downgrade

**Comment by brentblend** [comment]
What two systems are you using, and what version are they each on?

**Comment by AdryelPinguuu** [comment]
I got it! although I got a question though can I still perform a DSIWareHax, using the same method again, without buying it?

**Comment by brentblend** [comment]
Using what method? Buying what?

Always try to add as much info as possible. It makes trouble shooting more manageable.

**Comment by helmergoza** [comment]
i have the same problem with 50 3ds japan to USA, did you get any solution to go to eshop after the change.??
