### ISSUE TITLE
DSiWare Downgrade clarity issue at Section III and IV

### ISSUE THREAD

**Issue by kevinbushman** [Plailect/Guide#661]
After finishing section II, it's not clear where to go if you have no chance of being able to configure steelhax anyway. In my case, I have both 3DS #1 and 3DS #2 on 11.2.0 and therefor, I won't be able to use the steelhax entry point. 

We should add more information here about where to go for 11.2.0 users. 

For example, they should be able to use any other entry point they have like ninjahax/oot3dhax, right?

If that is true, then users can skip from Section II to Section V.

I haven't moved onto Section V yet and will wait until this issue is looked into.

**Comment by tianweiliu** [comment]
ninjhax and freakyhax are confirmed working.

**Comment by dark-samus** [comment]
Also, one 3ds needs to be hack already, using a custom loader (which luma
supports) you can take the ASLR out of the equation, from there you just
install it on the hacked 3ds and it'll work fine on the second 3ds, since
now you have 10.4 native_firm with doesn't have any PASLR at all, so
steelhax will work there as well (also, I think steelhax was updated
anyways? Not sure, but it just might)

**Comment by CyHo** [comment]
can use steelhax...

**Comment by brentblend** [comment]
Once you do the partial downgrade, you can use steelhax. I agree though, the guide should be more concise.

**Comment by kevinbushman** [comment]
Yeah that makes sense. I dont see why steelhax wouldn't work after the partial downgrade, however we can't verify it is working and based on the guide (i've never used steelhax before) it looks like steelhax only works intermittently? Meaning the save tends to get corrupted often. Is that true all the time? 

Also, the guide says we should use steelhax with the version of the 3ds at the time. So that would be 11.2.0. Would it be better to install the 10.4.0 payload?

**Comment by kevinbushman** [comment]
Update: I've successfully downgraded 3DS #2 and reverted 3DS #1 back with this guide. Thanks! If I can provide any other info to help close out this issue, let me know.

**Comment by brentblend** [comment]
You managed to get steelhax working on the partially downgraded 11.2 3DS?
If so, what was the setup procedure you used on the first 3DS for steelhax?
What was the steelhax setup procedure used on the second 3DS?

Lastly, what types of 3DS are they? O3DS, N3DSXL, O3DSXL etc

**Comment by kevinbushman** [comment]
Sorry. I ended up not testing steelhax even though I prepared it since 1) I could not verify it was working (I was on 11.2.0) and 2) I had a working entry point with oot3dhax. 

I was using cfw o3ds xl > stock n3ds xl.

**Comment by brentblend** [comment]
No worries @kevinbushman 
I have two systems on 11.2
O3DS and N3DSXL. 
Even though system one is on 11.2, I was still able to get steelhax to launch homebrew.
On the O3DS I ran hblauncher>steelhax installer until opening steel divers finally booted up hb
In the steelhax installer on hblauncher I used the true firmware 11.2 and it worked.

It took a few tries, but it works.
