### ISSUE TITLE
updated

### ISSUE THREAD

**Issue by KillaRose** [Plailect/Guide#662]
i  updated throught system settings tp 11.2 and then decided to restore to 8.1 sysnand restore... restored my sysnand min backup and now i cannont do the ctr 2,1.0 part of the guide anymore it says auto ctrnand transfer failed img  corrupted or modified and i have downloaded the file  few times but same problem happeneds every time and its just a error for the sha file

**Comment by Committee** [comment]
Did you copy just the .sha file or both?

**Comment by KillaRose** [comment]
i copied both

**Comment by Plailect** [comment]
https://github.com/d0k3/Decrypt9WIP/issues
