### ISSUE TITLE
Freeze upon Installing arm9loaderhax + can not detect SD card

### ISSUE THREAD

**Issue by blackhorse088** [Plailect/Guide#664]
Hi,
I'm having this problem hope you guys can help.
so after successful downgrading to 2.0.1, I am on step where to Install arm9loaderhax
However after following all step and copying all necessary files to SD card, and inserting it in I get this message "Can not detect SD card, software on SD card can't be displayed" 
ignoring this message going to  http://dukesrg.github.io/2xrsa.html?arm11.bin   on 3DS browser
it says "loading arm11.bin" screen flash once, then screen freeze, nothing can be pressed, tried SELECT but nothing happens. shut off device and tried again same thing happened.

I took my SD card back to PC, I get message " Card must be formatted before use" and cannot access the card, till format. I format card and did the whole process again, still getting the same issue.

So what went wrong there?
Old 3DS from 4.3.0-10U to 2.0.1 following tutorial.
Thank you.

**Comment by Plailect** [comment]
User a different SD card.

**Comment by blackhorse088** [comment]
Great, worked now! :)
I'd never guess brand new SD was corrupt! Damn Toshiba -_-

One last favor, I have a .3ds need to convert to .cia can't find any way to generate xorpad from nnchinfo.bin
All guides are different, saying hold START on boot to load Decrypt9, but it loads Hourglass?

A link or name of the guide is all I need.
Thank you very much.

**Comment by Margen67** [comment]
You should return that SD card.

**Comment by Ev1lbl0w** [comment]
You'll need to get the Decrypt9 payload and put it in your payloads folder. You can name it down_d9.bin and then press the down d-pad button on boot to load Decrypt9. From there there's various options for decrypting games. You just nned to find an option to convert from .3ds to .cia.

**Comment by blackhorse088** [comment]
Nah, it was on sale for 4.99 Not worth it.

Thank you Ev1lbl0w I got how this work now. D9 have it all in one step now, that's awesome :D
This work deserve a donation.
Thank you all!
