### ISSUE TITLE
Troubleshooting lost DSIware save hits a dead end.

### ISSUE THREAD

**Issue by ForcedToRock** [Plailect/Guide#665]
I did the system transfer and was able to redownload Fieldrunners onto 3DS 2, but when going the troubleshooting section, copying the still working save from 3DS 1's system to microSD and using that card on 3DS 2, on the microSD section of DSiware management, it says "There is no accessible data." What are my options?

**Comment by brentblend** [comment]
Did you format the device after the system transfer?

**Comment by ForcedToRock** [comment]
I believe so, on 3ds 2.

**Comment by brentblend** [comment]
If you formatted the device that received the system transfer, then you'll have to wait 7 days and transfer the title over to it properly.

I tried to do the "trouble shooting" in the same scenario and the 2nd ds will not recognize the save.

If I am incorrect, someone please step in.

**Comment by pbanj** [comment]
Ya once formatted you will have to transfer again

**Comment by ForcedToRock** [comment]
When that happens, should I format 3DS 2 again since I linked it to the NNID originally belonging to 3DS 1?

**Comment by brentblend** [comment]
You can't transfer to a device with a nnid regardless

So yea, restore device 1, format device 2
