### ISSUE TITLE
Tool recommended for SD card formatting is a dead link

### ISSUE THREAD

**Issue by catalyticarkun** [Plailect/Guide#667]
I was looking for a good tool to format a 128 GB SD card, and eventually found a software download site for the tool you recommended in the guide.  It works, just minor issue with the link being dead.

**Comment by pbanj** [comment]
https://goo.gl/ScGYyp there is a copy of it uploaded to my Google drive. It can be added to the guide if you want

**Comment by Plailect** [comment]
Fixed
