### ISSUE TITLE
An error has occured:

### ISSUE THREAD

**Issue by CJCTheNoob** [Plailect/Guide#669]
An old unsupported FIRM has been detected.
Copy a firmware.bin in /luma to boot.

Anyway to fix this?

**Comment by Ev1lbl0w** [comment]
_"If your backup is of a version between 4.0.0 and 4.5.0, put firmware.bin -  in /luma/ (delete this file after updating your 3DS)"_
If your 3DS has in that version when you started the guide, try doing this step. You can get the firmware.bin file from this [link](https://plailect.github.io/Guide/torrents/o3ds_firmware.torrent).

**Comment by CJCTheNoob** [comment]
I put a firmware.bin and a ctek in /luma like asked, and now i'm on 4.1.0-6E

This all happened after restoring my NANDmin.bin

**Comment by CJCTheNoob** [comment]
If i update the console, should it go back to normal, a9lh seems to still be in

**Comment by Ev1lbl0w** [comment]
After putting that file the 3DS booted on 4.1?

What is your 3DS? Old3DS, 2DS, New3DS, etc...

Can you boot arm9loaderhax payloads?

**Comment by CJCTheNoob** [comment]
I was formatting my console to sell it, but when I formatted the screen was a bit glitched, and I think i saw that i had to restore my NANDmin.bin.
After i restorted, it gave me that error, now after putting a firmware.bin and ctek in the luma folder, the firmware is now 4.1.0-6E

I have a Old 3DS XL, should i see if i can start hourglass9 or something?

**Comment by Ev1lbl0w** [comment]
Yes, try booting an arm9 payload.

**Comment by CJCTheNoob** [comment]
Hourglass9 works

**Comment by CJCTheNoob** [comment]
So am i safe to update?

**Comment by Ev1lbl0w** [comment]
BTW did you finish the **Installing arm9loaderhax** instructions to the very end?

**Comment by CJCTheNoob** [comment]
Yes i did everything correctly, i already installed a9lh a long time ago on this console

**Comment by CJCTheNoob** [comment]
I still have FBI, Homebrew loader here on the menu

**Comment by CJCTheNoob** [comment]
Like i said, this all happened after i restored my NANDmin.bin file in hourglass9

**Comment by Ev1lbl0w** [comment]
Do you remember the version of your 3DS before doing the guide? Was it 4.0-4.5?

**Comment by CJCTheNoob** [comment]
I'm pretty sure it's the version it's on right now

**Comment by CJCTheNoob** [comment]
so yeah, 4.1.0

**Comment by CJCTheNoob** [comment]
woops

**Comment by Ev1lbl0w** [comment]
I'd say it's safe to update IF you're running Luma3DS with the configs from the guide (check them by pressing Select on boot)

**Comment by CJCTheNoob** [comment]
Alright lemme check

**Comment by CJCTheNoob** [comment]
Yeah everything is still here

**Comment by CJCTheNoob** [comment]
Want a picture of the Luma3DS config menu? just to confirm

**Comment by Ev1lbl0w** [comment]
Yeah, if you don't mind.

**Comment by CJCTheNoob** [comment]
Sending over the picture from my phone, hold on..

**Comment by CJCTheNoob** [comment]
![20161030_112928](https://cloud.githubusercontent.com/assets/6958898/19836325/cde10d32-9e94-11e6-97fd-1c9910170e4e.jpg)

**Comment by CJCTheNoob** [comment]
Should be good, right?

**Comment by Ev1lbl0w** [comment]
Alright, you're safe to update. Even if something goes wrong, you can boot hourglass and resotre nandbackup. Just remember to delete the firmware.bin and ctek files after updating.

**Comment by CJCTheNoob** [comment]
Alright, thanks

**Comment by CJCTheNoob** [comment]
Ill close the issue after I update, just to see if it's all clear

**Comment by Ev1lbl0w** [comment]
Ok

**Comment by CJCTheNoob** [comment]
Ok all clear, thanks
