### ISSUE TITLE
Part 4 Section II Step 8 reboot instruction misleading

### ISSUE THREAD

**Issue by shoop** [Plailect/Guide#67]
Hi,

Thank you for the wonderful guide!

I'm following along and noticed that on part 4 section II step 8 it says "press start + right to reboot into RedNAND". However while start + right rebooted, this was into SysNAND, not RedNAND (confirmed by the folder created previously). This might trip people up if they're not careful. I suggest adding the standard line about booting into RedNAND before step 9.

Again, thanks for the guide!

**Comment by Plailect** [comment]
Done
