### ISSUE TITLE
Consider pointing toward the latest release of SafeA9LHInstaller

### ISSUE THREAD

**Issue by cheatfreak47** [Plailect/Guide#672]
Seems that it's quite a bit more stable with the recent change of what ram to use that Aurora Wright implemented. 

~~Also, I'm pretty sure you don't need to link separate builds for Old3DS/New3DS.~~
forgot about 2xrsa, but the New 3DS really ought to be using the latest build.

**Comment by Ev1lbl0w** [comment]
New3DS SafeA9LHInstaller uses an OTPless method to install arm9loaderhax, which isn't supported on the Old3DS. This is why there are separate builds for types of console.

**Comment by ihaveamac** [comment]
actually it's because the newer SafeA9LHInstaller removed 2xrsa support temporarily due to memory corruption issues I think.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/fa627ea72c6c4917842c36f74d1ae7d59311a4ef

**Comment by CyHo** [comment]
@Plailect , this link become 404, for New 3DS Compatible Release

**Comment by Plailect** [comment]
whoops, shouldn't have the "tag" in the link
