### ISSUE TITLE
method of removing nnid

### ISSUE THREAD

**Issue by Xarec** [Plailect/Guide#679]
https://plailect.github.io/Guide/troubleshooting

"Removing an NNID without formatting the device"

I think it would be better if you recommended the decrypt9 nnidsave.bin method rather than instruct users to use godmode9. Godmode9 is not intended for your average user, and can easily cause more issues.

**Comment by pbanj** [comment]
Using the blank nnidsave is also a lot faster

**Comment by Plailect** [comment]
Godmode9 has a permissions system that prevents accidental SysNAND operations. There is nothing more inherently dangerous about using it, and most users probably can't hex edit a file to zero out the nnidsave bin.

**Comment by Xarec** [comment]
You don't need to hex edit a file, just provide a blank nnidsave through a link and tell them to place it in files9 and inject it. It's quicker and easier.
