### ISSUE TITLE
Part 5 step 8 error

### ISSUE THREAD

**Issue by Suppish** [Plailect/Guide#68]
Part 5 Step 8 seems to be inaccurate as there does not exist a "aurei" folder in any of the AuReiNand versions.

**Comment by Plailect** [comment]
???

![image](https://cloud.githubusercontent.com/assets/16979510/14444200/21f1890a-0012-11e6-82cb-1758e713cf27.png)

**Comment by Suppish** [comment]
Sorry, it would seem my decompression program (AlZip) just can't find the folder.

**Comment by Plailect** [comment]
Odd, it doesn't contain anything though and your program probably skips empty folders.

**Comment by Suppish** [comment]
Either way, sorry for bringing up the false error. Thanks you guys what you guys do.
