### ISSUE TITLE
warning for people doing hardmods on the new 3ds systems

### ISSUE THREAD

**Issue by pbanj** [Plailect/Guide#681]
can you add this image as a warning for people doing the hardmod downgrade on new 3ds systems. with the warning that the parts in red do not open, the cables just pull out. lots of people have screwed their systems up because they open them. the tut that is linked says nothing about them, so having the warning before sending them there would be helpful

![mobo](http://i.imgur.com/4vaRfZ2.jpg)
link for easy copy and pasting
http://i.imgur.com/4vaRfZ2.jpg

it is a new3ds xl mobo but there are 2 points like them on the non xl in the bottom left of the mobo, and one at the top.

**Comment by Plailect** [comment]
I'll just link them to this issue.
