### ISSUE TITLE
2DS black screen

### ISSUE THREAD

**Issue by Sorrento6** [Plailect/Guide#683]
After loading armloader and restoring NANDmin.bin with A9lh, it restarts into a dimly lit black screen. I can still boot into Luma and Hourglass, but nothing works on regular boot. Any suggestions?

**Comment by Sorrento6** [comment]
if it means anything, after downgrading to 2.1, the top screen was distorted...

**Comment by NoobleMcScrunchkin** [comment]
did you replace the arm9loaderhax.bin with a luma 3ds arm9loaderhax.bin?

Also on a 2DS it is fine if the screen was distorted. The 2ds normally can't go to a firmware that low.
[arm9loaderhax.bin.zip](https://github.com/Plailect/Guide/files/573563/arm9loaderhax.bin.zip)

**Comment by Sorrento6** [comment]
is that the link for the luma armloader?

**Comment by NoobleMcScrunchkin** [comment]
yes

**Comment by Sorrento6** [comment]
Okay. I'll give it a shot. Thank you!

**Comment by NoobleMcScrunchkin** [comment]
If you can launch payloads then your installation is fine you probably just need to change that file

**Comment by NoobleMcScrunchkin** [comment]
if that doesnt work then you might need to use another nand backup

**Comment by Sorrento6** [comment]
I removed the existing file from the root and replaced it with this one. No dice.

**Comment by NoobleMcScrunchkin** [comment]
if you have another backup you could try using that. Otherwise i have no idea

**Comment by Sorrento6** [comment]
Okay. Thanks..

**Comment by Sorrento6** [comment]
I've reloaded the NANDmin.bin multiple times and went through the troubleshooting page. The 2DS is still able to boot to Luma and Hourglass, but not Sysnand. Still open to other options. Someone, please help!

**Comment by NoobleMcScrunchkin** [comment]
Can you get into recovery?

**Comment by pbanj** [comment]
You need to don't he 9.2 ctr transfer

**Comment by Sorrento6** [comment]
My 2ds was a 6.1 originally.  Should I still do the 9.2 car?

**Comment by Sorrento6** [comment]
Ctr

**Comment by pbanj** [comment]
Yes, luma has issues booting the 6 firmwares

**Comment by Sorrento6** [comment]
Well,  my friend, you called it!!  Thanks a ton.

**Comment by pbanj** [comment]
No prob
