### ISSUE TITLE
Backup emunand SD not formatted for emunand

### ISSUE THREAD

**Issue by BigCSurprise** [Plailect/Guide#688]
Hello, i have been following the guide to the letter, i got to the point where i can use my previous emunand. following the steps i need to add the godmode9 to my sd then boot into hourglass and make a backup of my emunand. at this point i get this error SD is not formatted for emunand.

Should i have inserted my older sd (the original 4gb with my emunand) make the emunand backup and copy it to my new sd card (i have been doing the guide with this new 16gb ds fresh formatted) and restore that emunand?

If i'm not clear enought let me know.

Thanks in advance!

BigC

**Comment by Plailect** [comment]
yes, you should
