### ISSUE TITLE
2.2 Cubic Ninja OTP QR not mentioned

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#689]
Hi there! I noticed the old guide had downloads for dumping the OTP on 2.2 using Cubic Ninja and was hoping you could put it back in for those following the new guide? I think it would save 2.2 users a lot of time!

[https://github.com/Plailect/Guide_RedNAND/wiki/Cubic-Ninja-OTP](https://github.com/Plailect/Guide_RedNAND/wiki/Cubic-Ninja-OTP)

**Comment by Plailect** [comment]
It's untested, and probably doesn't work.
