### ISSUE TITLE
emunand9 won't load

### ISSUE THREAD

**Issue by Diefist** [Plailect/Guide#69]
So i've followed every step correctly in the downgrading section, however I can't get passed step 21. For some reason emunand 9 won't boot. I've been trying for days and it just shows a red screen, fades to black and then exits back into homebrew. What do?

**Comment by Plailect** [comment]
Partial downgrade probably, downgrade again (even if your version looks right).

**Comment by Diefist** [comment]
It's on the new 3DS by the way

**Comment by Diefist** [comment]
Thanks, I fixed the issue.

**Comment by giftederic** [comment]
Thanks. It helped me!
