### ISSUE TITLE
4.x MSET users with Gateway-formatted NAND with various issues...

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#690]
Just wanted to report something else: Some 4.x users experienced issues injecting FBI after installing A9LH, and another ctr-transferred to 2.1 and mysteriously ended up without a browser!

These users managed to fix their issue by performing a ctrtransfer to 9.2, then updating to 11.2 and injecting FBI.

I'm not sure if this is related, but one of those users also defragmented their CTRNAND using Decrypt9, then formatted their SD card with EmuNand9, so maybe that helped too..?

**Comment by Plailect** [comment]
https://plailect.github.io/Guide/troubleshooting#gw_fbi
