### ISSUE TITLE
Wrong link N3DS No Browser

### ISSUE THREAD

**Issue by MollerAndre** [Plailect/Guide#692]
Just a small typo, the link to "Homebrew Launcher (No Browser)" section for N3DS with firm version between 9.0.0 and 10.7.0 is pointing to "Homebrew Launcher (Browser)" section.

**Comment by Ev1lbl0w** [comment]
In case you need to see this page, here's the correct ink: https://plailect.github.io/Guide/homebrew-launcher-(no-browser)

**Comment by Plailect** [comment]
fixed
