### ISSUE TITLE
Slightly unclear part in Section IV - Restoring the System

### ISSUE THREAD

**Issue by Matt2097** [Plailect/Guide#693]
At one point the guide says "If your backup is of a version between 3.0.0 and 4.5.0, do the following:"

If you have a later version, it's not clear where you pick the guide up again. If would be great if the relevant section ("Download Luma..." to the bullet beginning "Release the old..." were inset or otherwise marked.

Great guide btw :-)

**Comment by pbanj** [comment]
![img](https://cdn.discordapp.com/attachments/196635695958196224/245681265343332352/unknown.png) i made this for the discord to show people. maybe just ad a line after the boxed parts that says "for every firmware"
