### ISSUE TITLE
10.7 is considered "no browser" on O3DS but "browser" on 3DS

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#697]
The page https://plailect.github.io/Guide/get-started-%28old-3ds-usa%29 lists 10.7/Browser as using "Homebrew Launcher (No Browser)".

The similar New 3DS page at https://plailect.github.io/Guide/get-started-%28new-3ds-usa%29 lists 10.7/Browser as being "Homebrew Launcher (Browser)".

I can argue that they should both say "Browser".  (Because the browser does work.)  I can also argue that they should both say "No Browser" (because if the browser ever connects to Nintendo the browser stops working and it is unlikely that this has not yet happened).  But it doesn't make sense that one says "Browser" and one says "No Browser".

**Comment by ihaveamac** [comment]
because there is a New 3DS-only update bypass for 10.7+ I think.

**Comment by Plailect** [comment]
Correct.
