### ISSUE TITLE
Steelhax won't open after downgrade

### ISSUE THREAD

**Issue by thatsmyface** [Plailect/Guide#699]
I had steelhax working flawlessly prior to the DSi Downgrade. I followed the guide exactly including setting the right system versions when installing steelhax. However, now that I've performed the system transfer and downgraded, whenever I open Steel Diver it pauses on a black screen for a bit and then crashes saying "An error has occurred forcing the software to close. The system will now restart.". I have no other way to get into the homebrew launcher (maybe browserhax?, but that appears to be down). Any help/ideas would be greatly appreciated! -Ethan

Edit: Just to clarify- I am using 11.2 and have tried downloading the 11.1.0-34U otherapp payload and putting it on the sd card as "steelhax_payload.bin" in an attempt to resolve the issue, but it didn't work

**Comment by Plailect** [comment]
Browserhax does not work on >=11.0.0.

Not sure exactly what's wrong, perhaps @VegaRoXas could provide some input?

**Comment by VegaRoXas** [comment]
"putting it on the sd card as "steelhax_payload.bin"" did you use the old or the new installer? The new version of steelhax requires everything to be in the /steelhax/ folder on your sd card.

**Comment by Plailect** [comment]
The guide uses the [previous version](https://vegaroxas.github.io/files/steelhax-installer.zip).

**Comment by VegaRoXas** [comment]
I don't get where the problem is then? The old version booted pretty much everytime. Using another payload was done by putting steelhax_payload.bin on the sd card and holding B while starting the game.

**Comment by Plailect** [comment]
[Whoops](https://github.com/Plailect/Guide/commit/c5f878e9268dd73024e98b416cce3b8083de4c91).

**Comment by VegaRoXas** [comment]
@thatsmyface try holding B then, it should work then.

**Comment by thatsmyface** [comment]
that didn't work either. maybe something messed up during the transfer. either way it worked when i bought Ocarina of Time
