### ISSUE TITLE
error 0x00000002 

### ISSUE THREAD

**Issue by Hazewing** [Plailect/Guide#7]
I have downgraded my o3ds and now on 9.2. I followed part 3 with the installation of emuNAND until where it says to reinstall menuhax again for sysNAND. i have tried everything, replacing the files, changing themes, moving the files. This the screen i get every time. Sorry if this issues has been solved before and thank you for the help. 
![received_946884195426430 1](https://cloud.githubusercontent.com/assets/17759396/13662867/98bb47f4-e6d8-11e5-9628-71011e0ee898.jpeg)

**Comment by sigboe** [comment]
The error message says you are missing some menuhax files from your SD card, so try to copy over the files related to menuhax again into the sd card.

**Comment by Hazewing** [comment]
Ok
It worked
Thank you for clarifying

Had the replace everything
