### ISSUE TITLE
Latest version of FBI causes problems when injected into H&S

### ISSUE THREAD

**Issue by Hellrespawn** [Plailect/Guide#70]
Multiple reports:
https://www.reddit.com/r/3dshacks/comments/4b4ocl/full_stock_to_arm9loaderhax_cfw_guide_everything/d1zr3s9
https://www.reddit.com/r/3dshacks/comments/4eegz3/fbi_200_rewritten_from_ground_up/d1zmf7j

Consider adding a warning to use 1.4.17 until this is fixed.

**Comment by Plailect** [comment]
Fixed
