### ISSUE TITLE
Parental Pin on 2.1.0-4U

### ISSUE THREAD

**Issue by Committee** [Plailect/Guide#702]
So followed the guide, downgrade is good however forgot to remove Parental Pin and now on 2.1.0-4U.

Owner cannot remember the Pin and doing the forgot Pin only hangs the 3DS, cannot set it to a new AP since Parental Controls block it.

Any advice?

**Comment by Plailect** [comment]
https://mkey.salthax.org/

**Comment by Committee** [comment]
Cannot get an access code, as stated tying to do a forgot pin only hangs the 3ds without generating an unlock code

**Comment by Plailect** [comment]
And you're unable to access wifi settings or format the device (make an SD backup if you can; don't format a 2ds)?

**Comment by Committee** [comment]
Cannot, when trying to format the Parental Control blocks it.

**Comment by maorninja** [comment]
If you can't access your browser, try getting cubic ninja, get an otp dump from there, cart update to 4.0+, get decrypt9wip, update to 9.2 and follow the instructions for SA9LH for HBL instead of the one on 2xrsa

**Comment by kade-robertson** [comment]
@Plailect, another person has had some issues with parental controls after a 2.1.0 CTRTransfer. He hangs on the home menu as soon as he boots, and trying to go through recovery mode hangs after entering his PIN. Maybe a notice should be added to the top of the 2.1.0 ctrtransfer page stating to remove Parental Controls beforehand?

**Comment by jaxrogers2** [comment]
Well, everyone in this position will need to bruteforce the key, it will take FOREVER but if you get the PIN right you'll be fine.

In terms of preventing this, it might be a good idea to make disabling Parental Controls as a whole a formal step in the Guide using the mkey generator before the ctrtransfer.

**Comment by kade-robertson** [comment]
@jaxrogers2 The person I was talking to already *knew* the key. However when they enter it the console would freeze and they could not proceed.
