### ISSUE TITLE
Just A Quick Question: Save Data

### ISSUE THREAD

**Issue by ManlyDonut** [Plailect/Guide#705]
This guide is incredibly easy to follow and I thank you for that. My only question is, is it possible to save the system I'm transferring to (A friend's 11.2 system)'s save data, as there are particular saves on that device she doesn't want to lose. I've spent the last 5 hours looking for a definitive answer. Any help is much appreciated!

**Comment by rikumax25** [comment]
use a homebrew entry to run JKSV on each game to backup the save data

**Comment by ManlyDonut** [comment]
Thank you sir! I was just worried if they'd still be readable after all is said and done.
