### ISSUE TITLE
Cant Downgrade Kernel or Firmware to 2.50-11

### ISSUE THREAD

**Issue by TsukiNoTragedy** [Plailect/Guide#706]
I tried to do it and I keep getting 2.51-0 or 2.52-0 and I followed the guide step by step like I did my other 3ds's
dgTool is up to date at Ver. 2.0.0 Console ver. is 11.2

**Comment by pbanj** [comment]
he was able to get this figured out by using the files for 11.0 once he got 2.51-0. not sure why he had to go through all of that.
