### ISSUE TITLE
the health and safety is not fbi

### ISSUE THREAD

**Issue by ploidt** [Plailect/Guide#707]
I have followed the guide until Section VI - Finalizing setup
and my health and safety is not fbi
I'm not sure about what I did wrong but I notice that my Decrypt9.log said
 Initializing SD card... success
Build: Decrypt9WIP (2016/11/13)
Work directory: /files9
Game directory: /files9
sector0x96 Key: otp.bin not found
0x03 KeyX & KeyY: already set up
0x05 KeyY: already set up
0x25 KeyX: already set up
0x18 KeyX: already set up
0x1B KeyX: not found
0x24 KeyY: automatically set up
Finalizing Initialization...

Initialization: partially failed

Selected: [NAND Backup (min size)]
Dumping SysNAND. Size (MB): 1240
Use arrow keys and <A> to choose a name
NANDmin.bin
Creating NANDmin.bin ...
NAND dump SHA256: B36BCF22...
Store to NANDmin.bin.sha: ok
NAND Backup (min size): succeeded!

Press B to return, START to reboot.

I'm not quite sure that is it is the reason for this.
Please let me know what I should do next.
Thank you in advanced

**Comment by Ev1lbl0w** [comment]
In the end of the guide, it's supposed you restore your original H&S app.

Did you finish the guide completely?

**Comment by Ev1lbl0w** [comment]
Sorry, didn't read you were starting the Section VI.

Redo the steps in Section V.

**Comment by ploidt** [comment]
I did redi steps in section V several times. Nothing has changed

**Comment by mockatoy** [comment]
what does it say when you inject the FBI injectable .app? When using
hourglass9

**Comment by ploidt** [comment]
Selected: [Health&Safety Inject]
Searching title "Health&Safety (N3DS)"...
Trying title ID 0004001020020300 (region 0)
Method 1: Search in title.db...
Found title ID 0004001020020300
TMD0 found at 10E58000, size 2916b
APP0 found at 0FA78000, size 900kB
APP1 found at 10E68000, size 156kB
Use arrow keys and <A> to choose a file
hs.app
Opening hs.app ...
Code / Crypto: CTR-N-HACJ / Secure3 
Encrypt ExHdr/ExeFS/RomFS (2kB/617kB/0MB)
Injecting H&S app...
Opening hs.enc ...
Fixing TMD...
Health&Safety Inject: succeeded!

Press B to return, START to reboot.

**Comment by Ev1lbl0w** [comment]
Are you using your hs.app dump to inject? You should be using FBI.app

**Comment by mockatoy** [comment]
your injecting your dump, use the FBI_v2.4.2_*3DS_***_injectable.app

**Comment by ploidt** [comment]
do I inject into sysnand or emunand backup/restore I can't find the way to change the file. Or did I go in to the wrong menu?

**Comment by cubecubec** [comment]
if you follow plailect guide,i assume you use SYSNAND,so go to sysnand inject FBI_v2.4.2_*3DS_***_injectable.app,but before you need to dump HS.App first.

**Comment by ploidt** [comment]
I got it. Thank you y'all.

**Comment by Levitical** [comment]
How do you select FBI_v2.4.2__O3DS..
I have the file but I just cant use the arrow keys to select it.

**Comment by Ev1lbl0w** [comment]
First, open a new issue instead of reviving a closed issue.

You're sure you did the steps right? To where did you copy the FBI files?

**Comment by Levitical** [comment]
First to the root, then I tried in files9. Both didn't let me choose anything but hs.app
