### ISSUE TITLE
step changes for noobs

### ISSUE THREAD

**Issue by pbanj** [Plailect/Guide#709]
people are skipping all of "Section IV - Restoring the System" as they think it is only for the o3ds or because they think it is only for 3.0.0-4.5.0. so they are not updating before moving to the next section. maybe add a not to step 3 that every system has to do it. them skipping it leads to them not being able to inject fbi for o3ds users as they are still on 2.1 and it leads to n3ds users complaining about games not running.

also in "Section I - Prep work" could you bold the steps for adding the files for the a9lh folder. people keep skipping it. they like to then argue that they didn't skip anything.

at this point i think we need a bigger spoon

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/917b4f1696853aebac66591029c3a126178aea0c

**Comment by pbanj** [comment]
thanks
