### ISSUE TITLE
No usable file found, Auto CTRNAND Transfer: failed!

### ISSUE THREAD

**Issue by Nexus-** [Plailect/Guide#711]
Cannot seem to get past the AUTO CTRNAND transfer, because it always fails with a 
"No usable file found" error, and there's not much I can do about it (tried Googling it to no avail).

I have `2.1.0-4U_ctrtransfer_o3ds.bin`, `2.1.0-4U_ctrtransfer_o3ds.bin.sha`, and `aeskeydb.bin` in my `/files9` directory; is there something I'm missing?

**Comment by pbanj** [comment]
backup your sd card, format it, restore it, try again

**Comment by Nexus-** [comment]
Apparently when I was ejecting sd card from my PC, it wasn't safely ejecting. Solved it. :)
