### ISSUE TITLE
Can't get CTRNAND FIRM to boot after restoring NANDmin.bin

### ISSUE THREAD

**Issue by forsureitsme** [Plailect/Guide#712]
After restoring NANDmin.bin back in [Section IV - Restoring the System Part 1 and Part 2](https://plailect.github.io/Guide/installing-arm9loaderhax)(because I have a o3ds 4.2.0-U backup), I get the following message when I try to boot:
```
An error has occurred:

Failed to get the CTRNAND FIRM.

Press any button to shutdown
```

What I've already tried to: 
- download both `firmware.bin` and `cetk` again (No success booting)
- restore `NANDmin.bin` a second time (No success booting)
- search for "Luma 3ds Failed to get the CTRNAND FIRM" on Google (No success finding someone with the same issue)

**Comment by forsureitsme** [comment]
Erased `firmware.bin` and `cetk` from and did a 9.2.0-U CTRTRANSFER as the people in the 3DS Hacking told me to do and now I can boot again.

**Comment by Urf3** [comment]
i actually have the same issue now, but i cant restore it please help godmode dont work when i press start

**Comment by Urf3** [comment]
i can run Luma and Decrypt9, i also think i have sighax
