### ISSUE TITLE
Stuck @2.1.0

### ISSUE THREAD

**Issue by lestatbytes** [Plailect/Guide#714]
browser not working, good wifi.

Is there another workaround aside from using a game cart as suggested from the guide to restore nand?

only have r4cart / nand backup but no game cart.

**Comment by CyHo** [comment]
Pls follow the guide properly, no need explolit to restore the nand.bin, using hourglass9, if you cannot boots into hourglass, check whether you put all the file require into your sd card

If you are an Old 3DS or 2DS user who has done 2.1.0 ctrtransfer, restore NANDmin.bin:
Copy NANDmin.bin to the /files9/ folder on your SD card
Open Hourglass9 from arm9loaderhax by holding (Start) on boot
Go to “SysNAND Backup/Restore”
Restore from NANDmin.bin
Press (Start) to reboot
If you get a black screen, follow 9.2.0 ctrtransfer

**Comment by lestatbytes** [comment]
i havent installed arm9loaderhax yet.
i cant cause of browser issue.

im using o3ds with original fw @4.3

this problem occurred right after i successfully transfer 2.1.0, now when i check system settings it show 2.1.0-4u

**Comment by lestatbytes** [comment]
im at this step:

-Old 3DS
You should be on 2.1.0
Go to http://dukesrg.github.io/2xrsa.html?arm11.bin on your 3DS

**Comment by lestatbytes** [comment]
solved by trying new wifi ssid.
