### ISSUE TITLE
Can inject FBI on O3DS 2.1.0-4U

### ISSUE THREAD

**Issue by weiyifeng** [Plailect/Guide#715]
I've followed the guide all the way down to Section V(injecting FBI).
The hs.app which I dumped is the only .app file I can inject.
I've tried to use a fbi_inject_with_banner.app which I downloaded online but came out a black screen after I launched H&S.
Any help?
Old 3ds with V2.1.0 FW (downgraded as the guide).
I'm sure the FBI injectable app files are in files9 folder.

**Comment by CrystalMoogle** [comment]
You should have updated before you got to section 5. You haven't done the steps in section 4, which is restoring and upgrading.

**Comment by weiyifeng** [comment]
Oh I thought section 4 is for people who want to restore their backups. I'll try it right away, thank you so much!

**Comment by weiyifeng** [comment]
All done, thank you for your guide!
