### ISSUE TITLE
Stuck on Restoring System

### ISSUE THREAD

**Issue by samanthamar** [Plailect/Guide#716]
Hi, I previously had rxTools + emunand on my o3ds. I followed the move emunand guide and I do not think the restore was successful as when I reboot, my firmware is on 2.1.0-4U.

I don't mind losing anything I had on that emunand, but is there something I'm missing? 

Should I try restoring the NANDmin.bin from the first step of restoring the system?

Also, when I tried updating the system, I think it failed as I'm still on the same firmware (my 3ds is in Japanese so I don't know what the screen says after the update finishes - I tap on the bottom and the 3ds restarts). After, I tried injecting the fbi but when I try and scroll for it, the .app is not found.

**Comment by pbanj** [comment]
restore the nandmin or make a backup of your emunand and restore that

**Comment by samanthamar** [comment]
>

**Comment by samanthamar** [comment]
"Copy NANDmin.bin to the /files9/ folder on your SD card" Where can i find nandmin.bin?

I don't have the sd card with me right now, will have to wait a couple hours until I get home to try this.

**Comment by pbanj** [comment]
It is either on your PC or still in files9. If you don't have a sysnand backup you can just do the move Emunand section https://plailect.github.io/Guide/move-emunand

**Comment by SpaceCraft33** [comment]
Hi, I'm in the same trouble. I'm ont a N3DS with 9.0.0-20E and i'm stuck at Section IV of the guide. I can't update my system. I tried to restore my Nand that I got fro, the first part of the tutorial, but nothing. Can't update, the N3DS just reboot after saying that it didn't work (the internet connexion works)

What am I doing wrong ?

**Comment by SpaceCraft33** [comment]
I saw that section, but i don't have any EmuNand already. I started with a blanck new SD Card.

**Comment by samanthamar** [comment]
Ended up flashing 9.2 ctrtransfer and went from there. Flawless!
