### ISSUE TITLE
arm9loaderhax.bin changed by SafeA9LHInstaller

### ISSUE THREAD

**Issue by james-d-elliott** [Plailect/Guide#717]
I believe the arm9loaderhax.bin is overwritten or renamed with the installer when you run it now. i.e. if you have the luma bin there it will overwrite it. A step needs to be added to section III of the arm9 page to account for this.

https://github.com/AuroraWright/SafeA9LHInstaller/commit/2be5a24262ca2219bb2cc711e6439b75573d53bd#diff-7f66c4cc7962b1c1494ed8b6328e1ca3

https://github.com/AuroraWright/SafeA9LHInstaller/blob/5d1c717cb4ec2a7e55f15fa1414f814a441b3566/source/installer.c#L205-L213

**Comment by Plailect** [comment]
This is true. It also uses a different file name for the 10.0 firm, so I'll fix that too.

**Comment by Plailect** [comment]
Fixed with https://github.com/Plailect/Guide/commit/6cdb9ace8aa1960964bfcff640c07ac4ca86f1d9

**Comment by AuroraWright** [comment]
This isn't true actually, it backups and restores the existing arm9loaderhax.bin automatically
