### ISSUE TITLE
Decrypt9 seeddb.bin problems any help would be appreciated. 

### ISSUE THREAD

**Issue by BlackSalmon** [Plailect/Guide#72]
when i use decrypt9 to get the xorpads from a 3ds file it just give me seeddb.bin cant be loaded and then cant load ncchinfo.bin and i didn't end up with anything. any help with this or any alternative method to convert 3ds files to cia would realy help thanks

**Comment by Plailect** [comment]
This is not for converting a 3ds file to CIA, use simple CIA converter for
that.

**Comment by BlackSalmon** [comment]
every converter i have found wants me to use decrypt9 or rxtools ,and rxtools doesent work with new 3ds
