### ISSUE TITLE
Using steelhax on 11.2

### ISSUE THREAD

**Issue by FranticUmbreon** [Plailect/Guide#721]
I'm having the same issue as https://github.com/Plailect/Guide/issues/675
I know the issue was closed, and I did try the old steelhax installer, but it's still not working, getting the same
00000002 Error: "the title this sploit_installer is running under is not supported"
(o3ds a9lh 11.2 trying to dsiware downgrade n3ds 11.2)

**Comment by Plailect** [comment]
Are you using the latest Luma version?

**Comment by FranticUmbreon** [comment]
Nevermind, please close this thread I got it working on my other o3ds, thanks

**Comment by the4anoni** [comment]
Have this same issue on n3ds with ofw 11.2.... To install i use oot3dhax
