### ISSUE TITLE
Linked Version of data_input and SafeA9LHInstaller in the "Updating A9LH" Guide Appears Incompatible

### ISSUE THREAD

**Issue by nrmh** [Plailect/Guide#722]
The [Updating A9LH](https://plailect.github.io/Guide/updating-a9lh) guide instructs you to download [data_input_v3.zip](https://plailect.github.io/Guide/torrents/data_input_v3.torrent) and the [latest SafeA9LHInstaller](https://github.com/AuroraWright/SafeA9LHInstaller/releases/latest), but it appears they're incompatible.

Someone in the 3DS Hacking discord got `Error: firm1.bin is invalid or corrupted` when trying to follow the guide, and I found [a thread on gbatemp](https://gbatemp.net/threads/error-installing-a9lh-on-new-3ds-firm1-bin-is-invalid-or-corrupt.450251/) with users having an issue doing the initial install. Someone posted saying that the initial arm9loaderhax guide was just recently updated today, so I'm guessing the Updating A9LH page needs an update, too?

The checksum in SafeA9LHInstaller v2.0.3 corresponds with the firm1.bin checksum from data_input_v3, not data_input_v4.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/fdb67af165282ddc8cbd785132fe4eda2f59ce8a
