### ISSUE TITLE
Bricked in a Weird Way

### ISSUE THREAD

**Issue by weirdfuckingbrick** [Plailect/Guide#723]

**Comment by Margen67** [comment]
What if you take out the SD card?

**Comment by weirdfuckingbrick** [comment]
I tried that, but nothing changed.

**Comment by FrozenChen** [comment]
You know a simple format would have fixed this

**Comment by weirdfuckingbrick** [comment]
It was on a 2ds. If I formatted on 2.1, then I would have bricked due to the 3d on requirement in initialization. On 8.1 I can't access the system settings to do a reformat.

**Comment by FrozenChen** [comment]
This happened to someone once(they had a browser on 2.1 but), they cartridge updated by accident, they got same problems as yours after the update. Most stuff on home menu didnt work.
No method worked, in the end they sought a hardmod. (I dont know if they got one)
