### ISSUE TITLE
move emunand step change

### ISSUE THREAD

**Issue by pbanj** [Plailect/Guide#724]
https://plailect.github.io/Guide/move-emunand step 20 can you add a message that says "this includes the arm9loaderhax.bin you backed up" having tons of people who leave the one from godmode9 on there and come crying about the system being bricked. they don't seem to grasp "Put your SD card in your computer, then copy all your files back into it" means ALL files -_-

**Comment by CyHo** [comment]
R.I.P brain....

**Comment by pbanj** [comment]
@CyHo right after i clicked post 2 more people asked about it again. i was like gfdi
