### ISSUE TITLE
Cannot start up homebrew after error middle of Section 2 Downgrade.

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#726]
I was on this part of downgrading..
Section II - Downgrading
Boot into the Homebrew Launcher (if you followed the previous part, you can do this by holding D-Pad down on boot)
Open sysDowngrader
Press (Y) to downgrade to 9.2.0
If you are stuck being unable to acquire the am:u service, power off your 3DS by holding the power button 

everything was fine till installation until an error occurred and told me to hold power button. Now when I launch OOt3dhax I get "An error has occured.." then instantly heads to the black screen that says to hold power button to turn off.

The Sys version says it is 9.2.0 now from 11.0, But I know it is a partial downgrade.. Do I have to reinstall payloads for oot3dhax for 9.2 now?

**Comment by Ev1lbl0w** [comment]
Probably. Or simply try using browserhax and downgrade again.
