### ISSUE TITLE
can't boot hourglass9 

### ISSUE THREAD

**Issue by mikevasileiadis** [Plailect/Guide#728]
Hello! please some help here! i have followed the guide (https://3ds.guide/installing-arm9loaderhax) done everything successfuly until section iv but was never able to boot hourglass9 on boot... i continiued following the guide with upgrading the system and im on 11.2 now with arm9 installed an luma running on boot properly but how do i fix the hourglass and decrypt 9 issue to finish the guide and intall hombrew(menuhax,fbi etc)?

**Comment by james-d-elliott** [comment]
Make sure you have the files in the sd:/luma/payloads folder and have them renamed correctly. For Hourglass9.bin it should be start_Hourglass9.bin, think Decrypt9 is x_Decrypt9WIP.bin

**Comment by mikevasileiadis** [comment]
yes i did that and nothing.... still can't access.. :(

**Comment by Ev1lbl0w** [comment]
If you keep the START button pressed all the time when booting, does it boot the system normally or it gets stuck to a black screen until you relese the button?
