### ISSUE TITLE
Problems converting 3ds to CIA with a new 3ds

### ISSUE THREAD

**Issue by BlackSalmon** [Plailect/Guide#73]
when i use decrypt9 to get the xorpads from a 3ds file it just give me seeddb.bin cant be loaded and then cant load ncchinfo.bin and i didn't end up with anything. any help with this or any alternative method to convert 3ds files to cia would realy help thanks.

P.S. simple CIA converter wants me to use rxtools to get the xorpads but rxtools doesent work on New 3ds

**Comment by BlackSalmon** [comment]
For more on my situation I have a New 3ds XL hyrule edition and just got done following this whole guide (everything went fine no problems). And I was looking to play 3ds & DS roms on it as well as some older games (GB,GBA,SNES,ect.). But I'm kinda stuck right now not knowing how to get the 3ds files converted and workin. So any help from someone who knows there way around a New 3ds sense the way to do it on the old 3ds or 2ds doesn't work on here.
Thank you.

**Comment by Plailect** [comment]
Not sure what the issue is, but I'm not involved with any of those, so ask on the relevant threads.

**Comment by BlackSalmon** [comment]
Alright thanks for getting back to me on that. I'm talking about it on gbatemp forums and apparently someone kinda knows what's going on.
