### ISSUE TITLE
Concern/suggestion on emunand transfer: tickets and SD formatting

### ISSUE THREAD

**Issue by Kazamimi** [Plailect/Guide#731]
https://3ds.guide/installing-arm9loaderhax
In Section VII - Reinstalling Tickets, 
Wouldn't it be unnecessary to reinstall tickets if you flashed an emunand you were already using before moving to a9lh? 
I reinstalled the tickets and streetpass wanted to update but couldn't, I fixed it by removing then reinstalling the sp updates. I haven't noticed anything else wrong with other applications.

https://3ds.guide/move-emunand
In steps 10-19 it asks to format the SD card using GodMode9 to remove emunand and open up space.
I ignored this and just used a partition manager on my computer to remove emunand and expand the primary partition, rather than formatting the whole thing. Anything bad with this method? 

If I'm not wrong, please consider making a note in their respective sections.

**Comment by Plailect** [comment]
Some partition managers can cause issues with various 3DS homebrews like decrypt9.
