### ISSUE TITLE
Ropbin after downgrading

### ISSUE THREAD

**Issue by Codexhavein** [Plailect/Guide#732]
I had a N3DS on version 10.7 with 10.7 ropbin of course. After downgrading, I couldn't launch homebrew through browserhax. I changed the 10.7 ropbin to 9.2 and it worked. Forgot to mention that this isn't shown on the guide.

**Comment by james-d-elliott** [comment]
The guide tells you that you need a ropbin matching your devices version for browserhax.. did you mean on this page? https://3ds.guide/decrypt9-(homebrew-launcher)

"What you need
config.zip
The ropbin matching your 3DS’s version"
https://3ds.guide/homebrew-launcher-(browser)

**Comment by Codexhavein** [comment]
Yeah that page. On the Decrypt9 page.
