### ISSUE TITLE
Games Nintendo Select for installation of the homebrew launcher?

### ISSUE THREAD

**Issue by angelop16** [Plailect/Guide#733]
Hi guys,

Can I use the games Nintendo select for installing the homebrew launcher? (E.g. The Legend of Zelda: Ocarina of Time 3D - Nintendo Select version).

Thanks a lot for the help.

**Comment by Plailect** [comment]
Yes. Perhaps read [the page](https://3ds.guide/homebrew-launcher-(no-browser)) where this is explained?

**Comment by angelop16** [comment]
Perfect. Thank you for the help.
