### ISSUE TITLE
Why I think people continue to ask if it's safe to update

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#736]
So even with the warnings, we still get people asking if it's safe to update and/or deliberately skipping the step and then asking why they can't inject FBI...

Even though the guide says "Yes, just do it," I feel it isn't enough to convince some people, because they were earlier told that if they update, they'll lose their hacks, and ask anyway for an immediate answer, than a written guide, for verification.

Can you clarify in the steps directly that their version string should say "Sys" and that an official system would otherwise say "Ver"? I think that would alleviate any doubt of updating the system, and they'll stop asking. For good measure, also add that if they don't see "Sys" or "Ver" then they need to either restore their NAND or redo Section III

**Comment by Ev1lbl0w** [comment]
I think it would be easier to say that when a user installs A9LH, he is protected from updates, since Luma3DS blocks any updates that modify the firm where the hacks are installed. Telling the users this kind of info might make people more wary of what is going on and worry less.

**Comment by Plailect** [comment]
Added an explanation

**Comment by mysterypaint** [comment]
Thanks for the amendment! Though I was actually hoping you could mention the version string thing, because I think some people don't even realize they're booting into Luma despite having configured it. Would you mind adding that little bit too?
