### ISSUE TITLE
Restored NANDmin and now console won't power on

### ISSUE THREAD

**Issue by NataliePequeno** [Plailect/Guide#737]
Hi, This might be a complete n00b thing and I might have broke my console, but I followed your guide on a 16GB SD Card and it worked perfectly fine. Then all of a sudden, the SD Card stopped being recognised in the DS and the PC. So I got a new 32GB card, copied all of the original files that I backed up (3ds, files9, boot.3dsx files etc.) And all the apps that were on the 3DS originally turned to black boxes and said "The SD Card has been removed, press home to go back" or something like that whenever I opened them.
So I decided to try the tutorial again from start to finish on the new SD Card.
I got to the part where you restore the NANDmin file, it checked fine, installed fine, then said B to go back to Start to reboot. I clicked start and now whenever I power on the console, the power light turns on for a second before fading off.

Have I just bricked my 2DS?
Thanks and sorry for being a n00b.

**Comment by jaxrogers2** [comment]
No, the quick shutoff means you have A9LH installed but you either no arm9loaderhax.bin on your SD card or you don't have an SD inserted (or your 3DS isn't recognizing the card).

**Comment by NataliePequeno** [comment]
I found out the problem. I restored the NAND that didnt have the A9HL installed on it so I need it on the SD card instead. Someone helped me figure it out. It's all sorted now 💃 Thanks for the reply!

**Comment by rome3ro** [comment]
@NataliePequeno I have the same issue could you please help me out what did you did to get everything working again?
