### ISSUE TITLE
Wireless Transfer vs. PC-Based Transfer

### ISSUE THREAD

**Issue by RidleyLarsen** [Plailect/Guide#738]
I'm on the system transfer step from an o3DS to n3DS and the system transfer asked about transferring the SD card data - The guide didn't mention it so I went with wireless transfer but according to some people it seems like PC-based allows you to just move the SD card over to the target 3DS. It may be worth mentioning this in the guide.

**Comment by james-d-elliott** [comment]
PC method is the best. It only asks on 2ds/o3ds to n3ds. All it requires is that you take the SD card out of the source system and put it into the target one if it's a microSD, or take it out, and copy all data to the microSD.

The instructions are very straight forward and it doesn't allow you to do anything wrong except format the source SD from memory. I think it warns you to have the source data in the target system or it will not restore them but I believe you can restore the game even after the transfer is done - I may be wrong.
