### ISSUE TITLE
devmode is not needed at all for sysUpdater

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#74]
https://github.com/profi200/sysUpdater/commit/8fea9d67cbc9e90db7a46d15ac6f70377bfd9b59

fixed by https://github.com/profi200/sysUpdater/commit/213aed9407f893c6a2bcc6f650e430b3b288636b

**Comment by dankzegriefer** [comment]
Then maybe you should stop being a lazy fool and actually type make a pull request.

**Comment by Plailect** [comment]
Please elaborate on how you plan to run unsigned code without patching signature checks, I'm really interested in seeing this miracle in action.

(PS: devmode is unrelated to firmlaunching)

**Comment by mariogamer2** [comment]
devmode is not needed,any other CFW who patch sig check can be used to update sysNAND

**Comment by Plailect** [comment]
And rxtools supports the widest version range.
