### ISSUE TITLE
Regarding the N3DS 2.1 Guide changes

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#744]
Hi! First of all, thank you for considering the issue from earlier. I was hoping we could clarify on a few things though:

- On the installing arm9loaderhax page, can you clarify on the black screen, specifying that N3DS will definitely get a "CTRNAND Error" message because Luma can't boot 2.1 firmware?
- On that same page, can you clarify the Sys/Emu note in the first bulletpoint of Section IV, Step #3?

Thanks again!

**Comment by Plailect** [comment]
No.

Regardless of whether the NAND string is enabled or not, firm patches are applied. Telling the user to look for this string just to comfort them is misleading.
