### ISSUE TITLE
"What you need" section is not clear in the file types needed

### ISSUE THREAD

**Issue by AvgAmericanMale** [Plailect/Guide#746]
Section: https://3ds.guide/installing-arm9loaderhax

The section where you download the required software only indicates that the user would need to download the following:

A previous release of SafeA9LHInstaller
The latest release of arm9loaderhax
The latest release of Luma3DS
The latest release of hblauncher_loader
The latest release of Hourglass9
The latest release of Luma3DS Updater
The latest release of DspDump
The latest release of FBI
The Homebrew Starter Kit

I feel that it would make more sense and be more user-friendly to be precise and state that the user will need to download a ".7z" file when required instead of letting the user choose.

**Example:** 
The guide mentions: **"Copy the contents of the SafeA9LHInstaller zip to the root of your SD card"**

I initially chose source code because I thought that was what was required, but if the original article claimed **"SafeA9LHInstaller.7z"** then I would specifically get that.

The addition of the file type should be a simple fix and would eliminate any potential for the wrong file being downloaded.

**Comment by FranticUmbreon** [comment]
You don't "choose" you only use the latest release of each in the releases tab, and you unzip the .7z or .zip files for the contents. You don't need the source code if I understand this correctly.
