### ISSUE TITLE
An error has occured: Failed to mount CTRNAND?

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#748]
I just finished installing arm9 using the site into the browser and was on the luma settings part. I pressed start to save and got this error: "An error has occured: Failed to mount CTRNAND Press any button to shutdown"? I am not sure what this means. I am on new 3DS 2.1 and havent restored yet.

**Comment by CrystalMoogle** [comment]
https://github.com/Plailect/Guide/issues/744
As this issue states, it's normal. Try restoring to 9.2

**Comment by Gelums** [comment]
I restored it. Thanks!

**Comment by FatherYas** [comment]
I'm having the same problem, and I don't know what you mean by restoring to 9.2

**Comment by CrystalMoogle** [comment]
The guide should cover this now

"If you get a “Failed to mount CTRNAND” error, just continue to the next section" next section being
https://3ds.guide/installing-arm9loaderhax.html#section-iv---restoring-the-system

**Comment by FatherYas** [comment]
well I hold start on boot but nothing it just goes to the failed to mount screen

**Comment by FatherYas** [comment]
and I can't get past the screen whatsoever

**Comment by CrystalMoogle** [comment]
Double check you've done this step right

> Copy Hourglass9.bin from the Hourglass9 .zip to the /luma/payloads/ folder on your SD card and rename Hourglass9.bin to start_Hourglass9.bin

**Comment by FatherYas** [comment]
IT WORKED. THANK YOU

**Comment by FatherYas** [comment]
I am absent minded sometimes sooooo thank you soooo much

**Comment by travjmaggs** [comment]
What about after everything? I have everything done but need to go back into Luma settings to edit something, will I get the failed to mount CTRLNAND again? Every time? If so, THEN how would i get out of it? Or should it not say the error after? Any advice please!

**Comment by CrystalMoogle** [comment]
You only get that error on 2.1 or should

**Comment by travjmaggs** [comment]
Thanks, I just went into it and worked fine.

**Comment by kokujo** [comment]
Hi, i also have the same problem at first. Then repeat the from the first step in prep work and overwrite everything from the start. After that, i saw that this problem arise because i write payloads in luma folder without 's'. But i cant get to installing the arm9loaderhax by go to dukesrg.github.io/2xrsa.html?arm11.bin because i cant open my 3ds since this error keep coming. so is it ok if i didnt do that? i already copy the otp.bin file to the a9lh folder which do it before. then i just recover with hourglass9 and then do all the steps.

**Comment by Pecashi** [comment]
Hi I'm having the failed to load ctrnand issue but this also happens when I try to turn it on normally the only other thing I can access to is luma configuration by pressing select and on at the same. I'm following instructions for installing a9lh and not hourglass 9
