### ISSUE TITLE
Installing titles back. Some failed?

### ISSUE THREAD

**Issue by Gelums** [Plailect/Guide#749]
Was on this part of the ending of installing arm9.
Open FBI
Select “SD”
Select “files9”
Select “<current directory>”
Select “Install and delete all tickets”
Wait. The system may appear to freeze, just give it time.
Press (A) to confirm
Press (B) to decline installing tickets from CDN.
Exit with the home button

 It installed some tickets then gave an error of failing to install something.. and said press any button to continue. Is that okay?

**Comment by pbanj** [comment]
Yes that's fine

**Comment by david-zzj** [comment]
this part is for what purpose ？
