### ISSUE TITLE
Requesting a minor change to the Installing arm9loaderhax page.

### ISSUE THREAD

**Issue by Xarec** [Plailect/Guide#750]
> If you have done 2.1.0 ctrtransfer, restore NANDmin.bin:
> Copy NANDmin.bin to the /files9/ folder on your SD card
> Open Hourglass9 from arm9loaderhax by holding (Start) on boot
> Go to “SysNAND Backup/Restore”
> Restore from NANDmin.bin
> Press (Start) to reboot
> If you get a black screen, follow 9.2.0 ctrtransfer

This section (Section IV, https://3ds.guide/installing-arm9loaderhax) makes it seem like you're supposed to have moved the nand backup, but no previous page says that you should. If you were to, for example, edit the 2.1.0 ctrtransfer page to say that you should move or copy your nand file onto your computer, then it would make more sense. But that seems unnecessary, since they'll be using the file very shortly after making it.

Also, I would also like to add that it would be nice if you informed users about how getting "Failed to mount CTRNAND" isn't a bad thing. The old guide used to mention it, but it seems to have been removed after you changed the 2.1.0 section to mostly focus on the O3DS.

**Comment by pbanj** [comment]
The failed to mount ctrnand or a black screen are normal, so a note about both should be added

**Comment by Xarec** [comment]
Yeah, but the black screen is already mentioned, I believe. Just not the mounting error.
