### ISSUE TITLE
Redundant Nand Dump in Decrypt9

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#752]
Before we recommended 2.1 on N3DS, "Decrypt9 (Homebrew Launcher)" told us to dump NAND. However, when CTRNAND transferring to 2.1, it asks the user to dump another one.

Can we remove the one from Decrypt9 (Homebrew Launcher)?

**Comment by Ev1lbl0w** [comment]
"_If you do not already have a NAND backup, backup SysNAND to NANDmin.bin when prompted by pressing (A)_"
It warns the user to do a dump if he hasn't done one yet. It's not making the user dump twice.
