### ISSUE TITLE
Section VI, arm9loaderhax

### ISSUE THREAD

**Issue by Marika4Princess** [Plailect/Guide#753]
Hi guys, I am actually at the step on Section VI, number 7 on the following guide: https://3ds.guide/installing-arm9loaderhax

I cannot see the arm9loaderhax.bin, I prefer asking you before doing anything bad. Did I miss any step?
Thank you for your help.

Marika

**Comment by Plailect** [comment]
This is an issues section, not a troubleshooting section.
