### ISSUE TITLE
Amend a DSiWare List of games that do not work?

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#757]
Hi! I was just wondering, could we also amend to a list of games that do not work? It would save people time/money testing out other games that have already been tested not to work.

**Comment by Plailect** [comment]
https://3ds.guide/dsiware-list

**Comment by Xarec** [comment]
@Plailect that's not what he was asking for. he was asking for the opposite, a list of games which have been confirmed not to work. there are games which have not yet been properly tested, and people might try to use them anyway.

**Comment by Plailect** [comment]
That is not a list of tested games, that is the entire possible list of games. If it is not on that list, it will not work.

**Comment by Margen67** [comment]
If you're going to add games that don't work you should also add untested games.
