### ISSUE TITLE
re-add the "Yes, this is safe, stop asking about it" to installing arm9loaderhax

### ISSUE THREAD

**Issue by Xarec** [Plailect/Guide#758]
![image](https://cloud.githubusercontent.com/assets/13697777/21012295/9c8fb726-bd55-11e6-9961-c9d6552efc43.png)

https://3ds.guide/installing-arm9loaderhax

it reassured a lot of people, and without it being there, a lot more people come to ask whether it's safe or not. i know that it still tells you that it's safe, but the phrasing somehow makes people doubt whether it's actually safe or not.

**Comment by pbanj** [comment]
Most important part of the guide

**Comment by Xarec** [comment]
and that ^
