### ISSUE TITLE
Extensions conflicts on Instaling arm9loaderhax page

### ISSUE THREAD

**Issue by Armastan** [Plailect/Guide#762]
https://3ds.guide/installing-arm9loaderhax

A previous release of SafeA9LHInstaller (the .7z file)
The latest release of arm9loaderhax (the .7z file)
The latest release of Luma3DS (the .7z file)

Copy the contents of the SafeA9LHInstaller zip to the root of your SD card
Copy the contents of the arm9loaderhax release zip to a9lh folder on your SD card
Copy arm9loaderhax.bin from the Luma3DS zip to the root of your SD card, overwrite existing files

Those are 7z files, but later on we're referring them as zip files.

**Comment by Plailect** [comment]
Fixed as part of https://github.com/Plailect/Guide/commit/f7a2a8763b33c437512c33e510a105319a7ebc79
