### ISSUE TITLE
DsiWare save doesn't work

### ISSUE THREAD

**Issue by Osga21** [Plailect/Guide#766]
On 11.2 whenever you open legends of exidia it gets stuck on a loop saying "Initializing save data"

**Comment by Plailect** [comment]
Added instructions for stuff like this

https://github.com/Plailect/Guide/commit/64daa1169490a99134a31d1cf3ac89e16df70fcf

**Comment by ekids1234** [comment]
@Plailect  
Could you help check whether the operation is error ? 
I had tried many times.

[https://www.youtube.com/watch?v=GjyTHSbObLI](https://www.youtube.com/watch?v=GjyTHSbObLI)

**Comment by CyHo** [comment]
@ekids1234 you copy a wrong savedata

**Comment by ekids1234** [comment]
@CyHo  Really ? 
This 3ds region is JPN.

I put them like this : 

http://i.imgur.com/peUUId0.png

**Comment by ekids1234** [comment]
OK, it was solved.
My .sav file is too big to use. 
If somebody has same problem, you can catch a 16kb sav or restore NAND (which backup in section 1).
