### ISSUE TITLE
[Request]  Quick navigation on the guide

### ISSUE THREAD

**Issue by Altairseven** [Plailect/Guide#767]
Hi, Plailect,  first of all,  thank you very much for the hard work you do with this guide,  it's awesome,  and I really love the design it has since a couple of months now,  but I do find a small issue that comes with it,  and could easily be fixed. 

I have done many a9lh installs at this point,  so I know most of the guide by memory,  but whenever I want to Check a specific part,  I find myself navigating section by section in order to get where I need to get,  and it's really annoying,  could you add like and index,  or a way to quickly access the different parts of the guide,  like back when the guide was hosted directly in github,  we had the "pages" list. 

Thanks again for everything

**Comment by Plailect** [comment]
Look in the footer :P

**Comment by Altairseven** [comment]
lel... cant believe I never seen it.. Sorry for the trouble, and keep up the good work
