### ISSUE TITLE
Can't boot HB launcher in partial 9.2

### ISSUE THREAD

**Issue by nickthegamer5** [Plailect/Guide#769]
As said in the title, I can't boot any of the entry points.
I have tried freakyhax, SteelHax, and BrowserHax

They all fail to boot(Won't even show the payload loading), My otherapp and rospbin files have been set o 9.2 20 U as for that's what it fail to downgrade too.

I came from 11.0, downgraded my nfirm to 14.0 and tried to go to 9.2.

Please help, I got no idea on what to do now.

**Comment by Margen67** [comment]
Try a 10.4 payload

**Comment by nickthegamer5** [comment]
Nothing, not working.

**Comment by nickthegamer5** [comment]
Just decided to update and redo the prosses.

**Comment by Margen67** [comment]
It might have been browserhax not detecting the right version due to the partial downgrade.

**Comment by nickthegamer5** [comment]
I already did, tried 4 different payloads to be exact Hutu fixed it anyway. Updated to the latest version keeping the DSIwareHax and just repeated the procces.
