### ISSUE TITLE
Why use NTR-compatible firmware.bin by default?

### ISSUE THREAD

**Issue by Hellrespawn** [Plailect/Guide#77]
The guide mentions nothing about what NTR is or why one would use it, but instructs everyone to use the 10.2 firmware.bin.

Considering AuReiNand doesn't need firmware files for normal operation anymore and has the N3DS CPU options built-in, it might be prudent to relegate this to an optional section.

**Comment by Plailect** [comment]
Why wouldn't you?

There's no downside to using the NTR bin, and makes it easier for people to get NTR.
