### ISSUE TITLE
Is it possible to use FBI instead of GM9 for dsiware downgrade?

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#770]
Just a question like that,since FBI can manage CTR NAND.

(also,it should be the latest commit)

**Comment by Plailect** [comment]
1. FBI cannot mount `public.sav`
2. It should *not* be latest commit *specifically* because of [this](https://github.com/Steveice10/FBI/issues/231)
3. Why would you want that?

**Comment by Plailect** [comment]
If your goal was to use FBI via "slowhax" for k11, it's not going to work. 

See https://www.3dbrew.org/wiki/NCCH/Extended_Header#ARM9_Access_Control

**Comment by mariogamer2** [comment]
Not at all. It because of some problem I have with GM9
