### ISSUE TITLE
Homebrew is gone?

### ISSUE THREAD

**Issue by Marika4Princess** [Plailect/Guide#772]
Hi guys, I am actually at the step on Section VI (finalizing setup) on the following guide: https://3ds.guide/installing-arm9loaderhax

My issue is the step 13. I need to start homebrew, but I got no idea how to do it. Also, the version of my old 3ds is now 11.2.0, is it normal? Did my homebrew uninstall cause it is back to 11.2.0 ? I prefer asking for your advice before adventuring and brick.

Thank you, 
Marika. 

(if I am not asking for help in the right section, please link me to the right place, ty.)

**Comment by Ev1lbl0w** [comment]
Try opening FBI and redoing this step:

"_Navigate to hblauncher_loader.cia and press (A) to install_"

**Comment by Marika4Princess** [comment]
Okay, ive just done it but it doesnt change anything . :O

**Comment by Ev1lbl0w** [comment]
But does it install?

If yes, I'd recommend download the hblauncher_loader file again. It's on the Waht you need section.

**Comment by Marika4Princess** [comment]
How it is the step 16, which is reboot while holding Start to launch hourglass 9.... it's not doing anything. I get into the home menu.

**Comment by Ev1lbl0w** [comment]
What section are you in?

**Comment by Marika4Princess** [comment]
http://prntscr.com/din7dt
# 16.

Thank you for taking the time to help me btw.

**Comment by Ev1lbl0w** [comment]
Np xD

So you can't boot Hourglass9, but can boot FBI...

First things first, do you have a start_Hourglass9.bin file on /luma/payloads/ folder on the root of your SD card?

**Comment by Marika4Princess** [comment]
I do, and I've just refreshed it with a new one and still nothing. And ya I can boot fbi and all just fine. !

**Comment by Ev1lbl0w** [comment]
Can you open the Luma config screen? (Select on boot)

**Comment by Marika4Princess** [comment]
yes!!!

**Comment by Ev1lbl0w** [comment]
And I assume every option stated in the guide is selected?

**Comment by Marika4Princess** [comment]
hum... now that I booted luma config, all the cia I had installed in the home menu are gone... except for fbi

**Comment by Ev1lbl0w** [comment]
Did you restore your NANDmin.bin backup?

**Comment by Marika4Princess** [comment]
omg... I found the problem.. I was pressing the power button and THEN I was pressing Start. I have to hold Start before.. it is working now. And no I didnt restore it. :O

**Comment by Ev1lbl0w** [comment]
LOL. BTW, arm9loaderhax loads miliseconds upon boot, so it's best to press the required button before turning on the console.

So, are you sure you didn't do Section IV?

**Comment by Marika4Princess** [comment]
tbh I think I didnt... But now I am at number 21 and I dont see the '' show NAND '' -_- Is it in the home menu? I'm tilting lol

**Comment by Ev1lbl0w** [comment]
No, in that part you should press Select on boot with the SD card removed to configure SD-less CFW.

**Comment by Marika4Princess** [comment]
You shoulda made the guide yourself. You explain way better xD I need to transfer everything to my new 3ds now. I hope it will go well. Thank you so much for your help I wouldnt have done it without you.
