### ISSUE TITLE
Guide for 11.0-11.1 has remnants of system transfer method

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#774]
https://3ds.guide/dsiware-downgrade-%28save-injection%29

"1. Go to System Settings, then “Data Management”, then “DSiWare”, then “Nintendo DS Profile” **on the source 3DS**"

Because this method doesn't use system transfer, there is no "source 3DS".

Also, this method contains a link for "New 3DS 11.2.0 to 10.4.0" and "Old 3DS 11.2.0 to 10.4.0".  Because this page is meant only for 11.0 and 11.1 3DSes without system transfer, there is never a use for the 11.2 version.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/4ef2107faf80d7fd35fdf6644456e4304a19d7ed
