### ISSUE TITLE
Duplicate reference to EmuNAND

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#775]
https://3ds.guide/dsiware-downgrade-%28app-injection-and-second-3ds%29

"The source 3DS: the 3DS running some kind of custom firmware (arm9loaderhax or some form of EmuNAND/EmuNAND) on the latest version".  

Should say "some form of EmuNAND/RedNAND".

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/4ef2107faf80d7fd35fdf6644456e4304a19d7ed
