### ISSUE TITLE
Redundant line

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#776]
https://3ds.guide/get-started-%28new-3ds-usa%29

"For all versions you can Cart Update to a higher version in the same column to follow its instructions instead."

The New 3DS guide only has two versions in the same column.  And there is never a reason to cart update from 9.0-10.7 to 11.0-11.2.  So this line should be removed.

EUR version has the same issue.

Technically the JP guide is okay since you can cart update from 8.1, but people reading the guide who don't know any better might think it is useful to cart update from 9.0-10.7 to 11.0-11.2, which is a bad idea, so you may want to take out the line and stick it inside the 8.1 "no browser" table entry instead

**Comment by Plailect** [comment]
Eh, makes it easier for me to maintain in the future as new versions are added. I'll leave it; nobody has mentioned this as as a point of confusion before.
