### ISSUE TITLE
Missing file? 

### ISSUE THREAD

**Issue by Marika4Princess** [Plailect/Guide#777]
Hi guys, I am following this guide: https://3ds.guide/dsiware-downgrade-(app-injection-and-second-3ds)
 
I am at the **Section III - Injecting the game and save** (number 5), it says that I'm supposed to find a file 00030004, but I only have the file 00030005 and 0003000f. Would you be able to help me? 

If I am not in the right section for help, please link me to the right place, thank you!

Marika.

**Comment by Plailect** [comment]
What DSiWare game do you have installed?

**Comment by Marika4Princess** [comment]
I dont have any :O

**Comment by Marika4Princess** [comment]
Well I bought Guitar Rock Tour like it was recommended on the list. but I didn't know I had to install anything.

**Comment by Marika4Princess** [comment]
Aright, do you know about steelhax? I've put the installer in the 3ds file, but I dont see it in my 3ds to launch it :O
