### ISSUE TITLE
Suggestion for Guide Step

### ISSUE THREAD

**Issue by 4ndytech** [Plailect/Guide#780]
For page: https://3ds.guide/dsiware-downgrade-(app-injection-and-second-3ds) , under Section VIII - Backing up the target 3DS’s NFIRM, Step 1 isn't so clear where one copies the boot.nds file from. 

For consistency with the rest of the guide I suggest adding the mention of dgTool.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/ba9fe90cc1d69e03cafc881999850e5cf534514f
