### ISSUE TITLE
Include 11.2 to 10.4 NFIRM zips on the DSiWare downgrade (save injection) page in case of softbrick

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#781]
If users are forced to update using recovery mode after a softbrick, they will need to use dgtool again to downgrade their NFIRM to attempt the downgrade again, but since these users previously had 11.0 or 11.1 NFIRM they now need to use the 11.2 to 10.4 NFIRM zip instead.

Edit: Another possible solution might be to just reflash the old NAND backup made with dgtool, but I'm not sure if that would work...

**Comment by pbanj** [comment]
If the nand backup has the downgraded firm it will. But it is faster to just downgrade the firm again

**Comment by Plailect** [comment]
They format, so nobody should soft brick anyways...
