### ISSUE TITLE
Hardmod page: Autofirm generates nand_patched.bin, not nand.bin

### ISSUE THREAD

**Issue by matcarfer** [Plailect/Guide#782]
Hardmod page: Autofirm generates nand_patched.bin, not nand.bin.

**Comment by Davidosky99** [comment]
The NAND.bin is the NAND you originally dump and the nand_patched.bin is the NAND you flash with the 10.4 FIRM to downgrade...

**Comment by matcarfer** [comment]
Yeah, I know, thats what I posted it here. The guide doesnt say that.

**Comment by Plailect** [comment]
We want the original nand backup, though it really didn't matter because hourglass9 doesn't restore FIRM partitions.

**Comment by matcarfer** [comment]
Sorry to insist, but "we" want nand_patched.bin to flash back to the 3ds, not nand.bin (which isnt touched). This should be corrected in the guide.
