### ISSUE TITLE
Update guide for AuReiNand 5.0

### ISSUE THREAD

**Issue by jayessthree** [Plailect/Guide#79]
AuReiNand 5.0 was released today and has a bunch of changes. Most notable to this guide is that the various firmware files (including AGB and TWL) are no longer needed. There may be some other changes that affect the guide but that's the biggest one.

**Comment by Uranometria** [comment]
I'm extremely new into 3DS modding/hacking and have not started the A9LH process yet. Should I hold off until AuReiNand 5.0 is addressed?

**Comment by Plailect** [comment]
They have already been addressed.

**Comment by Uranometria** [comment]
My bad, new to GitHub. I was only looking at the Home page of the guide and didn't realize each individual page had its own "Plailect edited this page" times and dates.
