### ISSUE TITLE
Add NTRCardHax

### ISSUE THREAD

**Issue by Margen67** [Plailect/Guide#790]
http://gbatemp.net/threads/ntrcardhax-progress.412495/page-4#post-6926819

**Comment by d3m3vilurr** [comment]
http://gbatemp.net/threads/ntrcardhax-progress.412495/page-4#post-6942347 and updated app & steps :)

**Comment by mariogamer2** [comment]
So kor region would have to dg to 10.3 and use ntrcardhax?

**Comment by d3m3vilurr** [comment]
@mariogamer2 yes

**Comment by mariogamer2** [comment]
https://github.com/TiniVi/safehax :P.

**Comment by Plailect** [comment]
no longer needed
