### ISSUE TITLE
Guide links aren't working

### ISSUE THREAD

**Issue by effectiveaim** [Plailect/Guide#796]
While in the guide, 9.2.0 downgrade, ctrtransfer 2.1.0,  aeskeydb.bin, fbi-2.4.2-injectable.zip, data_input_v3.zip are all not working. I've tried multiple browsers (safari, chrome, edge) and they seem not to be clickable for download. I really want this fixed as I'm starting to hack my 3ds

**Comment by Plailect** [comment]
They're magnet links.
