### ISSUE TITLE
Use SafeSysUpdater

### ISSUE THREAD

**Issue by n4ru** [Plailect/Guide#8]
SafeSysUpdater is finally safe, and will prevent bricks using wrong FW files.

See:
https://github.com/Cpasjuste/SafeSysUpdater/commit/7b13bc418885d911d5d97662d3edafae9e807ef0

Should have people download the latest release (1.0) and use it to downgrade/upgrade.

**Comment by Plailect** [comment]
Does it include hashes for 2.1.0 aswell?

**Comment by Plailect** [comment]
I will once 2.1.0 hashes and an update function are added.
