### ISSUE TITLE
Error in part 5 - Section I - Preparatory work

### ISSUE THREAD

**Issue by Xenon-Hacks** [Plailect/Guide#80]
https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax-&-AuReiNand)

Says:Copy MiniPasta.3dsx and MiniPasta.smdh to the /3ds/ folder on your SD card

When it should say: Create a folder called MiniPasta inside of the /3ds/ folder and copy MiniPasta.3dsx and MiniPasta.smdh to the /MiniPasta/ folder on your SD card

**Comment by Plailect** [comment]
It can be placed directly in the folder.

**Comment by fox8091** [comment]
Well, putting the SMDH there is pointless then..
