### ISSUE TITLE
ctrtransfer_CTR-0_15_20-panda_snake.zip torrent dead

### ISSUE THREAD

**Issue by joemck** [Plailect/Guide#800]
The ctrtransfer_CTR-0_15_20-panda_snake.zip torrent on the 0_15_20-ctrtransfer page and referenced in rss.xml is dead. There's a bunch of peers in it and they're all at 99%. The first chunk is missing; everyone already has all the others.

**Comment by jaxrogers2** [comment]
I noticed this too, while I wouldn't ever use the devGuide since I don't have a dev 3DS (just a normal retail Flame Red old3DS and possibly a retail Metallic Red New3DS XL on the way), this torrent is still dead and is needed to complete the devGuide for those who need it.

**Comment by Plailect** [comment]
Oh. I'll fix this.
