### ISSUE TITLE
Suggestion for the partial 9.2 downgrade instructions in case the user was using steelhax as his entrypoint

### ISSUE THREAD

**Issue by AlexisFelix** [Plailect/Guide#802]
The guide says that you can use browserhax as an entrypoint to regain access to the homebrew launcher and downgrade a second time to install all the files that were not installed, but doesn't tell you that if sysDowngrader keeps freezing at the beginning of the process (stuck in "attempting svchax..."), you need to install HomeMenuHax and launch the homebrew launcher from it to make sysDowngrader work correctly.

**Comment by Plailect** [comment]
That's because it works fine from browserhax. Anecdotal evidence from this working for you doesn't mean this is the case for everyone else.
