### ISSUE TITLE
A9LH II.2: Note no QR

### ISSUE THREAD

**Issue by RollingStar** [Plailect/Guide#804]
"Go to http://dukesrg.github.io/2xrsa.html?arm11.bin on your 3DS"

Note that there's no QR codes in 2.2 camera, so don't bother trying to make a QR code.

**Comment by pbanj** [comment]
first its 2.1 and second the guide doesnt tell you to even try to make a qr for it. it give the link for a reason. the guide assumes you have some common sense so you should be able to get hey if it could be a qr it would be.

**Comment by Ev1lbl0w** [comment]
"_Don't fix what's not broken._"
