### ISSUE TITLE
A9LH Prep: Replace with automatic process

### ISSUE THREAD

**Issue by RollingStar** [Plailect/Guide#808]
https://3ds.guide/installing-arm9loaderhax

This is a long shot, but a lot of the prep work could be replaced with a [Modmii-like](https://gbatemp.net/threads/modmii-for-windows-official-support-topic.207126/) program. The first part of this section is just downloading files and extracting specific files from them and putting them in specific places.

If you really wanted to, you could even include the torrenting part in this, but that creates two problems:

1. Hit and run on torrents
2. Inciting and enabling downloading of files that aren't hosted regularly on the web for good reason

There are plenty of programs that would download and manipulate the files, many of them built-in at the OS level. If a cross platform solution was desired, Python or some other language could be used.

And for those who don't want to run a program, the guide could split into an A and B section at the start of this page, like it does with "Section IV - Restoring the System" parts 1 and 2.

**Comment by mariogamer2** [comment]
This probably create noob-like user that want everything done automatically....

IT's my point of view...

**Comment by pbanj** [comment]
or people can just learn to read and follow basic instructions. people mess up because they dont pay attention. all automating it will do is make people pay even less attention.

**Comment by RollingStar** [comment]
>or people can just learn to read and follow basic instructions. people mess up because they dont pay attention. all automating it will do is make people pay even less attention.

If this was the guiding philosophy, the guide would never have been written. As far as I can tell, it's absolutely supposed to make noobs able to hack their 3DSs.

**Comment by pbanj** [comment]
> If this was the guiding philosophy, the guide would never have been written. As far as I can tell, it's absolutely supposed to make noobs able to hack their 3DSs.

that is why i said basic instructions. this guide is noob friendly. making it so they have to pay even less attention isn't noob friendly. it would cause them to fuck up more as they wouldn't pay any attention at all.

if you cant handle basic shit like download this, move this to sd card, run this, etc... you shouldn't be hacking any sort of system.


what you're asking for
![image](https://cloud.githubusercontent.com/assets/17306233/21539948/9b3d7910-cd79-11e6-8075-429288322f3f.png)

**Comment by mariogamer2** [comment]
@pbanj :P

**Comment by RollingStar** [comment]
It looks like OCS [automates much of the process](https://3ds.guide/installing-boot9strap-(homebrew-launcher)). Why the change of heart?
