### ISSUE TITLE
Before doing anything,dumping nand should be prompted

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#809]
There's nothing before ctrtransfer that prompt the user to make a dump of the actual nand. (I mean when you are already in a firmware where you can use D9WIP).

For example:

Main page -> Get Started -> Get started old 3ds eur -> 9.2.0 Decrypt9WIP with browser -> 2.0.0 transfer (Nothing prompt the user to dump the NAND)

**Comment by CrystalMoogle** [comment]
Doesn't Decrypt9 itself prompt you before you do the actual transfer?

**Comment by dark-samus** [comment]
It does.

**Comment by mariogamer2** [comment]
forgotten,sorry
