### ISSUE TITLE
AuReiNAND 5.1+ Payload Labeling Issues and a couple CFW page enhancements

### ISSUE THREAD

**Issue by jaxrogers2** [Plailect/Guide#81]
In the AuReiNAND section, Part 5, and steps 9-16 in the guide, it states to name your payload files "def_Decrypt9.bin", "y_emuNAND9.bin", and "x_uncart.bin" and put them into the /aurei/payloads folder on the SD card. However, on the AuReiNAND github Wiki page located here (https://github.com/AuroraWright/AuReiNand/wiki/Installation-and-Upgrade), under the "Upgrading from 5.0 to 5.1.1" section, it states that the payload files can be no longer than 13 characters, including the 4 ".bin" characters at the end or else they will not work. This is also mentioned on the wiki page located here at [https://github.com/AuroraWright/AuReiNand/wiki/Other-features-and-notes]. This means that the payload file names mentioned above that are in the current guide's instructions (except "x_uncart.bin", since it has 12 characters) would not work. Instead, shorthand alternatives need to be used, such as "def_d9WIP.bin" and "y_emuN9.bin" and replaced in part 5, steps 9-16 of the guide.

Also, this is somewhat of an add-on, but if you made the ARM9 chainloading payload key the same for CakesFW and AuReiNAND in the guide so that A, B, X, Y, etc loads the same thing on both as set up in the guide, it would help to maintain consistency and to make switching between the two CFWs easier. Similarly, it is not necessary to reinstall A9LH after restoring a pre-A9LH backup to switch your CFW. You can just put the new CFW files on the SD card and rename any overlapping files from your old CFW to something else (such as renaming "arm9loaderhax.bin" from CakesFW to "arm9loaderhaxCakes.bin"). Then, if the new CFW works properly, you can just delete the files (such as the cakes folder, the boot_config.ini, "arm9loaderhaxCakes.bin", etc. if you switched from Cakes to AuReiNAND) that corresponded to your old CFW. No A9LH reinstallation required.

Lastly, it might be good if you linked the AuiReiNAND github guide (located at https://github.com/AuroraWright/AuReiNand/wiki) to the main Part 5 page or to the page specifically about AuReiNAND in Part 5. This is because this wiki might be really helpful for anyone who doesn't know how to update AuReiNAND, as it gives specific instructions on how to update from certain AuReiNAND versions on the "Installation and Upgrade" page. Also, the "Options and Usage" along with the "Other Features and Notes" pages would help 3DS hacking noobs to make a more informed decision to which CFW they should use with A9LH.

**Comment by Plailect** [comment]
Done
