### ISSUE TITLE
n3ds 8.1.0-XXJ

### ISSUE THREAD

**Issue by arubar0** [Plailect/Guide#811]
The guide sends you to **"Homebrew Launcher (Browser)**", to set up menuhax etc... and we know this is not possible below 9.0
Although I don't even know if New 3DS 8.1.0 JPN with browser exists... but just in case

**Comment by Plailect** [comment]
Once SoundHax can launch Decrypt9 on versions <9.0, NTR & Cubic Ninja should no longer be required.
