### ISSUE TITLE
SafeA9LHInstaller 2.0.3, but current is 2.6.7

### ISSUE THREAD

**Issue by Pitel** [Plailect/Guide#812]
Page: installing-arm9loaderhax

Is old SafeA9LHInstaller 2.0.3 really needed? I noticed there was an issue with 2.0.2, but 2.0.3 seems to be old now.

Disclaimer: I'm going to hack my first 3DS soon, and I want to do it right, and with latest stuff possible.

**Comment by rocket0634** [comment]
installer 2.5 (the version after 2.0.3) is just for the otpless method using New 3ds. 2.5-2.6.7 only focus on this method, and it's been known to cause random bricks.

As such, version 2.0.3 is the version recommended in the guide for both N3ds and O3ds, until the issue is solved.

**Comment by Pitel** [comment]
Okay. :)
