### ISSUE TITLE
New guide issues

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#819]
The guide only points you to the "NFIRM downgrade" page for 11.2, not 11.0-11.1.  However, the NFIRM downgrade page itself still says "If you are between 11.0.0 and 11.2.0...."  Also, the NFIRM downgrade page contains a section "Use this link to downgrade your NFIRM with DSiWare and one of four listed games (11.0.0 through 11.1.0 only)"  Since this page is no longer used for 11.0 and 11.1, the section is never used.

Also, you may as well replace the page with one which says "11.2: Wait for Fasthax to come out".

**Comment by kade-robertson** [comment]
Instead of completely removing information to say "Wait for fasthax", why not just leave it as it is and update when fasthax is ready? Doesn't make sense to remove something that works. Maybe a notice at the top would be fine.
