### ISSUE TITLE
Suggestion regarding reporting issues

### ISSUE THREAD

**Issue by sora10pls** [Plailect/Guide#820]
Perhaps have a button somewhere at the top of each page in the guide that links people to https://github.com/Plailect/Guide/issues/new where they can report issues if they feel it's necessary

![image](https://cloud.githubusercontent.com/assets/17801814/21600567/6ff3ef42-d14c-11e6-883d-85a607cdcd74.png)

**Comment by mariogamer2** [comment]
You also should have a .github folder with an ISSUE_TEMPLATE.md in it (default text in an issues).

**Comment by mariogamer2** [comment]
#822
