### ISSUE TITLE
Installing A9LH - Section IV - Step 3.

### ISSUE THREAD

**Issue by miltoncandelero** [Plailect/Guide#821]
It reads:

> * Regardless of whether or not you did either of the above two steps, update your 3DS by going to System Settings, then “Other Settings”, then going all the way to the right and using “System Update”
>   * Updates while using A9LH + Luma (what you have) are safe, stop asking about it
>   * If this gives you an error, set your DNS settings to “auto”
>   * If this still gives you an error and your NAND is below 9.2.0, follow 9.2.0 ctrtransfer

Doesn't a New 3DS brick if you try to update from 2.1.0?

(We are assuming here that the person decided to skip step one as step three says *"regardless of whether or not you did either of the above two steps"* )

**Comment by SMarioMan** [comment]
If the user is on 2.1.0, then they would need to follow step one before following step 3. This is indicted in the guide. 

> 1. If you have done 2.1.0 ctrtransfer, restore NANDmin.bin:

**Comment by miltoncandelero** [comment]
I know, but as step 3 disregards step 1 maybe errors may occur.

**Comment by Plailect** [comment]
>Doesn't a New 3DS brick if you try to update from 2.1.0?

Luma3DS cannot even boot 2.1.0 on n3ds.
