### ISSUE TITLE
Minor nitpick regarding Section VI - Finalizing setup of the last page

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#827]
**Select “SD”
Select “cias”**
Navigate to FBI.cia and press (A) to install
Navigate to hblauncher_loader.cia and press (A) to install
Navigate to lumaupdater.cia and press (A) to install
**Navigate to arm9loaderhax.bin, then press (A) on it and select the “Copy” option**

Someone recently got confused why they couldn't find arm9loaderhax.bin in SD:/cias/... Can you add a quick B press step in-between?

**Comment by lordscales91** [comment]
I would add it in the same sentence as the lumaupdater.cia. Like this:
Navigate to lumaupdater.cia and press (A) to install. Press (B) to go back.
...
