### ISSUE TITLE
Downgrading (repeated softbricks)

### ISSUE THREAD

**Issue by Scenekakashi** [Plailect/Guide#83]
I'm having some problems downgrading my EUR N3DS. I've tried three times so far on 10.3 and on 10.7 and every time PlaiSysUpdater says it's successful but freezes on the "Rebooting in 10 seconds" part at the end and when I force the power off and boot up again I get the Nintendo "error has occured" message and i'm forced to go into recovery mode and update to the latest firmware again.

I've found a few threads of this on gbatemp with others having the same issue, all people with N3DS and apparently if they format then it works first try afterwards, but I dont wanna lose any data so dont really wanna do that

Might be worth adding this to the Troubleshooting section, because if this happens and you dont have Cubic Ninja or OOT then you can't access the homebrew menu again

**Comment by Plailect** [comment]
This is not something that has a known solution beyond formatting, so that may be your only option. 

Use svdt to backup your saves and reinstall the games later if you decide to format.
