### ISSUE TITLE
Region Changing Question

### ISSUE THREAD

**Issue by theplumber123** [Plailect/Guide#831]
@Plailect With the many recent changes occurring with the 3DS scene (Soundhax, Safehax, etc), is the guide on Region Changing still up to date? That is, do we still use the 9.2.0 ctrtransfer image, etc?'

I plan on following your guide on installing A9LH + Luma3DS and proceed with following the Region Changing with. Please let me know if this is the correct way of proceeding.

 Thanks!

**Comment by Plailect** [comment]
Those are all just entrypoints. They do not affect the Region Changing process.
