### ISSUE TITLE
Hombrew Launcher don't load

### ISSUE THREAD

**Issue by angelop16** [Plailect/Guide#832]
Hi guys, I have a problem. Hombrew Launcher don't load when I open the soundhax file, it freez on the red screen. Thanks for the help.

**Comment by Committee** [comment]
Did you download and place the otherapp.bin on the root of your sd card?

**Comment by angelop16** [comment]
Yes e now it's work. But I have another problem. Drecrypt9 don't load when I open safehax. xD
