### ISSUE TITLE
Decrypt9 don't load when I open safehax

### ISSUE THREAD

**Issue by angelop16** [Plailect/Guide#833]
Guys I have another problem. Decrypt9 don't load when I open safehax.

**Comment by CyHo** [comment]
Copy Decrypt9WIP.bin from the Decrypt9WIP .zip to the root of your SD card and rename Decrypt9WIP.bin to arm9.bin

did you do this one?

**Comment by angelop16** [comment]
Yes I do this, but when I open safehax it freez in black screen

**Comment by masamune99** [comment]
I have  the dame problem please help ... My firmware is 11.0.0.33 N3ds USA.

**Comment by masamune99** [comment]
I dos everything like the guide told me, cant access decryt9 from the HBL either,  when I use the safehax  It says beggining attempts And then goes black.

**Comment by angelop16** [comment]
I use the previous version of decrypt9 and now it work

**Comment by masamune99** [comment]
Please Angelo rellenar me what versión!!

**Comment by Armastan** [comment]
I had some friends running in this problem, they updated to 11.2 and it worked.

**Comment by masamune99** [comment]
Do I hace tiempo update my 3ds?

**Comment by masamune99** [comment]
Do I have to update my 3ds?

**Comment by masamune99** [comment]
Everything works except decryt9 I Fontana know what yo do

**Comment by pbanj** [comment]
Maybe use spell check

**Comment by angelop16** [comment]
This is the page https://github.com/d0k3/Decrypt9WIP/releases and this is the version Decrypt9WIP all-in-one 20161111

**Comment by mabvmet** [comment]
@angelop16 I went to the Decrypt9WIP github profile, I try to use a previous version of it, I downloaded the .zip file, but what file should I use?

- How to replace it into my SD card, I am using the  **arm9loaderhax + CFW** (homebrew launcher + soundhax) and my versión is 11.0.0.33-U.

Thanks!
