### ISSUE TITLE
Error with updating at 9.2.0

### ISSUE THREAD

**Issue by FatherYas** [Plailect/Guide#835]
when I go to update the system through the system settings it says there's an error and restarts the system. What did I do wrong??

**Comment by cubecubec** [comment]
then you should try to inject CTR 9.2.0 using Decrypt9 choose auto CTR transfer.then you can update the system properly

**Comment by FatherYas** [comment]
it didn't help tho, I still can't update

**Comment by cubecubec** [comment]
check the troubleshooting section mate.
