### ISSUE TITLE
[Suggestion] The process of backing up Title/Titlekey needs a better explanation

### ISSUE THREAD

**Issue by lordscales91** [Plailect/Guide#838]
On the ctrtransfer guide: https://3ds.guide/2.1.0-ctrtransfer

The section II says:
```
Delete all .tik files in the /files9/ folder that do not start with “00-“
Leave all the .tik files that do start with “00-“ in the folder
    If none start with “00-“, then just continue.
```
This part it's a bit unclear to me. I have very clear that if there are files which start with "00-" and files which don't I need to delete the latter ones. However, if there are no files which start with "00-". Should I remove them all or leave them there? It seems a bit confusing. Why not merge them into a single sentence like: 

Delete **only** the .tik files in the /files9/ folder that **do not** start with "00-"

**Comment by lordscales91** [comment]
@Plailect Sorry to bother you again but... From what I saw in the commit it seems like it's not necessary to backup the tickets for the 2.1.0-ctrtransfer but only for the 9.2.0-ctrtransfer. Am I right? If the answer is yes then: Why it is only necessary for the 9.20?

**Comment by kade-robertson** [comment]
@lordscales91 I believe the reason is because when you restore from your NAND backup, you get your tickets back. Since there's no (necessary) 9.2.0 step anymore, there's no ctrtransfer that makes you lose your tickets.
