### ISSUE TITLE
Update safehax to the newest revison+safehaxpayload.bin

### ISSUE THREAD

**Issue by trbocode** [Plailect/Guide#842]
Kasher_CS made a build https://gbatemp.net/attachments/safehax-7z.73852/
Works fine for at least 2 users

**Comment by Plailect** [comment]
I'm just going to switch to using the latest release of each now that official releases for both exist.

**Comment by jaxrogers2** [comment]
Yeah, there's now a cartridgeless safehax from GBATemp that fixed the timing issue requiring a cart to be inserted here at https://gbatemp.net/attachments/safehax-zip.74069/

This could then be used with fasthax Beta 2 at https://github.com/nedwill/fasthax/releases/tag/v0.2.0
