### ISSUE TITLE
Add to troubleshoot what to do with a N3ds on 2.1.0 with no nand backup.

### ISSUE THREAD

**Issue by miltoncandelero** [Plailect/Guide#843]
A lot of people either skipped the backups or deleted them by accident.

On new 3ds they can't update away from 2.1.0

I think they can do a 9.2.0 crttransfer but I am not sure and the guide doesn't tell you what to do :/

(not my problem, just saying for the people I've seen on Reddit)

**Comment by miltoncandelero** [comment]
(I am not sure if the CTRtrasfer is the right way, that's why I don't do the PR myself. If confirmed to be the right step I will pr myself)

**Comment by Plailect** [comment]
1. These people are idiots.
2. I'll add the ctrtransfer later.
