### ISSUE TITLE
Translation / Language Support

### ISSUE THREAD

**Issue by kevinchau321** [Plailect/Guide#848]
I recently heard of a youtube video in another language that caused tons of people to brick their 3ds. If the guide supported other languages, mistakes like this wouldn't happen. We should add translations so that more people can follow this definitive guide.

I would suggest that Spanish and French be the first translations to focus on.

**Comment by mariogamer2** [comment]
@THEDARKK Have a french one: https://github.com/THEDARKK/Guide

**Comment by Armastan** [comment]
There are multiple translations on the internet, most of them on forums. The problem with having officially linked translations is that some of them might end up out of date (as happened before).

I am myself keeping an Spanish translation active and I've seen a couple more that are good.

**Comment by mariogamer2** [comment]
Why not somewhat merging everything? (not exactly merging...)

**Comment by Plailect** [comment]
I will tentatively agree to look into this.

Currently thinking of using [this](https://www.sylvaindurand.org/making-jekyll-multilingual/) with each translation as a git submodule, but this would be a *lot* of work.

**Comment by Plailect** [comment]
I have also submitted a request to https://crowdin.com/page/open-source-project-setup-request

**Comment by Plailect** [comment]
Update: This is going to be a *massive* undertaking. I'm working on getting the page directories into a usable format for this and implementing a language selector.

**Comment by kevinchau321** [comment]
@Plailect I'm glad to see that you support the translation effort. I know it's a daunting task but if other open source projects on github can successfully implement translation and localization I don't see why this one wouldn't be able to as well!

**Comment by derkalaender** [comment]
So my plans with this https://ostos9r.oneskyapp.com/collaboration/project?id=93812 are completely useless?

**Comment by jkcgs** [comment]
@derkalaender let's use Plailect's setup, so we have the "official" status.

I'm also translating in [this fork](]https://github.com/jkcgs/Guide) so then we can start on a base, also keeping up to date with upstream.

**Comment by Plailect** [comment]
@derkalaender The work will probably be easily ported over.

![image](https://cloud.githubusercontent.com/assets/16979510/21743027/3e258974-d4c8-11e6-8861-d0103e9e400d.png)

**Comment by jkcgs** [comment]
Great! Please count me in! :smile:

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/49ee6c019a9400c1cc60b5585a019629e96c4dff

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/72a9def7dc9ef0163490cabdee71a3847d27dc00

**Comment by m1guelpf** [comment]
I'd also like to help with an Spanish version!

**Comment by THEDARKK** [comment]
@Plailect  Ready for french version 👍

**Comment by derkalaender** [comment]
Well then I can translate to German!

**Comment by jkcgs** [comment]
I paused the spanish translation to wait for the official setup

**Comment by THEDARKK** [comment]
@jkcgs same for french version

**Comment by zimlokks** [comment]
Same here, I'll help with the Spanish translation

**Comment by jkcgs** [comment]
@Plailect Remember that it's possible that we need to split Spanish translations, but we need to discuss that issue.

**Comment by zimlokks** [comment]
@jkcgs honestly I think we're gonna have to do  both but add labels to them

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/be1c2c5cb81b1d13637867a0b5c55cb39b5de8c0


![image](https://cloud.githubusercontent.com/assets/16979510/21743824/4355872c-d4d8-11e6-9b1c-85a3a719a735.png)


![image](https://cloud.githubusercontent.com/assets/16979510/21743822/40548f28-d4d8-11e6-8909-1da094de9299.png)

**Comment by jkcgs** [comment]
I think that means you should use four language code (like pt-BR)

**Comment by gselivanof** [comment]
Could you add Greek as a language available for translation? I would love to translate your guide to Greek :D

**Comment by jkcgs** [comment]
@gselivanof It's added on Crowdin

**Comment by derkalaender** [comment]
@jkcgs is the crowdin up and running yet?

**Comment by jkcgs** [comment]
@derkalaender Looks like it's not ready yet

**Comment by mariogamer2** [comment]
Huuuu.... Sorry for the question,but **what is crowdin?** X)

**Comment by jkcgs** [comment]
@mariogamer2 A platform for crowdsourced translation

**Comment by gselivanof** [comment]
I saw that he created some folders on GitHub, one for each language, including all the files that required translation, and Greek wasn't one of them. With crowding am I going to be able to translate it to Greek?

**Comment by jkcgs** [comment]
Maybe the files will be added later, but, as I said, the language option is there

**Comment by gselivanof** [comment]
Okay thanks

**Comment by Ev1lbl0w** [comment]
Already doing some Portuguese translation with the already translated parts in my fork xD

**Comment by monaaaar** [comment]
I also have some questions. Is translation proceed in GitHub? Are there any dashboard such as this screenshot?
![20120122110736.png](https://cloud.githubusercontent.com/assets/24962254/21744582/eab3131c-d55b-11e6-94a9-3f9d545cf21c.png)

**Comment by Ev1lbl0w** [comment]
I don't know if it's this that you want, but, here's the crowdin link for the guide: https://crowdin.com/project/3ds-guide

**Comment by jkcgs** [comment]
I didn't wanted to comment the link here so the platform is not spammed now that is not ready yet

**Comment by Ev1lbl0w** [comment]
Yeah, sorry about that. Deleted it.

**Comment by THEDARKK** [comment]
@jkcgs https://github.com/Plailect/Guide/pull/860 ?

**Comment by jkcgs** [comment]
@THEDARKK but that doesn't mean it's ready, Plailect hasn't said anything yet

**Comment by monaaaar** [comment]
Oh, I should't touch anything so far...?
Thanks for answers.

**Comment by derkalaender** [comment]
Can we start translating?

**Comment by mariogamer2** [comment]
@derkalaender Asking the same question.

**Comment by jkcgs** [comment]
We should wait for Plailect

**Comment by mariogamer2** [comment]
http://translate.3ds.guide/translate/3ds-guide/

**Comment by monaaaar** [comment]
Wow, I found the 404. I guess the path is not needed ( http://translate.3ds.guide/ )

**Comment by monaaaar** [comment]
Can I join and translate to Japanese? @Plailect hasn't said anything about yet...

**Comment by monaaaar** [comment]
Can I join and translate to Japanese? @Plailect hasn't said anything about yet...

**Comment by monaaaar** [comment]
Can I join and translate to Japanese? @Plailect hasn't said anything about yet...

**Comment by Plailect** [comment]
The current roadblock is that Crowdin is messing with my markdown formatting and breaking everything.

Regular page: https://raw.githubusercontent.com/Plailect/Guide/master/_pages/en_US/2.1.0-ctrtransfer.md
Crowdin parsed page: https://raw.githubusercontent.com/Plailect/Guide/l10n_master/_pages/af_ZA/2.1.0-ctrtransfer.md

**Comment by monaaaar** [comment]
Oh... Should I stop translation on Crowdin?
I started translation on Crowdin because you're active

**Comment by Plailect** [comment]
Just be aware that you could lose your progress.

**Comment by monaaaar** [comment]
All right. I translate on my fork at first and copy to Crowdin. Thanks a lot.

**Comment by jkcgs** [comment]
We are gathering translators on this Discord server https://discord.gg/fmdrm so we can coordinate the translation. We are also asking people to wait for an announcement.

**Comment by monaaaar** [comment]
All right. I translate on my fork first and copy it to Crowdin. Thanks a lot

**Comment by Deltios** [comment]
I'll help translating to Dutch

**Comment by majia67** [comment]
The Simplified Chinese version has always been actively maintained in my repository. I also noticed that the Crowdin project has already been set up. Until an official notice here that the translation is ready to be ported, I will maintain the update in my repository. Just to make an announcement here to prevent repeat work.

**Comment by jkcgs** [comment]
@majia67 keep the good work! When everything is ready, you should be able to port the translation easily.

**Comment by rikumax25** [comment]
@jkcgs i cannot join the discord .-.

**Comment by jkcgs** [comment]
@rikumax25 https://discord.gg/HPgJzjM there you have it

**Comment by mariogamer2** [comment]
Just like this.... #860 is it a bot of crowdin?

**Comment by jkcgs** [comment]
Looks like it's set up to push translations with Plailect's account

**Comment by mariogamer2** [comment]
Yep. I was thinking to XD.

**Comment by Plailect** [comment]
Yes, that's a bot linked to my account that makes the pull requests and commits to the l10n_master branch.

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/766a7ad69b306abc96be9b7065cca801a8351777

**Comment by Plailect** [comment]
:D
