### ISSUE TITLE
Artifacts on both screens after install a9lh

### ISSUE THREAD

**Issue by m0uthless** [Plailect/Guide#857]
Hi,
yesterday i follow the guide and i installed a9lh successfully.
Unfortunately, once restored nandmin.bin I noticed artifacts like this http://imgur.com/a/A87Ia
I tried to use Config_v11_4_NAND.cia like issue #794 says but nothing change.

Is a 2DS with Sys 11.2.0-35E

**Comment by jaxrogers2** [comment]
I believe you can use one of the dev apps to reset it manually...
