### ISSUE TITLE
Adding Photos And/or Video to Guide

### ISSUE THREAD

**Issue by ricksee** [Plailect/Guide#858]
Is it possible to add photos or a video to the guide for make it easier for users who are uncomfortable with only text and the many warnings in the text. I know they get outdated quick, but it seems to be a more of a necessity since people still go to YouTube videos for help, even though it is not recommended.

**Comment by Hikari-chan** [comment]
This is a dumb idea. Text is the easiest, quickest way to convey information and there is absolutely no justifiable reason for someone to be "uncomfortable with only text". Any users claiming to be are simply lazy, and deserve what they get.

**Comment by ricksee** [comment]
@Hikari-chan I don't think that's fair to those users. Some people could understand more because visuals might make it easier for them to understand. There are some people that don't fully understand English and translation projects haven't really caught up yet.

**Comment by Hikari-chan** [comment]
The translation projects are being worked on as we speak, and aren't a justification for further lobotomizing the guide. Additionally, the text is as simple as could be, someone with even a basic grasp of English should be able to understand it; if they can't, they don't need to be trying to hack any of their devices in the first place.

**Comment by ricksee** [comment]
Despite all of the inconveniences video guides result in, some people will look and or make for them. By just telling people not to use video guides, I don't think we do them a favor, because they just won't say anything and find one by themselves, and this can be disastrous, as seen by the recent bricking fiasco.

**Comment by Hikari-chan** [comment]
Like I said, if they're so lazy they refuse to read a bit of text, they deserve the consequences. 

"Play stupid games, win stupid prizes."

**Comment by ricksee** [comment]
I don't think these people deserve to lose their device because of this though. I think it is more than refusing to read it, but it tends to be confusing or to cluttered for them.

**Comment by Hikari-chan** [comment]
It's not confusing or cluttered. The guide is as simple as could be, as I said prior. And, as I said earlier, if they're so incompetent that they can't handle such a basic text guide, they shouldn't be attempting to hack their devices in the first place. 

They **do** deserve to lose their devices if they do not read the guide fully and head all of its warnings.

**Comment by ricksee** [comment]
How about this, splitting the process into several parts with a small video or gif in between.

**Comment by ricksee** [comment]
I know this is an unpopular opinion, but I feel like there should be at least something for visual learners who see visuals as easier than text.

**Comment by Ev1lbl0w** [comment]
I don't think this idea is completely stupid. I remember [this tutorial on GBATemp](https://gbatemp.net/threads/tutorial-setting-up-9-0-9-2-n3ds-xl-for-cfw-including-emunand-coldboot-cia-installer.405589/) that uses useful screenshots after some stpes for convenience.

"The tutorial is step by step. Just follow it closely from start to finish. If you see the little [​IMG] icon, that means there is a helpful screenshot available for that step. Just click it to open the screenshot."

I don't think it's a bad idea. In fact, when I hacked my 3DS long ago, I was always scared I might do something wrong. Using simple GIFs and images should help those people feel more comfortable when following the guide.

**Comment by derkalaender** [comment]
I have an idea. We could create a youtube channel and upload videos to youtube in every language. These videos follow some guidelines specified by Plailect of course. That way it is official and correct. We could then link the specific Video to the selected language on 3ds.guide (Btw I'm also more comfortable using videos/pictures than plain text)

**Comment by Ev1lbl0w** [comment]
The only downside of doing this would be the time it takes to make those videos and the frequency this guide is updated.

**Comment by derkalaender** [comment]
It wouldn't take that much time. You could point out edits with annotations. If it gets too old you could make an updated video

**Comment by ricksee** [comment]
If there is a change of a visual guide of some sorts, it needs to be approved and somewhat professional and clear. Thanks for all that are at least open to the idea.

**Comment by kevinchau321** [comment]
I don't mean to polarize people on this issue, but I think adding videos and images clutter up the guide and make it harder to follow. Yes I know the guide is a little long, but its really not all that complicated, just read each line. This issue should be closed.

**Comment by ricksee** [comment]
@kevinchau321 There are people that still have trouble with the guide and don't understand English all that well. Something should be done for the visual learners and not just "let them live with the consequences."

**Comment by kevinchau321** [comment]
@ricksee Check out the crowdin effort going on for translations that Plailect himself has set up

**Comment by s1cp** [comment]
I can't see why adding screenshots is bad.
If you can see what you're supposed to be doing, you get more confident that you're following the steps correctly. They should complement the guide and not be a replacement for the text instructions.
If you are bothered by them, just implement some kind of switch to hide all pictures.
Options are always welcome.

**Comment by ricksee** [comment]
@kevinchau321 It helps, but it probably won't complete solve the problem as there are people still rely too much on visuals like YouTube and screenshots to increase their confidence. What would also help would be an official visual guide to increase confidence.

**Comment by ricksee** [comment]
@s1cp Exactly, this will help with the guide, not to replacement. Visuals can be an additional help for the community and it can reduce question load.

**Comment by Plailect** [comment]
I agree with @Hikari-chan.
