### ISSUE TITLE
AuReiNAND: adding emuNAND option

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/Guide#86]
For the part of configuring AuReiNand ( https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax-&-AuReiNAND)#configuring-aureinand ), does it is possible to add EmuNAND option (not only updated sysNAND)

**Comment by Plailect** [comment]
No. Read [this](https://www.reddit.com/r/3dshacks/comments/49qj9w/arm9loaderhax_if_you_dont_like_sysnand_permahax/d0ud80d).
