### ISSUE TITLE
3DS CTRtransfer failed: Not enough space on 4GB sd card

### ISSUE THREAD

**Issue by SarukoDark** [Plailect/Guide#862]
Hello everyone. I need some help pls.
I was about to start the ctrnand transfer on my 3DS. As i pressed 'Auto CTRNAND Transfer', it  looked like it would worke fine, untill it said that i don't have any space left. It was right at the beginning, it didn't even start to make the backup, so I stopped the process and it put me back into 'SysNAND Transfer Options'. What am i supposed to do now?

- Can i simply turn my 3DS off and turn it back on?
- Can i simply redo everything with a bigger sd card?
- Can i delete something from my sd card in order to get more space?

I kept it on and i'm waiting for someone to help me.
Pls i want this to work, but right now i'm too scared that i might brick my 3DS.
I think i would have done everything right, just this stupid problem i got there...

And pls one more thing. If somebody can help me, could it be with a step by step explanation? My english is not the best and i tend to misunderstand things really easyly.

I would appreciate some help.
Thanks in advance!﻿

**Comment by kevinchau321** [comment]
You should try redoing everything with a bigger sd card. Transferring to a larger sd card is easy, just make sure your new sd card is formatted fat32 and you should be able to just copy and paste everything over.

How much content do you have on your 4gb card by the way? IIRC the guide doesn't say you need to upgrade your card size if you have a clean/stock 3ds.
