### ISSUE TITLE
How do I uninstall a9lh?

### ISSUE THREAD

**Issue by FranticUmbreon** [Plailect/Guide#863]
I had previously installed a9lh on my n3ds, with the old guide which didn't include the 2.1.0 ctrtransfer for n3ds. So how do I uninstall a9lh to get my otp? (I dont have any pre-a9lh NAND backups..)

**Comment by jaxrogers2** [comment]
Use the .bin version of SafeA9LHInstaller (the latest one) and load it from A9LH. It has an uninstall option.

From there, follow the guide again to redo the process and get your OTP and install A9LH again.

**Comment by FranticUmbreon** [comment]
Thanks!
