### ISSUE TITLE
DSP Dump

### ISSUE THREAD

**Issue by 3llo00osh** [Plailect/Guide#864]
Hi Plailect,hi people
I've installed FBI, lumaUpdater, and Homebrew. I am now in the HB menu and I am supposed to select DSP DUMP. However, I just couldn't find the option DSP Dump.
Can anyone tell me what's going on here ?
Ps, I'm following the 3DS.guide to install the a9lh

**Comment by kevinchau321** [comment]
I believe you need to install Dsp Dump by downloading the release from here:
https://github.com/Cruel/DspDump/releases/tag/1.0
you should put it in your 3ds/ folder on your sd card. Then Homebrew Launcher will be able to see it. Let me know if that works.

**Comment by MooneyX545** [comment]
does not work kevinchau
