### ISSUE TITLE
Suggest using allocation size of 64k

### ISSUE THREAD

**Issue by spcrypt2** [Plailect/Guide#865]
Changing allocation size from 16 to 32 or 64 made Luma3DS boot on 2.1.0, but 16 didn't. A suggestion would be to tell users to format their SD to FAT32(32k/64k) with something like GUI Format before doing this guide. I encountered the issue and others in the Discord chat have as well.

**Comment by Plailect** [comment]
This is on the home page.

**Comment by deadair3210** [comment]
32k preferably, as people have repeatably reported issues of VC titles being affected by having the SD card formatted with 64k clusters
