### ISSUE TITLE
AuReiNand [Part 5]

### ISSUE THREAD

**Issue by axewfious** [Plailect/Guide#87]
AuReiNand's latest build needs the payloads and files to boot at start to be 13 characters max including the .bin.
https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax-&-AuReiNand)
Section 1, #14, renaming it to y_EmuNAND9.bin won't cause it to boot at Section 5, #5.
Renaming it to y_EmuN9.bin would be better

**Comment by Plailect** [comment]
Fixed
