### ISSUE TITLE
New Fasthax/Safehax not actually working

### ISSUE THREAD

**Issue by olliz0r** [Plailect/Guide#872]
From the amount of reports in the 3dshacking discord and the q&a on reddit I'd say the new fasthax/safehax combo is not working, everyone is getting stuck with a black top, red bottom screen. Please investigate before we get overrun by the same questions

**Comment by jaxrogers2** [comment]
Is this old3DS only? AFAIK fasthax is currently having issues with old3DS, but I haven't heard about New3DSes having problems.

**Comment by idgrepthat** [comment]
The files that zoogie posted boot 100% of the time. This change doesn't make sense.

**Comment by jaxrogers2** [comment]
The guide should use Zoogie's cartridgeless build then until this is resolved.

**Comment by jkcgs** [comment]
There are new releases for safehax and fasthax, maybe the should be used separatedly now?

**Comment by kade-robertson** [comment]
@jkcgs about an hour before your comment, the guide was updated with https://github.com/Plailect/Guide/commit/2d0ec87c2619ebba0d1386ca8e392690d137e745 to link to the official releases again.
