### ISSUE TITLE
2ds freezes when trying to go to http://dukesrg.github.io/2xrsa.html?arm11.bin

### ISSUE THREAD

**Issue by TheAzure289** [Plailect/Guide#88]
Everything succeeded up to this part: 

Section III - Getting the OTP

go to http://dukesrg.github.io/2xrsa.html?arm11.bin on 3ds.

What is causing it to freeze? Thanks in advance! :(

**Comment by Plailect** [comment]
Try it a bunch of times, also try clearing the browser history. Just fiddly, not a real issue.
