### ISSUE TITLE
Safea9lhinstaller

### ISSUE THREAD

**Issue by bonboncat** [Plailect/Guide#882]
Dear plailect,
I just wanna ask if is it ok to use safea9lhinstaller v2.0.3 instead of v2.0.6? 
I can't get it work with v2.0.6 from the guide. Always freeze at browser after loading arm11. 
Someone said to use v2.0.3 instead, but is it safe?
I have double or even quadruple check every files was place in the right place according to the guide to the word.
Sorry for this dumb question

**Comment by Plailect** [comment]
It's safe, but make absolutely doubly sure you do not have an `otp.bin` file in `/a9lh/`.

**Comment by bonboncat** [comment]
Yay it works now. Yup there's no opt. Lbin yet there. Now i get the otp from v2.0.3 instead of v2.0.6 
Thanks for your help
Case close :)
