### ISSUE TITLE
Safehax and Fasthax payloads aren't working.

### ISSUE THREAD

**Issue by BlackSpark644** [Plailect/Guide#883]
We've been having problems over on the Discord with the payloads linked in the Decrypt9 section of the guide. When people launch fasthax from the homebrew channel, they end up with a freeze and a red screen, and must follow the old instructions (https://www.reddit.com/r/3dshacks/comments/5lsfar/112_downgrade_success_with_combined_safehaxfasthax/)

**Comment by mysterypaint** [comment]
Agreed, I had helped someone on a separate server and realized the guide had been updated, resulting in the red screen. We ended up using the previous build of fasthax+safehax included in the guide: The one most people had used before the alpha came out.

**Comment by Plailect** [comment]
Should work fine with the latest fasthax release.
