### ISSUE TITLE
NAND Backup Assurance

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#885]
I notice there's a common trend of people failing to make NAND backups, and I want to point out two possible reasons:

> Performing a ctrtransfer will remove all user-installed tickets from the device until a backup is restored. Under NO CIRCUMSTANCES should you skip creating the backup, or you will LOSE access to all installed games and saves!

The guide here (and all other places it says something along these lines) can be interpreted that, "you don't need to make a NAND backup if you don't care about your games/saves." Can we just omit the last bit about the games/saves in that warning?

Additionally, some people have not been able to verify their NAND backup because they dumped it at the same time they're downgrading to 2.1 firmware... Some reported it was due to a bad microSD-to-SD reader or other factors, but the fact the NAND backup might not always dump properly is definitely something to consider here.

One extra note: I don't think the guide tells people to turn on/set up Wi-Fi on their 3ds before downgrading to 2.1, despite some people having only now bought their 3ds brand new. I do know it's possible to fix on 2.1, but I think it'd be better if the guide said to do so before the downgrade to ensure nobody has to reset their clock or set up Wi-Fi through safe firm.

**Comment by mysterypaint** [comment]
By the way, what happens when a user starts the guide from 2.1 firmware with a web browser? How would they restore NAND, or can they just system update directly from 2.1 without problems?

**Comment by ItsKipz** [comment]
I put in a PR to make the nand backup step clearer.

**Comment by CrystalMoogle** [comment]
>I don't think the guide tells people to turn on/set up Wi-Fi on their 3ds before downgrading to 2.1, despite some people having only now bought their 3ds brand new. I do know it's possible to fix on 2.1, but I think it'd be better if the guide said to do so before the downgrade to ensure nobody has to reset their clock or set up Wi-Fi through safe firm.

It makes two mentions of needing wireless, in a way. One tells you how to reset it, the other says you have to be connected to the internet. I would hope people understand after those two messages. Resetting clock isn't that big a deal, especially since after installing CFW, you can use [config menu](https://www.3dbrew.org/wiki/3DS_Development_Unit_Software#Config) to reset time without it changing time based games.

> How would they restore NAND, or can they just system update directly from 2.1 without problems?
They can try updating, sometimes it doesn't work, and the guide suggests a 9.2.0 ctrtransfer.
