### ISSUE TITLE
Guide error? - Cakes reboot into Decrypt9

### ISSUE THREAD

**Issue by dollerbill** [Plailect/Guide#89]
On the last page of the guide, setting up Cakes, it reads:

"**Section IV - Copying RedNAND data to SysNAND**

Reboot, then open Decrypt9 from arm9loaderhax by holding X on boot"

Shouldn't this say "open Decrypt9 by holding Start on boot" as X is used to launch Uncart?

**Comment by Plailect** [comment]
Fixed
