### ISSUE TITLE
Help, please. Issue with safehax. Complicated story.

### ISSUE THREAD

**Issue by dagjwfan** [Plailect/Guide#894]
Hello everyone,

So I have a N3DSXL and a few days ago I followed the guide to install Hombrew etc. Everything went perfect. I'm on 11.2.0.35U and I didn't have a single hitch. 

I was happy and using my newly hacked 3DS, downloading some games and dumping some of my own cartridges, when my SD card got corrupted and refused to work anymore. It just died on me. 

So I decided to buy another micro SD, and did a system memory format from the 3DS settings. I figured I might as well start the process again with the new SD card. 

So I did that and now I get stuck trying to run safehax into decrypt9. I just get a blank screen or the "failed init" error. I looked around and tried all possible solutions (putting a cartridge in before running safehax, etc) but nothing seems to work. 

What can I do? I'd like to just start over from zero, if possible. Don't mind the data loss nor redownloading everything. 

A couple observations in case they're useful:

- I still have the backup files from the otp and the files9 folder with all the tickets I got the first time I hacked my 3DS.

- I also manually copied all the contents of the SD card into a folder in my PC AFTER I finished hacking everything. 

- After the system format, I still get the Luma menu if I press reset when turning on the console. how do I get rid of this? 

Thanks a lot in advance.

**Comment by GerbilSoft** [comment]
A9LH is installed to NAND. There's no need to reinstall A9LH just because you swapped SD cards.

You should be able to just copy the old SD card contents to the new one, then use Luma's chainload feature to load Decrypt9WIP.

(The reason Luma config is still showing up is because you copied arm9loaderhax.bin to CTRNAND as per the last steps in the guide, which allows for SD-less CFW.)

**Comment by dagjwfan** [comment]
Thanks! Will this work even after having formatted the system memory on the 3DS? I'll give it a try.

**Comment by GerbilSoft** [comment]
"Format System Memory" doesn't actually format CTRNAND. (If it did, all the system software would be gone.) A better name would be "clear all user data and generate new IDs".

Luma in CTRNAND (and A9LH) isn't affected by a system format.

**Comment by dagjwfan** [comment]
Great! So I copied everything to the new SD card and things are working well, except for one thing.

All my legal digital games are back there, but none of the manually-installed .cias are. I downloaded a bunch of stuff from the freeshop and dumped my own cards, but those don't show up in the home menu anymore. 

I know the content is still there, somewhere in the depths of the "Nintendo 3DS" folder, but how do I make them show up again in the home menu as installed? 

When I go into the "tickets" folder with FBI, I see a long list of title IDs. Some are colored green (I can tell those are the titles that show up as installed) and some are colored red (those are the titles I downloaded from the freeshop//dumped myself). If I select one of the titles in red it gives me the option   "Install from CDN."

Should I do that manually for each title that doesn't show up (that'd take ages) or is there a way to have them show up again as installed in the home menu. 

Again, I can't express enough how greateful I am for your help!

**Comment by GerbilSoft** [comment]
Formatting usually resets the SD encryption key, which makes the contents of the "Nintendo 3DS" directory useless. System Format usually deletes these files.

Do the titles show up in Data Management? If they do, then there's something screwy with the ticket. Otherwise, you'll need to reinstall the titles.

**Comment by dagjwfan** [comment]
They don't show up in data management. 

By reinstall you mean what I mentioned before, doing it from the "tickets" folder in FBI? 

I've been reading a bit and indeed it seems to be a problem with the directory in "Nintendo 3DS."

**Comment by dagjwfan** [comment]
I think I've figured it out. Just need to reinstall them. It takes a while but everything seems to be back to normal. Thanks again for the help!
