### ISSUE TITLE
https://3ds.guide/2.1.0-ctrtransfer issue

### ISSUE THREAD

**Issue by BlastFurnaceNS** [Plailect/Guide#895]
Section II - ctrtransfer
2. Select the 2.1.0 ctrtransfer image when prompted by pressing (A), then input the key combo given

People are asking "I can't find the image!" Because it says "select image, then put in key combo", when it's actually "put in key combo, then select image"

It's pretty minor, but we get people asking about it constantly.

**Comment by badteddy81** [comment]
Hi BlastFurnanceNS,

i think i screwed up pretty bad. i followed the 3ds.guide but was multi tasking while doing so.

I have new 3ds xl latest firmware (11.2.0.35), followed guide (soundhax) to this page: (https://3ds.guide/2.1.0-ctrtransfer), ended up at Section II step #4,
Step #5: Once the transfer is complete, press (B) to go back. I skipped this step and read #8: Press (Start) to reboot without reinserting your SD card
As I was waiting for the 3ds to boot back up, I realized my mistake and was like, maybe I can restart the process.

Well I was wrong. At first, the 3ds wouldnt load up and just stayed blank. Next, I took sd card out, it loaded. Then I thought, let's clear out the sd card. So now I try to load the soundhax homebrew and it just freezes. I clearing the sd card and starting the process over, still the same result, soundhax freezes when trying to load homebrew. I am stumped. Any advice is truly appreciated!

**Comment by BlastFurnaceNS** [comment]
I don't believe this is the correct area to ask this sort of question, I will resolve it for you regardless.

You no longer need homebrew access. You are now on FW 2.1, remove your SD card if you would like to boot into the Home Menu, you can put the SD card into the system after booting.

You should now follow from the beginning of this page https://3ds.guide/installing-arm9loaderhax

**Comment by kevinchau321** [comment]
@BlastFurnaceNS 
A lot of issues on this repo are being opened by people having trouble with the guide/ following directions... not really bugs or errors with the code base or guide. *sigh*

**Comment by badteddy81** [comment]
BlastFurnaceNS,

Thank you for understanding. I will move forward with the guide. I have googled and searched and was in the incorrect section prior to this and was directed here. 

If you or kevinchau321 could direct me once again, I would appreciate it. Kevin, sorry if I have ruined your day from my post.
