### ISSUE TITLE
Failed to mount CTRAND. Cant access hourglass9/decrypt9wip/godmode

### ISSUE THREAD

**Issue by huygreat1996** [Plailect/Guide#896]
After installed arm9loaderhax i went on to config luma, saved and that screen appeared. Press any button and it will shutdown, turn on and it still at that screen, i cant even go to hourglass9 or others files in payloads folder by using button combination.

**Comment by kade-robertson** [comment]
Did you rename the payload files correctly?
Did you make sure they are in the payloads folder?
Did you make sure the payloads folder is named correctly?

**Comment by huygreat1996** [comment]
I'm sure those you listed. Found the issue and fixed, done hax!
