### ISSUE TITLE
Can't update A9LH installation

### ISSUE THREAD

**Issue by Invidious89** [Plailect/Guide#897]
I followed the steps in the guide about an hour ago explicitly as always, and I get this error when booting into down_safea9lhinstaller.bin[https://images.discordapp.net/.eJwNxksOhCAMANC7cABKy0frZQxBgk5UCNTVZO4-vtX7qqefalG7SBsLwHaMVPumh9QeS9al1nLm2I6hU70gisS0X_mWAcghWB_Ys5_fEzmgwEiWGSf0szMvIIOTQaQVDaGz-tOK-v0BBPUi6w.CvhtDUhiWIADgkMVpnkDbZ5CHYA?width=1125&height=2000](url)

**Comment by Invidious89** [comment]
![image](https://cloud.githubusercontent.com/assets/25084116/21898121/c64b155e-d8b9-11e6-917a-aea839fa5b13.png)

**Comment by Plailect** [comment]
Wrong `arm9loaderhax.bin`. Reread the instructions...

**Comment by Invidious89** [comment]
That is exactly what the instructions led to... I didn't deviate whatsoever.

**Comment by Invidious89** [comment]
I went and used AuroraWright's payload and it works. The one you have linked in the guide is what was broken for me. Just letting you know. No need to dismiss my question as me being an idiot. Thanks.
