### ISSUE TITLE
There is no step 28 through 32

### ISSUE THREAD

**Issue by orangpelupa** [Plailect/Guide#9]
Despite its being mentioned with BOLD in the tutorial

**Comment by Plailect** [comment]
There certainly is...

**Comment by orangpelupa** [comment]
On what part? I have searched every parts and can't find any :(

**Comment by orangpelupa** [comment]
Searching for 32 only give that sentence https://imgur.com/X1TFth7

**Comment by Plailect** [comment]
Directly above, beginning with

"Launch the Health and Safety Application (which is now FBI) on EmuNAND"

**Comment by orangpelupa** [comment]
This one? It says steps 8 and 9 on me. Maybe the public served a stale version of the page?

https://imgur.com/IV20pkl

**Comment by Plailect** [comment]
Github's mobile site cuts off the very left, try using landscape mode.
