### ISSUE TITLE
Warning for Luma3DS Updater

### ISSUE THREAD

**Issue by Ev1lbl0w** [Plailect/Guide#900]
Since AuroraWright's account was hacked, I think we should warn the people for now that they should not use Luma3DS Updater until this problem is resolved.

**Comment by jaxrogers2** [comment]
AW's account has been restored, although updating normal builds via Luma3DSUpdater will fail, as the downloads on the Github releases page don't currently work.

Updating from Hourly builds works perfectly fine though.

**Comment by jaxrogers2** [comment]
I agree that the Guide should direct to the Nightly site or the mirror of 6.6 stable Luma3DS until the Github releases are fixed though, as you can't download Luma3DS binaries from the Github releases page at all right now (you can only download the source), leaving people stuck.
