### ISSUE TITLE
Error updating A9LH

### ISSUE THREAD

**Issue by miltoncandelero** [Plailect/Guide#903]
Hi there.

I'm trying to update this console that is running godknowswhatversion of A9LH.

I follow the guide and when I press select to update it says

>Error: the OTP hash or the NAND key sector are invalid.

The OTP file is not there. first step of the guide is delete the a9lh folder. (and I don't have it for that matter).

So... what does "the nand key sector are invalid" means?

I am using the data_input_v4.zip (i noted that the guide for flashing uses v3. Don't know whats the difference) and the The latest fork of SafeA9LHInstaller (the .7z file) + The latest release of arm9loaderhax (the .7z file) **(As stated in the guide)**.

Triplechecked all the files are in the correct place. What am I doing wrong?

**Comment by nedwill** [comment]
Also have this issue on my N3DS.

**Comment by Plailect** [comment]
What happens when https://github.com/AuroraWright/SafeA9LHInstaller/releases/tag/v2.6.7 is used?

**Comment by nedwill** [comment]
I actually just tried that myself, and it worked.

**Comment by Plailect** [comment]
ah

I believe I did see a commit that fixes this but I never backported it to the 2xrsa compatible installer (my fork). I'll just have users use the latest actual release for updating.

**Comment by nedwill** [comment]
Thanks for addressing this quickly.

**Comment by Plailect** [comment]
np

**Comment by awesomeice7** [comment]
I am also having the problem stated by the title. What was the solution?

**Comment by james-d-elliott** [comment]
Use the latest release of SafeA9LHInstaller: https://github.com/AuroraWright/SafeA9LHInstaller/releases/latest
