### ISSUE TITLE
FBI can be installed without Health & Safety injection

### ISSUE THREAD

**Issue by kkjdroid** [Plailect/Guide#905]
Once you've booted Luma, you can run Fasthax, then the 3dsx version of FBI to install FBI on SysNAND. This is faster and easier than injecting FBI to H&S, installing it to SysNAND, and restoring H&S.

**Comment by Plailect** [comment]
This will not always work, so the hs method will stick around until a better one is implemented (Luma hooking some module w/ privs on startup to install it would be one example).
