### ISSUE TITLE
No active seeds for latest file in rss feed

### ISSUE THREAD

**Issue by Zomnut** [Plailect/Guide#914]
There are zero active seeds (I have seen as many as two in the last month, but have never been able to connect to one) for the latest torrent file added to the torrent rss feed, "10.3.0-28K(Full)_n3DS.zip"

Currently seeing 144 peers in the cloud, with every client connected reporting 0%

**Comment by Plailect** [comment]
Ah, right. This was something that was going to be added (along with ntrcardhax) before safehax dropped to the public. I can get it up, but I doubt it'll be of use to anyone.
