### ISSUE TITLE
Problem with CTRNAND  transfer

### ISSUE THREAD

**Issue by niko1910** [Plailect/Guide#925]
Hi, I'm having troubles hacking my 2DS (Firmware 11.2.0-35U, so I'm using the Soundhax method). I'm following the guide, and I'm stuck in the 2.1.0 ctrtransfer step. I can enter to Decrypt9, but when I try to use "Auto CTRNAND Transfer" and input the combo, I get the following message:

"A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
No usable file found
Auto CTRNAND Transfer: failed!"

I have the 2.1.0-4U_ctrtransfer_o3ds.bin and bin.sha in my /files9/ folder. _Also, decrypt9 shows the following in the start menu:

"Work directory: /
Game directory: (not available)
SD card: 4 mb / 15185 mb & no EmuNAND"

I have repeated several times the proccess, and checked if the files were corrupt, I formated the SD (by the way, it's in FAT32) but nothing have worked. Also tried with the european 2.1 files, but I got the same error.

Finally, I have checked the [Issue 711](https://github.com/Plailect/Guide/issues/711) but the solution didn't worked.

Thanks in advance.

**Comment by Plailect** [comment]
https://github.com/d0k3/Decrypt9WIP/issues
