### ISSUE TITLE
Please add back renaming Hourglass9.bin

### ISSUE THREAD

**Issue by mysterypaint** [Plailect/Guide#926]
Minor issue, but a couple of people were freaking out about the CTRNAND error message because they couldn't boot into Hourglass9

**Comment by Jisagi** [comment]
Seems like everyone who has the “Failed to mount CTRNAND” error cant start houglass9 through luma3ds cl menu. The part with manually renaming and booting directly into hg9 fixes this for those people. There are constantly people coming to Q&A on discord having this problem.
