### ISSUE TITLE
I followed your guide and finished it, but theres some problem

### ISSUE THREAD

**Issue by darkck** [Plailect/Guide#944]
My console is 2ds 11.2.0-35J, here's some question:
1.when i removed the sd card, it can still launch the system.
2.a9lh and luma, i updated them to the latest version. But when i use fbi to install cia games, it said “Desc：Cert signature or hash checkfailed（106）”

help

**Comment by Ev1lbl0w** [comment]
1. - That's intended
2- Check another CIA or reinstall FBI

**Comment by darkck** [comment]
thx，I've tried again and i found other cia could install。but monsterhunter x and pokemon sun still cant install。

**Comment by Ev1lbl0w** [comment]
Try getting the CIA from elsewhere. Or get an _3DS homebrew that install tickets into the system..._

**Comment by darkck** [comment]
i have 3ds homebrew launcher，how to do with tickets？

**Comment by Ev1lbl0w** [comment]
Google something like _3ds tickets installer_

**Comment by darkck** [comment]
@Ev1lbl0w like tiksweep？

**Comment by Ev1lbl0w** [comment]
Tiksweep uninstalls tickets. You need something to install tickets.

**Comment by Ev1lbl0w** [comment]
I can't say the name, because we're not allowed to post pirated stuff here. But you'll find. Or just browse and/or create a thread on GBATemp.
