### ISSUE TITLE
https://3ds.guide/2.1.0-ctrtransfer

### ISSUE THREAD

**Issue by BlastFurnaceNS** [Plailect/Guide#948]
Can the guide instruct people to make the NAND backup separate from the automatic NAND backup you are prompted to do when attempting auto CTRNAND transfer? Many people are messing up the NAND backup and ending up on 2.1 without a NANDmin.bin

**Comment by lordscales91** [comment]
Yeah. I also think that it's a good idea to introduce a separate step for the NAND backup, it should be as early as Decrypt9 has been successfully launched. From there, and after ensuring the backup is not corrupted (which can be done checking its filesize) proceed to the CTR TRANSFER step

**Comment by Plailect** [comment]
I honestly cannot see a good reason for this. 

If someone cannot read "**backup SysNAND to `NANDmin.bin` when prompted by pressing (A)**", then that is not the fault of the guide.

**Comment by BlastFurnaceNS** [comment]
The problem is people ending up with 0 byte NANDmin.bin's when they don't
have enough space.
