### ISSUE TITLE
safea9lhinstaller bug

### ISSUE THREAD

**Issue by pbanj** [Plailect/Guide#949]
So I have had 2 bricks from users that I've fixed with this issue, Not sure Wtf is the cause. they run the installer, it says it installed successfully, then never boots again. The installer didn't dump an otp either. I know both users had the wrong arm9loaderhax.bin, they had the installers not lumas. But that shouldn't be and never did cause a brick. 

Also lots of other users have been having issues using the version of the installer you link in the guide and we end up having to have them use the 2.0.3 ver from AW. Issues include it not wanting to run at all, to it saying files are missing that are not missing. Using the 2.0.3 ver fixes that.

**Comment by sora10pls** [comment]
Honestly I think the best thing to do is to advise users to use v2.0.3, check for `otp.bin` in the `a9lh` folder before install, and if it's there, delete it and proceed.

**Comment by Plailect** [comment]
Mine is identical to 2.0.3, but includes the following commits on top of it:

https://github.com/AuroraWright/SafeA9LHInstaller/commit/9e579395af0c9ca3ba1e0f2df231a656caf1c6ee    
https://github.com/AuroraWright/SafeA9LHInstaller/commit/4ab5ad9a892667ba7000bb06299f4072147db13b

I can't really think of why there would be any issues.

**Comment by pbanj** [comment]
Ya I have no idea either. Like you said its the same with some slight changes.

**Comment by Plailect** [comment]
I'm guessing that this is from people using the wrong version which they previously had downloaded, which an IRC user did. I am closing this issue.
