### ISSUE TITLE
Step 17 onwards?

### ISSUE THREAD

**Issue by Meochi** [Plailect/Guide#95]
Well I have followed all those steps but when I try to access Homebrew
via the OOT game after the downgrade the console just kicks me out after the message
robpin etc etc is ready which usualy gets me to homebrew..
But now instead I get an error occured restart the system etc..

**Comment by Terathiel** [comment]
*hax payloads are version specific, and the payload you used would be for a different fw version than the one you downgraded to. After downgrading, browserhax and menuhax are completely usable and it's advisable to use those as entry points for the remainder of the guide.

**Comment by Meochi** [comment]
I have neither

**Comment by Terathiel** [comment]
If you want to continue using oothax, then yes, you'll need to replace the ropbin with an appropriate 9.2 version. I would highly recommend using the installer included in the homebrew starter pack to set up menuhax afterwards, though you can continue using oothax for the remainder of the guide.

**Comment by Meochi** [comment]
I don't get how I am supposed to use the installer.
Just put it on the root of the sd open homebrew and set up menuhax this way?

**Comment by Terathiel** [comment]
The `menuhax_installer` folder should be inside the `3ds` folder on your SD root. You can then open homebrew and launch the installer to set it up, yes.

**Comment by Meochi** [comment]
There is only menuhax_manager v2.2 
and the desciption is that its a tool to manage home menu hax
if i click on it i only get a yellow screen..

furthermore do i still need to use the sploit installer-oot3dhax?
cant find the menuhax installer regardless tho

**Comment by Terathiel** [comment]
Try again, yellow screen crashes simply occur sometimes. If it crashes repeatedly, I'm not sure what the problem could be.

I'm afraid I'm not sure what exactly your current situation is, and probably can't be much more help.

**Comment by Meochi** [comment]
it worked afterwards but gave me an error in the process when i pressed install
i probably need internet connection

**Comment by Meochi** [comment]
![file 24-04-16 10 07 36](https://cloud.githubusercontent.com/assets/18528535/14766309/7c09e440-0a04-11e6-95d4-1b5214b8692c.jpeg)

**Comment by Meochi** [comment]
It says boot rednand to update..
but how do i know that im on rednand and not sysnand?

**Comment by Plailect** [comment]
"If you do not see "Emu" in front of the version number, then you are not on RedNAND. DO NOT UPDATE, FIND WHAT WENT WRONG"

That's how you tell.

**Comment by Meochi** [comment]
hello i finished everything and am gratefull for the help but one last thing remainsafter installing games as cia can i remove the cia data from the sd?

Date: Sun, 24 Apr 2016 07:50:37 -0700

**Comment by Plailect** [comment]
Yes.
