### ISSUE TITLE
.

### ISSUE THREAD

**Issue by vonKoenigsberg** [Plailect/Guide#958]
.

**Comment by vonKoenigsberg** [comment]
Please remove the lock of "https://github.com/Plailect/Guide/issues/955" so I can edit the comment to dots, for reasons. Will not add comments. Don't lock this plz as well so I can delete this comment.

**Comment by lordscales91** [comment]
I'm currently working on a graphical tool to automate the process, including handling the downloads. You can check it out here: https://github.com/lordscales91/magic9 

It's still on an early state but the first [pre-alpha](https://github.com/lordscales91/magic9/releases/tag/0.1-pre-alpha) release already automates the downloads, including the torrents. 

The files stored on these torrents are extracted directly from the device so they are subject to patents and other laws. So, please just don't keep asking about this.

**Comment by vonKoenigsberg** [comment]
I made this thread for a specific purpose, please just unlock the old thread so I can delete my comments and we are done.

3rd time: Just unlock https://github.com/Plailect/Guide/issues/955 so I can change my post to dots like in this thread. That's all. Thanks a lot. Alternatively plz wipe this and https://github.com/Plailect/Guide/issues/955 issue as a whole, but I'm not sure if you even can delete issues on GitHub.
