### ISSUE TITLE
Part 4, step 11

### ISSUE THREAD

**Issue by athairus** [Plailect/Guide#96]
> Open Decrypt9 (This can sometimes take a few tries), then go to "EmuNAND Options", then select the "Health & Safety Dump" option to dump Health & Safety to hs.app (you can use Up and Down / Left and Right to change the name)

The default filename is `hs_emu.app`. None of the options match `hs.app`. Choosing "SysNAND Options" and then "Health & Safety Dump" lets you save a file called `hs.app`. I've done both, not sure how to proceed.

**Comment by Plailect** [comment]
Use the left and right buttons on the D-Pad as well as up and down.
