### ISSUE TITLE
Installing arm9loaderhax torrents not working.

### ISSUE THREAD

**Issue by dejan1233** [Plailect/Guide#963]
All of the torrents for the Installing arm9loaderhax step fail to download having no seeders. Is there anything I can do? This includes aeskeydb.bin, fbi-2.4.2-injectable.zip, and data_input_v3.zip. I've had the torrents running for about a week now.

**Comment by deadair3210** [comment]
Something is wrong with either your torrent client or your network, as I just finished downloading and setting up the files earlier today

**Comment by dejan1233** [comment]
I'm using Utorrent but I am on college wifi.

**Comment by deadair3210** [comment]
Collage wifi is probably killing it, most have torrent protocol blocked
