### ISSUE TITLE
Missing section in Region Changing guide

### ISSUE THREAD

**Issue by SaltfishAmi** [Plailect/Guide#967]
I changed my USA N3DS to JPN (because I want to use the Japanese input method) with the guide. When I come to "Section V - Reinstalling Tickets" it told me open FBI but I don't have usable FBI just after a ctrtransfer. I managed to solve it by myself but I think it would be better to add the Injecting FBI section to that guide.
Besides, when I do Auto CTRNAND Transfer Decrypt9 will generate another configsave file, so when I do the last step "Inject configsave.bin" there are two files for me to choose, and you didn't tell me which to use...I picked the one that generated manually before and it seemed OK but I'm not sure whether my 3DS will explode next second.

**Comment by Plailect** [comment]
I'll add the FBI steps, and the config save is actually automatically backed up and injected now, so I'll remove that part.
