### ISSUE TITLE
The N3DS warning about homebrew is too subtle

### ISSUE THREAD

**Issue by witheld9** [Plailect/Guide#971]
The guide says you can increase the clockspeed in two separate places in the installing arm9loaderhax, first in Section III step 3 with a brief mention that "This breaks the Homebrew Launcher on 11.3!" without any explanation of how this is relevant, despite homebrew launcher being needed later. But it's also in Section VI step 23 anyway, and it's confusing users who have forgotten why homebrew launcher isn't working by the time they're told to use HomeBrew launcher.

**Comment by Plailect** [comment]
I'll bold it, but if they can't remember a warning they just read a few sections earlier that's not really my problem.
