### ISSUE TITLE
How do I execute this in a web browser? 

### ISSUE THREAD

**Issue by bag3318** [Plailect/Guide#975]
I want to know how to execute this in a web browser. Please help. I also am going to donate later today :)

**Comment by rikumax25** [comment]
just clone the repo and load one of the files into the browser

**Comment by bag3318** [comment]
which file? ther are no html files

**Comment by Plailect** [comment]
What are you talking about?

**Comment by bag3318** [comment]
the home page is home.txt and is not programmed in html

**Comment by bag3318** [comment]
In fact, I don't even know what lang its programmed in

**Comment by Plailect** [comment]
What are you trying to do?

**Comment by bag3318** [comment]
open the source code in a web browser to view the web page

**Comment by bag3318** [comment]
the 3ds.guide webpage

**Comment by Plailect** [comment]
The words you are saying mean absolutely nothing. You want a local version or something?

**Comment by bag3318** [comment]
yes please

**Comment by Plailect** [comment]
Not a clue why you'd want to do that.

It's based on [mmistakes/minimal-mistakes](https://github.com/mmistakes/minimal-mistakes), so clone the guide repo and do [these](https://mmistakes.github.io/minimal-mistakes/docs/installation/) instructions.

If you can't figure it out from there, you can search elsewhere for help.
