### ISSUE TITLE
homebrew launcher issue on 11.3

### ISSUE THREAD

**Issue by SykieChen** [Plailect/Guide#976]
When installing arm9loaderhax, the guide suggested new 3ds users to turn “New 3DS CPU” to “Clock+L2(x)”, and it warned that homebrew on 11.3 will be broken.
However, in the following steps entering homebrew is still necessary, since the latest sys version is 11.3, it will surly make the luncher stuck on "the homemenu ropbin is ready", which may be confusing.
So please remind new 3ds users to turn clock+L2 later, thx!

**Comment by Plailect** [comment]
The warning is bold, so I think they can see it. It's not my fault if they can't remember the option they *just* enabled and the warning that goes with it.

**Comment by SykieChen** [comment]
Fine, thanks for replying.
