### ISSUE TITLE
Hello, I'd like to point out a serious issue that I ran into with the NAND backup.

### ISSUE THREAD

**Issue by bahatmaan** [Plailect/Guide#978]
This guide states several times that creating a NAND backup is important. That's all well and good, but what it fails to state is how easy it is to accidentally skip that part!

I pressed B at the part where it asked me to backup my NAND in an attempt to return to the previous option and was horrified to watch as the 3DS suddenly started overwriting my NAND. Can a note be added mentioning that it is possible to accidentally skip the backup if you're not careful?

**Comment by sora10pls** [comment]
Not our fault you can't read

![img_7066](https://cloud.githubusercontent.com/assets/17801814/23363116/ff4879ec-fcc6-11e6-8ab8-4bcbf77a2fd2.PNG)

![img_7067](https://cloud.githubusercontent.com/assets/17801814/23363117/ff48e88c-fcc6-11e6-8f4c-09f288feee75.PNG)

**Comment by bahatmaan** [comment]
Nothing written there refers to the issue I mentioned. I went in knowing I needed to do the NAND backup. I was not expecting that it was possible to skip that section by accident.

It seems to me that you are the one that doesn't know how to read.

**Comment by quantumcat1** [comment]
Maybe add a suggestion to Hourglass9's repo to maybe have a key combo to input to confirm you really want to proceed without backing up your NAND.

**Comment by pbanj** [comment]
It's decrypt9 that does the ctr transfer not hourglass9

**Comment by Plailect** [comment]
This will be irrelevant soon given upcoming changes to the tools used.
