### ISSUE TITLE
Will CFW ever be fixed?

### ISSUE THREAD

**Issue by Psionic8** [Plailect/Guide#979]
I just got a new 3DS that the previous owner factory reset. Sadly, this means I can't use 3ds.guide since its on 11.3.0.36U firmware. Is there any way to reverse this without fasthax and safehax or do you think there will ever be hope?

**Comment by FranticUmbreon** [comment]
...CFW might be updated to work for 11.3, but that'll be a long time from now without a miracle. And no, this can't be reversed.
