### ISSUE TITLE
(Suggestion) add DSiWare hax back in for restoring NAND backups 

### ISSUE THREAD

**Issue by quantumcat1** [Plailect/Guide#980]
Some users lost a9lh due to booting Gateway sysNAND mode, and others accidentally updated their sysNAND while using menuhax or similar. They have NAND backups, and could restore them using DSiWare hax and another console, but unfortunately that part of the guide is gone. Could you maybe add it back in, rewritten to just restore NAND backups? It could maybe be linked from the main firmware section under 11.3, but with a giant disclaimer saying you need a previous NAND backup. Or if you're worried people will start inundating you with help requests saying where do we get this NAND backup, I used one from my friend's console and now I'm bricked help, etc etc, you could have it just in the troubleshooting section for us to link people to, or for them to find themselves.

**Comment by Plailect** [comment]
Or people could just not be stupid and overwrite their install...

**Comment by Uumas** [comment]
Well... Making mistakes doesn't always mean you are stupid. Everybody does mistakes and it would be a great addition to the troubleshooting section.

**Comment by seleron** [comment]
It would be very beneficial for some people. Consider that everybody may screw up since it is a little bit complicated process for average joe. It would be wonderful if you can upload that again. Cheers
