### ISSUE TITLE
Consoles updated from 2.1 to 11.2 with cartridges cage use soundhax

### ISSUE THREAD

**Issue by quantumcat1** [Plailect/Guide#981]
Some research is probably needed to find out at which firmware the sound app changed to its current state. Then the guide needs to have something like, if your browser is -4 or less, then don't go past 6.x with cart updates (and have alternative entrypoints linked for those on higher firmwares with -4 or less).

Edit: sorry that was meant to be can't not cage

**Comment by james-d-elliott** [comment]
The current version was released with 7.0.0-13 from memory (3dbrew could tell you), also cart updates don't update the soundapp title or any other non-essential title (menu, mset, etc).

**Comment by Plailect** [comment]
This is mentioned in the guide.
