### ISSUE TITLE
Can I upgrade to 11.3 without breaking homebrew launcher?

### ISSUE THREAD

**Issue by kaidemarco** [Plailect/Guide#986]
Im confused on if I update my new 3ds xl to 11.3(ive already installed your guide and installed the newest luma3ds version),can I turn on Clock+L2(x) in luma after I update, or can I never turn it on?

**Comment by Uumas** [comment]
You can. If you want to run hbl, you will need to disable Clock+L2 when you want to use it or use Luma hourly builds.

**Comment by kaidemarco** [comment]
does the luma hourly builds have a patch? also, will I lose kernel access by updating? thanks.

**Comment by kaidemarco** [comment]
@Uumas

**Comment by kaidemarco** [comment]
nevermind i just went to the nightly build and it worked
