### ISSUE TITLE
2.1.0-4U_ctrtransfer_o3ds name error in Dcrypt9

### ISSUE THREAD

**Issue by RikaKunisaki** [Plailect/Guide#988]
Hello!! I have a problem when Im tryng to downgrade a 11.0 OLD 3ds usa.

1- I put all the necesary in the SD
2 - Start the hombrew using SOUNDHAX
3 - Enter in the decrypt9 
4 - go to "SysNAND Options/CTRNAND transfer/CTRNAND Transfer"
5 - put the characters and displayed a lost of no sense character.

Correct displayed:
Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
2.1.0-4U_ctrtransfer_o3ds.bin

non sense character displayed:
Selected: [Auto CTRNAND Transfer]
A9LH not detected, checking FIRM0...
Select CTRNAND transfer image
Use arrow keys and <A> to choose a file
}╦╠░¢ Decryption success!

Im tryning a lot of diferent memories a lot of ctrnand transfer file mirrors.... I dont know what to do...

**Comment by Plailect** [comment]
I do not understand.
