### ISSUE TITLE
Minor grammar issue in Portuguese

### ISSUE THREAD

**Issue by minecast** [Plailect/Guide#99]
"Para visitar este tutorial em clique aqui Português (traduzido por asaver)." should be "Para visitar este tutorial em Português clique aqui (traduzido por asaver)."

**Comment by willkof2** [comment]
This tutorial it's in Portuguese from Portugal or Brazillian's Portuguese?

**Comment by minecast** [comment]
European Portuguese, as far as I'm aware.

**Comment by willkof2** [comment]
Thanks

**Comment by Plailect** [comment]
Fixed
