### ISSUE TITLE
Japanese 3DS XL (LL) CFW

### ISSUE THREAD

**Issue by audacious11** [Plailect/Guide#991]
Hello everyone 
Is it easy to install CFW on Japanese 3DS XL (LL) ? Insttaled Arm9hax on my NA 3DS XL without any problems !! Is there anyway to get English language on Japanese 3DS XL (LL) before or after CFW ? I have a Japanese 3DS XL lying around unused for years and want to utilize it

**Comment by Plailect** [comment]
Try reading the guide...?
