### ISSUE TITLE
Guide doesn't mention edition of SecureInfo_C on region changing

### ISSUE THREAD

**Issue by Elckerlijc** [Plailect/Guide#994]
I was trying to region change an o3DS from EUR to JPN and after following the guide, 3DS doesn't boot. The guide does not refer to the SecureInfo_C we need to create and edit to match the region we want.
following this makes my 3DS to boot properly on the new region :
https://github.com/Plailect/Guide/blob/22ada97762145d15e11a5971b3a4925b4f439dc0/_pages/en_US/Region-Changing.txt#L77
Thanks to Miah_Molkot on 3DShacks IRC who find this for me.

##### Section IV - Editing SecureInfo

1. Press (Start) then hold (Up) to reboot into arm9loaderhax GodMode9      
2. Navigate to `SYSNAND CTRNAND` -> `rw` -> `sys`
3. Press (Y) on `SecureInfo_A` to copy it
4. Press (Y) to paste a copy of `SecureInfo_A`
5. Select "Copy path(s)"
6. Press (A) to unlock SysNAND writing, then input the key combo given
7. Select "Choose new name"
8. Use the D-Pad to rename the file to `SecureInfo_C`, pressing (A) when you're done (overwrite any existing `SecureInfo_C`)
9. Scroll down to the `SecureInfo_C` you just pasted
10. Press (A) on `SecureInfo_C` then select "Show in Hexeditor"
11. Press (A) to continue
12. Press (A) to enter edit mode
13. Go to the beginning of line 00000100 and press (A) on it
14. Hold (A) while pressing (Up) or (Down) on the D-Pad to edit the number
15. Change the first number pair on line 00000100 to the following pair that corresponds to *the region you want to change to*:
    - "00" : JPN
    - "01" : USA
    - "02" : EUR
16. Press (B) to exit edit mode, then save changes, then press (B) again to return to the directory
17. You should see both a `SecureInfo_A` and `SecureInfo_C` if everything was done properly. (`SecureInfo_C` is used in place of `SecureInfo_A` when using Luma3DS if it detects the file on boot)
18. Press and hold (Start) to reboot into Hourglass9

**Comment by Plailect** [comment]
Doesn't have to, GM9 does it automatically. Unfortunately there appears to be a bug with this which will be fixed soon.

**Comment by Elckerlijc** [comment]
Actually, tested with d0k3 on #3dshacks yesterday, 1.0.7 version of godmod9 solved this issue ;)
